### ISSUE TITLE
Compilation issue for absl::optional and GCC 7.2

### ISSUE THREAD

**Issue by mattklein123** [abseil/abseil-cpp#100]
Please see the related Envoy issue here for an explicit example: https://github.com/envoyproxy/envoy/issues/2987

We are looking for guidance on how best to handle this in our code base. Is there any fix we can do in the library? Or should we globally disable this warning?

cc @htuch @jmarantz

**Comment by bobby-stripe** [comment]
This GCC bug is related, but has seen little discussion since last summer: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80635

**Comment by zhangxy988** [comment]
I looked briefly at this issue and there doesn't seem to be anything we can do in absl::optional to suppress this false positive "-Wmaybe-uninitialized". I'd say just disable the warning globally for your build, or add `#pragma GCC diagnostic disable "-Wmaybe-uninitialized"` to the affected code if there aren't many.

**Comment by JonathanDCohen** [comment]
Hey there!  Is this still an issue, or did Xiaoyi's `pragma` solve the problem?

**Comment by JonathanDCohen** [comment]
Closed due to lack of response
