### ISSUE TITLE
ABSL_HAVE_ADDRESS_SANITIZER use breaks build for MSVC 16.11 with /fsanitize=address

### ISSUE THREAD

**Issue by DoDoENT** [abseil/abseil-cpp#1010]
**Describe the bug**

This bug was originally reported in [TensorFlow](https://github.com/tensorflow/tensorflow/issues/51685)

I'm using Abseil 202103.24.2, Visual Studio 16.11.

At first, building abseil with `/fsanitize=address` fails with 

```
 fatal error C1083: Cannot open include file: 'sanitizer/common_interface_defs.h': No such file or directory
```

and 

```
fatal error C1083: Cannot open include file: 'sanitizer/asan_interface.h': No such file or directory
```

This is an issue of MSVC and has been reported to [Microsoft](https://developercommunity.visualstudio.com/t/ASan-API-headers-not-in-include-path-whe/1517192?space=62&q=sanitizer%2Fcommon_interface_defs.h&entry=myfeedback).

However, after hardcoding the include directory path in my `CMakeLists.txt` to `C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\crt\src` just to test the build in case MSVC added that path correctly to default includes, abseil still doesn't build:

This time I get the following error:

```
absl/container/fixed_array.h(432): error C3646: '__attribute__': unknown override specifier
```

As far as I see, the line 432 of `fixed_array.h` is 

```
   private:
    ABSL_ADDRESS_SANITIZER_REDZONE(redzone_begin_);  // line 432
    alignas(StorageElement) char buff_[sizeof(StorageElement[inline_elements])];
    ABSL_ADDRESS_SANITIZER_REDZONE(redzone_end_);
```

and `ABSL_ADDRESS_SANITIZER_REDZONE` is defined as

```
#define ABSL_ADDRESS_SANITIZER_REDZONE(name) \
  struct {                                   \
    char x[8] __attribute__((aligned(8)));   \
  } name
```

in case when `ABSL_HAVE_ADDRESS_SANITIZER` is defined (i.e. when ASan is detected). I think this attribute should be set differently with MSVC - ideally with `alignas` specifier, which is compiler agnostic.

I believe this is an abseil bug that needs to be resolved.

**Steps to reproduce the bug**

Simply enable address sanitizer for your Visual Studio project generated with CMake.

**What version of Abseil are you using?**

I'm using Abseil 202103.24.2

**What operating system and version are you using**

Windows 10

**What compiler and version are you using?**

Visual Studio 16.11 (MSVC 14.29.30133)

**What build system are you using?**

CMake v3.19.1

**Additional context**

This bug was originally reported in [TensorFlow](https://github.com/tensorflow/tensorflow/issues/51685).

**Comment by derekmauro** [comment]
This is already fixed at HEAD by https://github.com/abseil/abseil-cpp/pull/947.
