### ISSUE TITLE
Cannot use Abseil copts in my project when using Bazel

### ISSUE THREAD

**Issue by ofats** [abseil/abseil-cpp#1023]
Hello!
I'd like to standardize on Abseil compilation flags in my projects.

I'm using Bazel and trying to use [variables sharing](https://docs.bazel.build/versions/4.2.1/skylark/tutorial-sharing-variables.html) from external workspace.

BUILD file is straightforward:
```starlark
load(
    "@com_google_absl//absl:copts/configure_copts.bzl",
    "ABSL_DEFAULT_COPTS",
    "ABSL_TEST_COPTS",
)

cc_library(
    name = "log",
    hdrs = ["log.h"],
    copts = ABSL_DEFAULT_COPTS,
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/time",
    ],
)

cc_test(
    name = "log_test",
    srcs = ["log_test.cc"],
    copts = ABSL_TEST_COPTS,
    deps = [
        ":log",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
    ],
)
```

However, I'm getting such errors:
```
ERROR: Analysis of target '//ofats/log:log_test' failed; build aborted: no such package 'absl': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

I'm referencing correct `.bzl` file by correct path, double checked.

I started looking more into this and found out that the following setup builds successfully:
```starlark
load(
    "@com_google_absl//absl:copts/GENERATED_copts.bzl",
    "ABSL_LLVM_FLAGS",
    "ABSL_LLVM_TEST_FLAGS",
)

cc_library(
    name = "log",
    hdrs = ["log.h"],
    copts = ABSL_LLVM_FLAGS,
    deps = [
        ":source_location",
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/time",
    ],
)

cc_test(
    name = "log_test",
    srcs = ["log_test.cc"],
    copts = ABSL_LLVM_TEST_FLAGS,
    deps = [
        ":log",
        "@com_google_absl//absl/strings",
        "@com_google_googletest//:gtest_main",
    ],
)
```

So it seems that, for some reason, Bazel cannot resolve the [load label](https://github.com/abseil/abseil-cpp/blob/1ce4ceca2b2931bc4d7e470228c2dbb2f3dfea0f/absl/copts/configure_copts.bzl#L8) in `configure_copts.bzl` file when loading from it from external workspace: looks like it treats it as a local label in my project.

Now I'm wondering if it's a problem in Bazel itself (maybe some known limitation?) or in the setup of Abseil copts.

P.S. Abseil [doc](https://abseil.io/docs/cpp/platforms/compilerflags) still points to already non-existent https://github.com/abseil/abseil-cpp/blob/master/absl/copts.bzl.

**Comment by derekmauro** [comment]
It's possible that we would need to add a `bzl_library` target, or something similar, if this was intended to work, but `ABSL_DEFAULT_COPTS` and friends are not intended to be used by other projects.

I've sent a change to fix the broken link in the docs.

**Comment by ofats** [comment]
Don't you want to make those available externally eventually? I can for sure use my own compilation flags but would prefer not to and this list of flags looks reasonable in general case.
If it's something I can upstream to abseil myself - just say.

**Comment by derekmauro** [comment]
I don't think we intend to do this and I'm not even sure our compilation flags are even well thought out.

I also think you may not understand the purpose of `ABSL_TEST_COPTS`. This would ideally just be `ABSL_DEFAULT_COPTS`, but for historical reasons, it would take some effort to get there. For example, for a long time (before the open-sourcing of Abseil), we had `-Wno-sign-compare`. We had to fix those issues in our headers because people would complain otherwise, but in tests we don't particularly care.

I also think that users don't want us breaking their builds by simply adding warnings they aren't ready for.
