### ISSUE TITLE
[FreeBSD+Bazel] absl/debugging/internal/elf_mem_image.h:66:11: error: unknown type name 'ElfW'

### ISSUE THREAD

**Issue by yesudeep** [abseil/abseil-cpp#1024]
**Describe the bug**

```
ERROR:
...
  /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.d '-frandom-seed=bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.o' -fPIC -iquote external/com_google_absl -iquote bazel-out/freebsd-fastbuild/bin/external/com_google_absl '-DHAVE_BAZEL_BUILD=1' '-std=c++2a' -Wall -Wreturn-type -Wuninitialized -Wunused-result '-Werror=narrowing' '-Werror=reorder' -Wunused-local-typedefs '-Werror=conversion-null' '-Werror=overlength-strings' '-Werror=pointer-arith' '-Werror=varargs' '-Werror=vla' '-Werror=write-strings' -Wmissing-declarations '-fdiagnostics-color=always' -Wall -Wextra -Wcast-qual -Wconversion-null -Wformat-security -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -DNOMINMAX -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/debugging/internal/elf_mem_image.cc -o bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.o)
Execution platform: @local_config_platform//:host
In file included from external/com_google_absl/absl/debugging/internal/elf_mem_image.cc:18:
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:66:11: error: unknown type name 'ElfW'
    const ElfW(Sym) *symbol;    // Symbol in the dynamic symbol table.
          ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:66:20: error: expected ';' at end of declaration list
    const ElfW(Sym) *symbol;    // Symbol in the dynamic symbol table.
                   ^
                   ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:90:9: error: unknown type name 'ElfW'
  const ElfW(Phdr)*    GetPhdr(int index) const;
        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:90:19: error: expected ';' at end of declaration list
  const ElfW(Phdr)*    GetPhdr(int index) const;
                  ^
                  ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:91:9: error: unknown type name 'ElfW'
  const ElfW(Sym)*     GetDynsym(int index) const;
        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:91:18: error: expected ';' at end of declaration list
  const ElfW(Sym)*     GetDynsym(int index) const;
                 ^
                 ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:92:9: error: unknown type name 'ElfW'
  const ElfW(Versym)*  GetVersym(int index) const;
        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:92:21: error: expected ';' at end of declaration list
  const ElfW(Versym)*  GetVersym(int index) const;
                    ^
                    ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:93:9: error: unknown type name 'ElfW'
  const ElfW(Verdef)*  GetVerdef(int index) const;
        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:93:21: error: expected ';' at end of declaration list
  const ElfW(Verdef)*  GetVerdef(int index) const;
                    ^
                    ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:94:9: error: unknown type name 'ElfW'
  const ElfW(Verdaux)* GetVerdefAux(const ElfW(Verdef) *verdef) const;
        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:94:22: error: expected ';' at end of declaration list
  const ElfW(Verdaux)* GetVerdefAux(const ElfW(Verdef) *verdef) const;
                     ^
                     ;
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:34: error: unknown type name 'ElfW'
  const char*          GetDynstr(ElfW(Word) offset) const;
                                 ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:45: error: expected ')'
  const char*          GetDynstr(ElfW(Word) offset) const;
                                            ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:33: note: to match this '('
  const char*          GetDynstr(ElfW(Word) offset) const;
                                ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:41: error: unknown type name 'ElfW'
  const void*          GetSymAddr(const ElfW(Sym) *sym) const;
                                        ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:51: error: expected ')'
  const void*          GetSymAddr(const ElfW(Sym) *sym) const;
                                                  ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:34: note: to match this '('
  const void*          GetSymAddr(const ElfW(Sym) *sym) const;
                                 ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:34: error: unknown type name 'ElfW'
  const char*          GetVerstr(ElfW(Word) offset) const;
                                 ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:45: error: expected ')'
  const char*          GetVerstr(ElfW(Word) offset) const;
                                            ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:33: note: to match this '('
  const char*          GetVerstr(ElfW(Word) offset) const;
                                ^
external/com_google_absl/absl/debugging/internal/elf_mem_image.h:117:9: error: unknown type name 'ElfW'
  const ElfW(Ehdr) *ehdr_;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
INFO: Elapsed time: 9.610s, Critical Path: 2.41s
INFO: 76 processes: 9 internal, 67 local.
FAILED: Build did NOT complete successfully

```

**Steps to reproduce the bug**

- [ ] Build on FreeBSD using Bazel using `bazel test ...`.

**What version of Abseil are you using?**

git HEAD

**What operating system and version are you using**

```
❯ uname -a
FreeBSD hostname 13.0-STABLE FreeBSD 13.0-STABLE GENERIC  amd64
```

**What compiler and version are you using?**

```
❯ clang --version
clang version 14.0.0
Target: x86_64-portbld-freebsd13.0
Thread model: posix
InstalledDir: /usr/local/llvm-devel/bin
```

**What build system are you using?**

```
❯ bazel --version
bazel 4.2.1
```

**Additional context**

None.

**Comment by laramiel** [comment]
What c library are you using?

On FreeBSD `<link.h>` does not define the ELF symbols in the same way as linux, so it seems that it might need a significant reworking of elf_mem_image.h to work.

**Comment by EmployedRussian** [comment]
I cloned https://github.com/freebsd/freebsd-src.

AFAICT, `link.h` eventually `#includes` `sys/elf_generic.h`, which does `#define ElfW`, so everything should work as-is.

Please attach the output from
```
 /usr/bin/clang -E -dD -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector  '-std=c++0x' -DNOMINMAX -no-canonical-prefixes  external/com_google_absl/absl/debugging/internal/elf_mem_image.cc 
```

**Comment by yesudeep** [comment]
Hey @EmployedRussian I've added the output here: https://gist.github.com/yesudeep/5cec1b102b81571a18baef009c46c793

I'm not sure why there isn't a 1:1 between a freebsd installation and github.com/freebsd/freebsd-src repo, but on the command line I see this:

https://gist.githubusercontent.com/yesudeep/5cec1b102b81571a18baef009c46c793/raw/43ec7ca7703d7c932a86500dac04e5f6ee5f9211/search%2520for%2520elfw

**Comment by EmployedRussian** [comment]
It looks like this chunk of `elf_generic.h` from freebsd-src is missing:
```
    55  #define __elfN(x)       __CONCAT(__CONCAT(__CONCAT(elf,__ELF_WORD_SIZE),_),x)
    56  #define __ElfN(x)       __CONCAT(__CONCAT(__CONCAT(Elf,__ELF_WORD_SIZE),_),x)
    57  #define __ELFN(x)       __CONCAT(__CONCAT(__CONCAT(ELF,__ELF_WORD_SIZE),_),x)
    58  #define __ElfType(x)    typedef __ElfN(x) __CONCAT(Elf_,x)
    59
    60  /* Define ElfW for compatibility with Linux, prefer __ElfN() in FreeBSD code */
    61  #define ElfW(x)         __ElfN(x)
```
It was added  very recently:
```
34e7e4b6a059e (Dimitry Andric      2021-08-05 20:57:22 +0200 60) /* Define ElfW for compatibility with Linux, prefer __ElfN() in FreeBSD code */
34e7e4b6a059e (Dimitry Andric      2021-08-05 20:57:22 +0200 61) #define        ElfW(x)         __ElfN(x)
34e7e4b6a059e (Dimitry Andric      2021-08-05 20:57:22 +0200 62)
```
This suggests that the fix in  `elf_mem_image.cc ` should be along the lines of:
```
#if defined(__FreeBSD__) && !defined(ElfW)
#define ElfW(x) __ElfN(x)
#endif
```

**Comment by yesudeep** [comment]
Ah, that makes sense.

**Comment by gwhiteeagle3726623** [comment]
> **Describe the bug**
> 
> ```
> ERROR:
> ...
>   /usr/bin/clang -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer '-std=c++0x' -MD -MF bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.d '-frandom-seed=bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.o' -fPIC -iquote external/com_google_absl -iquote bazel-out/freebsd-fastbuild/bin/external/com_google_absl '-DHAVE_BAZEL_BUILD=1' '-std=c++2a' -Wall -Wreturn-type -Wuninitialized -Wunused-result '-Werror=narrowing' '-Werror=reorder' -Wunused-local-typedefs '-Werror=conversion-null' '-Werror=overlength-strings' '-Werror=pointer-arith' '-Werror=varargs' '-Werror=vla' '-Werror=write-strings' -Wmissing-declarations '-fdiagnostics-color=always' -Wall -Wextra -Wcast-qual -Wconversion-null -Wformat-security -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -DNOMINMAX -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/com_google_absl/absl/debugging/internal/elf_mem_image.cc -o bazel-out/freebsd-fastbuild/bin/external/com_google_absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.o)
> Execution platform: @local_config_platform//:host
> In file included from external/com_google_absl/absl/debugging/internal/elf_mem_image.cc:18:
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:66:11: error: unknown type name 'ElfW'
>     const ElfW(Sym) *symbol;    // Symbol in the dynamic symbol table.
>           ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:66:20: error: expected ';' at end of declaration list
>     const ElfW(Sym) *symbol;    // Symbol in the dynamic symbol table.
>                    ^
>                    ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:90:9: error: unknown type name 'ElfW'
>   const ElfW(Phdr)*    GetPhdr(int index) const;
>         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:90:19: error: expected ';' at end of declaration list
>   const ElfW(Phdr)*    GetPhdr(int index) const;
>                   ^
>                   ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:91:9: error: unknown type name 'ElfW'
>   const ElfW(Sym)*     GetDynsym(int index) const;
>         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:91:18: error: expected ';' at end of declaration list
>   const ElfW(Sym)*     GetDynsym(int index) const;
>                  ^
>                  ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:92:9: error: unknown type name 'ElfW'
>   const ElfW(Versym)*  GetVersym(int index) const;
>         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:92:21: error: expected ';' at end of declaration list
>   const ElfW(Versym)*  GetVersym(int index) const;
>                     ^
>                     ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:93:9: error: unknown type name 'ElfW'
>   const ElfW(Verdef)*  GetVerdef(int index) const;
>         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:93:21: error: expected ';' at end of declaration list
>   const ElfW(Verdef)*  GetVerdef(int index) const;
>                     ^
>                     ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:94:9: error: unknown type name 'ElfW'
>   const ElfW(Verdaux)* GetVerdefAux(const ElfW(Verdef) *verdef) const;
>         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:94:22: error: expected ';' at end of declaration list
>   const ElfW(Verdaux)* GetVerdefAux(const ElfW(Verdef) *verdef) const;
>                      ^
>                      ;
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:34: error: unknown type name 'ElfW'
>   const char*          GetDynstr(ElfW(Word) offset) const;
>                                  ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:45: error: expected ')'
>   const char*          GetDynstr(ElfW(Word) offset) const;
>                                             ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:95:33: note: to match this '('
>   const char*          GetDynstr(ElfW(Word) offset) const;
>                                 ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:41: error: unknown type name 'ElfW'
>   const void*          GetSymAddr(const ElfW(Sym) *sym) const;
>                                         ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:51: error: expected ')'
>   const void*          GetSymAddr(const ElfW(Sym) *sym) const;
>                                                   ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:96:34: note: to match this '('
>   const void*          GetSymAddr(const ElfW(Sym) *sym) const;
>                                  ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:34: error: unknown type name 'ElfW'
>   const char*          GetVerstr(ElfW(Word) offset) const;
>                                  ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:45: error: expected ')'
>   const char*          GetVerstr(ElfW(Word) offset) const;
>                                             ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:97:33: note: to match this '('
>   const char*          GetVerstr(ElfW(Word) offset) const;
>                                 ^
> external/com_google_absl/absl/debugging/internal/elf_mem_image.h:117:9: error: unknown type name 'ElfW'
>   const ElfW(Ehdr) *ehdr_;
>         ^
> fatal error: too many errors emitted, stopping now [-ferror-limit=]
> 20 errors generated.
> INFO: Elapsed time: 9.610s, Critical Path: 2.41s
> INFO: 76 processes: 9 internal, 67 local.
> FAILED: Build did NOT complete successfully
> 
> ```
> 
> **Steps to reproduce the bug**
> 
> - [ ] Build on FreeBSD using Bazel using `bazel test ...`.
> 
> **What version of Abseil are you using?**
> 
> git HEAD
> 
> **What operating system and version are you using**
> 
> ```
> ❯ uname -a
> FreeBSD hostname 13.0-STABLE FreeBSD 13.0-STABLE GENERIC  amd64
> ```
> 
> **What compiler and version are you using?**
> 
> ```
> ❯ clang Chrome/94.0.4606.71```
```
> clang version 14.0.0
> Target: x86_64-portbld-freebsd13.0
> Thread model: posix
> InstalledDir: /usr/local/llvm-devel/bin
> ```
> 
> **What build system are you using?**
> 
> ```
> ❯ bazel --version
> bazel 4.2.1
> ```
> 
> **Additional context**
> 
> None.
>

**Comment by yesudeep** [comment]
Thank you! Fixed.
