### ISSUE TITLE
Linker issue with raw_hash_set

### ISSUE THREAD

**Issue by benstadin** [abseil/abseil-cpp#1026]
I'm linking statically against libabsl_raw_hash_set.a, though I cannot track down the cause for the following linker error. Method ShouldInsertBackwards() be inside raw_hash_set:

```
Undefined symbols for architecture x86_64:
  "absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)", referenced from:
      absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<int, google::simple_lru_cache::SimpleLRUCacheElem<int, google::simple_lru_cache::TestValue>*>, google::simple_lru_cache::internal::SimpleLRUHash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, google::simple_lru_cache::SimpleLRUCacheElem<int, google::simple_lru_cache::TestValue>*> > >::find_first_non_full(unsigned long) in simple_lr
```

**Comment by derekmauro** [comment]
Please re-open this issue with the bug report template completely filled out.

https://github.com/abseil/abseil-cpp/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md

In particular:

> Steps to reproduce the bug
>
> It's important that we are able to reproduce the problem that you are experiencing. Please provide all code and relevant steps to reproduce the problem, including your BUILD/CMakeLists.txt file and build commands. Links to a GitHub branch or godbolt.org that demonstrate the problem are also helpful.
