### ISSUE TITLE
Linker error while cross-compiling with bazel

### ISSUE THREAD

**Issue by pkbehera** [abseil/abseil-cpp#1027]
I am trying to upgrade our version of abseil-cpp to the latest release, Abseil LTS 20210324.2

I have cloned the latest release as a submodule in my git repo and defined this in my Bazel WORKSPACE file

```
local_repository(
    name = "com_google_absl",
    path = "third_party/abseil-cpp",
)
```

This works while building natively on linux, however while trying cross compile, I am seeing this linker error

`bazel-out/bxx-opt-bn_b10/bin/external/com_google_absl/absl/strings/libstrings.a(charconv.o): undefined reference to symbol 'nanf@@GLIBC_2.4'`

Any idea how I can resolve this?

**Comment by derekmauro** [comment]
You probably need to link the math library. Try adding `--linkopt=-lm` to your bazel command.

**Comment by pkbehera** [comment]
Well shouldn't abseil be adding this link option already in its build configuration?

**Comment by pkbehera** [comment]
```
diff --git a/absl/strings/BUILD.bazel b/absl/strings/BUILD.bazel
index 123b5efb..8c73cf8e 100644
--- a/absl/strings/BUILD.bazel
+++ b/absl/strings/BUILD.bazel
@@ -79,6 +79,7 @@ cc_library(
         "//absl/numeric:bits",
         "//absl/numeric:int128",
     ],
+    linkopts = ["-lm"], #link math library, charconv.cc calls nanf()
 )
```
I had to do this change to fix this for my cross compilation (looks like the cross compiler does not link with math library by default)
