### ISSUE TITLE
Intellisense header include location

### ISSUE THREAD

**Issue by Coronon** [abseil/abseil-cpp#1029]
Hi there, it's my first time using Bazel and Abseil and I have a little question about intellisense.
It is probably dead simple, but I could not find a solution after 20min of googling around.

I have two other libraries (pq & pqxx) that I build locally and then include using Bazel's `new_local_repository`+`BUILD`_file_, which gives me immediate access to their headers. With Abseil however, after including it into my `WORKSPACE` file (as recommended [here](https://abseil.io/docs/cpp/quickstart)), my intellisense complains, because it can not discover the included header files. All I see in `bazel-bin` are `.pic.d` and `.pic.o` files. The only way I see at the moment is to include `bazel-{projectName}/external/com_google_absl/absl` into my intellisense include path. Is there any cleaner way?

My selfbuild libraries have their actually header files copied to `bazel-bin`, which would make it extremely convenient to simply add `bazel-bin/external` to intellisense.

The code builds like a charm, but I would love to get intellisense back, especially when working with a new library.

Thank you so much for Bazel and Abseil, would love to hear back 😃

**Comment by gwhiteeagle3726623** [comment]
I'm extremely new to this to and didn't understand half of the words you said but it sounded hella cool but I think that if you were to integrate an application programming interface for code languages not unlike Google translate.  I'm sure all it would be is a basic algorithm and a cloud link to a store of code languages

**Comment by Coronon** [comment]
> I'm extremely new to this to and didn't understand half of the words you said but it sounded hella cool but I think that if you were to integrate an application programming interface for code languages not unlike Google translate.  I'm sure all it would be is a basic algorithm and a cloud link to a store of code languages 

It's probably a bit disappointing if you fully understand my question. I am using VsCode with some extensions, including the official C++ one. That gives me access to syntax highlighting and [intellisense](https://code.visualstudio.com/docs/editor/intellisense). In order to work properly however, the extension needs access to the definitions of classes, functions etc. which are normally to be found in header files (at least in c/c++). My question revolved around an easy to use location of these headers when using [Bazel](https://bazel.build) so I can tell the C++ extension (in VsCode) where to look for them.

When you mentioned 'something like google translate for code' you probably meant a so called _transpiler_, which is not what I am going for. I have however made one from [Python->Racket(Scheme)](https://github.com/coronon/pyschemetranspiler)

Welcome to the community, hope you have an awesome start with programming :)

PS: May I ask why you start with something like abseil when you are new to programming or C++ in general? It is quite the challenging language, maybe try [Python](https://www.python.org) (which also has an abseil package).

**Comment by themarwhal** [comment]
Hey @Coronon, have you tried https://marketplace.visualstudio.com/items?itemName=StackBuild.bazel-stack-vscode-cc ? It essentially adds a command to generate a compilation database file that VSCode can use as a starting point. I use the extension above and the clangd extension, but I think it would probably work with the official C++ extension as well!

**Comment by Coronon** [comment]
> Hey @Coronon, have you tried https://marketplace.visualstudio.com/items?itemName=StackBuild.bazel-stack-vscode-cc ? It essentially adds a command to generate a compilation database file that VSCode can use as a starting point. I use the extension above and the clangd extension, but I think it would probably work with the official C++ extension as well!

WOW 🤩

This is such an awesome tip! I never used clangd before, neither did I try clang (always gcc). But I really have to say: The tooling is awesome! The IDE hints are so much better than those the normal C++ extension can provide. They are also much faster, so I'm definitely sticking with clangd now.

Thank you heaps @themarwhal

**Comment by Coronon** [comment]
Little tip for those that have own libraries in some `vendor` subdir when you use the recommended _StackBuild.bazel-stack-vscode-cc_ extension: You should exclude them in the specified targets because the extension can't figure out visibility properly when treating them as "internal", they will be pulled in over dependencies from other targets. Exclude them like so:

```json
{
    // ...
    "bsv.cc.compdb.targets": [
        "--config=clang_config", // custom tooling config
        "--",
        "//...",
        "-//vendor/..." // folder with "external" repos
    ]
}
```

PS:
There is also [this](https://github.com/hedronvision/bazel-compile-commands-extractor) extension recommended on the official [clangd site](https://clangd.llvm.org/installation).
