### ISSUE TITLE
Chromium base::NoDestructor<T>

### ISSUE THREAD

**Issue by sabbakumov** [abseil/abseil-cpp#103]
What do you think of Chromium's base::NoDestructor<T> for local static variables (https://cs.chromium.org/chromium/src/base/no_destructor.h?q=base/no_d&sq=package:chromium&l=1)
So, instead of
```
std::string& Foo() {
  static std::string* str = new std::string();
  return *str;
}
```

one can write:
```
std::string& Foo() {
  static NoDestructor<std::string> str;
  return *str;
}
```

There's no malloc and pointer indirection.
What do you think of adopting NoDestructor to Abseil?

**Comment by derekmauro** [comment]
Everything in Abseil is widely used in Google's production codebase. While Chromium is a Google project, it isn't the same codebase as our production codebase, and our production codebase doesn't have `base::NoDestructor`. We aren't considering anything that we have no experience with in our production codebase at this time.

**Comment by tituswinters** [comment]
We may want to revisit this - there is a very similar class in light use internally and some discussion about changing some style guide / TotW recommendations to rely upon it more heavily.  I think it wouldn't be shocking if we chose to ship one, it's just not on the roadmap.
