### ISSUE TITLE
anyway to build abseil as a whole

### ISSUE THREAD

**Issue by willmafh** [abseil/abseil-cpp#104]
I use opencensus-cpp in my project, but it depends abseil, therefore I use bazel to build abseil then copy many .so libs into the project's structure and then I have to use many -lXXX, I am wondering whether there is a way to build each parts of abseil into a whole one like libabseil.so and then I can link it directly with option -labseil...Another part that confuse me is CMake support...I read the doc but could not figure it out how to build it...Can't it be something like cmake -f ... I am just curious ...Thanks for the work anyway ...

**Comment by derekmauro** [comment]
I don't think we are going to provide a way to build Abseil as a whole, we'd rather you pick the parts you care about. However, you can probably create your own rule to build everything you care about into one .so, see https://github.com/bazelbuild/bazel/issues/1920#issue-182071880.

@JonathanDCohen, please see the question on CMake.

**Comment by JonathanDCohen** [comment]
I'm confused.  opencensus-cpp builds with Bazel and has Abseil in their WORKSPACE file, so you should just be able to build that with Bazel and Bazel should take care of the dependency.

**Comment by JonathanDCohen** [comment]
Hey there.  Is this issue still causing you trouble?

**Comment by JonathanDCohen** [comment]
I'm going to close this due to lack of answer.  As a note for future readers, Bazel provides absl/... and cmake provides an `all` target.  I'm not sure if these create a single library or not, but it's worth a look.
