### ISSUE TITLE
Over-aligned type causes test failures

### ISSUE THREAD

**Issue by miladfarca** [abseil/abseil-cpp#1044]
This test case can causes compilation warnings depending on the compiler/platform:
https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/layout_test.cc#L1350
```
 warning: requested alignment 16 is larger than 8
```
`alignas(2 * M) ` is creating an over-aligned type which makes the behaviour implementation defined and potentially unsupported on some platforms.

Currently it is causing a test failure on PPC and S390 due to this line:
https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/layout.h#L483
The value is byte aligned whereas `alignment` is equal to `16`.

I was wondering if this test case can be refactored, guarded to be platform specific or removed to fix the above two issues?

**Comment by miladfarca** [comment]
@derekmauro Hi Derek, would you have a suggestion on the best way we can fix this issue?

**Comment by derekmauro** [comment]
That's a good question. Off the top of my head I'm not sure if Abseil uses any over-aligned types in code that isn't platform specific. I do think we want to ensure that `Layout` works with over-aligned types when supported by the platform. It might be sufficient to create a `#define` for platforms that support over-alignment and use it in some kind of `static_assert` about the alignment in `Layout`. But I'll ask around and see if anyone has a better idea.

**Comment by jyknight** [comment]
Looks like this was a GCC bug, fixed in GCC 10 and the 9.3 patch release, see https://gcc.gnu.org/PR89357. A workaround would be to use `__attribute__((aligned(N)))` for those older versions, rather than `alignas(N)`.

**Comment by miladfarca** [comment]
Thank you for the suggestion, this does fix the warning and passes the test, however I'm wonder if this falls under undefined behaviour as it's greater than `std::max_align_t`?

**Comment by jyknight** [comment]
It is implementation-defined whether "extended alignment" (alignments greater than max_align_t) are supported -- and a program which requests an extended alignment which the implementation does not support is deemed to be ill-formed (which means a diagnostic is required). This is not "undefined behavior", but is potentially non-portable.

In practice, compiler support for over-aligned types is pretty much universal.

The bug in GCC was that it was trying to implement said standards requirement, but did so incorrectly. GCC did in fact support over-aligned types all along, yet was emitting a diagnostic (and ignoring the alignas) as if it did not.

**Comment by miladfarca** [comment]
Thank you for the information, I have created this PR: https://github.com/abseil/abseil-cpp/pull/1049

**Comment by derekmauro** [comment]
Fixed by #1049
