### ISSUE TITLE
undefined reference to `absl::variant_internal::ThrowBadVariantAccess()'

### ISSUE THREAD

**Issue by Quincunx271** [abseil/abseil-cpp#105]
Abseil recently added `absl::variant`. Unfortunately, it appears that the source file that defines `absl::variant_internal::ThrowBadVariantAccess()` wasn't added to the github project.

I get this linker error:

```
/<path-to-absl>/absl/types/internal/variant.h:261: undefined reference to `absl::variant_internal::ThrowBadVariantAccess()'
```

**Comment by derekmauro** [comment]
I haven't tried this myself, @zhangxy988 knows most about this, but I do see https://github.com/abseil/abseil-cpp/blob/faf0a1b90374eab44e8956973b0e13febdcf3377/absl/types/bad_variant_access.cc#L37. How are you building this?

**Comment by Quincunx271** [comment]
Ehh, I just forgot to link with `absl::variant` (CMake). Strangely enough, there is no `absl::bad_variant_access` like there is `absl::bad_optional_access` and `absl::bad_any_cast`
