### ISSUE TITLE
NominalCPUFrequency Test from SysInfoTest Suite Fails on M1 Mac

### ISSUE THREAD

**Issue by anthonygraca** [abseil/abseil-cpp#1053]
**Describe the bug**

When running abseil tests, the ```NominalCPUFrequency``` test from the ```SysInfoTest``` test suite fails from ```absl/base/internal/sysinfo_test.cc```. 

**Steps to reproduce the bug**

The command that I ran specifically on my M1 MacBook Pro is:
```
bazel test --test_tag_filters=-benchmark --test_output=errors @com_google_absl//...
```
The failing test should show as:
```
FAIL: //absl/base:sysinfo_test (see /private/var/tmp/_bazel_anthonygraca/e02ebe8c94fcab7aaef2c566ce188ffa/execroot/com_google_absl/bazel-out/darwin_arm64-fastbuild/testlogs/absl/base/sysinfo_test/test.log)
INFO: From Testing //absl/base:sysinfo_test:
==================== Test output for //absl/base:sysinfo_test:
Running main() from gmock_main.cc
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from SysinfoTest
[ RUN      ] SysinfoTest.NumCPUs
[       OK ] SysinfoTest.NumCPUs (0 ms)
[ RUN      ] SysinfoTest.NominalCPUFrequency
absl/base/internal/sysinfo_test.cc:57: Failure
Expected: (NominalCPUFrequency()) >= (1000.0), actual: 1 vs 1000
NominalCPUFrequency() did not return a reasonable value
[  FAILED  ] SysinfoTest.NominalCPUFrequency (0 ms)
[ RUN      ] SysinfoTest.GetTID
[       OK ] SysinfoTest.GetTID (23 ms)
[----------] 3 tests from SysinfoTest (23 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (23 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SysinfoTest.NominalCPUFrequency

 1 FAILED TEST
================================================================================
```

**What version of Abseil are you using?**
Head: Commit [d6c75d9](https://github.com/abseil/abseil-cpp/commit/d6c75d9dd895922bf5dc6c38245ac8887d3e68fc)

**What operating system and version are you using**

macOS Monterey 12.0.1

**What compiler and version are you using?**

```
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: arm64-apple-darwin21.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**What build system are you using?**

``` bazel 5.0.0-pre.20211011.2 ```

**Additional context**

It looks like the code that causes the issue is from ```absl/base/internal/sysinfo.cc``` between lines 177 - 186 in function ```GetNominalCPUFrequency()```.

The root cause stems from line 181 where ```if(sysctl(mib, 2, &freq, &size, nullptr, 0) == 0)``` evaluates to false, so that causes the function to never return freq. If we ignored the check and just returned the value in freq anyways, the test passes but I am not sure if that is an appropriate solution. 

It looks like the sysctl() call returns an error status of ENOENT, meaning the input to the first parameter of sysctl() is invalid. However both values in the mib[2] array, CTL_HW and HW_CPU_FREQ are defined, so I am not sure why this is the problem. I think this may be a bug with macOS itself because this behavior can be replicated outside of abseil in an external program. Any ideas on how to approach this problem?

**Comment by derekmauro** [comment]
You may want to see my comments in #728. If the only problem you are trying to solve is a failing test, this is safe to ignore since this code is never called. I should consider stripping this test out of the open source release. NominalCPUFrequency is only called in code private to Google and we do have tests on the platforms we use it on.

**Comment by anthonygraca** [comment]
Thanks @derekmauro for looking into this and thank you for links to your prior comments. I will be more thorough on my search next time. 

Do you have any recommendations for development workflow? I could temporarily DISABLE_* the failing tests (there are two other tests that fail but I just wanted to make an issue with this one) but I am not sure how to separate signal from noise if the failing tests turn out to be an actual issue. 

Would it be helpful for you if I made a PR on removing the NominalCPUFrequency code?

**Comment by derekmauro** [comment]
I will have to see what I can do, but please do not remove the NominalCPUFrequency code.
