### ISSUE TITLE
Tracking Issue: Abseil CMake Support

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#106]
There's been a lot of scattered discussion with respect to Abseil's CMake support.  We are now prepared to offer a sequence of milestones for Abseil's CMake support.  This tracking issue is meant to be a place of discussion on this sequence and a message board for when we are going to make potentially-breaking changes to our CMake files.  Individual milestones will be tracked in the [Abseil CMake Support Project](https://github.com/abseil/abseil-cpp/projects/1) as separate issues, for more detailed discussion.

**Comment by JonathanDCohen** [comment]
Step 1: Drop our cctz dependency.  This is finished, and as such abseil is now completely self-contained aside from googletest dependencies in testing.

**Comment by asoffer** [comment]
All issues have been completed.
