### ISSUE TITLE
CMake Build failure on Debian 8 complaining on SYS_connect

### ISSUE THREAD

**Issue by veblush** [abseil/abseil-cpp#1064]
**Describe the bug**

gRPC build with the head version (299f59c) of Abseil failed with the following error. Although Debian 8 is a bit out dated, gRPC is using Debian/8 docker image to run the test.

```
/var/local/git/grpc/third_party/abseil-cpp/absl/debugging/internal/address_is_readable.cc: In function 'bool absl::debugging_internal::AddressIsReadable(const void*)':
/var/local/git/grpc/third_party/abseil-cpp/absl/debugging/internal/address_is_readable.cc:75:30: error: 'SYS_connect' was not declared in this scope
       ABSL_RAW_CHECK(syscall(SYS_connect, fd, addr, 1) == -1,
                              ^
/var/local/git/grpc/third_party/abseil-cpp/absl/base/optimization.h:177:59: note: in definition of macro 'ABSL_PREDICT_FALSE'
 #define ABSL_PREDICT_FALSE(x) (__builtin_expect(false || (x), false))
                                                           ^
/var/local/git/grpc/third_party/abseil-cpp/absl/debugging/internal/address_is_readable.cc:75:7: note: in expansion of macro 'ABSL_RAW_CHECK'
       ABSL_RAW_CHECK(syscall(SYS_connect, fd, addr, 1) == -1,
```

**Steps to reproduce the bug**

I think this can be reproducible by building cmake-build on Debian 8 Linux.

**What version of Abseil are you using?**

Commit: 299f59c

**What operating system and version are you using**

Debian 8 docker image

**What compiler and version are you using?**

gcc 4.9

**What build system are you using?**

N/A

**Additional context**

N/A

**Comment by derekmauro** [comment]
Debian 8 is EOL and GCC 4.9 is unsupported. Is gRPC really still supporting it?

**Comment by veblush** [comment]
gRPC still supports gcc 4.9 (I'm open to bumping this next year, though) but we're in process of moving away from Debian 8 on test fleet. If Debian 8 is the only Linux distribution with this issue, I'm okay with leaving it. 

I think `SYS_connect` should exist even on Debian 8 since it's a pretty old syscall. Is it the case where proper #include is missing? or some syscall package is not installed on my test environment?

**Comment by derekmauro** [comment]
The proper header is included. The `SYS_*` names come from glibc. It might be present in the kernel, but not glibc. Also, it may not be present on all architectures. What CPU is this being built for?

**Comment by veblush** [comment]
This only applies to x86 (32bits) build on Debian:8. I checked the syscall.h header file on both Debian 8 and Debian 9 and Debian 8 doesn't have `SYS_connect` definition for x86. But Debian 9 does.

**Comment by veblush** [comment]
gRPC changed its 32bits test to use Debian:9 instead of Debian:8 and gRPC is now good so I'm closing this.
