### ISSUE TITLE
erase_if for absl:: containers should probably return the number of erased elements

### ISSUE THREAD

**Issue by moskupols** [abseil/abseil-cpp#1065]
**Describe the bug**

C++20 standard describes a function template `size_type erase_if(unordered_set&, Pred)` that erases elements based on a predicate and _returns the number of erased elements_: https://en.cppreference.com/w/cpp/container/unordered_set/erase_if .
A similar function template is available for std::unordered_map.

Abseil provides `erase_if` overloads for {flat_hash,node_hash,btree}_{set,map}. However, these overloads return void.

I realize that absl containers should not be considered as drop-in replacement for STL containers. However, they are designed to have a very similar interface, and I think in this case bringing the interface closer would only help with adoption of absl containers in existing codebases.

Looking at the code, it seems like this can be implemented in a generic way that doesn't depend on internal implementation of the containers. As an example, we could remember the size of the container in the beginning of erase_if and subtract the new size from it after removal.

This would however technically be an API break since someone could do compile-time logic based on return value of erase_if.

**Steps to reproduce the bug**

https://godbolt.org/z/7qTbhdWPe

**What version of Abseil are you using?**

trunk on godbolt.org

**What operating system and version are you using**

Irrelevant

**What compiler and version are you using?**

gcc 10.3

**What build system are you using?**

godbolt.org

**Additional context**

**Comment by derekmauro** [comment]
Thanks for letting us know. I'm going to gather some real-world data about the impact of the possible API break.

**Comment by derekmauro** [comment]
I've made this change. It should hopefully end up on GitHub tomorrow.

**Comment by mohammed755** [comment]
Re: ترويج https://www.patreon.com/_kataaaphhttps://t.co › DnrGObHyU2 خطابة
#سعودية #مسيار للتوصل 0507281379 - t.co / Twithttps://
www.patreon.com/_kataaaphter [ref:00DA0000000K0A8.5004w00002HIlo9:ref]

في الثلاثاء، ٣٠ نوفمبر ٢٠٢١ ١٠:٤٣ م Derek Mauro ***@***.***>
كتب:
