### ISSUE TITLE
Failed to compile under c++11

### ISSUE THREAD

**Issue by monadbobo** [abseil/abseil-cpp#1071]
Environment:

OS: centos 8.2.2
GCC: gcc version 8.4.1 20200928
abseil: Abseil LTS 20211102
stdc++: 3.4.x

Here I set the c++ version to c++11, but if I use c++14 then everything will be ok.

Error message:

> In file included from /data/workspace/test-lib/extern/abseil/absl/container/internal/inlined_vector.h:31,
                 from /data/workspace/test-lib/extern/abseil/absl/container/inlined_vector.h:54,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.h:57,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.cc:14:
/data/workspace/test-lib/extern/abseil/absl/memory/memory.h: In instantiation of 'typename absl::memory_internal::MakeUniqueResult<T>::scalar absl::make_unique(Args&& ...) [with T = absl::InlinedVector<absl::status_internal::Payload, 1>; Args = {absl::InlinedVector<absl::status_internal::Payload, 1, std::allocator<absl::status_internal::Payload> >&}; typename absl::memory_internal::MakeUniqueResult<T>::scalar = std::unique_ptr<absl::InlinedVector<absl::status_internal::Payload, 1> >]':
/data/workspace/test-lib/extern/abseil/absl/status/status.cc:243:77:   required from here
/data/workspace/test-lib/extern/abseil/absl/memory/memory.h:171:13: error: no matching function for call to 'std::__cxx11::basic_string<char>::basic_string(absl::InlinedVector<absl::status_internal::Payload, 1>&)'
       new T(static_cast<const std::string>(std::forward<Args>(args))...));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/8/string:52,
                 from /usr/include/c++/8/bits/locale_classes.h:40,
                 from /usr/include/c++/8/bits/ios_base.h:41,
                 from /usr/include/c++/8/ios:42,
                 from /usr/include/c++/8/ostream:38,
                 from /usr/include/c++/8/iostream:39,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.h:54,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.cc:14:
/usr/include/c++/8/bits/basic_string.h:614:9: note: candidate: 'template<class _InputIterator, class> std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(_InputIterator, _InputIterator, const _Alloc&)'
         basic_string(_InputIterator __beg, _InputIterator __end,
         ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:614:9: note:   template argument deduction/substitution failed:
In file included from /data/workspace/test-lib/extern/abseil/absl/container/internal/inlined_vector.h:31,
                 from /data/workspace/test-lib/extern/abseil/absl/container/inlined_vector.h:54,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.h:57,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.cc:14:
/data/workspace/test-lib/extern/abseil/absl/memory/memory.h:171:13: note:   candidate expects 3 arguments, 1 provided
       new T(static_cast<const std::string>(std::forward<Args>(args))...));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/8/string:52,
                 from /usr/include/c++/8/bits/locale_classes.h:40,
                 from /usr/include/c++/8/bits/ios_base.h:41,
                 from /usr/include/c++/8/ios:42,
                 from /usr/include/c++/8/ostream:38,
                 from /usr/include/c++/8/iostream:39,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.h:54,
                 from /data/workspace/test-lib/extern/abseil/absl/status/status.cc:14:
/usr/include/c++/8/bits/basic_string.h:576:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(basic_string&& __str, const _Alloc& __a)
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:576:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:572:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(const basic_string& __str, const _Alloc& __a)
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:572:7: note:   candidate expects 2 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:568:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::initializer_list<_Tp>, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(initializer_list<_CharT> __l, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:568:7: note:   no known conversion for argument 1 from 'absl::InlinedVector<absl::status_internal::Payload, 1>' to 'std::initializer_list<char>'
/usr/include/c++/8/bits/basic_string.h:541:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(basic_string&& __str) noexcept
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:541:7: note:   no known conversion for argument 1 from 'absl::InlinedVector<absl::status_internal::Payload, 1>' to 'std::__cxx11::basic_string<char>&&'
/usr/include/c++/8/bits/basic_string.h:529:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, _CharT, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
       basic_string(size_type __n, _CharT __c, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:529:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:514:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(const _CharT* __s, const _Alloc& __a = _Alloc())
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:514:7: note:   no known conversion for argument 1 from 'absl::InlinedVector<absl::status_internal::Payload, 1>' to 'const char*'
/usr/include/c++/8/bits/basic_string.h:499:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
       basic_string(const _CharT* __s, size_type __n,
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:499:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:481:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:481:7: note:   candidate expects 4 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:465:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:465:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:450:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&, std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]'
       basic_string(const basic_string& __str, size_type __pos,
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:450:7: note:   candidate expects 3 arguments, 1 provided
/usr/include/c++/8/bits/basic_string.h:437:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(const basic_string& __str)
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:437:7: note:   no known conversion for argument 1 from 'absl::InlinedVector<absl::status_internal::Payload, 1>' to 'const std::__cxx11::basic_string<char>&'
/usr/include/c++/8/bits/basic_string.h:429:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string(const _Alloc& __a) _GLIBCXX_NOEXCEPT
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:429:7: note:   no known conversion for argument 1 from 'absl::InlinedVector<absl::status_internal::Payload, 1>' to 'const std::allocator<char>&'
/usr/include/c++/8/bits/basic_string.h:420:7: note: candidate: 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]'
       basic_string()
       ^~~~~~~~~~~~
/usr/include/c++/8/bits/basic_string.h:420:7: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [extern/abseil/absl/status/CMakeFiles/absl_status.dir/build.make:82: extern/abseil/absl/status/CMakeFiles/absl_status.dir/status.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3841: extern/abseil/absl/status/CMakeFiles/absl_status.dir/all] Error 2

**Comment by derekmauro** [comment]
I cannot reproduce this problem. Please provide all steps necessary to get a build into the same state as yours including all build commands.

**Comment by monadbobo** [comment]
Sorry, it's my problem, I can compile successfully after cleaning up the directory.
