### ISSUE TITLE
cmake test flags may need an update in the quick start documentation

### ISSUE THREAD

**Issue by miladfarca** [abseil/abseil-cpp#1079]
`ABSL_BUILD_TESTING` flag was added in this PR: https://github.com/abseil/abseil-cpp/commit/fb7dd24b18e82893e5922be5d1c8ae0f3fe3c9fa
However not all the README files may have been updated to include this new flag, an example is this file: 
https://github.com/abseil/abseil.github.io/blob/master/docs/cpp/quickstart-cmake.md which gets loaded in this url: https://abseil.io/docs/cpp/quickstart-cmake.html

/cc @matta

**Comment by derekmauro** [comment]
I've submitted a change to the docs. It should make it to GitHub soon.

**Comment by miladfarca** [comment]
@derekmauro Thank you for the information.
