### ISSUE TITLE
Step 3: Update Minimum Required Version

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#108]
Abseil currently requires an ancient version of CMake.  We need to support at least CMake 3.0.0 as the first "modern" release of CMake.  We be slightly stricter if there are some critical bugfixes after 3.0.0, but as a low-level library we need to be very careful about bumping this number upwards.

This is sequenced right after tests as about the smallest change we could make to give a run to our testing infrastructure.  It is also something we want to do sooner rather than later as we want to avoid breaking users over this as much as possible.

**Comment by JonathanDCohen** [comment]
#106

**Comment by JonathanDCohen** [comment]
The current thought is to set our minimum_required_version to cmake 3.1.2 to allow us to use CMAKE_CXX_STANDARD directly as opposed to our kludgey ABSL_STD_CXX_FLAG.  We are very curious who and how this may break people and would like to hear thoughts on the matter

**Comment by JonathanDCohen** [comment]
That plan was taken.  We now use standard env and Cmake variables where we can.  This includes $CC and $CXX to set the compiler, and the use of CMAKE_CXX_STANDARD.  We don't use the CXX_STANDARD flag anywhere else so abseil should adapt language level to whatever project it is compiled as a part of.

**Comment by MikeGitb** [comment]
@JonathanDCohen: AFAIK, ABSL_STD_CXX_FLAG is still used:

https://github.com/abseil/abseil-cpp/blob/bea85b52733022294eef108a2e42d77b616ddca2/CMakeLists.txt#L57-L58

Are you refering to some internal branch of abseil?
