### ISSUE TITLE
The Mix function fallback for arm64 is too weak in diffusion

### ISSUE THREAD

**Issue by renzibei** [abseil/abseil-cpp#1093]
**Describe the bug**

The [Mix function](https://github.com/abseil/abseil-cpp/blob/c59e7e59f5d29619ddc07fcb59be3dcba9585814/absl/hash/internal/hash.h#L915-L932) uses an alternative solution on arm64 architecture, with a note in the comments that uint128_t multiplication is too slow for arm64 cpus because two instructions are required.

However, the alternative provided as a function of mixing bits does a poor job of diffusion.

Below is what is does on arm64 platform(some comments were omitted):

```c++
ABSL_ATTRIBUTE_ALWAYS_INLINE static uint64_t Mix(uint64_t state, uint64_t v) {
    using MultType = uint64_t;
    MultType m = state + v;
    m *= kMul;
    return static_cast<uint64_t>(m ^ (m >> (sizeof(m) * 8 / 2)));
  }
```

Basically, there are three steps,
1. Add `state` and `v` with `m = state + v`. 
2. Multiply m by a constant `m *= kMul`. 
3. XOR the upper 32 bits and the lower 32 bits of m as the new lower 32 bits `m ^= (m >> 32)`. And return m as the Mix value. 

If we specify that the highest bit of a uint64_t type is the 64th bit and the lowest bit is the 1st bit. The problem with this function is that the i-th bit of state and the i-th bit of v (i is greater than 33) do not affect the final bits from i - 1 to 33 and from i - 33 to 1. For example, the value of 64-th bit of state will only affect bits 64 and 32 of the return value. This makes Mix's diffusion as an important part of the hash function (and the only part of integer hashing) very weak.

In particular, if only the high-order bits of the input keys are different, and the low-order bits are all the same, then using it as a hash function will have a lot of collisions. And this input feature is actually very common. Examples are pointers and 64-bit integers made with shorter keys.

The results in [this benchmark](https://github.com/renzibei/hashtable-bench#kv-uint64_t-with-bits-in-low-position-masked-out-uint64_t) further confirmed this. The following figure is the lookup test results from that benchmark. Please focus on the performance of `absl::flat_hash_map` with `absl::Hash`.

![mask_low_bits_uint64_t,uint64_t ,avg_hit_find_with_rehash](https://user-images.githubusercontent.com/31380016/150161698-62b5c456-7806-458d-bc8a-6221dde879e1.png)

**Steps to reproduce the bug**

Refer to the linked [benchmark code](https://github.com/renzibei/hashtable-bench#kv-uint64_t-with-bits-in-low-position-masked-out-uint64_t). The "uint64_t with bits in low position masked out, uint64_t" part shows the poor performance.

**What version of Abseil are you using?**

c59e7e59f5d29619ddc07fcb59be3dcba9585814

**What operating system and version are you using**

macOS 12.1 arm64

**What compiler and version are you using?**

```
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What build system are you using?**

```
cmake version 3.22.1
```

**Comment by renzibei** [comment]
The [Mix function](https://github.com/abseil/abseil-cpp/blob/9bb42857112ad13b23de4333fbb75eb47db9de95/absl/hash/internal/low_level_hash.cc#L25-L40) used in low level hash also suffers from quality problem.

**Comment by derekmauro** [comment]
We have another report of this internally (b/204369943). I will forward this information.

**Comment by atdt** [comment]
Thanks for this! Your analysis is correct. To echo my comment on your pull request (#1094), I'd like to find a way to fix this that does not require re-introducing the 64x64→128 bit multiply, because of its poor performance on the Arm Neoverse microarchitecture. Is there a way we can get good diffusion and still stick to efficient 64-bit arithmetic?

**Comment by renzibei** [comment]
@atdt Thanks for your reply. 

I think if one can find a Mix function that doesn't require two multiplication instructions for 64x64->64 but achieves similar quality and at least not slower, that will improve the efficiency of many multiplication based hash functions. But based on the fact that I haven't found such a multiplication-based hash function using less than two multiplication in the mix function, I suspect that the difficulty of finding such a function is high.

I once found [a blog](http://jonkagstrom.com/bit-mixer-construction/index.html) tried to analyze this problem in an experimental way. Although the three related articles on this blog do not mathematically prove that a 64x64->64 multiply instruction and a few simple instructions cannot be combined into a hash function with good properties, its empirical analysis is partially corroborated to the difficulty of finding such a hash function.

**Comment by morinmorin** [comment]
I also encountered this when running a benchmark in [joaquintides/fxa_unordered](/joaquintides/fxa_unordered). Turning off the special handling of AArch64 improves benchmark results (on Apple M1 Pro) from
```
[uint64.cpp] absl::node_hash_map: 5208 ms, absl::flat_hash_map: 3759 ms
```
to
```
[uint64.cpp] absl::node_hash_map: 3873 ms, absl::flat_hash_map: 2903 ms
```
Thank you for the analysis and PR.

**Comment by renzibei** [comment]
> The [Mix function](https://github.com/abseil/abseil-cpp/blob/9bb42857112ad13b23de4333fbb75eb47db9de95/absl/hash/internal/low_level_hash.cc#L25-L40) used in low level hash also suffers from quality problem.

The last PR https://github.com/abseil/abseil-cpp/pull/1094 fixed the problem of `Mix` function which is used in integer hashing and state mixing. The [Mix function used in low level hash function](https://github.com/abseil/abseil-cpp/blob/3204cc0625230e9876f0310a6dea0014210ab325/absl/hash/internal/low_level_hash.cc#L25-L40) (which is used for strings and bytes arrays) is not fixed yet.  The current version of low level hash function for strings does not have good hash quality on aarch64 due to the weak Mix function, and won't pass some hash tests like [smhasher](https://github.com/rurban/smhasher).

There are two quick fixes. One is to revert the fallback on aarch64 temporarily, like what we did in last PR. The other is to change [the condition](https://github.com/abseil/abseil-cpp/blob/3204cc0625230e9876f0310a6dea0014210ab325/absl/hash/internal/hash.h#L1110-L1117) that switches the hash function for bytes array to `CityHash64` i.e. using CityHash64 on aarch64. It should be noted that CityHash64 does not pass the smhasher currently.
