### ISSUE TITLE
Compilation failure in absl/container/internal/inlined_vector.h with NVCC

### ISSUE THREAD

**Issue by suryakiran** [abseil/abseil-cpp#1099]
**Describe the bug**

When including `absl/container/flat_hash_set.h` in a cuda source file and compiling the source file with `nvcc (11.4.1)` and `gcc (9.3.0)`, the compilation fails with the following error.

`/usr/local/packages/rez/abseil/2021.11.2/gcc-9.3.0/include/absl/container/internal/inlined_vector.h:907:97: error: expected ‘;’ before ‘}’ token`

**Steps to reproduce the bug**

Include `absl/container/flat_hash_set.h` in a cuda source file and compile with nvcc. Attached `CMakeLists.txt`, `test.cpp` (as test.cpp.txt) and `test.cu` (as test.cu.txt) to reproduce the problem.

It's important that we are able to reproduce the problem that you are
experiencing. Please provide all code and relevant steps to reproduce the
problem, including your `BUILD`/`CMakeLists.txt` file and build commands. Links
to a GitHub branch or [godbolt.org](https://godbolt.org/) that demonstrate the
problem are also helpful.

**What version of Abseil are you using?**
Abseil LTS 20211102

**What operating system and version are you using**
5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

If you are using a Linux distribution please include the name and version of the
distribution as well.

Ubuntu 20.04

**What compiler and version are you using?**

Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.

COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

**What build system are you using?**
`cmake version 3.21.1`
[CMakeLists.txt](https://github.com/abseil/abseil-cpp/files/7921001/CMakeLists.txt)
[test.cpp.txt](https://github.com/abseil/abseil-cpp/files/7921003/test.cpp.txt)
[test.cu.txt](https://github.com/abseil/abseil-cpp/files/7921004/test.cu.txt)

Please include the output of `bazel --version` or `cmake --version`, or the
equivalent for your build system.

**Additional context**

**Comment by Liu-xiandong** [comment]
I get the same error

**Comment by derekmauro** [comment]
I'm guessing the reason TensorFlow has this patch <https://github.com/tensorflow/tensorflow/blob/da83132aba8d2b6a3c3a9b2e662868eb24f4dd1e/third_party/absl/com_google_absl_fix_mac_and_nvcc_build.patch#L243-L256> is to deal with this issue.

I'm not setup with the compiler you are using, but if someone could verify that this fixes the issue I will patch our code.

**Comment by suryakiran** [comment]
This patch is working.

**Comment by derekmauro** [comment]
Thank you for confirming. A patch is coming.

**Comment by derekmauro** [comment]
Fixed in 5202173ca7671ebe241cb4d9447dc4b1f2d3ec10.

**Comment by suryakiran** [comment]
Thanks much for the fix. I'd like to know if there is any patch for the LTS coming up or should I use the master ?

**Comment by derekmauro** [comment]
This won't be patched in the LTS. We actually recommend living at head and updating frequently.

**Comment by suryakiran** [comment]
Thanks for the confirmation. And once again, thank you for the patch. I'll use the master.
