### ISSUE TITLE
Implementing to_chars like function

### ISSUE THREAD

**Issue by gvollant** [abseil/abseil-cpp#1109]
absl/strings/charconv.cc implements a c++17 like vers fast from_chars

I did not found a fast to_chars to have a fast integer to string conversion.

Is it planned?

regards

**Comment by derekmauro** [comment]
It sounds like you are looking for https://github.com/abseil/abseil-cpp/blob/master/absl/strings/str_cat.h

```
int x = ...;
std::string s = absl::StrCat(x);
```

Does this work for you?

**Comment by gvollant** [comment]
This is perfect, thank you!
