### ISSUE TITLE
Step 6: Allow Abseil to be installed and used with find_package()

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#111]
This has been a contentious one, but yes, Abseil is going to support the `git clone; make; make install` workflow.

This will come at the same time as Abseil cuts our first Long Term Support Branch -- basically cuts of our source code stuck in versioned inline namespaces which we will maintain for a length of time with emergency security bugfixes and the like, and which will also be tagged for use by package managers and the like.  Ideally, the `find_package()` workflow will only work with Long Term Support branches of Abseil -- it's the only safe way to use a precompiled version of abseil, as we can make sure that symbols don't clash unless they're identical (as long as they're compiled and linked with the same settings, etc).  So the supported usages of abseil will be either live-at-head using Bazel, a mirror, a git submodule, or config-time downloading of source as in googletest's model, or using a precompiled Long Term Support branch of Abseil.  It's unclear as of yet how this can be accomplished -- discussion on this point will happen closer to the point in time we're ready for this step.

**Comment by JonathanDCohen** [comment]
#106

**Comment by darix** [comment]
+1

**Comment by pifon2a** [comment]
Are there any updates? [Google Cartographer](https://github.com/googlecartographer/cartographer) project now depends on Abseil. Unfortunately, since we are using ROS and catkin, we have to maintain the CMake build as well. We ended up using `ExternalProject_Add` in [FindAbseil.cmake](https://github.com/googlecartographer/cartographer/blob/master/cmake/modules/FindAbseil.cmake), but it is not optimal. Really looking forward to having `make install` in Abseil.

**Comment by alexweej** [comment]
Is there any "work in progress" branch for this? I'm having a little stab myself in order to integrate with our organization's packaging system.

**Comment by pifon2a** [comment]
@Mizux, are you planning to submit your CMake Install rules?

**Comment by Mizux** [comment]
@pifon2a The current plan is to push internally one by one all the #199 commits, then maybe revamp (i.e. rebase/rework) my `Add CMake Install rules (abseil#111)` on top of it...

We will remove `absl_test()`, `absl_library()`, `absl_headeronly_library()` and `absl_test()` so we will "just" have to add install rules on `absl_cc_library()` and `absl_cc_test()`...

**Comment by shardator** [comment]
is it now even possible to build Google Cartographer without internet access or a fake github repo?

**Comment by pifon2a** [comment]
Unfortunately, not yet. After abseil has proper support for  `make install`, it will be possible.

**Comment by JonathanDCohen** [comment]
This is finally live!  Thanks everyone for all the patience :)
