### ISSUE TITLE
ABSL_PROPAGATE_CXX_STD does not set standard correctly

### ISSUE THREAD

**Issue by h-vetinari** [abseil/abseil-cpp#1116]
Abseils ABI depends on the standard version used to compile (e.g. around `string_view`), so propagating the standard requirement of the produced binaries should reflect the standard used to compile. Currently it is set to the meta-feature `cxx_std_11` unconditionally.

It might also be a good idea to add this to the windows DLL build.

**Comment by h-vetinari** [comment]
This should have been closed by https://github.com/abseil/abseil-cpp/commit/308bbf300fe9332130f4784c7a91fa2ad707d6e4, but AFAICT, the C++ standard is not propagated for shared windows builds (see `CMake/AbseilDll.cmake`), c.f. also the diff of https://github.com/abseil/abseil-cpp/pull/1117

CC @coryan

**Comment by coryan** [comment]
Doh!  Apologies.  I have prepared a change in the internal SCM.  I expect I should be able to send it for review later today.

**Comment by coryan** [comment]
@h-vetinari let me know if the changes don't work.

**Comment by h-vetinari** [comment]
> @h-vetinari let me know if the changes don't work.

Thanks for the super-quick handling! :)
