### ISSUE TITLE
CMake Refactor: Remove extra _test suffix

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#112]
All of our test binaries currently look like absl_foo_test_test because absl_test adds _test at the end, but we already have a convention of suffixing our test names with _test.  This isn't the worst thing in the world, but it's annoying and easy to fix.

**Comment by zach2good** [comment]
Has this been completed? test binaries are now in the form `absl_foo_test_bin`

**Comment by rongjiecomputer** [comment]
All CMake tests use `absl_cc_test` which does not add suffix to the name. Time to close this issue?
