### ISSUE TITLE
CMake Refactor: Remove Global Variables

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#113]
Our CMakeLists.txt files have many global variables in the form of default sources, default library dependencies, or just lists of sources and libraries.  These are verbose and unneeded at best, or antipatterns where we could instead use INTERFACE targets at worst.  These should be cleaned up so we have a minimal amount of global variables polluting the CMake namespace. Any globals we can't get rid of should be prefixed with ABSL_

**Comment by rongjiecomputer** [comment]
The number of global variables has been reduced to just a few that has `ABSL_` prefix, so this should not cause any trouble to CMake users. Time to close this issue?
