### ISSUE TITLE
abseil random double has much worse performance than stl

### ISSUE THREAD

**Issue by GOGOYAO** [abseil/abseil-cpp#1138]
```
// test absl
uint64_t test_count = 10000000UL;
absl::BitGen bitgen_;
for (size_t i = 0; i <test_count; i++) {
  absl::Uniform<double>(bitgen_, 0, 3);  
}

// test stl
std::random_device rd;
std::mt19937 gen(rd());
std::uniform_real_distribution<double> dis(0, 3);
for (size_t i = 0; i <test_count; i++) {
  dis(gen);
}
```
I tested the performance as above. But I found absl random has much worse performance(5x) than std random.

I tested the int random in the same way. And I found absl random has much better performance(10x) than std random.

**Comment by derekmauro** [comment]
Writing a good benchmark isn't so simple. Some compilers are smart enough to reason that certain operations don't have an effect on the result and are able to remove them. When you write a benchmark, you need to take care that this isn't happening. I rewrote your code to use the Google Benchmark framework. `benchmark::DoNotOptimize` is there to ensure that compiler can't remove that line.

```
#include <cstdint>
#include <random>
#include <benchmark/benchmark.h>
#include "absl/random/random.h"

static void BM_Absl(benchmark::State& state) {
  absl::BitGen bitgen;
  for (auto _ : state) {
    benchmark::DoNotOptimize(absl::Uniform<double>(bitgen, 0, 3));
  }
}
BENCHMARK(BM_Absl);

static void BM_Std(benchmark::State& state) {
  std::random_device rd;
  std::mt19937 gen(rd());
  std::uniform_real_distribution<double> dis(0, 3);
  for (auto _ : state) {
    benchmark::DoNotOptimize(dis(gen));
  }
}
BENCHMARK(BM_Std);
```

And the results:
```
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
BM_Absl          6.29 ns         6.29 ns     97571179
BM_Std           14.7 ns         14.7 ns     49109077
```

You can also take a look at and run the extensive suite of benchmarks we have at https://github.com/abseil/abseil-cpp/blob/master/absl/random/benchmarks.cc.

**Comment by GOGOYAO** [comment]
Thank you for your reply. I will try it again. @derekmauro

**Comment by GOGOYAO** [comment]
I test again with '-O2' and I get a much better performance with `absl::random`. If I use '-O3', I get the result as I mentioned before.
I am confused why random for double has much poorer performance in absl with `-O3`. In my opinion, absl should not has much poorer performance than stl.

**Comment by derekmauro** [comment]
I can't reproduce your results.
