### ISSUE TITLE
CMake Refactor: Update interface of absl_library()

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#114]
A long term goal for us is to be able to generate our CMakeLists.txt files from our Bazel BUILD files so as to relieve engineering overhead.  The first step for this is to make the corresponding cc_library and absl_library invocations in Bazel and CMake respectively have the same set of arguments, allowing us to easily generate one from the other.

**Comment by rongjiecomputer** [comment]
I believe this is done with `absl_cc_{library,test}` now. Time to close this issue?
