### ISSUE TITLE
How about to support specified hash value in flat_hash_map?

### ISSUE THREAD

**Issue by GOGOYAO** [abseil/abseil-cpp#1142]
If flat_hash_map could use the specified hash value to insert, I can use flat_hash_map to assemble a concurrent flat_hash_map just like `https://greg7mdp.github.io/parallel-hashmap/` does, in which hash value  will be calculated only once. 
So will this be supported? Or will a concurrent flat_hash_map be provided in absl ?

**Comment by derekmauro** [comment]
We do not intend to provide this, at least directly. You could probably get something similar by providing a custom hasher, and pairing your type with a hash value, and having the custom hasher simply return the hash value.

**Comment by GOGOYAO** [comment]
> We do not intend to provide this, at least directly. You could probably get something similar by providing a custom hasher, and pairing your type with a hash value, and having the custom hasher simply return the hash value.

I have thought about this method. But it will add extra bytes of memory. For example, I will add 8 bytes if I use std::pair<key, uint64_t> as the key in flat_hash_map.

So I think a better way is to support specified hash value in flat_hash_map.

**Comment by GOGOYAO** [comment]
And why not provide a concurrent flat_hash_map in absl?

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library

The answer is simply that we don't use either of these features.

**Comment by GOGOYAO** [comment]
> https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library
> 
> The answer is simply that we don't use either of these features.

get it. thank you

**Comment by GOGOYAO** [comment]
> features

I see some similar interface here https://github.com/abseil/abseil-cpp/blob/e854df09dfcb35056c1d42420028648ee0ebebaf/absl/container/internal/raw_hash_set.h#L1647. So this has been supported internally but not exposed to absl hash_map.

**Comment by derekmauro** [comment]
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1661r1.html explains a better way of doing this.
