### ISSUE TITLE
To Support abseil-cpp in QNX 

### ISSUE THREAD

**Issue by c6supper** [abseil/abseil-cpp#1143]
## To Support abseil-cpp in QNX 
Bring some fresh air to automotive industry.

## Background
I was porting gPRC-cpp to QNX arm based platform, 
When I cross compile the gRPC, I found the abseil-cpp is not compatible with QNX too, so I made changes and have been successfully port them to QNX 704 aarch. 

## Proposed API Change (s)
I just forked and made some changes on your branch lts_2020_02_25, which is a submodule for gRPC, I have made changes ,and please help to review ,if it's suitable for a pull request, thx.
[Changes](https://github.com/abseil/abseil-cpp/commit/b3cea002cc0900a86637e8a367810955d4b2d0ca)

**Comment by derekmauro** [comment]
Similar changes would be fine if applied to the main branch. Feel free to submit a pull request, or let me know and I can make the changes for you.

**Comment by c6supper** [comment]
> Similar changes would be fine if applied to the main branch. Feel free to submit a pull request, or let me know and I can make the changes for you.

Thanks for you quick response, pull request have been created.
Please help to review , if it's compatilbe to main branch, you could help to  merge  to it either, thx.
