### ISSUE TITLE
P0798: Monadic operations for std::optional

### ISSUE THREAD

**Issue by BenFrantzDale** [abseil/abseil-cpp#1150]
P0798 adds `transform`, `or_else`, and `and_then` to `std::optional` for C++23. http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0798r4.html#proposed-wording

Sy has an implementation here: https://github.com/TartanLlama/optional

I'd love to see these for `absl::optional`.

**Comment by derekmauro** [comment]
I don't think we intend to add much else in terms of future functionality so our polyfill types. By default they are not enabled for C++17 and beyond, and instead melt away to the standard types.

**Comment by BenFrantzDale** [comment]
> I don't think we intend to add much else in terms of future functionality so our polyfill types. By default they are not enabled for C++17 and beyond, and instead melt away to the standard types.

That’s a shame. We use yours over std since Apple Clang doesn’t have the value() exception. With the nomadic operations coming I’d like to stay on an implementation of the future standard. I guess we’ll pull in Sy’s.
