### ISSUE TITLE
CMake Upgrade: Create "Hello Abseil" CMake project

### ISSUE THREAD

**Issue by JonathanDCohen** [abseil/abseil-cpp#116]
The README should link to it.

**Comment by rockwotj** [comment]
Is there a "hello abseil" example for bazel? One that documents how to setup the correct copts and configuration setting from abseil?

**Comment by ahedberg** [comment]
Hi @rockwotj - are you looking for something different from https://abseil.io/docs/cpp/quickstart? Abseil aims to be zero-config (https://abseil.io/blog/20170926-welcome-to-abseil).

**Comment by derekmauro** [comment]
@rockwotj - there is https://github.com/fowles/absl-hello

**Comment by OlafvdSpek** [comment]
Hi @JonathanDCohen,

What's the status of this (and cmake support in general)?

**Comment by OlafvdSpek** [comment]
@derekmauro ^

**Comment by derekmauro** [comment]
@JonathanDCohen has something in the works, but he's on vacation. He will give an update when he gets back.

**Comment by JonathanDCohen** [comment]
https://github.com/abseil/abseil-hello/tree/master/cmake-hello
