### ISSUE TITLE
How can iteration over keys be implemented? 

### ISSUE THREAD

**Issue by smartbarbarian** [abseil/abseil-cpp#1183]
Hi,

The guide (https://abseil.io/docs/cpp/guides/container#iteration-order-instability) said flat_hash_map/set has Iteration Order Instability. It means the iteration order will change even with the same keys and insert order. But I find raw_hash_set (https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/raw_hash_set.h) "To iterate, we simply traverse the array". It seems will not cause iteration order instability.

So my question is: How does flat_hash_map/set's iteration work? What's the difference compared with std::unordered_map/set(they seems to use forward_list to hold keys)?

Thank you so much.

**Comment by derekmauro** [comment]
The hash function seeds itself randomly on startup, which means elements will land in a random location.
https://github.com/abseil/abseil-cpp/blob/9e408e050ff3c1db12f9a58081b6af10e05561c4/absl/hash/internal/hash.h#L1119-L1148

In some cases, insertions are randomized by the table implementation as well.
https://github.com/abseil/abseil-cpp/blob/9e408e050ff3c1db12f9a58081b6af10e05561c4/absl/container/internal/raw_hash_set.h#L768-L774

**Comment by smartbarbarian** [comment]
Thank you so much for your detailed explanation! I have one more question. Is it a good idea to modify the two parts to have deterministic results in tests?

**Comment by derekmauro** [comment]
> Thank you so much for your detailed explanation! I have one more question. Is it a good idea to modify the two parts to have deterministic results in tests?

Our position is that the answer to that is no. Imagine you work at a large company and thousands of tests depend on having deterministic results. Now also imagine that you discover a new hash implementation that is 10x more performant than the old one, but changes the iteration order. How do you migrate from the old implementation to the new one?

If your tests rely on deterministic results, the only solution is to migrate them manually, fixing all tests, which is very costly. If your tests do not rely on deterministic results, you have a drop in solution.

You can find a longer explanation in the section on [Hyrum's Law](https://www.hyrumslaw.com) in Software Engineering at Google book. See https://abseil.io/resources/swe-book/html/ch01.html#hyrumapostrophes_law.

If you are worried this is going to make writing tests harder, the GoogleTest framework has `::testing::UnorderedElementsAre`. You can find examples in our own tests:
https://github.com/abseil/abseil-cpp/blob/2d492a13c652df2d3fa9b4712cb4ac91f120478c/absl/container/flat_hash_set_test.cc#L156-L160

**Comment by smartbarbarian** [comment]
Thank you so much for the further info.
One more question again. For example, if we need to use the floating summation of a flat set as the threshold to classify the result, we have to use more computation resource to do the summation otherwise the result will be irreproducible. It will make debugging more difficult. Especially when it happens in a large and complicated system. So that means we should make a trade-off between the performance of the map and the resource consumption of the deterministic computation. Is my understanding correct?
Thank you again for your help.

**Comment by derekmauro** [comment]
That's a good question. I think your understanding is correct, and there is no right answer. For that situation, if you actually need set, you may want to consider using our `absl::btree_set` class since it does maintain sorted ordering, and should also give good performance. You could also try a vector or a sorted vector. As you suggest, it is about managing trade-offs.
