### ISSUE TITLE
Consider using ThrowBadAllow on allocation failures

### ISSUE THREAD

**Issue by coryan** [abseil/abseil-cpp#1184]
**Describe the bug**

Consider this failure:

https://github.com/abseil/abseil-cpp/blob/2d492a13c652df2d3fa9b4712cb4ac91f120478c/absl/base/internal/low_level_alloc.cc#L570

This seems like an allocation failure, maybe it would be better to use this

https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/throw_delegate.h#L62

?

**Steps to reproduce the bug**

N/A

**What version of Abseil are you using?**

Latest LTS

**What operating system and version are you using**

Linux, all distros.

**What compiler and version are you using?**

Seems to apply to all compilers.

**What build system are you using?**

N/A

**Comment by derekmauro** [comment]
If that fails, something is very wrong, and I'm not sure it is possible or safe to recover from such a failure.
