### ISSUE TITLE
provide colorized version of flags "--help" page  

### ISSUE THREAD

**Issue by romange** [abseil/abseil-cpp#1188]
gtest `--help` is nice. It uses terminal colors which makes it much easier to visually comprehend the text.

I understand that such change is a) opinionated and b) would require some effort for library maintainers. 

Instead, I suggest a less intrusive change - adding `transform_flagname` function to FlagsUsageConfig struct that would be able to change flag names when they are emitted to the final string.  Very similar to `normalize_filename` function. 
Then it would be up-to application developer to emit appropriate ansi-term colors for each flag. 

I could contribute this change if abseil maintainers agree.

**Comment by derekmauro** [comment]
Sorry, but I would not take such a change, either to use terminal colors, or to add features to FlagsUsageConfig.

**Comment by romange** [comment]
I guess nothing I can do here. Care to explain why not? Are you against colorized help? :)

**Comment by derekmauro** [comment]
The maintenance burden and reliability of the feature are two reasons.

**Comment by romange** [comment]
Thanks. Closing.
