### ISSUE TITLE
absl::MutexLock needs an Unlock method.

### ISSUE THREAD

**Issue by jmarantz** [abseil/abseil-cpp#119]
Background
>In codebases that use exceptions, the `absl::MutexLock` construct is important to avoid the possibility of a thrown exception leaving a lock held. However, it is not always convenient or optimal to have the lock scope nest properly within the scope of other variables.  Hence an Unlock method, similar to [std::unique_lock::unlock](http://en.cppreference.com/w/cpp/thread/unique_lock) is needed, to release a lock prior to closing out its scope.  Functionally, `std::unique_lock` can be used with `absl::Mutex`, however, this composition does not have the required thread annotations to allow clang's `-Wthread-safety` to work properly.  `std::unique_ptr<absl::MutexLock>::reset()` is also functionally correct, and also does not work with thread annotation.

Proposed API Change (s)
>Add `absl::Mutex::Unlock()`, which will unlock the owned mutex.  When this occurs, the `MutexLock` destructor will no longer need to unlock the mutex.  This is forward compatible as it adds a new API without changing the functionality of any existing API.  A prototype of a possible implementation strategy is available in a pending [Envoy Proxy PR](https://github.com/jmarantz/envoy/blob/2b7f969d7e63a861bbbac32b4075334cc1eb584b/source/common/common/absl_mutex.h), albeit with slightly different coding conventions than absl.

**Comment by derekmauro** [comment]
We already have `absl::ReleasableMutexLock`, which I think solves your problem:
https://github.com/abseil/abseil-cpp/blob/26b789f9a53d086c8b8c9c2668efb251e37861cd/absl/synchronization/mutex.h#L857-L879

We've talked about making `absl::MutexLock` movable as well, but we haven't come up with a compelling argument for doing so yet. Google's codebase (somewhat famously) doesn't use exceptions, but we should add that argument to the calculus.

Does `absl::ReleasableMutexLock` work for you?

**Comment by jmarantz** [comment]
Yes this looks great.  Thanks!
