### ISSUE TITLE
C++17 constexpr storage deprecation warnings

### ISSUE THREAD

**Issue by xuchen-han** [abseil/abseil-cpp#1191]
**Describe the bug**

In our downstream project [Drake](https://github.com/RobotLocomotion/drake), we get deprecation warnings (which we treat as errors) from redeclaration of static constexpr data members. For example, from `absl/container/fixed_array.h`

```
 template <typename T, size_t N, typename A>
 constexpr size_t FixedArray<T, N, A>::kInlineBytesDefault;
 
 template <typename T, size_t N, typename A>
 constexpr typename FixedArray<T, N, A>::size_type
     FixedArray<T, N, A>::inline_elements;
```

"If a ... constexpr static data member is odr-used, a definition at namespace scope is ... deprecated for constexpr data members since C++17." -- https://en.cppreference.com/w/cpp/language/static

We have a downstream patch that guard against these redeclarations with `#if  __cplusplus < 201703L`. I wonder if it's worth it to move this fix upstream.

**Steps to reproduce the bug**

`bazel build //... --copt=-Werror=deprecated --copt=--std=c++17`

**What version of Abseil are you using?**

Our Abseil is pinned at this commit:
cc04c0e07427deb78091231238189d14561a9441

**What operating system and version are you using**

Ubuntu 20.04

**What compiler and version are you using?**

gcc version 9.4.0

**What build system are you using?**

bazel 5.1.0

**Comment by derekmauro** [comment]
Thanks for letting us know. It looks like we currently don't test with `-Wdeprecated`, but we probably should.

If you don't mind I'd like to patch this myself. `FixedArray` isn't the only place where this issue triggers, and `__cplusplus` isn't set correctly on MSVC, so I think the patch is slightly more complicated than the one you have.

**Comment by xuchen-han** [comment]
Of course, that would be appreciated!
