### ISSUE TITLE
FixedArray has an inefficient move constructor 

### ISSUE THREAD

**Issue by Kaznov** [abseil/abseil-cpp#1196]
```c++
  FixedArray(
      FixedArray&& other,
      const allocator_type& a = allocator_type()) noexcept(NoexceptMovable())
      : FixedArray(std::make_move_iterator(other.begin()),
                   std::make_move_iterator(other.end()), a) {}
```
This is the current implementation of the move constructor.
In case `other` has an out-of-line storage, it would be preferable to "steal" this storage, instead of allocating a new one.

The counterpoint is, that this operation would change the size of the original array. I don't know if it's a problem -  the object would be left in a destructible state, even if an invariant was broken.

Is it a desirable change?

**Comment by derekmauro** [comment]
You should think of a `FixedArray` as a stand-in for `std::array` or even a C-style array. Its size must never change. Further, the address of the underlying storage must not change either.
