### ISSUE TITLE
Help!!!  Undefined reference to absl::ByChar::Find(std::basic_string_view<char, std::char_traits >, unsigned long) const'

### ISSUE THREAD

**Issue by iDonghq** [abseil/abseil-cpp#1199]
[ 56%] Linking CXX executable cartographer_print_configuration
CMakeFiles/cartographer_print_configuration.dir/cartographer/common/print_configuration_main.cc.o: In function cartographer::common::PrintSubdictionaryById(cartographer::common::LuaParameterDictionary*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)': print_configuration_main.cc:(.text+0x244): undefined reference to absl::ByChar::Find(std::basic_string_view<char, std::char_traits >, unsigned long) const'
print_configuration_main.cc:(.text+0x65c): undefined reference to absl::ByChar::Find(std::basic_string_view<char, std::char_traits<char> >, unsigned long) const' CMakeFiles/cartographer_print_configuration.dir/cartographer/common/print_configuration_main.cc.o: In function absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty, std::basic_string_view<char, std::char_traits > >::ConvertToContainer<std::vector<std::basic_string_view<char, std::char_traits >, std::allocator<std::basic_string_view<char, std::char_traits > > >, std::basic_string_view<char, std::char_traits >, false>::operator()(absl::strings_internal::Splitter<absl::ByChar, absl::SkipEmpty, std::basic_string_view<char, std::char_traits > > const&) const':
print_configuration_main.cc:(.text.ZNK4absl16strings_internal8SplitterINS_6ByCharENS_9SkipEmptyESt17basic_string_viewIcSt11char_traitsIcEEE18ConvertToContainerISt6vectorIS7_SaIS7_EES7_Lb0EEclERKS8[ZNK4absl16strings_internal8SplitterINS_6ByCharENS_9SkipEmptyESt17basic_string_viewIcSt11char_traitsIcEEE18ConvertToContainerISt6vectorIS7_SaIS7_EES7_Lb0EEclERKS8]+0xc8): undefined reference to absl::ByChar::Find(std::basic_string_view<char, std::char_traits<char> >, unsigned long) const' print_configuration_main.cc:(.text._ZNK4absl16strings_internal8SplitterINS_6ByCharENS_9SkipEmptyESt17basic_string_viewIcSt11char_traitsIcEEE18ConvertToContainerISt6vectorIS7_SaIS7_EES7_Lb0EEclERKS8_[_ZNK4absl16strings_internal8SplitterINS_6ByCharENS_9SkipEmptyESt17basic_string_viewIcSt11char_traitsIcEEE18ConvertToContainerISt6vectorIS7_SaIS7_EES7_Lb0EEclERKS8_]+0x194): undefined reference to absl::ByChar::Find(std::basic_string_view<char, std::char_traits >, unsigned long) const'
collect2: error: ld returned 1 exit status
CMakeFiles/cartographer_print_configuration.dir/build.make:153: recipe for target 'cartographer_print_configuration' failed
make[2]: *** [cartographer_print_configuration] Error 1
CMakeFiles/Makefile2:421: recipe for target 'CMakeFiles/cartographer_print_configuration.dir/all' failed
make[1]: *** [CMakeFiles/cartographer_print_configuration.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
libcartographer.a(histogram.cc.o): In function cartographer::common::Histogram::ToString[abi:cxx11](int) const': histogram.cc:(.text+0x310): undefined reference to absl::strings_internal::CatPieces[abi:cxx11](std::initializer_list<std::basic_string_view<char, std::char_traits > >)'
histogram.cc:(.text+0x778): undefined reference to `absl::strings_internal::AppendPieces(std::__cxx11::basic_string<char, std::char_traits, std::allocator >*, std::initializer_list<std::basic_string_view<char, std::char_traits > >)'
collect2: error: ld returned 1 exit status
CMakeFiles/cartographer_pbstream.dir/build.make:153: recipe for target 'cartographer_pbstream' failed
make[2]: *** [cartographer_pbstream] Error 1
CMakeFiles/Makefile2:395: recipe for target 'CMakeFiles/cartographer_pbstream.dir/all' failed

Help! I have met the same problem, even if I did it as "Confirmed on my end: if I add back what was removed from AbseilConfigureCopts.make in commit https://github.com/abseil/abseil-cpp/commit/c6954897f7ece5011f0126db9117361dc1a6ff36 then it works."

**Comment by derekmauro** [comment]
We need to know exactly what you did before we can help you. Please fill out the bug report form: https://github.com/abseil/abseil-cpp/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md

This is very likely a mixed-mode build issue. See https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil.

**Comment by derekmauro** [comment]
Closing due to insufficient information.
