### ISSUE TITLE
How to choose a error status when the cause relies on errno?

### ISSUE THREAD

**Issue by EtoDemerzel0427** [abseil/abseil-cpp#1228]
I was using `absl::Status` and `absl::StatusOr` to wrap some Linux system calls where many errors rely on `errno`, and I found it hard to choose a proper error code for each `errno`. From my eyes, the status codes provided in abseil are more like "external error code", while my use case needs a set of "internal error code".

Are there any tips/suggestions about the best practice on this issue?

**Comment by derekmauro** [comment]
Call `absl::ErrnoToStatusCode()`:
https://github.com/abseil/abseil-cpp/blob/701185dbce17a2f49334027ca3cb5788a5d06c6d/absl/status/status.h#L741-L746

**Comment by EtoDemerzel0427** [comment]
Thanks, I realized this was introduced in a commit in April while I had been using the 20211102 release.
