### ISSUE TITLE
[suggestion] Can you create trim functions for string?

### ISSUE THREAD

**Issue by paulocoutinhox** [abseil/abseil-cpp#1229]
Hi,

Can you create trim functions for string?

Example:
https://stackoverflow.com/questions/216823/how-to-trim-a-stdstring

Thanks.

**Comment by derekmauro** [comment]
The `strings` library probably has what you are looking for. For example, there is `absl::StripAsciiWhitespace()`. Let us know exactly what you are looking for if you can't find it.

**Comment by paulocoutinhox** [comment]
Thanks, is this :)

Sorry, i search here before but not find it, because this i post here. Thanks, is what i need :)
