### ISSUE TITLE
absl:status  library is missing from http_archive

### ISSUE THREAD

**Issue by neshdev** [abseil/abseil-cpp#1240]
**Describe the bug**

Adding a dependency to absl/status is returning with the following error:

ERROR: C:/.../BUILD:16:11: no such package '@com_google_absl//absl/status': BUILD file not found in directory 'absl/status' of external repository @com_google_absl'

Also, to note, the status folder and files are is missing in zip: https://github.com/abseil/abseil-cpp/archive/98eb410c93ad059f9bba1bf43f5bb916fc92a5ea.zip

**Steps to reproduce the bug**

Add the following to your bazel BUILD file:
cc_library(
    name = "mytime",
    srcs = ["time.cc"],
    hdrs = ["time.h"],
    deps = [
        "@com_google_absl//absl/strings",
         "@com_google_absl//absl/status",
    ],
)

Add the following to your WORKSPACE file:

http_archive(
  name = "com_google_absl",
  urls = ["https://github.com/abseil/abseil-cpp/archive/98eb410c93ad059f9bba1bf43f5bb916fc92a5ea.zip"], 
  strip_prefix = "abseil-cpp-98eb410c93ad059f9bba1bf43f5bb916fc92a5ea",
)

**What version of Abseil are you using?**
official released version from archive and documentation.

**What operating system and version are you using**
Windows 11

**What compiler and version are you using?**
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe

Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.

**What build system are you using?**
bazel

**Please include the output of `bazel --version` or `cmake --version`, or the
equivalent for your build system.**

bazel 5.1.0

**Additional context**

**Comment by derekmauro** [comment]
You are using version of Abseil that predates the release of `absl::Status`. Update to the latest version.
