### ISSUE TITLE
How to tell absl's bazel script which compiler (gcc/clang)

### ISSUE THREAD

**Issue by aaron-michaux** [abseil/abseil-cpp#1263]
Hi,

I've got an interesting problem, where I've specified my own (gcc based) toolchain, and this is preventing me from using absl's bazel integration. In particular, absl is detecting that I'm using gcc, and starts passing clang-only flags, and... kBOOM!

How does absl figure which compiler I'm using, and how do I tell it to assume gcc?

Thanks

**Comment by derekmauro** [comment]
Bazel should default to using gcc flags, so I'm not sure why it isn't. What OS are you using and how is your compiler setup/installed?

But to answer your question, there are environment variables you can use to override these things. Try something like
`CC=/path/to/gcc BAZEL_COMPILER=gcc bazel test ...`

**Comment by aaron-michaux** [comment]
Using Ubuntu 20.04. We have custom gcc rules, so we use a "gcc toolchain" even though it's the system gcc. It's a large project... it could well be something woolly that we've done. 

One curious thing: the error happens when build `@com_google_absl//absl/strings:strings`. It successfully builds a bunch of files using gcc flags, but then fails to build some random file, which changes each time. This is the generated build command when it fails to build `str_cat.cc`

```
/usr/bin/gcc -MD -MF bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/str_cat.d \
'-frandom-seed=bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/str_cat.o' \
-iquote external/com_google_absl -iquote bazel-out/k8-dbg/bin/external/com_google_absl \
'-std=c++17' -g -Wall -Wextra -Wcast-qual -Wconversion -Wfloat-overflow-conversion -Wfloat-zero-conversion \
-Wfor-loop-analysis -Wformat-security -Wgnu-redeclared-enum -Winfinite-recursion -Wliteral-conversion \
-Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wself-assign -Wshadow -Wstring-conversion \
-Wtautological-overlap-compare -Wundef -Wuninitialized -Wunreachable-code -Wunused-comparison \
-Wunused-local-typedefs -Wunused-result -Wvla -Wwrite-strings -Wno-float-conversion -Wno-implicit-float-conversion \
-Wno-implicit-int-float-conversion -Wno-implicit-int-conversion -Wno-shorten-64-to-32 -Wno-sign-conversion \
-DNOMINMAX -c external/com_google_absl/absl/strings/str_cat.cc \
-o bazel-out/k8-dbg/bin/external/com_google_absl/absl/strings/_objs/strings/str_cat.o
```

(This doesn't work `CC=/path/to/gcc BAZEL_COMPILER=gcc bazel test ...`)

**Comment by derekmauro** [comment]
When you say you are using a "gcc toolchain", does that mean you are using a toolchain config file? That would explain why the command I gave doesn't work, but unfortunately I can't offer anymore help without a full reproduction that I can try myself.

The start point for how we select compiler flags is here: https://github.com/abseil/abseil-cpp/blob/92fdbfb301f8b301b28ab5c99e7361e775c2fb8a/absl/copts/configure_copts.bzl#L24-L29

**Comment by aaron-michaux** [comment]
Yes, we have our own `cc_common.create_cc_toolchain_config_info`, which has special options for various features. Thanks for pointing me to the relevant `bzl` file. I guess I'll see if I can get the skylark debugger working.

**Comment by aaron-michaux** [comment]
If you are curious, this may be the bug: https://github.com/bazelbuild/bazel/issues/12707

**Comment by derekmauro** [comment]
> If you are curious, this may be the bug: [bazelbuild/bazel#12707](https://github.com/bazelbuild/bazel/issues/12707)

If that's actually the issue then I think this can be fixed in a backwards compatible way by adding an additional case to the selectors. I'll give that a try.

**Comment by derekmauro** [comment]
@aaron-michaux - Please re-open if this your issue isn't fixed.
