### ISSUE TITLE
error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by andreas-schwab** [abseil/abseil-cpp#1275]
Building on riscv64 fails:

In file included from /suse/schwab/src/github/abseil-cpp/absl/debugging/stacktrace.cc:46:
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc: In function ‘int UnwindImpl(void**, int*, int, int, const void*, int*)’:
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:131:12: error: ‘numeric_limits’ is not a member of ‘std’
  131 |       std::numeric_limits<size_t>::max() - sizeof(void *)
      |            ^~~~~~~~~~~~~~
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:131:33: error: expected primary-expression before ‘>’ token
  131 |       std::numeric_limits<size_t>::max() - sizeof(void *)
      |                                 ^
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:131:36: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  131 |       std::numeric_limits<size_t>::max() - sizeof(void *)
      |                                    ^~~
      |                                    std::max
In file included from /usr/include/c++/12/string:50,
                 from /usr/include/c++/12/bits/locale_classes.h:40,
                 from /usr/include/c++/12/bits/ios_base.h:41,
                 from /usr/include/c++/12/ios:42,
                 from /usr/include/c++/12/ostream:38,
                 from /usr/include/c++/12/iostream:39,
                 from /suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:32:
/usr/include/c++/12/bits/stl_algobase.h:300:5: note: ‘std::max’ declared here
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
[ 28%] Building CXX object absl/base/CMakeFiles/malloc_internal.dir/internal/low_level_alloc.cc.o
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc: In instantiation of ‘int UnwindImpl(void**, int*, int, int, const void*, int*) [with bool IS_STACK_FRAMES = false; bool IS_WITH_CONTEXT = false]’:
/suse/schwab/src/github/abseil-cpp/absl/debugging/stacktrace.cc:124:11:   required from here
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:128:29: error: could not convert ‘{((size_t)sysconf(((int)_SC_PAGESIZE))), <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::pair<long unsigned int, long unsigned int>’
  128 |   std::pair<size_t, size_t> stack = {
      |                             ^~~~~
      |                             |
      |                             <brace-enclosed initializer list>
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc: In instantiation of ‘int UnwindImpl(void**, int*, int, int, const void*, int*) [with bool IS_STACK_FRAMES = false; bool IS_WITH_CONTEXT = true]’:
/suse/schwab/src/github/abseil-cpp/absl/debugging/stacktrace.cc:126:11:   required from here
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:128:29: error: could not convert ‘{((size_t)sysconf(((int)_SC_PAGESIZE))), <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::pair<long unsigned int, long unsigned int>’
  128 |   std::pair<size_t, size_t> stack = {
      |                             ^~~~~
      |                             |
      |                             <brace-enclosed initializer list>
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc: In instantiation of ‘int UnwindImpl(void**, int*, int, int, const void*, int*) [with bool IS_STACK_FRAMES = true; bool IS_WITH_CONTEXT = false]’:
/suse/schwab/src/github/abseil-cpp/absl/debugging/stacktrace.cc:130:11:   required from here
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:128:29: error: could not convert ‘{((size_t)sysconf(((int)_SC_PAGESIZE))), <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::pair<long unsigned int, long unsigned int>’
  128 |   std::pair<size_t, size_t> stack = {
      |                             ^~~~~
      |                             |
      |                             <brace-enclosed initializer list>
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc: In instantiation of ‘int UnwindImpl(void**, int*, int, int, const void*, int*) [with bool IS_STACK_FRAMES = true; bool IS_WITH_CONTEXT = true]’:
/suse/schwab/src/github/abseil-cpp/absl/debugging/stacktrace.cc:132:11:   required from here
/suse/schwab/src/github/abseil-cpp/absl/debugging/internal/stacktrace_riscv-inl.inc:128:29: error: could not convert ‘{((size_t)sysconf(((int)_SC_PAGESIZE))), <expression error>}’ from ‘<brace-enclosed initializer list>’ to ‘std::pair<long unsigned int, long unsigned int>’
  128 |   std::pair<size_t, size_t> stack = {
      |                             ^~~~~
      |                             |
      |                             <brace-enclosed initializer list>
make[2]: *** [absl/debugging/CMakeFiles/stacktrace.dir/build.make:76: absl/debugging/CMakeFiles/stacktrace.dir/stacktrace.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1644: absl/debugging/CMakeFiles/stacktrace.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by derekmauro** [comment]
Patch coming
