### ISSUE TITLE
DFATAL log level is not implemented

### ISSUE THREAD

**Issue by mumbleskates** [abseil/abseil-cpp#1279]
**Describe the bug**

`LOG(DFATAL)` is incompletely implemented. `::absl::kLogDebugFatal` is referenced in the macro definition of `ABSL_LOGGING_INTERNAL_LOG_DFATAL`, and `DFATAL` log level is mentioned several other places, but `kLogDebugFatal` is not defined anywhere and there seem to be other pieces of the puzzle missing.

Note that `LOG(DFATAL)` is not the same as `DLOG(FATAL)`: the latter is compiled out in the presence of `NDEBUG`, while the former (which this bug report is about) is demoted to be equivalent to `LOG(ERROR)`.

**Steps to reproduce the bug**

```c++
#include "absl/log/log.h"
int main() {
  LOG(DFATAL) << "compilation failure";
}
```
```
misc/scratch.cc:3:3: error: expected ';' after expression
  LOG(DFATAL) << "compilation failure";
  ^
external/com_google_absl/absl/log/log.h:168:7: note: expanded from macro 'LOG'
      ABSL_LOGGING_INTERNAL_LOG_##severity.InternalStream()
      ^
<scratch space>:401:1: note: expanded from here
ABSL_LOGGING_INTERNAL_LOG_DFATAL
^
external/com_google_absl/absl/log/internal/strip.h:59:3: note: expanded from macro 'ABSL_LOGGING_INTERNAL_LOG_DFATAL'
  ::absl::log_internal::LogMessage(__FILE__, __LINE__, ::absl::kLogDebugFatal)
  ^
misc/scratch.cc:3:3: error: use of undeclared identifier 'STATELESS'
external/com_google_absl/absl/log/log.h:167:42: note: expanded from macro 'LOG'
  ABSL_LOG_INTERNAL_CONDITION_##severity(STATELESS, true) \
                                         ^
misc/scratch.cc:3:3: error: no member named 'kLogDebugFatal' in namespace 'absl'
  LOG(DFATAL) << "compilation failure";
  ^~~~~~~~~~~
external/com_google_absl/absl/log/log.h:168:7: note: expanded from macro 'LOG'
      ABSL_LOGGING_INTERNAL_LOG_##severity.InternalStream()
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<scratch space>:401:1: note: expanded from here
ABSL_LOGGING_INTERNAL_LOG_DFATAL
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/com_google_absl/absl/log/internal/strip.h:59:64: note: expanded from macro 'ABSL_LOGGING_INTERNAL_LOG_DFATAL'
  ::absl::log_internal::LogMessage(__FILE__, __LINE__, ::absl::kLogDebugFatal)
                                                       ~~~~~~~~^
3 errors generated.
```

**What version of Abseil are you using?**

master: 9398fa76a3436bfb89f7a6ec5c74a21f1e4d6029

**What operating system and version are you using**

ubuntu 22.04.1

**What compiler and version are you using?**

Ubuntu clang version 16.0.0-++20220921031234+9f13b9346b7c-1~exp1~20220921151331.436
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64

**What build system are you using?**

Build label: 5.3.1
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Sep 19 17:28:49 2022 (1663608529)
Build timestamp: 1663608529
Build timestamp as int: 1663608529

**Additional context**

This is a potential blocking regression for a migration away from `glog`.

**Comment by Mizux** [comment]
@derekmauro could you add it to the Release https://github.com/abseil/abseil-cpp/releases/tag/20230125.0 as "known issue" ?

Too bad the last release (6 months after the first `absl::log` export on `main` branch) still doesn't contain a fix for it....

**Comment by derekmauro** [comment]
> @derekmauro could you add it to the Release https://github.com/abseil/abseil-cpp/releases/tag/20230125.0 as "known issue" ?

I added a note.

**Comment by Mizux** [comment]
As an **ugly** workaround we are currently using these defines before including `absl/log`

```cpp
#define ABSL_LOG_INTERNAL_CONDITION_DFATAL ABSL_LOG_INTERNAL_CONDITION_ERROR
#define kLogDebugFatal LogSeverity::kError
#define kDebugFatal kError
```

thus we can depend on the last absl release and still use `log(DFATAL) <<` otherwise package manager are doomed to integrate/bump both packages (e.g. homebrew).
note: While we could patch abseil-cpp in our build when using a static linking to absl deps it is not possible when depending on a system wide (cmake) install of absl
