### ISSUE TITLE
cctz::detail::parse ignore zone validation

### ISSUE THREAD

**Issue by rusde** [abseil/abseil-cpp#1282]
Zone parsed [here](https://github.com/abseil/abseil-cpp/blob/master/absl/time/internal/cctz/src/time_zone_format.cc#L812-L814) is not validated. This results in wrong format validation. 

For example below parse returns true where zone is derived as `Z/2017-12-01T00:00:00Z` which is not a valid zone:

```
absl::ParseTime("%Y-%m-%dT%H:%M:%E*S %Z",
                              "2017-11-01T00:00:00Z/2017-12-01T00:00:00Z",
                              &dummy, &error));
```

**Comment by derekmauro** [comment]
@devbww

**Comment by devbww** [comment]
> example below parse returns true

It looks like it returns false to me.

The code snippet you linked to concerns the `%Z` (upper-case) specifier instead, which, as mentioned [here](https://github.com/abseil/abseil-cpp/blob/1cd889767e518d1bbb1bf8b226ee2c4dd3e85390/absl/time/time.h#L1345-L1348), shouldn't be used for `absl::ParseTime()`.

**Comment by rusde** [comment]
oops yes I copied the wrong time format. I meant CAPITAL Z above. 

You are saying we should not rely on absl::ParseTime to parse time zone?

**Comment by devbww** [comment]
> You are saying we should not rely on absl::ParseTime to parse time zone?

Yes, in a nutshell.

`%Z` would not parse a "timezone", but presumably rather a "timezone name or abbreviation", which is ill-defined and/or ambiguous enough to be [useless](https://github.com/abseil/abseil-cpp/blob/1cd889767e518d1bbb1bf8b226ee2c4dd3e85390/absl/time/time.h#L1345-L1348).

I would instead recommend either:

1. your input strings [include a UTC offset](https://github.com/abseil/abseil-cpp/blob/1cd889767e518d1bbb1bf8b226ee2c4dd3e85390/absl/time/time.h#L1341-L1343), matched by `%z`, `%Ez`, or `%E*z`, and you call `absl::ParseTime(format, input, &t, &err)`, or
2. your input strings [do not contain a UTC offset](https://github.com/abseil/abseil-cpp/blob/1cd889767e518d1bbb1bf8b226ee2c4dd3e85390/absl/time/time.h#L1373-L1375), and you call `absl::ParseTime(format, input, tz, &t, &err)`, where the input is interpreted within `tz`.

In the case you cited, option 1 is sufficient and preferred.

**Comment by derekmauro** [comment]
It sounds like there is nothing to do here.
