### ISSUE TITLE
flat_hash_map<string, vector<double>>: "constructed value does not match the lookup key"

### ISSUE THREAD

**Issue by schoetbi** [abseil/abseil-cpp#1291]
**Describe the bug**

I use a `flat_hash_map<std::string, std::vector<double>>` map to store vectors of doubles with a name as lookup key and get the error message: `constructed value does not match the lookup key` when using the `operator[]`.

This is my program where the error occurs:

```
class Expression {
    Map map;

   public:
    void AddVector(const string& name, size_t len) { map.emplace(name, len); }

    auto& Map() { return map; }
};

int main(void) {
    Expression e;

    e.AddVector("xd_1d", 6);

    vector<int>& xd_1d = e.Map()["xd_1d"]; // <-- Error  "constructed value does not match the lookup key" here
    print("{}", xd_1d.size());
}

```
I made a breakpoint at Miscellaneous Files\raw_hash_set.h:2167 and printed {hash}->{key}
![grafik](https://user-images.githubusercontent.com/764173/194827624-933b2e78-2305-4631-a834-7791182af0dc.png)

This was my output:
```
17027332470334110426 -> "xd_1d"
2421795245354484797 -> 0x00007ff7d9054568 "xd_1d"
Debug Error!
```

My question is why are there two different hashes for `xd_1d`. The first time this is `17027332470334110426 ` the second time `2421795245354484797 `. 

Is there a difference in the hash if the has is calculated from a string temporary in contrast to a char[6]?

Side note: The class Expression is in a static library and not in the same compilation unit.

The next experiment I did was to inline the method `AddVector`

```
auto& vectors = expr.Vectors();
vectors.emplace("xd_1d", n);
vector<double>& xd_1d = vectors["xd_1d"];
```

This time the error does not occur. And also the hashes are the same. 

```
11484059543670448217 -> 0x00007ff7657145ec "xd_1d"
11484059543670448217 -> 0x00007ff7657145f4 "xd_1d"
```

Is the hash function dependent on the compilation unit? I do not understand this.

To verify this, I include my own hash function. I used [murmurhash ](https://sites.google.com/site/murmurhash/ )for this. Since this implementation does not depend on a per library address, the hashes are stable and my program works. So it seems that the added safety using the seed has the drawback that the hashes are unstable if the code to calculate the hashes reside in different compilation units.

**Steps to reproduce the bug**

Unfortunately, I am not able to create an example to reproduce the bug yet. This program on [godbolt](https://godbolt.org/z/G5ref57GE) works fine.

**What version of Abseil are you using?**

Conan package `abseil/20220623.0`

**What operating system and version are you using**

Windows 19042.2006

**What compiler and version are you using?**

Visual Studio 2019 16.7.22

**What build system are you using?**

Visual Studio & MSBUILD

**Comment by derekmauro** [comment]
This is one of the more common questions that we get. Please see the following note:
https://github.com/abseil/abseil-cpp/blob/76466b85fb9c86be56bfe773667ee6ad4fc3b87f/absl/hash/hash.h#L39-L46

**Comment by schoetbi** [comment]
@derekmauro Thanks. It is correct that I should not rely on the hash values, but I need this for unit testing. I solved this case by using the MurmurHash algorithm with a stable seed to get the same hash values even across dlls.
