### ISSUE TITLE
Memory corruption after constructing an absl::BitGen

### ISSUE THREAD

**Issue by gumwreath** [abseil/abseil-cpp#1297]
**Describe the bug**

Constructing an `absl::BitGen` can corrupt memory. 

Built with Clang using Bazel. The memory corruption is easiest to see using msan.

**Steps to reproduce the bug**

Clone this repo, which has a minimal reproducing example: https://github.com/gumwreath/absl-bitgen-broken
Then, run this command:

```
bazel run -c dbg --copt=-fsanitize=memory --cxxopt=-fsanitize=memory --linkopt=-fsanitize=memory :random_test
```

msan will show a `use-of-uninitialized-value` error. This happens on the line after the `absl::BitGen` is constructed, specifically when the `std::endl` is written to `std::cout`. Seeing as `std::cout` and `std::endl` presumably aren't buggy, `absl::BitGen` must have corrupted some data used by `cout` or `endl`.

(However, more complex examples cause segfaults even without msan).

This is the minimum reproducer code included in that repo:
```
#include <iostream>

#include "absl/random/random.h"

void MRandom() {
  absl::BitGen gen2(std::seed_seq{1, 2, 3});
  std::cerr << "A X" << std::endl;
  return;
}

int main(int argc, char** argv) {
  MRandom();
  return 0;
}
```

**What version of Abseil are you using?**

Tested with several versions, including the latest commit hash `5fa65f28e46e86c44966a1ca8a727a329d9c1ff8`.

**What operating system and version are you using**

Ubuntu:

```
Linux MS-7A34 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**What compiler and version are you using?**

```
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

**What build system are you using?**

```
bazel 5.3.1
```
Uses the toolchain included in the repo I provided. This is a minimal toolchain to use clang instead of gcc.

**Comment by derekmauro** [comment]
https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo

Correct use of MemorySanitizer requires that all code, including the standard library, be built with MemorySanitizer, otherwise you can get false positives from the standard library. This unfortunately means it is nearly impossible to use distro provided toolchains with MemorySanitizer.

I tested your example with Clang using a MemorySanitzer built libc++ and didn't get any errors. Unfortunately I don't have a MemorySanitizer built libstdc++ available.

You can try this yourself a Docker container:
```
docker run -it gcr.io/google.com/absl-177019/linux_hybrid-latest:20220217 /bin/bash

cd
git clone https://github.com/gumwreath/absl-bitgen-broken
cd absl-bitgen-broken

export CC="/opt/llvm/clang/bin/clang"
export BAZEL_CXXOPTS="-std=c++17:-nostdinc++"
export BAZEL_LINKOPTS="-L/opt/llvm/libcxx-msan/lib/x86_64-unknown-linux-gnu:-lc++:-lc++abi:-lm:-Wl,-rpath=/opt/llvm/libcxx-msan/lib/x86_64-unknown-linux-gnu"
export CPLUS_INCLUDE_PATH="/opt/llvm/libcxx-msan/include/x86_64-unknown-linux-gnu/c++/v1:/opt/llvm/libcxx-msan/include/c++/v1"
/usr/local/bin/bazel --noworkspace_rc test ... \
  --compilation_mode=dbg \
  --copt="-fsanitize=memory" \
  --copt="-fno-sanitize-blacklist" \
  --features=external_include_paths \
  --linkopt="-fsanitize=memory" \
  --test_env="MSAN_SYMBOLIZER_PATH=/opt/llvm/clang/bin/llvm-symbolizer"
```

Please let me know if you disagree with this assessment or can reproduce this with an instrumented standard library.

**Comment by gumwreath** [comment]
Thanks.

I'll reopen this if I can reproduce the segfault with a minimal example. If not, the segfault was probably my fault somewhere.
