### ISSUE TITLE
std::launder was not implemented in clang until version 6

### ISSUE THREAD

**Issue by fuzzy-coats** [abseil/abseil-cpp#1309]
Edit: @glandium is correct in that this was not implemented in clang until version 8. This is easily verifiable using Compiler Explorer.

std::launder was implemented in clang 6.0, in revision https://github.com/llvm/llvm-project/commit/9180eb1f4ab96481413e93d35f35c3685de3084c . This causes a build failure when building with clang 5 in c++17 mode, see https://github.com/abseil/abseil-cpp/blob/master/absl/functional/internal/any_invocable.h#L198.  It should be possible to check for clang < 6 and fall back to the UB based implementation here https://github.com/abseil/abseil-cpp/blob/master/absl/functional/internal/any_invocable.h#L204.

**Comment by derekmauro** [comment]
Clang < 6 is unsupported. Please see https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md. Sorry about this.

**Comment by fuzzy-coats** [comment]
@derekmauro The supported platforms here https://abseil.io/docs/cpp/platforms/platforms seem to indicate that clang versions 3.4+ are supported on specific platforms.

**Comment by derekmauro** [comment]
That doc is out of date. I asked the person who updates abseil.io to correct it a few days ago.

**Comment by glandium** [comment]
Interestingly, clang 6 and 7, still supported per the support matrix, do *not*, support std::launder (std::launder relies on __builtin_launder, which was not implemented before clang 8). So while the patch here is incorrect, the issue does exist on supported platforms.
