### ISSUE TITLE
How to customization absl::btree_set<> container comparator ?

### ISSUE THREAD

**Issue by fansehep** [abseil/abseil-cpp#1312]
hi guys.
I want to use ```absl::btree_set``` in our project.
```c++
struct str_cmp {
  bool operator () (std::string& lef, std::string& ref) {
      // ... some our rules.
  }
};
```
we want to a ```absl::btree_set<std::string, str_comp> memMap_```.
but ```clang``` report many errors to us. how to solve it?

**Comment by derekmauro** [comment]
I'm guessing it's because the comparator needs to use `const std::string&`, but I can't say for sure. If you need additional help, you need to provide the actual code and the error from clang.

**Comment by fansehep** [comment]
> I'm guessing it's because the comparator needs to use `const std::string&`, but I can't say for sure. If you need additional help, you need to provide the actual code and the error from clang.

ok. fixed it.
```c++
struct str_cmp {
  bool operator () (std::string_view const& lef, std::string_view const& ref) const { 
    //...
  }
};
```
this can solve our problems. thanks.
