### ISSUE TITLE
CRC32C output operator seems not generalized

### ISSUE THREAD

**Issue by kelbon** [abseil/abseil-cpp#1319]
https://github.com/abseil/abseil-cpp/blob/842560d214649fc0077838e5b02cc35e4af12526/absl/crc/crc32c.h#L169

Firstly, header includes both `<iostream>` and `<ostream>`, which seems redundantly.
And `operator <<` defined for std::ostream, but not for `std::basic_ostream<Char, Traits>`.
It breakes code like `std::wcout << value;`

I dont think output operator is needed generally, atleast in this header

Also personally i dont see a reason to not make crc32c a type(class) without free functions

**Comment by MBkkt** [comment]
> I dont think output operator is needed generally, atleast in this header

\+

**Comment by derekmauro** [comment]
I think this is addressed to the extent that we are going to address it. `<iostream>` has been removed and `crc32c_t` is now a class. We don't have any support for wide streams. The operator is mainly for debugging.
