### ISSUE TITLE
Branch mentioned in LTS.md does not exist in Github repository

### ISSUE THREAD

**Issue by ilyapopov** [abseil/abseil-cpp#132]

**Comment by rongjiecomputer** [comment]
@ilyapopov It can be found at https://github.com/abseil/abseil-cpp/blob/master/absl/LTS.md

**Comment by ilyapopov** [comment]
@rongjiecomputer Yes, I know where LTS.md is located. Are you able to access the branch mentioned in it?

If I click on any links in that document, both [the link to the branch](https://github.com/abseil/abseil-cpp/tree/lts_2018_06_18/) and the [link to the "release management guide"](https://abseil.io/about/releases), I get 404 error. Neither branch not the Guide currently exist.

**Comment by mbxx** [comment]
It's not up yet because we ran into some issues while making the cut.  We're working on it.

**Comment by ilyapopov** [comment]
I see the branch is up now. This issue can be closed.

**Comment by Bu11etmagnet** [comment]
$ curl -v https://github.com/abseil/abseil-cpp/blob/master/absl/LTS.md
< HTTP/1.1 404 Not Found
< Server: GitHub.com
< Date: Thu, 21 Jun 2018 08:23:23 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Status: 404 Not Found

**Comment by rongjiecomputer** [comment]
@Bu11etmagnet It was moved to top-level now. https://github.com/abseil/abseil-cpp/blob/master/LTS.md
