### ISSUE TITLE
Abseil changes ABI based on whether address sanitizer is enabled

### ISSUE THREAD

**Issue by tudor** [abseil/abseil-cpp#1321]
**Describe the bug**

Abseil changes the ABI based on whether the address sanitizer is enabled.

Speficially, `FixedArray` uses `ABSL_ADDRESS_SANITIZER_REDZONE` which adds 2 8-byte blocks in sanitizer mode to `FixedArray::NonEmptyInlinedStorage`.

This means that the size of the object (and offset of the actual `buff_` member) changes between sanitizer and non-sanitizer mode.

In our case, we build S2Geometry against Abseil (compiled without sanitizers), and then build our own code (with address sanitizer) on top of that.

The ABI difference leads to obvious fun out-of-bounds reads and writes.

The layout should be based on *whether ASAN was on when Abseil itself was built*, not on whether it's on in a particular compilation unit that uses Abseil.

**What version of Abseil are you using?**

Broken code exists in HEAD.

**Comment by derekmauro** [comment]
Mixed-mode builds are not supported, and are too hard to maintain. If you want the sanitizers to work, all code, including Abseil and the standard library, needs to be built with sanitizers enabled.

**Comment by tudor** [comment]
Most of the world does not live in Bazel where we rebuild the standard library on a whim... folly, for example, has different flags whether ASAN was enabled when the library was built vs for a particular compilation unit that uses it: https://github.com/facebook/folly/blob/01e161fcc0c993ebfcc9e35353b68b0093752a99/folly/CPortability.h#L62

**Comment by tituswinters** [comment]
And most of the world doesn't understand ODR. We don't support this mechanism, both because it's risky, hard to support, and rare for people to operate properly according to the standard.

Declaring that we are unwilling to rebuild for correctness is a major contributor to C++ being unsafe in the first place. I do not support this line of argument.

**Comment by nbronson** [comment]
A mechanism like https://github.com/rockset/folly/blob/master/folly/container/detail/F14Table.cpp#L31 can be used to detect the mismatch at link time, which is much easier to diagnose than a runtime ABI mismatch
