### ISSUE TITLE
Undefined behavier in absl::flat_hash_map 

### ISSUE THREAD

**Issue by fansehep** [abseil/abseil-cpp#1322]
**Describe the bug**

Include a clear and concise description of what the problem is, including what
you expected to happen, and what actually happened.
```c++
#include <absl/container/flat_hash_map.h>

#include <iostream>
#include <string>
#include <unordered_map>

extern "C" {
#include <uuid/uuid.h>
}
int main() {
  absl::flat_hash_map<std::string, std::string> test_map;
  test_map.size();
  test_map["123"] = "456";
  const std::string* key_ptr = &(test_map.find("123")->first);
  int i = 0;
  const int N = 10000000;
  std::string key_v = "12312312312312cdsjkfhjsejdfh";
  std::string val_v = "dasjidhkfhsjkdfhkujsajhdiasjd";
  for (; i < N; i++) {
    test_map[(key_v + std::to_string(i))] = (val_v + std::to_string(i));
  }
  std::cout << *key_ptr << std::endl;

  return 0;
}
```

here i use std::string* key to a absl::flat_hash_map's key, but when i insert more data, the key pointer will be failure. but the ```std::unordered_map<>``` is successful.

---

You can use ```std::unordered_map<>``` to instread of the ```absl::flat_hash_map```. it will be ok.

**Steps to reproduce the bug**

It's important that we are able to reproduce the problem that you are
experiencing. Please provide all code and relevant steps to reproduce the
problem, including your `BUILD`/`CMakeLists.txt` file and build commands. Links
to a GitHub branch or [godbolt.org](https://godbolt.org/) that demonstrate the
problem are also helpful.

**What version of Abseil are you using?**

the latest master branch.

**What operating system and version are you using**

Arch Linux 6.0.9.

If you are using a Linux distribution please include the name and version of the
distribution as well.

**What compiler and version are you using?**

clang version: 14.0.6
Taget: x86_64-pc-linux-gnu
Thread model: posix

Please include the output of `gcc -v` or `clang -v`, or the equivalent for your
compiler.

**What build system are you using?**
bazel label : 5.3.2

Please include the output of `bazel --version` or `cmake --version`, or the
equivalent for your build system.

**Additional context**

**Comment by derekmauro** [comment]
This is working as intended. One way `absl::flat_hash_map` is able to achieve better performance than `std::unordered_map` by storing data in a way that cannot promise pointer stability.

Please see https://abseil.io/docs/cpp/guides/container and https://github.com/abseil/abseil-cpp/blob/4c5eb49d6aababb86d35a40c1a606b11c5bb554f/absl/container/flat_hash_map.h#L83-L89
