### ISSUE TITLE
Why absl::flat_hash_map doesn't have hash_ref function only hash_function?

### ISSUE THREAD

**Issue by MBkkt** [abseil/abseil-cpp#1324]

**Comment by derekmauro** [comment]
`absl::flat_hash_map` is designed to be as close to a drop-in replacement for `std::unordered_map` as possible. `std::unordered_map` names the method `hash_function()`, and so do we.

**Comment by MBkkt** [comment]
I mean why do you cannot extend unordered_map interface?

**Comment by derekmauro** [comment]
What problem are you trying to solve?

**Comment by MBkkt** [comment]
Not really problem, but I have code like

```cpp
auto const hash = cache_.hash_function()(string_key);
std::lock_guard lock{mutex_};
cache_.find(string_key, hash);
```

And I don't understand why do I need copy hash functor here

**Comment by MBkkt** [comment]
if `Hash::operator() const` implemented correctly it should be safe to call it from different threads, so no need copy.

**Comment by MBkkt** [comment]
Of course on practice hash functor stateless or have small state. But still don't understand why hash_ref/eq_ref/alloc_ref is private functions of raw_hash_set

**Comment by derekmauro** [comment]
> Of course on practice hash functor stateless or have small state. But still don't understand why hash_ref/eq_ref/alloc_ref is private functions of raw_hash_set

I don't know what went into the design considerations of `std::unordered_map`, but I think you've answered your own question. These are almost always stateless. And if they are not, you can wrap them with a reference type.

Deviating from the standard comes with a cost, and in this case, I don't see a motivating example to do so.
