### ISSUE TITLE
MSVC doesn't have __m128i_u

### ISSUE THREAD

**Issue by MBkkt** [abseil/abseil-cpp#1330]
**Describe the bug**

crc_memcpy_x86_64.cc(101,34): error C3861: '__m128i_u': identifier not found
crc_memcpy_x86_64.cc(275,44): error C3861: '__m128i_u': identifier not found

**Steps to reproduce the bug**

Just build with sse with MSVC

**What version of Abseil are you using?**

master

**What operating system and version are you using**

Windows

**What compiler and version are you using?**

MSVC

**What build system are you using?**

cmake

**Additional context**

Looks like on msvc should used signed `__m128i _mm_loadu_si128(__m128i*);`

https://learn.microsoft.com/en-us/cpp/cpp/m128i?view=msvc-170

https://learn.microsoft.com/en-us/cpp/intrinsics/x86-intrinsics-list?view=msvc-170

**Comment by derekmauro** [comment]
This works for me currently.

> Just build with sse with MSVC

Please supply all build steps. "Just build with sse with MSVC" doesn't tell me exactly what to do to reproduce the problem.

> What compiler and version are you using?
>
> MSVC

And the version?

**Comment by MBkkt** [comment]
> This works for me currently.

Microsoft just doesn't have this typedef, never...

Maybe it works for you few commits ago, when simd version of code will be not available under windows (sse4_2 ifdef)

Godbolt shows same error (I will send the reference when will be home, or you can try by yourself)

**Comment by derekmauro** [comment]
> Microsoft just doesn't have this typedef, never...

Apparently is does, please see https://godbolt.org/z/fGjYo37P7

**Comment by MBkkt** [comment]
probably godbolt compiler remove function in your example. also you forgot /arch:AVX

https://godbolt.org/z/qTn9q4hGf

**Comment by MBkkt** [comment]
> probably godbolt remove function in your example.

template + anon namespace

**Comment by MBkkt** [comment]
https://godbolt.org/z/vEKq8n3o7 @derekmauro your code, but without template and anon namespace (also you forgot ToCrc32c)

**Comment by MBkkt** [comment]
https://github.com/arangodb/abseil-cpp/commit/b3b33cf5fe27c78c3c22eda54864b95b96cd1fc5 should work.

I will write later, after my CI ends

**Comment by derekmauro** [comment]
Thanks, this is enough information for me to identify the issue.
