### ISSUE TITLE
Abseil raw_hash_set regression

### ISSUE THREAD

**Issue by MBkkt** [abseil/abseil-cpp#1333]
**Describe the bug**

Cannot compile

**Steps to reproduce the bug**

```cpp
struct A {
  absl::flat_hash_map<int, A> m;
};

TEST(FlatHashMap, RecursiveInstatiate) {
  A a;
  a.m[1] = A{};
}
```

**What version of Abseil are you using?**

master

**What operating system and version are you using**

Linux/Windows

**What compiler and version are you using?**

clang-14.0.6/MSVC

**What build system are you using?**

cmake

**Additional context**

check this please https://github.com/arangodb/abseil-cpp/commit/9f7cc1c4b1f0ff1b57ed58a30bff7008b0f46915

**Comment by derekmauro** [comment]
I believe this was fixed by 1063d2b829bbf1b5cf03f5f8e1e9fe4c71c9f966 and the test you suggested was added in 4e5ff1559ca3bd7bb777a1c48106464cb656e041. Thanks for finding this. Let us know if it is still an issue.
