### ISSUE TITLE
abseil-cpp-20220623.1/absl/numeric/internal/bits.h:100:28: error: call to non-'constexpr' function 'unsigned int __popcnt(unsigned int)

### ISSUE THREAD

**Issue by chennasi** [abseil/abseil-cpp#1336]
abseil-cpp-20220623.1/absl/numeric/internal/bits.h:100:28: error: call to non-'constexpr' function 'unsigned int __popcnt(unsigned int)
ninja: build stopped: subcommand failed.

python version 3.9

**Comment by derekmauro** [comment]
Please completely fill out the bug report form:
https://github.com/abseil/abseil-cpp/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md

**Comment by derekmauro** [comment]
Closing due to insufficient information.
