### ISSUE TITLE
[Bug]: Hash containers depend on StrFormat

### ISSUE THREAD

**Issue by asoffer** [abseil/abseil-cpp#1360]
### Describe the issue

containers such as `absl::flat_hash_map` have a Bazel dependency on `absl::StrFormat`.
This is restrictive because `absl::StrFormat` relies on Clang's non-standard `enable_if` extension.

### Steps to reproduce the problem

On any platform, using the Bazel build,

**Bazel query:**
```
bazel query 'allpaths("@com_google_absl//absl/container:flat_hash_set", "@com_google_absl//absl/strings:str_format")'
```
**Output:**
```
@com_google_absl//absl/container:flat_hash_set
@com_google_absl//absl/container:hash_function_defaults
@com_google_absl//absl/strings:cord
@com_google_absl//absl/strings:str_format
```

### What version of Abseil are you using?

HEAD.

### What operating system and version are you using?

Linux Mint 20

### What compiler and version are you using?

clang 14

### What build system are you using?

Bazel

### Additional context

From the depenency path, it looks like this exists because `absl::Cord` depends on `absl::StrFormat` and `absl::flat_hash_set` provides a default hashing implementation for `absl::Cord`. I suspect this dependency could be cut by using `AbslHashValue` to define `absl::Cord`s hash function. Alternatively (additionally?) it seems unlikely that `absl::Cord` needs the direct dependency on `absl::StrFormat`. The functionality might be achievable in a different way.

**Comment by derekmauro** [comment]
`absl::Cord` already uses `AbslHashValue`. It looks like the `absl::Cord` doesn't need the `absl::StrFormat` dependency at all.
