### ISSUE TITLE
[Bug]: The 20230125.0 LTS release fails to compile with sanitizers

### ISSUE THREAD

**Issue by sfc-gh-ebrossard** [abseil/abseil-cpp#1379]
### Describe the issue

It wasn't obvious to me before attempting to update to the newest release that it's broken without https://github.com/abseil/abseil-cpp/commit/35e8e3f7a2c6972d4c591448e8bbe4f9ed9f815a. Can you please create a new `20230125.1` release that includes this change? Thank you!

### Steps to reproduce the problem

Build the Cord library with `-fsanitize=address`. It fails to compile with:
```
absl/strings/internal/cord_internal.h: In copy constructor ‘constexpr absl::lts_20230125::cord_internal::InlineData::InlineData(const absl::lts_20230125::cord_internal::InlineData&)’:
absl/strings/internal/cord_internal.h:821:39: error: call to non-‘constexpr’ function ‘absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const’
  821 |     : rep_(rhs.rep_.SanitizerSafeCopy()) {
      |                                       ^
absl/strings/internal/cord_internal.h:771:9: note: ‘absl::lts_20230125::cord_internal::InlineData::Rep absl::lts_20230125::cord_internal::InlineData::Rep::SanitizerSafeCopy() const’ declared here
  771 |     Rep SanitizerSafeCopy() const {
      |         ^~~~~~~~~~~~~~~~~
```

### What version of Abseil are you using?

20230125.0

### What operating system and version are you using?

Linux/CentOS 7

### What compiler and version are you using?

GCC 10/Clang 15

### What build system are you using?

Either Bazel 6 or CMake 3

### Additional context

I'm excited for the new features like logging and crc32 in the 20230125 release :) Thanks for continuing to make improvements to Abseil!

**Comment by derekmauro** [comment]
I will likely do a patch release late next week. I'd like to wait to see if any more bug reports come in.

What's interesting is that our ASAN build did not detect this issue. I'm not sure why.

https://github.com/chipsalliance/verible/actions/runs/4011250841/jobs/6888635293#step:10:63 is how we learned about this issue. I would like to look into the differences with our ASAN build.

**Comment by derekmauro** [comment]
I've released https://github.com/abseil/abseil-cpp/releases/tag/20230125.1 to address this issue.
