### ISSUE TITLE
[Bug]: MSVC 2019 build fails with low_level_alloc.cc(331): error C2589: '(': illegal token on right side of '::'

### ISSUE THREAD

**Issue by jtattermusch** [abseil/abseil-cpp#1425]
### Describe the issue

I'm building gRPC python wheels with MSVC 2019, build fails.
See the original issue https://github.com/grpc/grpc/issues/32779

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWIN32_LEAN_AND_MEAN=1 -DMS_WIN64=1 -I. -Igrpc_root -Igrpc_root\include -Ithird_party\abseil-cpp -Ithird_party\protobuf\src -Ithird_party\utf8_range -IC:\Python37\include -IC:\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt" /EHsc /Tpthird_party\abseil-cpp\absl\base\internal\low_level_alloc.cc /Fobuild\temp.win-amd64-3.7\Release\third_party\abseil-cpp\absl\base\internal\low_level_alloc.obj -std=c++14 /MT

cl : Command line warning D9025 : overriding '/MD' with '/MT'

cl : Command line warning D9002 : ignoring unknown option '-std=c++14'

low_level_alloc.cc

third_party\abseil-cpp\absl\base\internal\low_level_alloc.cc(331): error C2589: '(': illegal token on right side of '::'

third_party\abseil-cpp\absl\base\internal\low_level_alloc.cc(331): error C2062: type 'unknown-type' unexpected

third_party\abseil-cpp\absl\base\internal\low_level_alloc.cc(331): error C2059: syntax error: ')'

C:\Python37\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: T:\altsrc\github\grpc\workspace_python_windows_x86_Python37_32bit\tools\distrib\python\grpcio_tools\grpc_tools\_protoc_compiler.pyx

  tree = Parsing.p_module(s, pxd, full_module_name)

error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```

### Steps to reproduce the problem

attempt grpc python artifact builds on windows.

### What version of Abseil are you using?

20230125.2 

### What operating system and version are you using?

Windows 2019 Server

### What compiler and version are you using?

MSVC 2019

### What build system are you using?

python wheel build (with native extension)

**Comment by jtattermusch** [comment]
The problem seems similar to https://github.com/abseil/abseil-cpp/pull/55 (which is very old, so perhaps a regression?)

**Comment by derekmauro** [comment]
We use `(std::min)(a, b)` in headers to guard against this problem because Windows has macros named `min` and `max`. If you are using one our supported build systems, build rules should have [`/DNOMINMAX`](https://github.com/abseil/abseil-cpp/blob/665ac5b425cea2462bf85dcbb56dd68ec19ad00f/absl/copts/copts.py#L41) for compiling `.cc` files.

Is this a custom build, and if so, is `/DNOMINMAX` missing?

See also: https://github.com/abseil/abseil-cpp/discussions/1271

**Comment by jtattermusch** [comment]
Thanks for the clarification. It turns out that we already set NOMINMAX for windows builds of python `grpcio` wheel (which already had dependency on absl for a while), but we don't set it yet for the `grpcio_tools` wheel (the codegen support), which only got absl dependency after upgrading to protobuf 22.x. 
So I think the solution will be to add NOMINMAX define to the grpcio_tools build as well. I'll try that and post the result here.

https://github.com/grpc/grpc/blob/724441d85bb7302d21709fa39780260cd3204908/setup.py#L400

**Comment by jtattermusch** [comment]
https://github.com/grpc/grpc/pull/32803 will fix this.
