### ISSUE TITLE
[Bug]: set(ABSL_PROPAGATE_CXX_STD ON) breaks Windows

### ISSUE THREAD

**Issue by leissa** [abseil/abseil-cpp#1432]
### Describe the issue

Using `ABSL_PROPAGATE_CXX_STD` breaks Windows support:
```
CMake Error at external/abseil-cpp/CMake/AbseilDll.cmake:790 (_absl_target_compile_features_if_available):
_absl_target_compile_features_if_available Function invoked with incorrect
arguments for function named: _absl_target_compile_features_if_available
Call Stack (most recent call first):
external/abseil-cpp/absl/CMakeLists.txt:40 (absl_make_dll)
```

### Steps to reproduce the problem

```cmake
set(ABSL_PROPAGATE_CXX_STD ON)
add_subdirectory(external/abseil-cpp)
```

### What version of Abseil are you using?

`20230125.2`: b971ac5250ea8de900eae9f95e06548d14cd95fe

### What operating system and version are you using?

Microsoft Windows Server 2022

### What compiler and version are you using?

MSVC 19.34.31943.0

### What build system are you using?

cmake 3.26.3

### Additional context

Unfortunately, I'm running into this issue with a GitHub runner as I'm personally not using Windows.
See also:
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

You can also just run the runner yourself:
https://github.com/AnyDSL/thorin2/blob/version_bump/.github/workflows/windows.yml

**Comment by coryan** [comment]
I think this is fixed already (https://github.com/abseil/abseil-cpp/commit/bd624d9f9825f76f14453beb3df81d82b9e17062), no release includes that commit though.

**Comment by leissa** [comment]
Yes, works on master. Thanks :)
