### ISSUE TITLE
[Bug]: FunctionRef doesn't resolve to correct function overload

### ISSUE THREAD

**Issue by sjperkins** [abseil/abseil-cpp#1436]
### Describe the issue

FunctionRef doesn't bind to the correct function overload which is a pity given that an FunctionRef is templated with an explicit function signature.

### Steps to reproduce the problem

```cpp
#include <string>
#include <string_view>

#include "absl/functional/function_ref.h"

std::string Func(std::string_view src) {
    return std::string(src);
}

void Func(std::string_view src, std::string & dest){
    dest = src;
}

int main(void) {
    absl::FunctionRef<std::string(std::string_view)> callable(Func);
}
```

```bash
$ g++ example.cpp -o example --std=c++17 -I ../ 
example.cpp: In function ‘int main()’:
example.cpp:15:67: error: no matching function for call to ‘absl::FunctionRef<std::__cxx11::basic_string<char>(std::basic_string_view<char>)>::FunctionRef(<unresolved overloaded function type>)’
   15 |     absl::FunctionRef<std::string(std::string_view)> callable(Func);
      |                                                                   ^
In file included from example.cpp:4:
../absl/functional/function_ref.h:128:3: note: candidate: ‘constexpr absl::FunctionRef<R(Args ...)>::FunctionRef(const absl::FunctionRef<R(Args ...)>&) [with R = std::__cxx11::basic_string<char>; Args = {std::basic_string_view<char, std::char_traits<char> >}]’
  128 |   FunctionRef(const FunctionRef& rhs) = default;
      |   ^~~~~~~~~~~
../absl/functional/function_ref.h:128:34: note:   no known conversion for argument 1 from ‘<unresolved overloaded function type>’ to ‘const absl::FunctionRef<std::__cxx11::basic_string<char>(std::basic_string_view<char>)>&’
  128 |   FunctionRef(const FunctionRef& rhs) = default;
      |               ~~~~~~~~~~~~~~~~~~~^~~
../absl/functional/function_ref.h:119:3: note: candidate: ‘template<class F, class, typename std::enable_if<absl::is_function<F>::value, int>::type <anonymous> > absl::FunctionRef<R(Args ...)>::FunctionRef(F*) [with F = F; <template-parameter-2-2> = <template-parameter-1-2>; typename std::enable_if<absl::is_function<F>::value, int>::type <anonymous> = <anonymous>; R = std::__cxx11::basic_string<char>; Args = {std::basic_string_view<char, std::char_traits<char> >}]’
  119 |   FunctionRef(F* f)  // NOLINT(runtime/explicit)
      |   ^~~~~~~~~~~
../absl/functional/function_ref.h:119:3: note:   template argument deduction/substitution failed:
example.cpp:15:67: note:   couldn’t deduce template parameter ‘F’
   15 |     absl::FunctionRef<std::string(std::string_view)> callable(Func);
      |                                                                   ^
In file included from example.cpp:4:
../absl/functional/function_ref.h:104:3: note: candidate: ‘template<class F, class> absl::FunctionRef<R(Args ...)>::FunctionRef(const F&) [with F = F; <template-parameter-2-2> = <template-parameter-1-2>; R = std::__cxx11::basic_string<char>; Args = {std::basic_string_view<char, std::char_traits<char> >}]’
  104 |   FunctionRef(const F& f ABSL_ATTRIBUTE_LIFETIME_BOUND)
      |   ^~~~~~~~~~~
../absl/functional/function_ref.h:104:3: note:   template argument deduction/substitution failed:
example.cpp:15:67: note:   couldn’t deduce template parameter ‘F’
   15 |     absl::FunctionRef<std::string(std::string_view)> callable(Func);
```

### What version of Abseil are you using?

8518869eb9a8ef098a9dd7780b9e55d5b43b5873

### What operating system and version are you using?

Ubuntu 20.04 (WSL2)

### What compiler and version are you using?

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 10.4.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-ADJDhj/gcc-10-10.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-ADJDhj/gcc-10-10.4.0/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.4.0 (Ubuntu 10.4.0-1ubuntu1~20.04)

### What build system are you using?

I used the following command line to generate the problem, `g++ example.cpp -o example --std=c++17 -I${ABSL_PATH}`, but also encountered the problem when using `absl::FunctionRef` with tensorstore.

### Additional context

This can be worked around by using a lambda that defers to the correct overload:

```cpp
int main(void) {
    absl::FunctionRef<std::string(std::string_view)> callable([](std::string_view src){ return Func(src); });
}
```

**Comment by derekmauro** [comment]
This example doesn't work with `std::function` either: https://godbolt.org/z/x6EGn5Ebb

I think this is (unfortunately) working as intended. See https://stackoverflow.com/a/30394755.

Please re-open if you disagree.
