### ISSUE TITLE
[Bug]: Infinite loop in find_or_prepare_insert / raw_hash_set.h on arm64

### ISSUE THREAD

**Issue by clundquist-stripe** [abseil/abseil-cpp#1437]
### Describe the issue

Related: https://github.com/envoyproxy/envoy/issues/27005

In Envoy, the bug manifests as an infinite loop on a worker thread.
The thread is stuck here:
https://github.com/abseil/abseil-cpp/blob/8317b9a01cbc32594ad4bf971709c97cb13ec921/absl/container/internal/raw_hash_set.h#L2175

The linked Envoy GitHub issue has various stack traces and disassembly information.

### Steps to reproduce the problem

Unfortunately we don't have a reproduction.
We've seen this issue 3 times over the last few weeks.

### What version of Abseil are you using?

8317b9a01cbc32594ad4bf971709c97cb13ec921

### What operating system and version are you using?

Ubuntu 20.04

### What compiler and version are you using?

clang 14

### What build system are you using?

Bazel
6.0.0-pre.20220706.4 

### Additional context

We've only seen this on Amazon `c7g` (Graviton / Neoverse) instances, after migrating from `c6i` (intel icelake?) instances

**Comment by bbarenblat** [comment]
Thanks for bringing this to our attention! Let me see if I can track down a root cause for this. In the meantime, if you do find a way to reliably reproduce this, please let me know!

**Comment by clundquist-stripe** [comment]
Thank you @bbarenblat! 

If it would help, @bobby-stripe or I could likely setup a Zoom meeting and screenshare / pair on this while we have a host stuck in this state. Trying to debug this without a repro is totally a tricky proposition!

I did my best to document what I could in the Envoy thread, if there are any other specific things we can gather, please let us know!

if you need to reach me, feel free to email me at clundquist@stripe.com.
I'm based in Seattle / Pacific time.

We have the stuck host cordoned off for the next while, but eventually we will lose it.

**Comment by bobby-stripe** [comment]
Copying over Chris's comment from the envoy issue: 
> 
> @bobby-stripe and I had a helpful debugging session with @bbarenblat, who working on aarch64 optimizations in Abseil. We spent time stepping through the code in lldb-14 (the debug symbols we ship don’t work in the default LLDB, or in gdb), and confirmed that we were infinitely looping in https://github.com/abseil/abseil-cpp/blob/8317b9a01cbc32594ad4bf971709c97cb13ec921/absl/container/internal/raw_hash_set.h#L2173-L2184 this `while (true)` loop.
> 
> The loop is supposed to exit when `if (ABSL_PREDICT_TRUE(g.MaskEmpty())) break;` returns true. But it looks/feels like a codegen issue — checking if the control block (a packed 64-bit set of integers) is empty is done via:
> 
> ```
>     uint64_t mask =
>         vget_lane_u64(vreinterpret_u64_u8(vceq_s8(
>                           vdup_n_s8(static_cast<int8_t>(ctrl_t::kEmpty)),
>                           vreinterpret_s8_u8(ctrl))),
>                       0);
>     return NonIterableBitMask<uint64_t, kWidth, 3>(mask);
> ```
> 
> (thats the MaskEmpty implementation). The expanded kEmpty SIMD value is stored in a register for use across values, but looks corrupted: we expect to see 8 0x80s in a row, but instead see:
> 
> ```
>         v8 = {0x3c 0x0f 0x4c 0x00 0x00 0x00 0x00 0x00 0x58 0x77 0x3d 0x34 0xea 0xff 0x00 0x00}
>        v10 = {0x75 0xff 0x75 0x80 0x80 0x80 0x80 0x80 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00}
> ```
> 
> (I think v8 is supposed to be the mask, but we’d expect to see 8 0x80s in a row)
> 
> The other possibility that we can think of apart from miscompilation is a kernel bug around saving + restoring SIMD registers.
> 
> (in particular, we see `seq.next()`; get called over and over, which does
> 
> ```
>   void next() {
>     index_ += Width;
>     offset_ += index_;
>     offset_ &= mask_;
>   }
> ```
> 
> , and index_ is stored in register x11, with a current value of `0x00046b0147854238`
> 
> Now with my own words:
> 
> We noted the capacity of the Abseil Hashmap reports as 1, which means we're probably in initialization case from Envoy because `lazy_hash_map` is a list until there are 3 entries.
> 
> Bobby found this llvm issue [llvm/llvm-project#56397](https://github.com/llvm/llvm-project/issues/56397) which feels like the right neighborhood.
> 
> Stripe will work to upgrade the version of llvm we use to compile Envoy. We hit a snag compiling on `focal` because the llvm artifact for aarch64 uses a newer version of glibc
> 
> ```
> /opt/llvm/bin/llvm-config: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /opt/llvm/bin/llvm-config)
> ```
> 
> so we will have to compile llvm for our platform to build Envoy with a newer version.
> 
> @bbarenblat is investigating from his side looking for a reproduction. Initial stress tests could not reproduce it.

**Comment by clundquist-stripe** [comment]
Here is a first approximation using [godbolt](https://godbolt.org/#g:!((g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:12,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:5,endLineNumber:26,positionColumn:5,positionLineNumber:26,selectionStartColumn:5,selectionStartLineNumber:26,startColumn:5,startLineNumber:26),source:'%23include+%3Ciostream%3E%0A%23include+%3Cvector%3E%0A%23include+%3Clist%3E%0A%23include+%3Cstring%3E%0A%0A++struct+HeaderEntryImpl+%7B%0A++++std::string+key_%3B%0A++++std::string+value_%3B%0A++++//+std::list%3CHeaderEntryImpl%3E::iterator+entry_%3B%0A++++HeaderEntryImpl(std::string+key,+std::string+value)+%7B%0A++++++++key_+%3D+key%3B%0A++++++++value_+%3D+value%3B%0A++++%7D%0A++%7D%3B%0A%0A%23include+%22absl/hash/hash.h%22%0A%23include+%22absl/container/flat_hash_map.h%22%0A%0A++using+HeaderNode+%3D+std::list%3CHeaderEntryImpl%3E::iterator%3B%0A++using+HeaderNodeVector+%3D+absl::InlinedVector%3CHeaderNode,+1%3E%3B%0A++using+HeaderLazyMap+%3D+absl::flat_hash_map%3Cabsl::string_view,+HeaderNodeVector%3E%3B%0A%0A++int+main(void)+%7B%0A++++std::list%3CHeaderEntryImpl%3E+headers_+%3D+std::list%3CHeaderEntryImpl%3E()%3B%0A++++headers_.push_back(HeaderEntryImpl(%22foo%22,+%22Bar%22))%3B%0A++++%0A++++HeaderLazyMap+lazy_map_%3B%0A%0A++++for+(auto+node+%3D+headers_.begin()%3B+node+!!%3D+headers_.end()%3B+%2B%2Bnode)+%7B%0A++++++HeaderNodeVector%26+v+%3D+lazy_map_%5Bnode-%3Ekey_%5D%3B%0A++++++v.push_back(node)%3B%0A++++%7D%0A++++return+0%3B%0A++%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:54.72236119893446,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:clang_trunk,deviceViewOpen:'1',filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'0',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:11,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:abseil,ver:trunk)),options:'-O2+-std%3Dc%2B%2B17',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86-64+clang+(trunk)+(Editor+%231)',t:'0')),k:45.27763880106554,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',m:66.9090909090909,n:'0',o:'',t:'0'),(g:!((h:output,i:(editorid:1,fontScale:12,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86-64+clang+(trunk)+(Compiler+%231)',t:'0')),header:(),l:'4',m:33.09090909090909,n:'0',o:'',s:0,t:'0')),l:'3',n:'0',o:'',t:'0')),version:4)

I don't write much C++ these days, so please forgive me.
One key difference is I'm using a std::string instead of an abs::string_view.

My hope is the above may help someone more familiar with aarch64 look at the codegen differences between clang versions for aarch64

Bobby and I are working on adapting this to use libfuzz and have it loop on `c7g` instances.

**Comment by clundquist-stripe** [comment]
We investigated with AWS and it was happening during some updates. Impact was limited to graviton3. This will not re-occur.
