### ISSUE TITLE
[Bug]: Call for std::move for non-moveable types

### ISSUE THREAD

**Issue by Exactlywb** [abseil/abseil-cpp#1443]
### Describe the issue

Hi!

I've mentioned that abseil-cpp sometimes is trying to call for `std::move` for non-moveable class types so `std::move` calls for copy-ctors.

Examples:
```bash
/home/exactlywb/abseil-cpp/absl/flags/marshalling.cc:158:24:   required from here
/home/exactlywb/abseil-cpp/absl/strings/internal/str_split_internal.h:268:25: warning: classtype absl::string_view has no move constructor [-Wclobbered]
   268 |       : text_(std::move(input_text)),
          |                         ^~~~~~~~~~
 13 /home/exactlywb/abseil-cpp/absl/strings/internal/str_split_internal.h:268:24: note: ‘std::move’ i    s going to call for a copy constructor
   268 |       : text_(std::move(input_text)),
          |               ~~~~~~~~~^~~~~~~~~~~~
 ```
 
 and another one:
 
 ```bash
/home/exactlywb/abseil-cpp/absl/strings/internal/cord_rep_consume.cc: In function ‘void absl::cor    d_internal::ReverseConsume(CordRep*, ConsumeFn)’:
 /home/exactlywb/abseil-cpp/absl/strings/internal/cord_rep_consume.cc:57:33: warning: classtype ha    s no move constructor [-Wclobbered]
     57 |   return Consume(rep, std::move(consume_fn));
          |                                 ^~~~~~~~~~
 /home/exactlywb/abseil-cpp/absl/strings/internal/cord_rep_consume.cc:57:32: note: ‘std::move’ is     going to call for a copy constructor
     57 |   return Consume(rep, std::move(consume_fn));
          |                       ~~~~~~~~~^~~~~~~~~~~~
 /home/exactlywb/abseil-cpp/absl/strings/internal/cord_rep_consume.cc:45:38: note:   initializing     argument 2 of ‘void absl::cord_internal::Consume(CordRep*, ConsumeFn)’
     45 | void Consume(CordRep* rep, ConsumeFn consume_fn) {
          |                            ~~~~~~~~~~^~~~~~~~~~
```

`absl::string_view` and `absl::FunctionRef` don't have move constructor. Excerpt from standard:

```
If the definition of a class X does not explicitly declare a move constructor, a non-explicit one will be implicitly
declared as defaulted if and only if
(8.1) — X does not have a user-declared copy constructor,
(8.2) — X does not have a user-declared copy assignment operator,
(8.3) — X does not have a user-declared move assignment operator, and
(8.4) — X does not have a user-declared destructor.
[Note: When the move constructor is not implicitly declared or explicitly supplied, expressions that otherwise
would have invoked the move constructor may instead invoke a copy constructor. — end note]
```

### Steps to reproduce the problem

I've used gcc with own patch.

### What version of Abseil are you using?

f39f340c589354db8ab2f07894894f23c9ea3ae6

### What operating system and version are you using?

ubuntu

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04

### What compiler and version are you using?

11.2 + own patches

### What build system are you using?

cmake version 3.16.3

**Comment by derekmauro** [comment]
Is this `-Wclobbered` warning something that exists only in your patched gcc? I can't reproduce it.

Fixing the second example is straightforward. The first example is in templated code that uses either `std::string` or `absl::string_view`. It seems to rely on the following:

> [Note: When the move constructor is not implicitly declared or explicitly supplied, expressions that otherwise
would have invoked the move constructor may instead invoke a copy constructor. — end note]

`std::is_move_assignable<absl::string_view>::value` returns true in my testing. Why should this be changed?

**Comment by Exactlywb** [comment]
> Is this `-Wclobbered` warning something that exists only in your patched gcc? I can't reproduce it.

Yes. This warning is reproducible only in my patched gcc and can't be reproduces with the regular one.
> Fixing the second example is straightforward. The first example is in templated code that uses either `std::string` or `absl::string_view`. It seems to rely on the following:
> 
> > [Note: When the move constructor is not implicitly declared or explicitly supplied, expressions that otherwise
> > would have invoked the move constructor may instead invoke a copy constructor. — end note]
> 
> `std::is_move_assignable<absl::string_view>::value` returns true in my testing. Why should this be changed?

I am agree with you that the first example doesn't need to be fixed and the behavior is founded on the following note. Anyway, the second example looks redundant. Don't you think that it looks better to remove calling `std::move` for `ConsumeFn`?

**Comment by derekmauro** [comment]
> I am agree with you that the first example doesn't need to be fixed and the behavior is founded on the following note. Anyway, the second example looks redundant. Don't you think that it looks better to remove calling `std::move` for `ConsumeFn`?

Yes. I think the second example is probably a vestigial `std::move` that was once correctly called on `std::function`. It will be removed by a pending change.
