### ISSUE TITLE
[Bug]: CMake build failing on MacOS Ventura 13.3.1 / Xcode 14.3

### ISSUE THREAD

**Issue by vrai** [abseil/abseil-cpp#1465]
### Describe the issue

When building Abseil using CMake (3.26.3) the build fails while linking with the error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libabsl_bad_any_cast_impl.a(bad_any_cast.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libabsl_bad_any_cast_impl.a(bad_any_cast.cc.o) has no symbols
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: libabsl_bad_any_cast_impl.a the table of contents is empty (no object file members in the library define global symbols)
```

The expectation being that the build would successfully complete under CMake.

### Steps to reproduce the problem

```
git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp
mkdir build
cd build
cmake -DCMAKE_CXX_STANDARD=17 ..
make
```

### What version of Abseil are you using?

```
e9bb35cea3d3b18bdaaa273f6e1746d9334aa324
```

### What operating system and version are you using?

```
ProductName:            macOS
ProductVersion:         13.3.1
ProductVersionExtra:    (a)
BuildVersion:           22E772610a
```

### What compiler and version are you using?

```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### What build system are you using?

```
cmake version 3.26.3
```

**Comment by Light-City** [comment]
I also got this problem.

**Comment by zpassanger** [comment]
It's not to me 😭

**Comment by tikikun** [comment]
i also got this problem

**Comment by c0rt** [comment]
I also got this problem

**Comment by anthonyalayo** [comment]
same, can we get some attention?

**Comment by anthonyalayo** [comment]
This problem is quite frustrating. Ranlib / Libtool will throw a warning that the following objects are empty:

```
[92/212] Linking CXX static library lib/libabsl_string_view.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_string_view.a the table of contents is empty (no object file members in the library define global symbols)
[160/212] Linking CXX static library lib/libabsl_bad_any_cast_impl.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_bad_any_cast_impl.a the table of contents is empty (no object file members in the library define global symbols)
[161/212] Linking CXX static library lib/libabsl_bad_optional_access.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_bad_optional_access.a the table of contents is empty (no object file members in the library define global symbols)
[164/212] Linking CXX static library lib/libabsl_bad_variant_access.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_bad_variant_access.a the table of contents is empty (no object file members in the library define global symbols)
[185/212] Linking CXX static library lib/libabsl_log_entry.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_log_entry.a the table of contents is empty (no object file members in the library define global symbols)
[207/212] Linking CXX static library lib/libabsl_flags.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: lib/libabsl_flags.a the table of contents is empty (no object file members in the library define global symbols)
[212/212] Linking CXX static library lib/libabsl_flags_parse.a
```

There is no way to turn these errors off. `-no_warning_for_no_symbols` only works for object files, but it does not work for static libraries. Here is my attempt at trying:

```
/Library/Developer/CommandLineTools/usr/bin/ranlib -no_warning_for_no_symbols -c _deps/absl-build/absl/types/libabsl_bad_variant_access.a
warning: /Library/Developer/CommandLineTools/usr/bin/ranlib: archive library: _deps/absl-build/absl/types/libabsl_bad_variant_access.a the table of contents is empty (no object file members in the library define global symbols)
```

@derekmauro , would it be possible to provide CMake flags to turn off the building of these static libraries?

**Comment by derekmauro** [comment]
It looks like the problem is that all of these libraries are conditionally empty, for example, in C++17 mode when the library is a polyfill. It seems annoying to fix this in CMake. It's possible that adding some no-op function or variable to these libraries will silence the issue. I'll test this fix this week.

**Comment by anthonyalayo** [comment]
> It looks like the problem is that all of these libraries are conditionally empty, for example, in C++17 mode when the library is a polyfill. It seems annoying to fix this in CMake. It's possible that adding some no-op function or variable to these libraries will silence the issue. I'll test this fix this week.

Agree on the assessment. Thanks a lot!

**Comment by derekmauro** [comment]
I don't have an Apple machine so 2a63665 was tested on CI. I was not able to replicate the build failure, but I did see the warning in the logs. I'm not sure why this fails the build for the people reporting the problem.

After 2a63665 I no longer see the warning in the logs. If someone who has the problem can verify this is fixed it would be helpful. Thanks!
