### ISSUE TITLE
[Bug]: error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by JaeseungYeom** [abseil/abseil-cpp#1467]
### Describe the issue

Compilation fails with gcc/11.2.1 and gcc/12.1.1. 

abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: ‘numeric_limits’ is not a member of ‘std’
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before ‘>’ token
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max

### Steps to reproduce the problem

It was part of gRPC building via
  FetchContent_Declare(grpc
    GIT_REPOSITORY https://github.com/grpc/grpc.git
    GIT_TAG        v1.28.0)

### What version of Abseil are you using?

commit b832dce8489ef7b6231384909fd9b68d5a5ff2b7 (HEAD, tag: 20200225)
Author: Abseil Team <absl-team@google.com>
Date:   Tue Feb 25 22:27:31 2020 +0100

### What operating system and version are you using?

linux toss 4 (4.18.0-425.19.2.1toss.t4.x86_64). It is based on redhat deployed on LLNL systems.

### What compiler and version are you using?

gcc/11.2.1 and gcc/12.1.1. 

### What build system are you using?

cmake/3.26.3

### Additional context

Simply adding "#include <limits>" fixes the issue.

**Comment by Sil3ntStorm** [comment]
https://github.com/abseil/abseil-cpp/blob/lts_2023_01_25/absl/synchronization/internal/graphcycles.cc#L40

**Comment by derekmauro** [comment]
> ### What version of Abseil are you using?
> commit [b832dce](https://github.com/abseil/abseil-cpp/commit/b832dce8489ef7b6231384909fd9b68d5a5ff2b7) (HEAD, tag: 20200225) Author: Abseil Team [absl-team@google.com](mailto:absl-team@google.com) Date: Tue Feb 25 22:27:31 2020 +0100

This issue has been fixed for nearly 3 years. Update to a more recent version.
