### ISSUE TITLE
[Bug]: Older gcc compilation error: 'max_align_t' is not a member of 'std'

### ISSUE THREAD

**Issue by JiachengLiang** [abseil/abseil-cpp#1470]
### Describe the issue

When I cross-compile the abseil-cpp source code using gcc4.8.1, I encounter the following problem:
error: 'max_align_t' is not a member of 'std'
![image](https://github.com/abseil/abseil-cpp/assets/60999072/2719105a-1d53-4745-a17d-29846895542b)
![image](https://github.com/abseil/abseil-cpp/assets/60999072/e3eac9fb-e0a8-4c5f-bff0-bb4bb36e926b)

### Steps to reproduce the problem

Compile the abseil-cpp source code in the context of gcc4.8.1.

### What version of Abseil are you using?

abseil-cpp：https://github.com/abseil/abseil-cpp/tree/20220623.1

### What operating system and version are you using?

EulerOS

### What compiler and version are you using?

gcc 4.8.1

### What build system are you using?

cmake version 3.20.5

### Additional context

I tried to make the following patch for absl/meta/type_traits.h in the abseil-cpp open source code to solve the above problem, please ask if this solution can be accepted by the community.

```
--- a/absl/meta/type_traits.h	2023-06-02 18:43:22.754151497 +0800
+++ b/absl/meta/type_traits_new.h	2023-06-02 18:37:25.366207927 +0800
@@ -49,11 +49,19 @@
 
 // Defines the default alignment. `__STDCPP_DEFAULT_NEW_ALIGNMENT__` is a C++17
 // feature.
+#if defined(__GNUC__) && (__GNUC__ < 5)
+#if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
+#define ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT __STDCPP_DEFAULT_NEW_ALIGNMENT__
+#else  // defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
+#define ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT alignof(max_align_t)
+#endif  // defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
+#else
 #if defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
 #define ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT __STDCPP_DEFAULT_NEW_ALIGNMENT__
 #else  // defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
 #define ABSL_INTERNAL_DEFAULT_NEW_ALIGNMENT alignof(std::max_align_t)
 #endif  // defined(__STDCPP_DEFAULT_NEW_ALIGNMENT__)
+#endif
 
 namespace absl {
 ABSL_NAMESPACE_BEGIN

```

**Comment by YanAnzouyijun** [comment]
@derekmauro

**Comment by JiachengLiang** [comment]
This is an urgent issue, please confirm.@derekmauro

**Comment by sgayda2** [comment]
Since this seems to be urgent I will reply here, but keep in mind I do not work on absl and I am only an observer. According to the documentation absl does not support gcc 4.8 and has not done so for a while.

See this comment from another thread: https://github.com/abseil/abseil-cpp/issues/718#issuecomment-646021612

According to the documentation the earliest supported gcc version is 7.3.1, the docs can be found here: https://abseil.io/docs/cpp/platforms/platforms

**Comment by JiachengLiang** [comment]
Thanks for answering! I was thinking that if some products must be compiled with a lower version of gcc, but a new version of abseil-cpp is selected, is this compatibility patch feasible?@sgayda2 @derekmauro

**Comment by derekmauro** [comment]
GCC 4.8 is not supported. Sorry about this.

**Comment by JiachengLiang** [comment]
> GCC 4.8 is not supported. Sorry about this.

Ok thanks. By the way, where can I get the basic dependency requirements for abseil-cpp.

**Comment by derekmauro** [comment]
https://opensource.google/documentation/policies/cplusplus-support
https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md

**Comment by JiachengLiang** [comment]
> https://opensource.google/documentation/policies/cplusplus-support https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md

Got it, thank you~😄
