### ISSUE TITLE
[Bug]: Build failure with NVCC and clang

### ISSUE THREAD

**Issue by dchen496** [abseil/abseil-cpp#1479]
### Describe the issue

Hi, I'm seeing a build failure with NVCC 12.1 and clang 15 in `absl/meta/type_traits.h`, specifically for this block of code:

```
#if ABSL_HAVE_BUILTIN(__is_trivially_relocatable) && \
    !(defined(__clang__) && (defined(_WIN32) || defined(_WIN64)))
template <class T>
struct is_trivially_relocatable
    : std::integral_constant<bool, __is_trivially_relocatable(T)> {};
#else
// Otherwise we use a fallback that detects only those types we can feasibly
// detect. Any time that has trivial move-construction and destruction
// operations is by definition trivally relocatable.
template <class T>
struct is_trivially_relocatable
    : absl::conjunction<absl::is_trivially_move_constructible<T>,
                        absl::is_trivially_destructible<T>> {};
#endif
```

The `#if` passes, but NVCC does not seem to actually know what `__is_trivially_relocatable` is and returns an error like this:

```
external/com_google_absl/absl/meta/type_traits.h(512): error: type name is not allowed
      : std::integral_constant<bool, __is_trivially_relocatable(T)> {};
                                                                ^

external/com_google_absl/absl/meta/type_traits.h(512): error: identifier "__is_trivially_relocatable" is undefined
      : std::integral_constant<bool, __is_trivially_relocatable(T)> {};
                                     ^
```

I've been able to work around it for now by just patching the code to use the `#else` case.

### Steps to reproduce the problem

Create a file called `test.cu` with the following contents (copied from type_traits.h and config.h):

```
#include <type_traits>

#ifdef __has_builtin
#define ABSL_HAVE_BUILTIN(x) __has_builtin(x)
#else
#define ABSL_HAVE_BUILTIN(x) 0
#endif

#if ABSL_HAVE_BUILTIN(__is_trivially_relocatable) && \
    !(defined(__clang__) && (defined(_WIN32) || defined(_WIN64)))
template <class T>
struct is_trivially_relocatable
    : std::integral_constant<bool, __is_trivially_relocatable(T)> {};
#endif
```

With NVCC 12.1 and the default host compiler (gcc 9) it works: `nvcc -std=c++17 test.cu`

With clang it fails: `nvcc -std=c++17 --compiler-bindir=/usr/lib/llvm-15/bin/clang-15 test.cu`

### What version of Abseil are you using?

0b6f0003e4bced9d04da8d6d240da7f77877f538, but I see the same code on master.

### What operating system and version are you using?

Ubuntu 20.04

### What compiler and version are you using?

```
$ clang-15 -v
Ubuntu clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
Found CUDA installation: /usr/local/cuda-12.1, version
```
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

### What build system are you using?

Bazel 6.2.1

**Comment by derekmauro** [comment]
I'm not sure if our check `ABSL_HAVE_BUILTIN(__is_trivially_relocatable)` is correct. `__is_trivially_relocatable` is not prefixed with `__builtin`, unlike `__builtin_ctzll`, for example. But I think we can just exclude `__NVCC__` until we figure out what the correct check is.
