### ISSUE TITLE
[Bug]: compilation of time_zone_format.cc broken under QNX

### ISSUE THREAD

**Issue by xzxzzxzxzca** [abseil/abseil-cpp#1490]
### Describe the issue

Source file `time/internal/cctz/src/time_zone_format.cc` does `#define _XOPEN_SOURCE` in order to use `strptime`.
However, on QNX (at least v 7.1) in `<sys/platform.h>` the definition isn't merely checked for presence, but is value-tested. It understands values 500, 600, and 700, and otherwise will bail out with `#error This version of XOPEN_SOURCE is not supported`.

The header is included like this:
```
In file included from .../qnx7/usr/include/limits.h:29,
                 from .../qnx7/usr/include/c++/v1/limits.h:58,
                 from external/com_google_absl/absl/base/config.h:52,
                 from external/com_google_absl/absl/time/internal/cctz/src/time_zone_format.cc:27:
```

I think it should be something like
```
#define _XOPEN_SOURCE 500
```

Or at least so under `#if defined(__QNX__)`

### Steps to reproduce the problem

Build abseil under QNX 7.1

### What version of Abseil are you using?

`c2435f8342c2d0ed8101cb43adfd605fdc52dca2`

(tag `20230125.3`)

### What operating system and version are you using?

Crosscompiling on Linux to QNX 7.1

### What compiler and version are you using?

```
$ ntox86_64-g++ -v
Using built-in specs.
COLLECT_GCC=ntox86_64-g++
COLLECT_LTO_WRAPPER=.../qnx/sdp710/host/linux/x86_64/usr/lib/gcc/x86_64-pc-nto-qnx7.1.0/8.3.0/lto-wrapper
Target: x86_64-pc-nto-qnx7.1.0
Configured with: ../configure --srcdir=.. --enable-gnu-indirect-function=yes --enable-cxx-flags=-stdlib=libstdc++ --enable-cheaders=c_global --enable-initfini-array --enable-default-pie --with-as=x86_64-pc-nto-qnx7.1.0-as --with-ld=x86_64-pc-nto-qnx7.1.0-ld --with-tune=generic --prefix=/opt/qnx710/host/linux/x86_64/usr --libexecdir=/opt/qnx710/host/linux/x86_64/usr/lib --with-gxx-include-dir=/opt/qnx710/target/qnx7/usr/include/c++/8.3.0 --enable-threads=posix --enable-__cxa_atexit --enable-languages=c++ --with-sysroot=/opt/qnx710/target/qnx7 --target=x86_64-pc-nto-qnx7.1.0 --disable-nls --disable-tls --disable-libssp --disable-libstdcxx-pch --enable-libgomp --enable-shared --enable-multilib --with-bugurl=http://www.qnx.com --enable-default-ssp CC=x86_64-unknown-linux-gnu-gcc CFLAGS=-m64 LDFLAGS='-Wl,-s ' CXX=x86_64-unknown-linux-gnu-g++ CXXFLAGS=-m64 AUTOMAKE=: AUTOCONF=: AUTOHEADER=: AUTORECONF=: ACLOCAL=:
Thread model: posix
gcc version 8.3.0 20190222 (lookup) [qnx710 1535#57] (GCC) 
```

### What build system are you using?

bazel 6.1.0

**Comment by derekmauro** [comment]
QNX is not a [supported platform](https://opensource.google/documentation/policies/cplusplus-support). Since we cannot test this, a fix from the community is required.

Please also note that we import this code from https://github.com/google/cctz. Fixes should be contributed to the CCTZ project.

**Comment by xzxzzxzxzca** [comment]
Thanks for the reply @derekmauro
What's the proposed action plan then? I could of course create a tiny PR with essentially just
```
--- #define _XOPEN_SOURCE
+++ #define _XOPEN_SOURCE 500
```

since I've tested and it "works on my machine". Would that be OK? Or should I submit that to the CCTZ project, so you could update later?

**Comment by xzxzzxzxzca** [comment]
Anyhow, reported the bug upstream: https://github.com/google/cctz/issues/265
UPD: fixed upstream!

**Comment by derekmauro** [comment]
The upstream fix was imported as ac39cc1ec6fed8d3738b4df9589803c23d6d1e3a.

**Comment by kheaactua** [comment]
@xzxzzxzxzca were your QNX builds ever successful?  I'm on ntoaarch64le (QNX 7.1, gcc8.3) and I hit a bunch of errors with `20240722.0`

For libtime_zone (which got me to this issue) I mysteriously hit "error: [pthread_cond_timedwait](http://www.qnx.com/developers/docs/7.1/index.html#com.qnx.doc.neutrino.lib_ref/topic/p/pthread_cond_timedwait.html) was not declared in this scope", though setting `_XOPEN_SOURCE=600` gets me past that.

And otherwise I hit an error where `MaskedPointer` is missing a default constructor.
```
In file included from /sdp710-qc/stage/target/qnx7/usr/include/c++/v1/memory:668,
                 from /sdp710-qc/stage/target/qnx7/usr/include/c++/v1/algorithm:644,
                 from /sdp710-qc/stage/target/qnx7/usr/include/c++/v1/__string:57,
                 from /sdp710-qc/stage/target/qnx7/usr/include/c++/v1/string_view:176,
                 from /sdp710-qc/stage/target/qnx7/usr/include/c++/v1/string:505,
                 from /src/absl/log/internal/flags.h:25,
                 from /src/absl/log/flags.cc:16:
/sdp710-qc/stage/target/qnx7/usr/include/c++/v1/atomic: In instantiation of '_Tp std::__1::__c11_atomic_load(const std::__1::__gcc_atomic::__gcc_atomic_t<_Tp>*, std::__1::memory_order) [with _Tp = absl::lts_20240722::flags_internal::MaskedPointer; std::__1::memory_order = std::__1::memory_order]':
/sdp710-qc/stage/target/qnx7/usr/include/c++/v1/atomic:926:34:   required from '_Tp std::__1::__atomic_base<_Tp, <anonymous> >::load(std::__1::memory_order) const [with _Tp = absl::lts_20240722::flags_internal::MaskedPointer; bool <anonymous> = false; std::__1::memory_order = std::__1::memory_order]'
/src/absl/flags/internal/flag.h:534:41:   required from 'bool absl::lts_20240722::flags_internal::FlagValue<T, (absl::lts_20240722::flags_internal::FlagValueStorageKind)3>::Get(const absl::lts_20240722::flags_internal::SequenceLock&, T&) const [with T = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >]'
/src/absl/flags/internal/flag.h:824:9:   required from 'T absl::lts_20240722::flags_internal::Flag<T>::Get() const [with T = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >]'
/src/absl/flags/internal/flag.h:852:21:   required from 'static T absl::lts_20240722::flags_internal::FlagImplPeer::InvokeGet(const FlagType&) [with T = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >; FlagType = absl::lts_20240722::flags_internal::Flag<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >]'
/src/absl/flags/flag.h:98:52:   required from 'T absl::lts_20240722::GetFlag(absl::lts_20240722::Flag<T>&) [with T = std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >; absl::lts_20240722::Flag<T> = absl::lts_20240722::flags_internal::Flag<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >]'
/src/absl/log/flags.cc:93:47:   required from here
/sdp710-qc/stage/target/qnx7/usr/include/c++/v1/atomic:708:7: error: no matching function for call to 'absl::lts_20240722::flags_internal::MaskedPointer::MaskedPointer()'
   _Tp __ret;
       ^~~~~
In file included from /src/absl/flags/flag.h:41,
                 from /src/absl/log/flags.cc:27:
```

I can get passed this be defining a default constructor, but that doesn't seem like the proper approach.  Everything builds without issue on x86x64 with modern compilers. :)

**Comment by xzxzzxzxzca** [comment]
Hi @kheaactua 

It's been a while since I built abseil using qcc but at the time it used to work, as far as I can remember.

I'm pretty sure I haven't seen the compiler error you posted. Maybe this is caused by a newer version of abseil. You could try the one from approx a year ago and see if it's any better.

Unfortunately, I won't be able to help beyond that advice. Good luck :)

**Comment by kheaactua** [comment]
Thanks!  I got it to work and posted [this PR](https://github.com/abseil/abseil-cpp/pull/1758).  Maybe they'll make it in and help other QNX devs. :)
