### ISSUE TITLE
[Bug]: `ParsedFormat` does not work with runtime minimum field length specifier (`*`)

### ISSUE THREAD

**Issue by jnooree** [abseil/abseil-cpp#1491]
### Describe the issue

`ParsedFormat` does not work with runtime minimum field length specifier (*).

### Steps to reproduce the problem

[godbolt](https://godbolt.org/z/ba4bs8q57)

```cpp
absl::ParsedFormat<'s'> fmt1("%*s");       // Error, Format specified does not match the template arguments
absl::ParsedFormat<'d', 's'> fmt2("%*s");  // Error, Format specified does not match the template arguments

using Conv = absl::FormatConversionCharSet;
absl::ParsedFormat<Conv::kIntegral, Conv::kString> fmt3("%*s");  // Error, Format specified does not match the template arguments
```

Interestingly, gcc compiles all of them (which is also a bug, first one should not compile).

### What version of Abseil are you using?

[`d74b1104a5e9a24964b34c30dcbfbc3bcca88576`](https://github.com/abseil/abseil-cpp/tree/d74b1104a5e9a24964b34c30dcbfbc3bcca88576)

### What operating system and version are you using?

Ubuntu Linux 20.04 (x86_64)

### What compiler and version are you using?

clang v16.0.0

### What build system are you using?

cmake version 3.16.3 (N/A, just FYI)

**Comment by higher-performance** [comment]
Hi, I think this may need `'*'` instead of `'d'` or `Conv::kIntegral`? See here: https://godbolt.org/z/sKEe3veYv

**Comment by jnooree** [comment]
Oops, thank you very much!
