### ISSUE TITLE
[Bug]: Compile error when building with MSVC in C++14 mode for AVX2

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [abseil/abseil-cpp#1504]
### Describe the issue

When building crc32c with MSVC in C++14 mode for AVX2 architecture I get a compilation failure:

`C:\Projects\SVN\ThirdPartyLibs\abseil\20230125.3\absl\crc\internal\crc_memcpy_x86_64.cc(391): error C7555: use of designated initializers requires at least '/std:c++20'`

Given this error, my educated guess is that the CRC code supporting AVX2 is not compatible with C++14 :(
Even if Abseil claims C++14 compatibility
Maybe there is some preprocessor macro I can activate to avoid this issue?

### Steps to reproduce the problem

I am using CMake and ninja, but the actual arror is straightforward to reproduce with the following command line:

`cl.exe  /nologo /TP  -IC:\Projects\SVN\ThirdPartyLibs\abseil\20230125.3 /DWIN32 /D_WINDOWS /W3 /GR /EHsc /O2 /Ob2 /DNDEBUG -MD /W3 /bigobj /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE -std:c++14 /Foabsl\crc\CMakeFiles\crc32c.dir\internal\crc_memcpy_x86_64.cc.obj /Fdabsl\crc\CMakeFiles\crc32c.dir\crc32c.pdb /FS -c C:\Projects\SVN\ThirdPartyLibs\abseil\20230125.3\absl\crc\internal\crc_memcpy_x86_64.cc /arch:AVX2`

Removing `/arch:AVX2` gets rid of the compiler error, but I'm compiling my project with that flag and it is not straightforward to disable it selectively for only this source file (not to mention potential ODR problems that non-uniform compilation flags may bring).

### What version of Abseil are you using?

LTS 20230125.3

### What operating system and version are you using?

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045

### What compiler and version are you using?

Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64

### What build system are you using?

cmake version 3.25.1-msvc1

ninja --version
1.11.0

### Additional context

I am building abseil as a dependency for libprotobuf, which is a dependency for my C++ library that I must build with `/arch:AVX2` for performance reasons.

**Comment by derekmauro** [comment]
Duplicate of #1413. This is fixed at head.

**Comment by dmenendez-gruposantander** [comment]
Thank you!
I see this was fixed in head on Mar 15.
Would you happen to know when this change will make it into a Release?

**Comment by derekmauro** [comment]
There should be a release in the next week.

**Comment by dmenendez-gruposantander** [comment]
Thank you for the info!
