### ISSUE TITLE
StripSuffix doc

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#151]
The input is absl::string_view, not std::string.. same for the other functions in the file.

```
// StripSuffix()
//
// Returns a view into the input std::string 'str' with the given 'suffix' removed,
// but leaving the original std::string intact. If the suffix does not match at the
// end of the std::string, returns the original std::string instead.
ABSL_MUST_USE_RESULT inline absl::string_view StripSuffix(
    absl::string_view str, absl::string_view suffix) {
  if (absl::EndsWith(str, suffix)) str.remove_suffix(suffix.size());
  return str;
}
```

**Comment by mbxx** [comment]
Thanks for pointing this out, I'll make a pass over the file.

**Comment by OlafvdSpek** [comment]
absl/strings/escaping.h is affected too.

**Comment by mbxx** [comment]
The problem turned out to be quite widespread, as it was introduced by some sed transformations.  I think this should be fixed across the entire Abseil codebase now.  Thank you for pointing this out.  If you notice any more trouble spots, please let us know and we'll fix those, too.
