### ISSUE TITLE
[Bug]: Cannot use absl::int128 in absl::StrCat

### ISSUE THREAD

**Issue by lperron** [abseil/abseil-cpp#1512]
### Describe the issue

cannot use int128 in StrCat

### Steps to reproduce the problem

Any code that try to use StrCat(absl::int128 value)

### What version of Abseil are you using?

20230802.0

### What operating system and version are you using?

mac os x, linux, windows...

### What compiler and version are you using?

on mac: 

Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### What build system are you using?

cmake, bazel

### Additional context

Sad that you can use int128 but cannot print them

**Comment by derekmauro** [comment]
This works for me.
https://godbolt.org/z/Man1aYYTq

Can you provide a complete reproduction?

**Comment by lperron** [comment]
You are right,.

I removed the code I added on the last release and it works.
