### ISSUE TITLE
[Bug]: Building Abseil 20230802 fails if `-DABSL_BUILD_TESTING=ON`

### ISSUE THREAD

**Issue by knotgrass** [abseil/abseil-cpp#1514]
### Describe the issue

OS: Ubuntu 22.04.2 LTS
GCC: 11.4
Cmake version 3.22.1

If I using flag `-DABSL_BUILD_TESTING=OFF`, the building progress is OK
But if `-DABSL_BUILD_TESTING=ON`, I got a problem

File below is show full console log
[cmake_build.log](https://github.com/abseil/abseil-cpp/files/12337449/cmake_build.log)

### Steps to reproduce the problem

I just launch this script below
```
workspaceFolder="$(dirname "$(dirname "$(realpath "$0")")")"
cd "$workspaceFolder"

mkdir -p third_party && cd third_party

# https://abseil.io/docs/cpp/tools/cmake-installs
git clone https://github.com/abseil/abseil-cpp.git -b lts_2023_08_02
cd abseil-cpp

mkdir -p build && cd build
cmake .. \
    -DABSL_BUILD_TESTING=ON \
    -DABSL_USE_GOOGLETEST_HEAD=ON \
    -DCMAKE_CXX_STANDARD=17 \
    -DABSL_PROPAGATE_CXX_STD=ON \
    -DCMAKE_INSTALL_PREFIX=$workspaceFolder/third_party/abseil-cpp/install

cmake --build . --target all -j$(nproc)
ctest
cmake --build . --target install -j$(nproc)
```

### What version of Abseil are you using?

the name of the LTS release: `lts_2023_08_02`
```
❯ cd third_party/abseil-cpp
❯ git rev-parse HEAD
29bf8085f3bf17b84d30e34b3d7ff8248fda404e
```

### What operating system and version are you using?

Ubuntu 22.04.2 LTS

### What compiler and version are you using?

❯ gcc --version
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### What build system are you using?

❯ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by derekmauro** [comment]
This is already fixed at head. Abseil was relying on a transitive include from GoogleTest.

If you use Abseil and GoogleTest at head, this will work.
If you use the latest LTS and the latest GoogleTest (1.14.0) this will work.
If you mix them, it will not.

**Comment by knotgrass** [comment]
GoogleTest is auto downloaded when I built with Cmake.
I try build GoogleTest 1.14.0 first, then build Abseil lts_2023_08_02. I got a same problem

Here is console log that describe googletest is downloaded when build.
```-- Build files have been written to: /home/tz/Documents/programming/SuperCxx/third_party/abseil-cpp/build/googletest-external
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (download, verify and extract) for 'googletest'
-- Downloading...
   dst='/home/tz/Documents/programming/SuperCxx/third_party/abseil-cpp/build/googletest-external/googletest-prefix/src/main.zip'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/google/googletest/archive/main.zip'
-- Downloading... done
-- extracting...
     src='/home/tz/Documents/programming/SuperCxx/third_party/abseil-cpp/build/googletest-external/googletest-prefix/src/main.zip'
     dst='/home/tz/Documents/programming/SuperCxx/third_party/abseil-cpp/build/googletest-src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 33%] No update step for 'googletest'
[ 44%] No patch step for 'googletest'
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest
```
