### ISSUE TITLE
[Bug]: gmock not included in two test targets

### ISSUE THREAD

**Issue by RobL371** [abseil/abseil-cpp#1515]
### Describe the issue

When building absl_hash_instantiated_test and absl_log_globals_test, gmock/gmock.h cannot be found. It appears that GTest::gtest_main in both test definitions needs to be GTest::gmock_main.

### Steps to reproduce the problem

I'm building with cmake, using a local simultanous build of googletest v1.14.0. Setting flags:

set(ABSL_USE_EXTERNAL_GOOGLETEST ON CACHE BOOL "")
set(ABSL_FIND_GOOGLETEST OFF CACHE BOOL "")
set(ABSL_ENABLE_INSTALL ON CACHE BOOL "")
set(BUILD_SHARED_LIBS ON CACHE BOOL "")
set(BUILD_TESTING ON CACHE BOOL "")
set(ABSL_BUILD_TESTING ON CACHE BOOL "")
set(ABSL_BUILD_TEST_HELPERS ON CACHE BOOL "")

### What version of Abseil are you using?

lts_2023_08_02

### What operating system and version are you using?

Windows

### What compiler and version are you using?

Visual Studio

### What build system are you using?

cmake

**Comment by derekmauro** [comment]
The absl_hash_instantiated_test issue looks to be a copy-paste issue from c154d20abce2f1ae6bd35bd774313e351493219b, where the test uses `hash_test.cc` instead of `hash_instantiated_test.cc`.

I'm not sure what the absl_log_globals_test issue is since it depends on GTest::gmock, which should be sufficient.

It's weird is that our tests don't catch either of these issues. I'm not sure why that is. I'll try making the replacements.

**Comment by RobL371** [comment]
This is what I see in absl/log/CMakeLists.txt, around line 831:

```
absl_cc_test(
  NAME
    log_globals_test
  SRCS
    "globals_test.cc"
  COPTS
    ${ABSL_TEST_COPTS}
  LINKOPTS
    ${ABSL_DEFAULT_LINKOPTS}
  DEPS
    absl::core_headers
    absl::log
    absl::log_globals
    absl::log_internal_globals
    absl::log_internal_test_helpers
    absl::log_severity
    absl::scoped_mock_log
    GTest::gtest_main
)
```

When I change the last line to GTest::gmock_main, it works.

For the hash test, even if I change the test to use the right file, there's still an issue.  hash_instantiated_test.cc includes absl/hash/hash_testing.h, which in turn includes gmock/gmock.h.  However, it appears that this gmock inclusion violates "minimal includes" style guidelines, because if I comment it out, the instantiated test runs without gmock.

**Comment by derekmauro** [comment]
True. Thanks for the heads up about the unneeded include. I'll change to gmock in CMake, then see if I can remove the include in a followup, since removing an include from a header sometimes breaks downstream users.

**Comment by RobL371** [comment]
True about downstream.  Zero penalty for using gmock instead of just gtest,
so if it were me I would leave gmock and call it a day.

**Comment by derekmauro** [comment]
This should be fixed. Please re-open if it is not.
