### ISSUE TITLE
absl/base/dynamic_annotations.h conflicts with glog when using TSAN

### ISSUE THREAD

**Issue by lhsoft** [abseil/abseil-cpp#1523]
### Describe the issue

I'm using abseil-cpp and glog(0.5.0) with COPTS `-fsanitize=thread` and  get the following error:
`external/_main~data_deps_ext~com_google_absl/absl/base/dynamic_annotations.h:218:6: error: conflicting declaration of C function 'void AnnotateBenignRaceSized(const char*, int, const volatile void*, size_t, const char*)'
  218 | void AnnotateBenignRaceSized(const char* file, int line,
      |      ^~~~~~~~~~~~~~~~~~~~~~~
In file included from external/_main~data_deps_ext~com_github_brpc_brpc/src/butil/logging.h:36,
                 from external/_main~data_deps_ext~com_github_brpc_brpc/src/bthread/types.h:27,
                 from external/_main~data_deps_ext~com_github_brpc_brpc/src/brpc/controller.h:31,
                 from taishan_common/profile_service.cpp:3:
bazel-out/k8-opt/bin/external/glog~0.5.0/_virtual_includes/glog/glog/logging.h:1006:17: note: previous declaration 'void AnnotateBenignRaceSized(const char*, int, const volatile void*, long int, const char*)'`

### Steps to reproduce the problem

build with glog

### What version of Abseil are you using?

a3020c763c12bd16bbf00804abe853afa5778174.zip

### What operating system and version are you using?

ubuntu

### What compiler and version are you using?

gcc 9.1

### What build system are you using?

6.1.1

**Comment by derekmauro** [comment]
glog fixed this problem nearly 2 years ago: https://github.com/google/glog/commit/ffb40018a50e86d3a9e518405cee59e76e5430d9

You need to update.
