### ISSUE TITLE
[Bug]: Riscv build of Protobuf fails due to abseil

### ISSUE THREAD

**Issue by apcameron** [abseil/abseil-cpp#1561]
### Describe the issue

Refer to https://github.com/protocolbuffers/protobuf/issues/14549

### Steps to reproduce the problem

Refer https://github.com/protocolbuffers/protobuf/issues/14549

### What version of Abseil are you using?

Unknown

### What operating system and version are you using?

Linux

### What compiler and version are you using?

gcc 12

### What build system are you using?

Refer to https://github.com/protocolbuffers/protobuf/issues/14549

**Comment by derekmauro** [comment]
I have no way of testing RISC-V, but I think the problem is that the code needs to be linked with `-latomic`. Can you try adding `-latomic` to your linker options? I don't know what build system you are using since you didn't answer that question, but I would accept a pull request to add it if someone could figure how where it needs to be added and test the fix.

**Comment by apcameron** [comment]
I managed to get protobuf to compile clean with the following diff

<pre><b>diff --git a/CMakeLists.txt b/CMakeLists.txt</b>
<b>index f78fccc27..51e866bc1 100644</b>
<b>--- a/CMakeLists.txt</b>
<b>+++ b/CMakeLists.txt</b>
<font color="#2AA1B3">@@ -191,7 +191,8 @@</font> if (NOT MSVC)
       return static_cast&lt;int&gt;(std::atomic&lt;int64_t&gt;{});
     }
   &quot; protobuf_HAVE_BUILTIN_ATOMICS)
<font color="#C01C28">-  if (NOT protobuf_HAVE_BUILTIN_ATOMICS)</font>
<font color="#26A269">+  if (NOT protobuf_HAVE_BUILTIN_ATOMICS OR ${CMAKE_SYSTEM_PROCESSOR} MATCHES</font>
<font color="#26A269">+</font>       <font color="#26A269">  &quot;riscv&quot;)</font><span style="background-color:#C01C28"> </span>
     set(protobuf_LINK_LIBATOMIC true)
   endif (NOT protobuf_HAVE_BUILTIN_ATOMICS)
   set(CMAKE_REQUIRED_FLAGS ${OLD_CMAKE_REQUIRED_FLAGS})
</pre>
