### ISSUE TITLE
int128.h warnings with -Wpedantic

### ISSUE THREAD

**Issue by ojura** [abseil/abseil-cpp#157]
When building Google Cartographer (which defines `-Wpedantic`) I get warnings like these if Abseil header directories are specified using `-I` instead of `-isystem`:

<details><summary>int128.h warnings</summary>
<p>

```
_deps/abseil-src/absl/numeric/int128.h:88:22: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
     alignas(unsigned __int128)
                      ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:102:30: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
   constexpr uint128(__int128 v);           // NOLINT(runtime/explicit)
                              ^
_deps/abseil-src/absl/numeric/int128.h:103:39: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
   constexpr uint128(unsigned __int128 v);  // NOLINT(runtime/explicit)
                                       ^
_deps/abseil-src/absl/numeric/int128.h:117:31: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
   uint128& operator=(__int128 v);
                               ^
_deps/abseil-src/absl/numeric/int128.h:118:40: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
   uint128& operator=(unsigned __int128 v);
                                        ^
_deps/abseil-src/absl/numeric/int128.h:142:31: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   constexpr explicit operator __int128() const;
                               ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:142:31: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h:143:40: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   constexpr explicit operator unsigned __int128() const;
                                        ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:143:40: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h:256:57: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   static constexpr bool traps = numeric_limits<unsigned __int128>::traps;
                                                         ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:313:45: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
 inline uint128& uint128::operator=(__int128 v) {
                                             ^
_deps/abseil-src/absl/numeric/int128.h:317:54: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
 inline uint128& uint128::operator=(unsigned __int128 v) {
                                                      ^
_deps/abseil-src/absl/numeric/int128.h:395:37: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
 constexpr uint128::uint128(__int128 v)
                                     ^
_deps/abseil-src/absl/numeric/int128.h: In constructor ‘constexpr absl::uint128::uint128(__int128)’:
_deps/abseil-src/absl/numeric/int128.h:397:54: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
       hi_{static_cast<uint64_t>(static_cast<unsigned __int128>(v) >> 64)} {}
                                                      ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h: At global scope:
_deps/abseil-src/absl/numeric/int128.h:398:46: warning: ISO C++ does not support ‘__int128’ for ‘v’ [-Wpedantic]
 constexpr uint128::uint128(unsigned __int128 v)
                                              ^
_deps/abseil-src/absl/numeric/int128.h:492:29: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
 constexpr uint128::operator __int128() const {
                             ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:492:29: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h:492:29: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h: In member function ‘constexpr absl::uint128::operator __int128() const’:
_deps/abseil-src/absl/numeric/int128.h:493:23: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   return (static_cast<__int128>(hi_) << 64) + lo_;
                       ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h: At global scope:
_deps/abseil-src/absl/numeric/int128.h:496:38: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
 constexpr uint128::operator unsigned __int128() const {
                                      ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:496:38: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h:496:38: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
_deps/abseil-src/absl/numeric/int128.h: In member function ‘constexpr absl::uint128::operator __int128 unsigned() const’:
_deps/abseil-src/absl/numeric/int128.h:497:32: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   return (static_cast<unsigned __int128>(hi_) << 64) + lo_;
                                ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h: In function ‘absl::uint128 absl::operator*(absl::uint128, absl::uint128)’:
_deps/abseil-src/absl/numeric/int128.h:655:31: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
   return static_cast<unsigned __int128>(lhs) *
                               ^~~~~~~~
_deps/abseil-src/absl/numeric/int128.h:656:31: warning: ISO C++ does not support ‘__int128’ for ‘type name’ [-Wpedantic]
          static_cast<unsigned __int128>(rhs);
```
</p>
</details>

This is on Ubuntu 18.04.

**Comment by derekmauro** [comment]
This is working as intended. We don't support `-Wpedantic` because it is counter-productive.

`-Wpedantic` warns about anything that doesn't strictly conform to ISO C++. Our implementation of `uint128` uses non-standard compiler intrinsics on platforms that support them. We also have an implementation of `uint128` that doesn't rely compiler intrinsics for platforms that don't have compiler support, but why would you want something that is slower?

See also https://abseil.io/docs/cpp/platforms/compilerflags.

**Comment by ojura** [comment]
In that case, it would be nice if we could have Abseil library targets export the interface headers in the [`INTERFACE_SYSTEM_INCLUDE_DIRECTORIES`](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_SYSTEM_INCLUDE_DIRECTORIES.html) property instead of [`INTERFACE_INCLUDE_DIRECTORIES`](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html), so they get included with `-isystem`.

Or maybe this is a good reason to get rid of `-Wpedantic` in Cartographer. I wonder if they would be open to that.

**Comment by ojura** [comment]
@derekmauro WDYT?

**Comment by derekmauro** [comment]
I don't know much about that. Would that disable all warnings when we are building Abseil on its own, or only when Abseil is used as a subproject?

**Comment by ojura** [comment]
Probably would silence them in both cases. How about `option(ABSEIL_SYSTEM_HEADERS “Declare Abseil headers as system headers.” false)`?

**Comment by derekmauro** [comment]
It would be an extra feature that would have a small but non-zero cost to maintain, and I don't think any of the Abseil maintainers are going to think much about it or care to maintain it. @JonathanDCohen is also be re-working CMake support soon. I don't know if there is a standard solution to this problem, but if there is, I think we'd rather figure out what that is than add another option.

**Comment by ojura** [comment]
Okay, my proposal is in #160. I am not aware that there is a standard way of handling this.

**Comment by Mizux** [comment]
side note: for googlecartographer/cartographer why not simply replacing the `INTERFACE_INCLUDE_DIRECTORIES` by `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES` ?

i.e.:
```cmake
set_target_properties(standalone_absl
    PROPERTIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
    ${ABSEIL_INCLUDE_DIRS}
  )
```
src: https://github.com/googlecartographer/cartographer/blob/master/cmake/modules/FindAbseil.cmake#L75

**Comment by ojura** [comment]
@Mizux, this problem is not exhibited in Cartographer master. Cartographer master uses `ExternalProject_add` to build Abseil. `standalone_absl` is a single imported target. Imported targets' include directories are marked as `SYSTEM` by default.

The problem is exhibited in my PR https://github.com/googlecartographer/cartographer/pull/1387, where I fetch abseil during configuring, and build it later using `add_subdirectory`. If we were fixing this on Cartographer's side, we would have to move `INTERFACE_SYSTEM_INCLUDE_DIRECTORIES` to `INTERFACE_INCLUDE_DIRECTORIES` for __all__ Abseil targets (and not just a single `standalone_abseil` target), and there is a whole bunch of them. I am not aware of how you would even enumerate them in CMake in a portable way - there is [`BUILDSYSTEM_TARGETS`](https://cmake.org/cmake/help/latest/prop_dir/BUILDSYSTEM_TARGETS.html), but that exists only in CMake 3.7+.

**Comment by EricWF** [comment]
I think Abseil's documentation here is wrong. `ExternalProject_add` seems like the correct way to include `abseil` despite what the documentation say.s

**Comment by JonathanDCohen** [comment]
As a historical note, the reason we avoided recommending ExternalProject_Add officially was that there was a lot of push back against requiring downloading abseil at build time.  If you're using ExternalProject_Add and you have at least CMake 3.11, it may be worthwhile to consider using [FetchContent](https://cmake.org/cmake/help/v3.14/module/FetchContent.html?highlight=externalproject) instead

**Comment by ojura** [comment]
@JonathanDCohen and if you are using `add_subdirectory()` to build Abseil after fetching it with FetchContent, you can still run into this. #160 is a proposed mitigation
