### ISSUE TITLE
[Bug]: Publish VLOG

### ISSUE THREAD

**Issue by dimo414** [abseil/abseil-cpp#1579]
### Describe the issue

The `VLOG` macro, available in [glog](https://github.com/google/glog#verbose-logging), is documented in [a few places](https://github.com/search?q=repo%3Aabseil%2Fabseil-cpp%20vlog&type=code) and is mentioned in the [guide](https://abseil.io/docs/cpp/guides/logging) but appears to not actually exist in open source Abseil.

The lack of `VLOG`, or at least a log level below `INFO`, prevents easily migrating from glog to Abseil, so it would be very helpful if this macro (or a reasonable replacement and migration path) could be provided.

### Steps to reproduce the problem

N/A

### What version of Abseil are you using?

HEAD

### What operating system and version are you using?

N/A

### What compiler and version are you using?

N/A

### What build system are you using?

N/A

**Comment by derekmauro** [comment]
It's finally here in https://github.com/abseil/abseil-cpp/commit/7b6c17e378224844d8663a410da2da5353b205b9. Please test it out and file new issues if you encounter any problems.
