### ISSUE TITLE
[Bug]: Add Privacy Manifest

### ISSUE THREAD

**Issue by dmaclach** [abseil/abseil-cpp#1602]
### Describe the issue

Apple has listed the Abseil library on its [list of SDKs](https://developer.apple.com/support/third-party-SDK-requirements/) that require Privacy Manifests ([WWDC Video](https://developer.apple.com/videos/play/wwdc2023/10060/), [docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests?language=objc)). Can we get a privacy manifest added to the depot?

### Steps to reproduce the problem

N/A

### What version of Abseil are you using?

Head

### What operating system and version are you using?

Any Apple OS

### What compiler and version are you using?

N/A

### What build system are you using?

N/A

**Comment by derekmauro** [comment]
I'm tagging this with "help wanted". I don't think any team member uses xcode or does Apple development or is in a position to test this. The Abseil library does not collect any information.

If someone needs this, I would welcome the contribution.
