### ISSUE TITLE
absl::string_view issues on "clang-target-msvc"

### ISSUE THREAD

**Issue by denchat** [abseil/abseil-cpp#161]
It seems clang-target-msvc has issues on `absl::string_view` (even with abseil own implementation)

While MSVC works on abseil own implementation :
```
  std::string_view sview_std = std::string_view(char_ptr, sz);
  absl::string_view sview_absl = absl::string_view(char_ptr, sz);

  std::cout << absl::StrCat(sview_absl, "ever") // Error on clang-target-msvc
  //          << absl::StrCat(sview_std, "ever")   // Error on MSVC
```
[godbolt.org/z/3dXOdg](https://godbolt.org/z/3dXOdg)

clang-target-msvc doesn't work and errors as:
```
In file included from C:/Program Files/C++ Source/abseil-cpp/absl/strings/ascii.cc:15:
C:\Program Files\C++ Source\abseil-cpp\absl/strings/ascii.h(198,10):  error: no matching constructor for initialization of 'absl::string_view' (aka 'basic_string_view<char>')
  return absl::string_view(it, str.end() - it);
         ^                 ~~~~~~~~~~~~~~~~~~
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.13.26128\include\xstring(809,12):  note: candidate constructor not viable: no known conversion from 'std::_String_view_iterator<std::char_traits<char> >' to 'const std::basic_string_view<char, std::char_traits<char> >::const_pointer' (aka 'const char *const') for 1st argument
        constexpr basic_string_view(_In_reads_(_Count) const const_pointer _Cts, const size_type _Count)
                  ^
```

This is related to [stackoverflow.com/q/51966426](https://stackoverflow.com/questions/51966426) .

**Comment by denchat** [comment]
The previous title is wrong because `__cplusplus >= 201703L` can filter out clang-target-msvc already. I misunderstood in the 1st place. 

It turns out MSVC compile abseil string_view implementation but clang-target-msvc doesn't.

Moreover, in both MSVC and clang-target-msvc, StrCat error when takes `std::string_view` parameters. If this could be fixed also, it would be nice.

[godbolt.org/z/xn2sa7](https://godbolt.org/z/xn2sa7)

**Comment by zhangxy988** [comment]
Thanks for the report.
This is definitely an issue because we don't want `std::string_view` and `absl::string_view` to both exist as two distinct types (which will cause a lot of trouble/confusion for users). I'll look into removing the commented `ABSL_HAVE_STD_STRING_VIEW` from the MSVC section.

**Comment by denchat** [comment]
Thank for response.  So this mean on MSVC now there are two distinct types of std;:string_view and absl::string_view but they are supposed to be one type std::string_view. However std::string_view of MSVC (and only MSVC) plays naughty to abseil string library. Am I correct?

I just found out that clang-target-msvc somehow successfully keeps aliasing std::string_view even if `ABSL_HAVE_STD_STRING_VIEW` still remains undefined.

```
// static_assert(ABSL_HAVE_STD_STRING_VIEW);
static_assert(!std::is_same_v<std::string_view,absl::string_view>,   // just fails on clang-target-msvc
              "absl::string_view is an alias of std::string_view"); // without defining ABSL_HAVE_STD_STRING_VIEW
```

**Comment by zhangxy988** [comment]
So there seems to be two issues here:
1. On MSVC, since `ABSL_HAVE_STD_STRING_VIEW` is not properly defined when `std::string_view` is available, both `absl::string_view` and `std::string_view` exist as distinct types. This causes `absl::StrCat()` to choke on `std::string_view` because it only accepts with `absl::string_view`. This can be fixed by correctly define `ABSL_HAVE_STD_STRING_VIEW`.

2. In ascii.h, the implementation of `StripLeadingAsciiWhitespace()` assumes `string_view::const_iterator` is `const char*` and this isn't true with the MSVC standard library (which has its own `std::_String_view_iterator`). This can be fixed by modifying the implementation from `absl::string_view(it, str.end() - it);` to `absl::string_view(&*it, str.end() - it);`.

I'll look into fixing both.

**Comment by denchat** [comment]
After some testing, enabling `ABSL_HAVE_STD_STRING_VIEW` and change pointer type into `&*it` and `&*str.begin()` seems to fix the complication. Thank you.

**Comment by zhangxy988** [comment]
I have the change ready and it's under review. It should land here some time next week.

**Comment by zhangxy988** [comment]
This should be fixed now. We are still working on adding MSVC 2017 coverage in our CI though.
