### ISSUE TITLE
CMake ABSL_RUN_TESTS not honored

### ISSUE THREAD

**Issue by wesleygriffin** [abseil/abseil-cpp#162]
Repro: https://github.com/wesleygriffin/absl-cmake-case

The main issue I'm reporting here is that using the setup outlined in the above repo, ABSL_RUN_TESTS=OFF seems to have no effect. I'm using the FetchContent module to populate absl so that I can then use add_subdirectory from my project.

third_party/Abseil.cmake forces ABSL_RUN_TESTS to OFF in the cache, but that's not being picked up. Perhaps this is a mis-understanding on my part.

More importantly, it would be nice if the absl CMake files did not even add the tests when absl is not the top-level project. Even if I get ABSL_RUN_TESTS to not run the tests, they are still being built as part of my project and I would prefer that they weren't.

Thanks.

**Comment by rongjiecomputer** [comment]
The fix should be simple enough: just change `BUILD_TESTING` to `ABSL_RUN_TESTS` in https://github.com/abseil/abseil-cpp/blob/30de20488bb88dc22d23521c5c222ec6d924e289/CMake/AbseilHelpers.cmake#L138-L141
@JonathanDCohen Should I take this issue?

**Comment by JonathanDCohen** [comment]
Just coming around to this.  Yeah, this seems like the problem, and youc an totally take the issue if you'd like :)
