### ISSUE TITLE
[Bug]: Parameter pack workaround fails with nvcc

### ISSUE THREAD

**Issue by h-vetinari** [abseil/abseil-cpp#1629]
### Describe the issue

Was looking into [failures](https://github.com/conda-forge/tensorflow-feedstock/pull/372) with abseil 20240116.1 and tensorflow today, which fail with
```
# Execution platform: @local_execution_config_platform//:platform
$PREFIX/include/absl/strings/str_cat.h: In function 'std::enable_if_t<(sizeof... (T) > 1), typename std::common_type<typename std::conditional<true, void, absl::lts_20240116::strings_internal::EnableIfFastCase<T, typename std::enable_if<((std::is_arithmetic<T>::value && (! std::is_same<T, char>::value)) && (! std::is_same<T, bool>::value)), void>::type> >::type ...>::type> absl::lts_20240116::StrAppend(absl::Nonnull<T*>, T ...)':
$PREFIX/include/absl/strings/str_cat.h:606:316: error: expected ';' before '...' token
  606 |   for (const SomeTrivialEmptyType& dummy2 :
      |                                           ^  

$PREFIX/include/absl/strings/str_cat.h:606:43: error: parameter packs not expanded with '...': 
  606 |   for (const SomeTrivialEmptyType& dummy2 :
      |                                           ^                         
```

The relevant chunk of code
https://github.com/abseil/abseil-cpp/blob/2f9e432cce407ce0ae50676696666f33a77d42ac/absl/strings/str_cat.h#L606-L614
got introduced recently (d5a2cec006d14c6801ddeb768bf2574a1cf4fa7f), and as it turns out, there already was a [comment](https://github.com/abseil/abseil-cpp/commit/d5a2cec006d14c6801ddeb768bf2574a1cf4fa7f#r138749803) on that commit noting exactly this problem:

> @georgthegreat: @derekmauro, this pattern breaks nvcc (tested with `nvcc11.4 + c++14`, `nvcc11.4 + c++17`, `nvcc12.1 + c++17` modes) with the following error:
> 
> ```
> absl/strings/str_cat.h:609:316: error: expected ';' after expression
> for (const SomeTrivialEmptyType &dummy2 : ({((((((void)(n = (lengths[i]))), ((void)((n < (0)) ? ((void)((*(pos++)) = '-')), (n = (~n)) : (0)))), ((void)numbers_internal::FastIntToBufferBackward(numbers_internal::UnsignedAbsoluteValue(std::move(args)), pos += n, static_cast< uint32_t>(n)))), ((void)(++i))), dummy1)...}))
> ```
> 
> Can we do anything about this? I do not quite understand the meaning of this code, so I can not truly refactor it to make it compilable.
> 
> I do understand that nvcc is quite weird when it comes to such complex c++ code, so I need a workaround of some kind.

> @derekmauro: @higher-performance - Can you take a look at this?

I think it effectively boils down to a compiler shortcoming of nvcc, but it would be good to be able to use abseil with CUDA.

### Steps to reproduce the problem

Build CUDA-enabled tensorflow with newest abseil.

### What version of Abseil are you using?

20240116.1

### What operating system and version are you using?

Linux

### What compiler and version are you using?

GCC + nvcc

### What build system are you using?

bazel

**Comment by higher-performance** [comment]
Thanks for following up, for some reason it seems I never received the notification for the initial comment. I'll take a look.

**Comment by higher-performance** [comment]
I seem to be [unable](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:12,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:1,endLineNumber:33,positionColumn:1,positionLineNumber:33,selectionStartColumn:1,selectionStartLineNumber:33,startColumn:1,startLineNumber:33),source:'%23include+%3Cstddef.h%3E%0A%23include+%3Cstring%3E%0A%23include+%3Ctype_traits%3E%0A%23include+%3Cutility%3E%0A%0Atemplate%3Cclass+T,+class...+U%3E+auto+foo(T+v,+U...)+%7B+return+v%3B+%7D%0Atemplate%3Cclass+T%3E+auto+bar(T+v)+%7B+return+v%3B+%7D%0A%0Atemplate%3Cclass+String,+class...+T%3E%0Avoid+StrAppend(String*+str,+T...+args)+%7B%0A++size_t+old_size+%3D+0%3B%0A++size_t+i+%3D+0%3B%0A++ptrdiff_t+n%3B%0A++typename+String::pointer+pos+%3D+%26(*str)%5Bold_size%5D%3B%0A++using+SomeTrivialEmptyType+%3D+std::false_type%3B%0A++ptrdiff_t+lengths%5Bsizeof...(T)%5D+%3D+%7B%7D%3B%0A++const+SomeTrivialEmptyType+dummy1%3B%0A++for+(const+SomeTrivialEmptyType%26+dummy2+:%0A+++++++%7B((void)(n+%3D+lengths%5Bi%5D),%0A+++++++++(void)(n+%3C+0+%3F+(void)(*pos%2B%2B+%3D+!'-!'),+(n+%3D+~n)+:+0),%0A+++++++++(void)foo(%0A+++++++++++++bar(std::move(args)),%0A+++++++++++++pos+%2B%3D+n,+static_cast%3Cuint32_t%3E(n)),%0A+++++++++(void)%2B%2Bi,+dummy1)...%7D)+%7B%0A++++(void)dummy2%3B%0A++%7D%0A%7D%0A%0Aint+main()+%7B%0A++++++++std::string+a%3B%0A++++++++StrAppend(%26a,+1)%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:52.39869199990427,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((g:!((h:compiler,i:(compiler:nvcxx_x86_cxx24_1,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'0'),flagsViewOpen:'1',fontScale:12,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!((name:abseil,ver:trunk),(name:benchmark,ver:trunk),(name:blaze,ver:trunk),(name:boost,ver:'181'),(name:googletest,ver:trunk),(name:llvm,ver:trunk),(name:magic_enum,ver:trunk)),options:'-O1+-s+-std%3Dc%2B%2B14',overrides:!(),selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'+x86+nvc%2B%2B+24.1+(Editor+%231)',t:'0')),k:48.77750596859633,l:'4',m:80.0834202294056,n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compilerName:'x86-64+clang+(trunk)',editorid:1,fontScale:12,fontUsePx:'0',j:1,wrap:'1'),l:'5',n:'0',o:'Output+of+x86+nvc%2B%2B+24.1+(Compiler+%231)',t:'0')),header:(),l:'4',m:19.91657977059436,n:'0',o:'',s:0,t:'0')),k:47.601308000095734,l:'3',n:'0',o:'',t:'0')),l:'2',m:100,n:'0',o:'',t:'0')),version:4) to reproduce the compile error with a minimal example. Could you please do the following?

1. Specify what compiler version & flags you are using

1. Try to reproduce the compile error with a minimal example in Godbot

Thanks!

**Comment by georgthegreat** [comment]
I am quite unsure that `nvc++` provided by godbolt actually is an NVidia / Cuda compiler

It looks like nvc++ is a part of HPC SDK, which is a totally diferent product
https://docs.nvidia.com/hpc-sdk/compilers/hpc-compilers-ref-guide/

It looks like godbolt does not provide nvcc compiler at all.

**Comment by higher-performance** [comment]
Ah. I tried this locally with an nvcc though and still didn't see an issue. So I'm still stuck.

**Comment by h-vetinari** [comment]
Interestingly, I've failed to reproduce the error my collaborator encountered as well (I've tried the godbolt example from [above](https://github.com/abseil/abseil-cpp/issues/1629#issuecomment-1964649073) with both `nvcc` 11.2 & 12.0 and `--std=c++17`)

@georgthegreat, can you reproduce the issue on your end?

**Comment by h-vetinari** [comment]
OK, it has been reproduced on our end now as well, but so far only in the context of building tensorflow. Full log can be found [here](https://github.com/conda-forge/tensorflow-feedstock/pull/372#issuecomment-1968002573).

**Comment by higher-performance** [comment]
Thanks for the log. Unfortunately this isn't enough for me to try to investigate it. I really need a reproduction I can run locally without significant effort -- which means (a) a compiler I can access easily (i.e. something on Godbolt, or available in a typical OS's package manager), and (b) a minimal reproduction (1 file) rather than an entire docker image. Having to set up a build environment and run Docker, etc. (even if I knew the command-lines for doing so, which I don't right now) is not something I can realistically do in the foreseeable future. So, if that's all we have available -- you may need to investigate this on your end.

Here's what I can help you with, though. I believe I've seen this error before. It arose from an expression like `std::forward<T>(args)...`, where the (buggy) compiler didn't like the fact that `args` and `T` were two seemingly unrelated parameter packs. In that case, using `std::forward<decltype(args)>(args)...` fixed the problem.

Unfortunately, we don't have that here... we just have `std::move(args)`, which _shouldn't_ have this problem, I would think, but perhaps it somehow still does for nvcc?

Since I have no way to reproduce this, I have no way to test it. But if you can reproduce this on your end, I would suggest trying out variations of this, such as using `std::forward<decltype(args)>(args)...` in lieu of `std::move(args)`, and seeing if that works? You can try passing template arguments to the other functions as well, and see if that makes any difference.

Ultimately, the compiler is buggy, so perhaps the answer ought to be to please upgrade your compiler, but it's hard to even suggest that without being able to test whether newer versions of nvcc break on this.

**Comment by anakinxc** [comment]
Hi @higher-performance 

A repro with godbolt [here](https://godbolt.org/z/G46hbcjvs)

**Comment by higher-performance** [comment]
Awesome, thanks a lot! So it looks like nvcc can't parse use of the comma operator in expansions:
```
template<class... T>
void StrAppend(T... args) {
  for (int _ : {((void)args, 0)...}) {
  }
}
```
I could probably find a workaround, but it would hurt code readability even more... let me look into it and see if I can do anything. I would suggest reporting this upstream to NVIDIA in any case.

**Comment by higher-performance** [comment]
Ah, here's a workaround. Apparently [this](https://godbolt.org/z/4on1G8EY8) works, I'll take care of it.

**Comment by h-vetinari** [comment]
Thank you very much! :)

**Comment by georgthegreat** [comment]
Thanks a lot!

**Comment by higher-performance** [comment]
Yup, thanks for the help!

**Comment by georgthegreat** [comment]
@derekmauro, is it possible to backport this into 20240116 release branch?

**Comment by derekmauro** [comment]
> @derekmauro, is it possible to backport this into 20240116 release branch?

If there is another patch release (and there likely will be) then I will include this change.

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/releases/tag/20240116.2 contains this patch.

**Comment by georgthegreat** [comment]
Thanks a lot!
