### ISSUE TITLE
Unclear how to use and expose in libraries

### ISSUE THREAD

**Issue by pitrou** [abseil/abseil-cpp#164]
I'm willing to use Abseil in [a library](https://github.com/apache/arrow/) I work on. However, it's not clear to me what to do when a Abseil type such as `string_view` is exposed in one of our public headers. Should we install the Abseil header files along our one header files? That doesn't seem compatible with the recommendation to "live at head" (what if different libraries try to install different versions of Abseil).

**Comment by ahedberg** [comment]
We have some documentation on this here: https://abseil.io/about/releases. How do users typically build and/or depend on your library? We might be able to provide more specific guidance with a little more information.

**Comment by pitrou** [comment]
We support several ways:
- use pre-built binaries (for various platforms and package managers)
- build their own copy from source

We use CMake as a build system. My current hunch is to build tag 20180600 as part of building Arrow, and install the Abseil headers alongside our own.

**Comment by ahedberg** [comment]
For pre-built binaries, Arrow will want to use an LTS branch, and users will need to compile their code with the same LTS branch. Pre-built binaries are not really compatible with living at head.

@JonathanDCohen knows more about our CMake setup and might have more suggestions.

**Comment by pitrou** [comment]
Yes, basically my current approach is to have a git submodule of the LTS branch:
https://github.com/apache/arrow/pull/2501/files#diff-9eeadb2bd9c56925f04c1885511d6a85

and then this piece of CMake code to integrate it in our build chain:
https://github.com/apache/arrow/pull/2501/files#diff-2420b0c5b6bdad921f1d538f92d64b59R276

**Comment by JonathanDCohen** [comment]
We now have quickstart documentation in https://github.com/abseil/abseil-hello.  installation of headers and static libs is basically only waiting on debugging some linking issues and then will also be added to the hello abseil.

I'm going to close this as fixed, please feel free to reopen :)
