### ISSUE TITLE
[Bug]: arm_neon.h inclusion causing issues

### ISSUE THREAD

**Issue by aweits** [abseil/abseil-cpp#1665]
### Describe the issue

Builds using nvcc driving either clang or gcc have issues with the arm_neon.h inclusion. This seems to underpin issues like this: https://github.com/tensorflow/tensorflow/issues/62490

### Steps to reproduce the problem

sample code:
```
#include "absl/container/flat_hash_map.h"


int main() {
  return 0;
}
```

compiled like so against a recently git clone'd version of absil-cpp into /tmp:

```
nvcc -gencode=arch=compute_70,\"code=sm_70\" -I /tmp/abseil-cpp/ /tmp/absl_test.cu 
```

yields errors like:
```
/dev/shm/aweits/spack/opt/spack/linux-rhel9-neoverse_v2/gcc-12.2.0/gcc-12.3.0-myhz7oqexkiskxlu4mgms4zljmzpum6a/lib/gcc/aarch64-unknown-linux-gnu/12.3.0/include/arm_neon.h(40): error: identifier "__Int8x8_t" is undefined
  typedef __Int8x8_t int8x8_t;
```

```
nvcc -allow-unsupported-compiler -ccbin=`which clang++` -gencode=arch=compute_70,\"code=sm_70\" -I /tmp/abseil-cpp/ /tmp/absl_test.cu 
```

yields errors like:
```
/dev/shm/aweits/spack/opt/spack/linux-rhel9-neoverse_v2/gcc-12.3.0/llvm-18.1.1-gzg6frbu43t7iizefsjmlnxciy5gvxyy/lib/clang/18/include/arm_neon.h(66280): error: identifier "__builtin_neon_vrnd32xq_f64" is undefined
    __ret = (float64x2_t) __builtin_neon_vrnd32xq_f64((int8x16_t)__p0, 42);
```

```
clang++ --cuda-gpu-arch=sm_80 -I /tmp/abseil-cpp/ /tmp/absl_test.cu
```

works just fine.

changing the header like so avoids all errors:
```diff
diff --git a/absl/base/config.h b/absl/base/config.h
index 5fa9f0ef..503a77af 100644
--- a/absl/base/config.h
+++ b/absl/base/config.h
@@ -962,7 +962,7 @@ static_assert(ABSL_INTERNAL_INLINE_NAMESPACE_STR[0] != 'h' ||
 // https://llvm.org/docs/CompileCudaWithLLVM.html#detecting-clang-vs-nvcc-from-code
 #ifdef ABSL_INTERNAL_HAVE_ARM_NEON
 #error ABSL_INTERNAL_HAVE_ARM_NEON cannot be directly set
-#elif defined(__ARM_NEON) && !defined(__CUDA_ARCH__)
+#elif defined(__ARM_NEON) && !defined(__NVCC__)
 #define ABSL_INTERNAL_HAVE_ARM_NEON 1
 #endif
```

### What version of Abseil are you using?

0941ce7fd95104ba5f4678c41802a3229db1d5eb

### What operating system and version are you using?

RHEL9 / upstream kernel
Linux gh-01.rc.rit.edu 6.1.85-1.el9.aarch64 #1 SMP PREEMPT_DYNAMIC Wed Apr 10 15:38:29 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux

### What compiler and version are you using?

gcc 12.3.0 / clang 18.1.1 / cuda 12.4.0

### What build system are you using?

none

**Comment by aweits** [comment]
As a clarification, the primary issue here is that when nvcc calls the c++ preprocessor for .cu files, arm_neon.h gets included and that brings along definitions of types that only the respective c++ compiler will understand. nvcc then calls cudafe++ on the resultant file and errors out. This is confusing and the output might lead folks to misunderstand where the error is originating from. Running nvcc with the --dryrun or --verbose flag will show all the individual steps being run in the background, and incrementally executing these steps allows one to see what's going on.

**Comment by aweits** [comment]
The above is probably overly broad (```!defined(__NVCC__)```), and should be scoped to this (```!(defined(__NVCC__) && defined(__CUDACC__))```) per https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html and https://llvm.org/docs/CompileCudaWithLLVM.html
```diff
diff --git a/absl/base/config.h b/absl/base/config.h
index 5fa9f0ef..503a77af 100644
--- a/absl/base/config.h
+++ b/absl/base/config.h
@@ -962,7 +962,7 @@ static_assert(ABSL_INTERNAL_INLINE_NAMESPACE_STR[0] != 'h' ||
 // https://llvm.org/docs/CompileCudaWithLLVM.html#detecting-clang-vs-nvcc-from-code
 #ifdef ABSL_INTERNAL_HAVE_ARM_NEON
 #error ABSL_INTERNAL_HAVE_ARM_NEON cannot be directly set
-#elif defined(__ARM_NEON) && !defined(__CUDA_ARCH__)
+#elif defined(__ARM_NEON) && !(defined(__NVCC__) && defined(__CUDACC__))
 #define ABSL_INTERNAL_HAVE_ARM_NEON 1
 #endif
```

**Comment by adamjstewart** [comment]
Are there any updates on this issue? This bug is preventing us from building TensorFlow and JAX on aarch64.
