### ISSUE TITLE
[Bug]: SEGV with btree_set::equal_range

### ISSUE THREAD

**Issue by briangreenery** [abseil/abseil-cpp#1680]
### Describe the issue

I want to use `absl::btree_set` to store a set of disjoint ranges, and then use `equal_range` to find overlapping ranges. However, it seems like using `equal_range` either returns the wrong result or crashes. Using `lower_bound` + `upper_bound` seems to work though.

### Steps to reproduce the problem

Here is a failing case using `equal_range`. It looks like it crashes.
https://godbolt.org/z/cb6Pdx556

Here is a working case using `lower_bound` + `upper_bound`. The matching range matches what I expect.
https://godbolt.org/z/EdKh3vqox

### What version of Abseil are you using?

Locally I'm using `20230125.3`. That seems to return the wrong result. I'm not sure which version godbolt is using, but it says "trunk".

### What operating system and version are you using?

Linux

### What compiler and version are you using?

Clang 17.0.1

### What build system are you using?

cmake 3.20.2

**Comment by derekmauro** [comment]
I can see why you might think this could work, but I believe the problem is that the comparator violates the strict weak ordering requirement. See https://en.cppreference.com/w/cpp/named_req/Compare. I consider this working as intended.

**Comment by briangreenery** [comment]
Thanks! To be clear, it looks like the condition it doesn't satisfy is transitivity of equivalence.
