### ISSUE TITLE
[Bug]: Compilation error for filesystem

### ISSUE THREAD

**Issue by philrq** [abseil/abseil-cpp#1682]
### Describe the issue

gcc 7.3.1
abseil-cpp lts_2024_01_16

Using 
cmake -DABSL_BUILD_TESTING=OFF -DABSL_USE_GOOGLETEST_HEAD=OFF -DCMAKE_CXX_STANDARD=17 -DABSL_ENABLE_INSTALL=ON -DCMAKE_INSTALL_PREFIX=/BuySide_dev_home/users/procques/abseil/Install ..

cmake --build . --target all

resulted in:
In file included from /home/abseil/Source/abseil-cpp/absl/hash/internal/hash.cc:15:0:
/home/abseil/Source/abseil-cpp/absl/hash/internal/hash.h:66:10: fatal error: filesystem: No such file or directory
 #include <filesystem>  // NOLINT

I expected abseil-cpp to be complied and linked successfully

### Steps to reproduce the problem

mkdir Source && cd Source
git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp/
git checkout lts_2024_01_16
mkdir build && cd build
cmake -DABSL_BUILD_TESTING=OFF -DABSL_USE_GOOGLETEST_HEAD=OFF -DCMAKE_CXX_STANDARD=17 -DABSL_ENABLE_INSTALL=ON -DCMAKE_INSTALL_PREFIX=/BuySide_dev_home/users/procques/abseil/Install ..
cmake --build . --target all

### What version of Abseil are you using?

lts_2024_01_16

### What operating system and version are you using?

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### What compiler and version are you using?

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-7/root/usr --mandir=/opt/rh/devtoolset-7/root/usr/share/man --infodir=/opt/rh/devtoolset-7/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com
/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --enable-plugin --
with-linker-hash-style=gnu --enable-initfini-array --with-default-libstdcxx-abi=gcc4-compatible --with-isl=/builddir/build/BUILD/gcc-7.3.1-20180303/obj-x86_64-redhat-linux/isl-install --enable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32
=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)

### What build system are you using?

$ cmake --version
cmake version 3.29.2

**Comment by derekmauro** [comment]
Already fixed by https://github.com/abseil/abseil-cpp/commit/bb83aceacb554e79e7cd2404856f0be30bd00303.
