### ISSUE TITLE
[Bug]: raw hash set test crash on centos7

### ISSUE THREAD

**Issue by lilothar** [abseil/abseil-cpp#1683]
### Describe the issue

when I try test on centos docker, it creash
*** Error in `./bin/absl_raw_hash_set_test': double free or corruption (fasttop): 0x00000000012a4710 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f983a09e329]
./bin/absl_raw_hash_set_test[0x5f0bc2]
./bin/absl_raw_hash_set_test[0x61a815]
./bin/absl_raw_hash_set_test[0x5fa11b]
./bin/absl_raw_hash_set_test[0x61456e]
./bin/absl_raw_hash_set_test[0x614959]
./bin/absl_raw_hash_set_test[0x615f90]
./bin/absl_raw_hash_set_test[0x6166e0]
./bin/absl_raw_hash_set_test[0x414325]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f983a03f555]
./bin/absl_raw_hash_set_test[0x414849]
======= Memory map: ========
00400000-00409000 r--p 00000000 00:35 14432556                           /root/turbo/build/abseil-cpp/build/bin/absl_raw_hash_set_test
00409000-0062b000 r-xp 00009000 00:35 14432556                           /root/turbo/build/abseil-cpp/build/bin/absl_raw_hash_set_test
0062b000-0076f000 r--p 0022b000 00:35 14432556                           /root/turbo/build/abseil-cpp/build/bin/absl_raw_hash_set_test
00770000-00771000 r--p 0036f000 00:35 14432556                           /root/turbo/build/abseil-cpp/build/bin/absl_raw_hash_set_test
00771000-00772000 rw-p 00370000 00:35 14432556                           /root/turbo/build/abseil-cpp/build/bin/absl_raw_hash_set_test
00772000-00776000 rw-p 00000000 00:00 0 
01294000-012f7000 rw-p 00000000 00:00 0                                  [heap]
7f9834000000-7f9834021000 rw-p 00000000 00:00 0 
7f9834021000-7f9838000000 ---p 00000000 00:00 0 
7f983a01d000-7f983a1e1000 r-xp 00000000 00:35 12847036                   /usr/lib64/libc-2.17.so
7f983a1e1000-7f983a3e0000 ---p 001c4000 00:35 12847036                   /usr/lib64/libc-2.17.so
7f983a3e0000-7f983a3e4000 r--p 001c3000 00:35 12847036                   /usr/lib64/libc-2.17.so
7f983a3e4000-7f983a3e6000 rw-p 001c7000 00:35 12847036                   /usr/lib64/libc-2.17.so
7f983a3e6000-7f983a3eb000 rw-p 00000000 00:00 0 
7f983a3eb000-7f983a400000 r-xp 00000000 00:35 13920230                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f983a400000-7f983a5ff000 ---p 00015000 00:35 13920230                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f983a5ff000-7f983a600000 r--p 00014000 00:35 13920230                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f983a600000-7f983a601000 rw-p 00015000 00:35 13920230                   /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f983a601000-7f983a702000 r-xp 00000000 00:35 12847044                   /usr/lib64/libm-2.17.so
7f983a702000-7f983a901000 ---p 00101000 00:35 12847044                   /usr/lib64/libm-2.17.so
7f983a901000-7f983a902000 r--p 00100000 00:35 12847044                   /usr/lib64/libm-2.17.so
7f983a902000-7f983a903000 rw-p 00101000 00:35 12847044                   /usr/lib64/libm-2.17.so
7f983a903000-7f983a9ec000 r-xp 00000000 00:35 13920415                   /usr/lib64/libstdc++.so.6.0.19
7f983a9ec000-7f983abec000 ---p 000e9000 00:35 13920415                   /usr/lib64/libstdc++.so.6.0.19
7f983abec000-7f983abf4000 r--p 000e9000 00:35 13920415                   /usr/lib64/libstdc++.so.6.0.19
7f983abf4000-7f983abf6000 rw-p 000f1000 00:35 13920415                   /usr/lib64/libstdc++.so.6.0.19
7f983abf6000-7f983ac0b000 rw-p 00000000 00:00 0 
7f983ac0b000-7f983ac22000 r-xp 00000000 00:35 12847062                   /usr/lib64/libpthread-2.17.so
7f983ac22000-7f983ae21000 ---p 00017000 00:35 12847062                   /usr/lib64/libpthread-2.17.so
7f983ae21000-7f983ae22000 r--p 00016000 00:35 12847062                   /usr/lib64/libpthread-2.17.so
7f983ae22000-7f983ae23000 rw-p 00017000 00:35 12847062                   /usr/lib64/libpthread-2.17.so
7f983ae23000-7f983ae27000 rw-p 00000000 00:00 0 
7f983ae27000-7f983ae2e000 r-xp 00000000 00:35 12847066                   /usr/lib64/librt-2.17.so
7f983ae2e000-7f983b02d000 ---p 00007000 00:35 12847066                   /usr/lib64/librt-2.17.so
7f983b02d000-7f983b02e000 r--p 00006000 00:35 12847066                   /usr/lib64/librt-2.17.so
7f983b02e000-7f983b02f000 rw-p 00007000 00:35 12847066                   /usr/lib64/librt-2.17.so
7f983b02f000-7f983b051000 r-xp 00000000 00:35 12847029                   /usr/lib64/ld-2.17.so
7f983b244000-7f983b24a000 rw-p 00000000 00:00 0 
7f983b24d000-7f983b250000 rw-p 00000000 00:00 0 
7f983b250000-7f983b251000 r--p 00021000 00:35 12847029                   /usr/lib64/ld-2.17.so
7f983b251000-7f983b252000 rw-p 00022000 00:35 12847029                   /usr/lib64/ld-2.17.so
7f983b252000-7f983b253000 rw-p 00000000 00:00 0 
7ffe9bc9e000-7ffe9bcbf000 rw-p 00000000 00:00 0                          [stack]
7ffe9bdc7000-7ffe9bdcb000 r--p 00000000 00:00 0                          [vvar]
7ffe9bdcb000-7ffe9bdcd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]
[       OK ] Table.MoveSelfAssignAborted (core dumped)

the log format test fail too, 
I0000 00:00:1716955884.722827  100028 log_format_test.cc:1307] 7.7e+07
/root/turbo/build/abseil-cpp/absl/log/scoped_mock_log.cc:39: Failure
Mock function called more times than expected - returning directly.
    Function call: Log(INFO, @0x7ffcbad2b748 "/root/turbo/build/abseil-cpp/absl/log/log_format_test.cc", @0x7ffcbad2b728 "7.7e+07")
         Expected: to be never called
           Actual: called once - over-saturated and active
/root/turbo/build/abseil-cpp/absl/log/log_format_test.cc:1293: Failure
Actual function call count doesn't match EXPECT_CALL(test_sink, Send(AllOf(TextMessage(MatchesOstream(comparison_stream)), TextMessage(AnyOf(Eq("0x1.25bb50p+26"), Eq("0x1.25bb5p+26"), Eq("0x1.25bb500000000p+26"))), ::testing::_)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] ManipulatorLogFormatTest.FixedAndScientificFloat (0 ms)
[ RUN      ] ManipulatorLogFormatTest.HexfloatFloat
I0000 00:00:1716955884.723326  100028 log_format_test.cc:1338] 7.7e+07
/root/turbo/build/abseil-cpp/absl/log/scoped_mock_log.cc:39: Failure
Mock function called more times than expected - returning directly.
    Function call: Log(INFO, @0x7ffcbad2b758 "/root/turbo/build/abseil-cpp/absl/log/log_format_test.cc", @0x7ffcbad2b738 "7.7e+07")
         Expected: to be never called
           Actual: called once - over-saturated and active
/root/turbo/build/abseil-cpp/absl/log/log_format_test.cc:1326: Failure
Actual function call count doesn't match EXPECT_CALL(test_sink, Send(AllOf(TextMessage(MatchesOstream(comparison_stream)), TextMessage(AnyOf(Eq("0x1.25bb50p+26"), Eq("0x1.25bb5p+26"), Eq("0x1.25bb500000000p+26"))), ::testing::_)))...
         Expected: to be called once
           Actual: never called - unsatisfied and active
[  FAILED  ] ManipulatorLogFormatTest.HexfloatFloat (0 ms)

### Steps to reproduce the problem

h

### What version of Abseil are you using?

457fdbf960b541743de0a08956b20f2421073284

### What operating system and version are you using?

cenos7

### What compiler and version are you using?

gcc 9.3.1

### What build system are you using?

cmake 3.24.3

### Additional context

logs fail too

**Comment by derekmauro** [comment]
Please file a new issue with the "Steps to reproduce the problem" properly filled out.
