### ISSUE TITLE
[Bug]: NegativeNaN test fails on riscv64

### ISSUE THREAD

**Issue by NeilHanlon** [abseil/abseil-cpp#1684]
### Describe the issue

When building abseil-cpp for riscv64 Fedora, we discovered one test fails:

```
+ # [==========] 125 tests from 35 test suites ran. (3501 ms total)
+ # [  PASSED  ] 124 tests.
+ # [  FAILED  ] 1 test, listed below:
+ # [  FAILED  ] FloatingPointLogFormatTest/0.NegativeNaN, where TypeParam = float
+ #  1 FAILED TEST
```

Disabling this test allows the build to complete properly: https://src.fedoraproject.org/rpms/abseil-cpp/pull-request/19

It appears that this is related to https://github.com/WebAssembly/design/issues/646

### Steps to reproduce the problem

Build abseil-cpp on riscv64

### What version of Abseil are you using?

20240116.2

### What operating system and version are you using?

Fedora (rawhide) - 41

### What compiler and version are you using?

[gcc-14.1.1-4.fc41](http://fedora.riscv.rocks/koji/buildinfo?buildID=306012) / [clang-18.1.3-2.0.riscv64.fc40](http://fedora.riscv.rocks/koji/buildinfo?buildID=305906)

### What build system are you using?

[cmake-3.28.3-4.fc41](http://fedora.riscv.rocks/koji/buildinfo?buildID=306015)

**Comment by derekmauro** [comment]
This might be of interest to @bbarenblat

**Comment by bbarenblat** [comment]
Debian has observed this as well, and [this test is disabled there too](https://sources.debian.org/patches/abseil/20240116.2-2/riscv-nan-formatting.diff/). We probably should apply the Debian patch here, at least until [LWG 4101](https://cplusplus.github.io/LWG/issue4101) is resolved. (Depending on the resolution, we may need to remove this particular test for all architectures.)
