### ISSUE TITLE
[Bug]: Rounding absl::Time is hacky

### ISSUE THREAD

**Issue by ivannp** [abseil/abseil-cpp#1685]
### Describe the issue

Rounding `absl::Time` to the nearest hour/minute/second is hacky. `absl::Time` doesn't have any arithmetic-like operations (`Floor` and `%`). These operations are available only for durations. The conversion/construction between Duration and Time are hidden. It seems to me that the only way to achieve time rounding, is something along the lines:

```
absl::Time = absl::Now();
absl::Duration d = (ts - absl::UnixEpoch()) % absl::Seconds(1);
absl::Time newts = ts - d;
```

### Steps to reproduce the problem

```
    std::string err;
    absl::Time ts;
    absl::ParseTime("%Y-%m-%d %H:%M:%S.%E*f", "2022-12-15 10:31:00.013984", &ts, &err);
    
    Need to round ts to "2022-12-15 10:31:00"
```

### What version of Abseil are you using?

Latest

### What operating system and version are you using?

Linux and Windows

### What compiler and version are you using?

GCC and MSVC

### What build system are you using?

cmake

**Comment by derekmauro** [comment]
The way you would do this, rounding to the nearest minute, for example, is `absl::CivilMinute(absl::UTCTimeZone().At(absl::Now()).cs);`.

**Comment by ivannp** [comment]
Thanks for looking into this. Your solution is maybe a bit clearer, but it also involves `CivicMinute` and time zones. What is the reason for these to be involved in time rounding - from API perspective, `absl::Time` is a time moment (absolute time) and it should be treated as such in terms of rounding.

**Comment by derekmauro** [comment]
Rounding absolute time is almost always done for the purposes of human consumption. That is why CivilTime is used.

**Comment by derekmauro** [comment]
Closing this because it is not something we plan to change.
