### ISSUE TITLE
[Bug]: Build failure MSVC x86 with /arch:AVX2

### ISSUE THREAD

**Issue by dmenendez-gruposantander** [abseil/abseil-cpp#1694]
### Describe the issue

Tried building abseil with MSVC in x86 using /arch:AVX2 flag and it fails
`absl/crc/internal/crc32_x86_arm_combined_simd.h(144): error C3861: '_mm_crc32_u64': identifier not found`
`absl/crc/internal/crc32_x86_arm_combined_simd.h(192): error C3861: '_mm_cvtsi128_si64': identifier not found`

### Steps to reproduce the problem

downloaded release 20240116.2
open Visual Studio 2022 x86 command prompt 
"x86 Native Tools  Command Prompt for VS 2022"
cd to abseil
```
mkdir buildFailure
cd buildFailure
set CXXFLAGS=/arch:AVX2
cmake -DCMAKE_CXX_STANDARD=17 -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
cmake --build . 

### What version of Abseil are you using?

20240116.2

### What operating system and version are you using?

Windows 10 Professional

### What compiler and version are you using?

MSVC toolset 14.40
$>cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.40.33811 for x86

### What build system are you using?

CMake & Ninja
$>cmake --version
cmake version 3.28.3-msvc11
$>ninja --version
1.11.0

### Additional context

_No response_

**Comment by derekmauro** [comment]
This is already fixed by https://github.com/abseil/abseil-cpp/commit/d4578efe7c3a8da81f6e555f6ac1ffa2862b75ed.

**Comment by dmenendez-gruposantander** [comment]
Thanks for looking into this!
Would you happen to know in which release this fix will be included?
The latest one does not have this fix...

**Comment by derekmauro** [comment]
It will be in the next release, which will happen sometime this month.

**Comment by dmenendez-gruposantander** [comment]
Thank you!
