### ISSUE TITLE
SimpleDtoaTest.ExhaustiveDoubleToSixDigits timeout

### ISSUE THREAD

**Issue by BrianEdmonds** [abseil/abseil-cpp#17]
This test times out consistently on my system (a 1.8GHz Atom with 4GB RAM, so not super tiny); increasing the size to medium lets it complete.

**Comment by jorgbrown** [comment]
What's the spread between how long it takes, and when the timeout occurs?

Does the test pass if you turn on higher optimization levels?

**Comment by JonathanDCohen** [comment]
Ping on this!  @BrianEdmonds are you still experiencing timeouts?

**Comment by JonathanDCohen** [comment]
Final ping here.  I'll close this as wontfix next week without a response

**Comment by katzdm** [comment]
Following up on previous comment; closing this as "wontfix". Please re-open with additional details (as requested by jorgbrown), if you're still experiencing this issue.

**Comment by BrianEdmonds** [comment]
Sorry about losing track of this; GitHub mail delivery seems to be extremely flaky for me. I just synced to the latest commit (8b727aa), and Bazel still times out this test in dbg. If I rerun strings:numbers_test alone, it still times out. If I run all the tests in opt it still times out in the same place. Running the test alone, in opt, manages to pass in 51.6s (out of 60s). So, I'd say it's running on the edge.
