### ISSUE TITLE
Expose CaseEqual as a public function?

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#171]
Would you consider to expose the CaseEqual function in match.cc? It's useful to use it standalone.

https://github.com/abseil/abseil-cpp/blob/master/absl/strings/match.cc#L22

**Comment by derekmauro** [comment]
I think @mbxx is already working on this, but some cleanup is required first though.

**Comment by mbxx** [comment]
@derekmauro is correct, we're actively working on this and we'll be adding the function to the public API soon as "absl::EqualsIgnoreCase".  There's just a little more internal cleanup to finish up first.

**Comment by mbxx** [comment]
This is now released: https://github.com/abseil/abseil-cpp/blob/a00bdd176d66ef0b417d9576052a19091fbdf891/absl/strings/match.h#L73
