### ISSUE TITLE
improvement : keep cmakelists clean, remove unneeded policy activations that are already active

### ISSUE THREAD

**Issue by killerbot242** [abseil/abseil-cpp#1716]
### Describe the issue

there are policy checks, in order to see if they are supported and if so,  set them to new. From that list the following ones can be removed, I listed also when they got introduced in cmake, in which version.

CMP0025 : cmake 3.0
CMP0057 : cmake 3.3
CMP0048 : cmake 3.0
CMP0067 : cmake 3.8

while cmake_minimum_required is set at 3.10, which means cmake needs to be at minimum 3.10 and should act with the default behavior of cmake 3.8 (unless overruled with cmake_policy)

So this is actually noise, setting something which is already set to the correct value.

Solution : remove these policy checks.

### Steps to reproduce the problem

code as it is

### What version of Abseil are you using?

20240116.2

### What operating system and version are you using?

linux

### What compiler and version are you using?

gcc 14
clang 18

### What build system are you using?

cmake 3.30

**Comment by derekmauro** [comment]
This is already done. See https://github.com/abseil/abseil-cpp/commit/f46495ea96f68fc3f6c394f099b2992743f6ff7f.

**Comment by killerbot242** [comment]
agreed, all nicely cleaned up wrt cmake min 3.16.
