### ISSUE TITLE
[Bug]: 20240722.rc1 can not be built for android ndk r25b / r25c

### ISSUE THREAD

**Issue by georgthegreat** [abseil/abseil-cpp#1725]
### Describe the issue

```
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/strings/internal/cordz_handle.cc:20:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/synchronization/mutex.h:75:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/synchronization/internal/kernel_timeout.h:30:
In file included from $(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/time/clock.h:29:
$(SOURCE_ROOT)/contrib/restricted/abseil-cpp/absl/time/time.h:1762:37: error: invalid operands to binary expression ('std::strong_ordering' and 'const std::strong_ordering')
  if (auto c = lhs_hi <=> rhs_hi; c != std::strong_ordering::equal) {
```

### Steps to reproduce the problem

See below

### What version of Abseil are you using?

20240722.rc1

### What operating system and version are you using?

Cross-compiling from linux to android

### What compiler and version are you using?

```
clang version 16.0.6
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

### What build system are you using?

[yatool](https://github.com/yandex/yatool)

**Comment by georgthegreat** [comment]
This looks like a bug in STL shipped with NDK r25b / r25c.
There is no problem when targeting ndk-r27.

I do not know if abseil should be doing a workaround for it.

**Comment by derekmauro** [comment]
I don't know how to run this build myself, but I would consider a workaround if one were proposed.

**Comment by georgthegreat** [comment]
I think this might be a workaround:
https://github.com/abseil/abseil-cpp/pull/1728

Looks legit to me.
