### ISSUE TITLE
[Bug]: Can't build C++20 project without .bazelrc

### ISSUE THREAD

**Issue by eugeneo** [abseil/abseil-cpp#1729]
### Describe the issue

(See this [Bazel bug](https://github.com/bazelbuild/bazel/issues/23117) for why this matters)

I have this `cc_executable` (my project uses C++20):
```
cc_binary(
    name = "generator",
    srcs = ["main.cc"],
    copts = [
        "-std=c++20",
        "-fno-exceptions",
    ],
    deps = [
        "@abseil-cpp//absl/strings",
    ],
)
```

It is broken, this code crashes:
```
std::span<char *> args(argv, argc);
std::cout << absl::StrJoin(args, " ") << "\n";
```

If I add the following line in my `.bazelrc` it succeeds:
```
build   --cxxopt=-std=c++20 --cxxopt=-Wall --cxxopt=-Werror --cxxopt=-fno-exceptions
```
For reasons explained in Bazel bugreport, `.bazelrc` is not feasible.

### Steps to reproduce the problem

Demo project: https://github.com/eugeneo/bazel-absl-bug

Run the executable (runs without issues): `bazel run //generator`
Build the rule: `bazel build //demo:test`

### What version of Abseil are you using?

`bazel_dep(name = "abseil-cpp", version = "20240116.2")`

### What operating system and version are you using?

Ubuntu 22.04

### What compiler and version are you using?

c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### What build system are you using?

Bazel

**Comment by derekmauro** [comment]
Please see https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil.

**Comment by eugeneo** [comment]
Not sure how this can be made to work in my case, when I am building a build rule. It is not practical to dictate the user the C++ version. There should be a way to have a version for an executable separate from the user project that imports my module.
