### ISSUE TITLE
[Bug]: Flag "-Wnon-virtual-dtor" is added to pkg-config files

### ISSUE THREAD

**Issue by mkauf** [abseil/abseil-cpp#1737]
### Describe the issue

Abseil 20240722.0 has the flag `-Wnon-virtual-dtor` in the pkg-config files:
```
Cflags: -isystem${includedir} -Wnon-virtual-dtor -DNOMINMAX
```

Previous Abseil versions did not set this flag.

It's probably a bug. See the code in [AbseilHelpers.cmake](https://github.com/abseil/abseil-cpp/blob/master/CMake/AbseilHelpers.cmake):
```
elseif(${cflag} MATCHES "^(-Wno|/wd)")
  # These flags are needed to suppress warnings that might fire in our headers.
  set(PC_CFLAGS "${PC_CFLAGS} ${cflag}")
elseif(${cflag} MATCHES "^(-W|/w[1234eo])")
  # Don't impose our warnings on others.
elseif(${cflag} MATCHES "^-m")
[...]
```

Because `-Wnon-virtual-dtor` begins with `-Wno`, it's handled by the "These flags are needed to suppress warnings" case, but actually it's a normal flag that should be handled by the "Don't impose our warnings on others" case.

Proposed bugfix: change `^(-Wno|/wd)` to `^(-Wno-|/wd)`

### Steps to reproduce the problem

Build Abseil: https://abseil.io/docs/cpp/quickstart-cmake.html

Inspect the generated pkg-config files at `lib/pkgconfig/*.pc`

### What version of Abseil are you using?

20240722.0

### What operating system and version are you using?

Linux

### What compiler and version are you using?

clang

### What build system are you using?

cmake version 3.27.7

**Comment by peter-winter** [comment]
I think you re-introduced this issue. Just updated this library on my Gentoo and it imposes -Wnon-virtual-dtor on my code.

**Comment by mkauf** [comment]
@peter-winter: Abseil 20240722.0 is the newest release, and it has the bug. You probably updated to that release. So no, this bug has not been re-introduced. It will be fixed in the next release.
