### ISSUE TITLE
[Bug]: Abseil does not honor C++ standard from Bazel target

### ISSUE THREAD

**Issue by eugeneo** [abseil/abseil-cpp#1756]
### Describe the issue

I am writing a tool that will be invoked from the Bazel rule from some package that depends on my module so I can not set standard from the command line. ABSL fails to link if I set a version that's "too new"

### Steps to reproduce the problem

1. C++ file:
```
#include <string_view>

#include "absl/log/log.h"

int main() {
  constexpr std::string_view s = "Boop!";
  LOG(INFO) << s;
}
```
2. Bazel rule:
```
cc_binary(
    name = "boop",
    srcs = ["boop.cc"],
    deps = [
        "@abseil-cpp//absl/log",
    ],
    copts = ["-std=c++17"],
    visibility = ["//visibility:public"],
)
```

Building fails with the error:
```
boop.cc:function main:(.text+0x5c): error: undefined reference to 'absl::lts_20240722::log_internal::LogMessage::operator<<(std::basic_string_view<char, std::char_traits<char> >)'
```

Running Bazel with the flag `--copt="-std=c++17"` completes fine.

### What version of Abseil are you using?

20240722

### What operating system and version are you using?

Ubuntu 24.4

### What compiler and version are you using?

c++ (Ubuntu 13.2.0-23ubuntu4) 13.2.0

### What build system are you using?

Bazel

**Comment by derekmauro** [comment]
Working as intended. See https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil.
