### ISSUE TITLE
Figure out why time is exporting symbols

### ISSUE THREAD

**Issue by vslashg** [abseil/abseil-cpp#176]
At cppcon, talking to MS, we realized the time library is exporting non-function symbols.  Figure out why, and see if we can fix it.

**Comment by JonathanDCohen** [comment]
Hey there.  Sorry this fell off the map. I'm not sure what the issue was here, but absl::Time is supposed to export all sorts of non-function symbols (eg absl::Time, absl::Duration...).  Do you remember what the problem was?

**Comment by EricWF** [comment]
Why is this a bug? Variables with external linkage are going to be exported. 

Was there some TLS of function-local static that was particularly surprising or troublesome?

**Comment by JonathanDCohen** [comment]
I don't remember at all why this was an issue.  I think it might date back to the time when cctz wasn't yet a subproject of abseil?
