### ISSUE TITLE
[Bug]: Issue with x86 Windows builds (MSVC) and ABSL usage of intrinsics #18503

### ISSUE THREAD

**Issue by imrichardcole** [abseil/abseil-cpp#1766]
### Describe the issue

Cross posting as advised by the protobuf maintainers - https://github.com/protocolbuffers/protobuf/issues/18503

I get the following two C3861 compiler errors:

```
'_mm_crc32_u64': identifier not found
'_mm_cvtsi128_si64': identifier not found
```

In both cases the error is coming from the crc32_x86_arm_combined_simd.h header file. This comes in as an absl submodule via the protobuf git repo.

Perhaps the issue is in how I'm compiling protobuf? The only CMake arg that stands out is my usage of -`Dprotobuf_MSVC_STATIC_RUNTIME=OFF`

Some intrinsic functions are found e.g` _mm_crc32_u16` and they're picked up from `include\intrin.h` and `include\nmmintrin.h` as part of the MSVC distribution.

### Steps to reproduce the problem

From protobuf v28.0, which uses abseil https://github.com/abseil/abseil-cpp/tree/4a2c63365eff8823a5221db86ef490e828306f9d

Compile using the latest v143 MSVC compiler.  x64 builds work fine, but x86 requires the following workaround to avoid the errors:

I get the following two C3861 compiler errors:

```
'_mm_crc32_u64': identifier not found
'_mm_cvtsi128_si64': identifier not found
```

In both cases the error is coming from the crc32_x86_arm_combined_simd.h header file. This comes in as an absl submodule via the protobuf git repo.

Workaround:

```
if(32_BIT_BUILD)
  add_definitions(ProjectLib "/arch:SSE2")
endif()
```

### What version of Abseil are you using?

https://github.com/abseil/abseil-cpp/tree/4a2c63365eff8823a5221db86ef490e828306f9d

### What operating system and version are you using?

Windows 10 Enterprise and Windows 2016 server

### What compiler and version are you using?

MSVC v143

### What build system are you using?

CMake 3.30.0

**Comment by derekmauro** [comment]
It looks like this issue was fixed by https://github.com/abseil/abseil-cpp/commit/d4578efe7c3a8da81f6e555f6ac1ffa2862b75ed.

**Comment by imrichardcole** [comment]
Many thanks @derekmauro I'll propose the protobuf repo moves along it's version.
