### ISSUE TITLE
[Bug]: CMakeLists.txt forces full rebuild on every install

### ISSUE THREAD

**Issue by nicolasnoble** [abseil/abseil-cpp#1769]
### Describe the issue

In its current state, the CMakeLists.txt of abseil inconditionally bypasses CMake's target longevity rules, and rewrites the file `options.h` every time CMake's consider the `install` rule during a build. This means this file gets touched on the filesystem inconditionally, forcing a rebuild of all of the descending targets which directly or indirectly depend on this file.

In practice, this means when a dependent is opting in to install abseil during its build, it effectively nullifies the caching mechanism of CMake, and forces a full rebuild of heavy hitter dependencies, such as gRPC, during CI testing for instance, but also when developers are iterating changes on their code.

Context: https://github.com/abseil/abseil-cpp/blob/4447c7562e3bc702ade25105912dce503f0c4010/CMakeLists.txt#L216-L255

### Steps to reproduce the problem

This repository for instance is affected by this problem:

```
$ git clone https://github.com/triton-inference-server/client.git
$ cmake -S client -B triton-client-build -DTRITON_ENABLE_CC_GRPC=ON
$ make -C triton-client-build
$ make -C triton-client-build # observe this fully rebuilds gRPC and other targets
```

Use `make -d -C triton-client-build` to observe the following chosen extracts from the log:

```
[...]

-- Up-to-date: /home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/optimization.h
-- Installing: /home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/options.h
-- Up-to-date: /home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/policy_checks.h

[...]

     Prerequisite '/home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/options.h' is newer than target 'CMakeFiles/gpr.dir/src/core/lib/config/config_vars.cc.o'.
     Prerequisite '/home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/options.h' is newer than target 'CMakeFiles/gpr.dir/src/core/lib/config/config_vars_non_generated.cc.o'.
     Prerequisite '/home/nnoble/sources/triton/client/build/third-party/absl/include/absl/base/options.h' is newer than target 'CMakeFiles/gpr.dir/src/core/lib/config/load_config.cc.o'.

[...]
 ```

### What version of Abseil are you using?

This happens at HEAD, and ever since this change has been introduced, on Sep 6, 2022, in https://github.com/abseil/abseil-cpp/commit/308bbf300fe9332130f4784c7a91fa2ad707d6e4

### What operating system and version are you using?

Irrelevant for this problem, as it is CMake-related.

### What compiler and version are you using?

Irrelevant for this problem, as it is CMake-related.

### What build system are you using?

Any version of CMake is affected.

### Additional context

As the change has been introduced, it has been slowly creeping up around the world's dependencies, and has since contributed to a significant CPU usage spike in CI jobs, and consumed an immense amount of developer-hours who are now waiting longer for their build while iterating on code. The effective dollar impact of the bug is difficult to properly estimate, but is definitely very large.

**Comment by derekmauro** [comment]
An internal contributor has a pending fix for this issue. Hopefully it will be submitted by Monday.

**Comment by nicolasnoble** [comment]
I can confirm the following patch fixes the issue for me:

https://github.com/triton-inference-server/third_party/blob/a2a8ab22b1654b80ba3bad4594ffaf74990b1dd2/tools/abseil_no_rebuild.patch
