### ISSUE TITLE
cmake: Undefined symbol absl::container_internal::ShouldInsertBackwards

### ISSUE THREAD

**Issue by matthewgingell** [abseil/abseil-cpp#177]
How should applications built with CMake depend on absl::flat_hash_map? I'm seeing a the following link error:

t.cc:

#include "absl/container/flat_hash_map.h"

int main() {
  absl::flat_hash_map<int, int> flat_map;
  flat_map.insert({1, 2});
}

CMakeLists.txt:

cmake_minimum_required(VERSION 3.12)
add_subdirectory(abseil-cpp)
set(CMAKE_CXX_STANDARD 17)

add_executable(t t.cc)
target_link_libraries(t
  absl::container
  absl::hash)

Link error:
Undefined symbols for architecture x86_64:
  "absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)", referenced from:
      absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<int, int>, absl::hash_internal::Hash<int>, std::__1::equal_to<int>, std::__1::allocator<std::__1::pair<int const, int> > >::find_first_non_full(unsigned long) in t.cc.o

**Comment by derekmauro** [comment]
This will be fixed once #173 gets merged.

**Comment by rdaum** [comment]
This is still happening for me off of master of absl, with CMake linkage. Not sure if the same problem, or a regression.

Relevant CMake pieces:

add_subdirectory(abseil-cpp)
target_link_libraries(moo
        PUBLIC
        x
        glog::glog
        absl::base
        absl::flags
        absl::flags_parse
        absl::status
        absl::str_format
        absl::hash
        absl::container
        absl::strings)

Link error:

/usr/bin/ld: libx.a(x.cc.o): in function `absl::container_internal::HashtablezInfoHandle::~HashtablezInfoHandle()':
/home/ryan/x/abseil-cpp/absl/container/internal/hashtablez_sampler.h:137: undefined reference to `absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)'
/usr/bin/ld: libx.a(x.cc.o): in function `absl::container_internal::HashtablezInfoHandle::operator=(absl::container_internal::HashtablezInfoHandle&&)':
/home/ryan/x/abseil-cpp/absl/container/internal/hashtablez_sampler.h:147: undefined reference to `absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)'
/usr/bin/ld: libx.a(x.cc.o): in function `absl::container_internal::HashtablezInfoHandle::RecordInsert(unsigned long, unsigned long)':
/home/ryan/x/abseil-cpp/absl/container/internal/hashtablez_sampler.h:165: undefined reference to `absl::container_internal::RecordInsertSlow(absl::container_internal::HashtablezInfo*, unsigned long, unsigned long)'
/usr/bin/ld: libx.a(x.cc.o): in function `absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const>, DBFile::handle>, absl::hash_internal::Hash<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> >, std::equal_to<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> >, std::allocator<std::pair<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const> const, DBFile::handle> > >::find_first_non_full(unsigned long)':
/home/ryan/x/abseil-cpp/absl/container/internal/raw_hash_set.h:1664: undefined reference to `absl::container_internal::ShouldInsertBackwards(unsigned long, signed char*)'
collect2: error: ld returned 1 exit status

**Comment by derekmauro** [comment]
You are missing the dependency on the hash table that you are using. Have a look at https://github.com/abseil/abseil-cpp/blob/master/absl/container/CMakeLists.txt, see which headers you are including, and add the corresponding dependency.
