### ISSUE TITLE
[Bug]: Missing stacktrace_libunwind-inl.inc

### ISSUE THREAD

**Issue by helly25** [abseil/abseil-cpp#1770]
### Describe the issue

File `absl/debugging/internal/stacktrace_libunwind-inl.inc` is missing.

### Steps to reproduce the problem

1) Setup a bazel repo that depends on Abseil and has Clang support (e.g. through `https://github.com/bazel-contrib/toolchains_llvm`)
2) bazel build --experimental_omitfp --config=clang @com_google_absl//absl
3) The header `absl/debugging/internal/stacktrace_libunwind-inl.inc` is missing.

```
In file included from external/com_google_absl/absl/debugging/stacktrace.cc:43:
external/com_google_absl/absl/debugging/internal/stacktrace_config.h:52:3: fatal error: absl/debugging/internal/stacktrace_libunwind-inl.inc: No such file or directory
   52 |   "absl/debugging/internal/stacktrace_libunwind-inl.inc"
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### What version of Abseil are you using?

any (latest)

### What operating system and version are you using?

Linux (22.04.1-Ubuntu)

### What compiler and version are you using?

Clang 17.0.4

### What build system are you using?

Bazel 6+ (7.2.1)

### Additional context

Converting the old glog implementation kind of works but the new Abseil implementation is of course very much preferred and I see no reason not to include it in Abseil, even if simplified.

**Comment by derekmauro** [comment]
This is intentionally unsupported.
