### ISSUE TITLE
Reintroduced: Flag "-Wnon-virtual-dtor" is added to pkg-config files

### ISSUE THREAD

**Issue by peter-winter** [abseil/abseil-cpp#1780]
### Describe the issue

Same as previously. The code was probably committed again.

### Steps to reproduce the problem

Try building anything that depends on the library and observe the compiler command line output for -Wnon-virtual-dtor

### What version of Abseil are you using?

20240722.0

### What operating system and version are you using?

Linux, Gentoo

### What compiler and version are you using?

Gcc 13.x

### What build system are you using?

Makefile

**Comment by mkauf** [comment]
This bug has been fixed in #1737. Abseil version 20240722.0 still has the bug (bugfix is in the `master` branch).
