### ISSUE TITLE
Exception safety guarantee 

### ISSUE THREAD

**Issue by weidonglian** [abseil/abseil-cpp#179]
I know that Google internally does not allow exceptions as error handling in the whole code base. 
How about abseil? It is exception safe? 
In our code base, we also have a sophisticated return value handling system instead of throwing an exception. 

Out of curiosity, how Google internally guarantee the operator new or operator new[] never throw bad_alloc? Do you normally handle this globally in std::set_new_handler or you have a consistent exception-free allocator? An exception free allocator requires strong coding discipline which is not good. 

Since abseil is mainly used for Google internally, do you have somewhere to configure this or change the default new and new[] behavior? 

Thanks.
Weidong

**Comment by mbxx** [comment]
Abseil promises the basic exception safety guarantee on all of our types (https://abseil.io/about/compatibility).  It's true that Google doesn't use exceptions internally, so our exception safety isn't as thoroughly tested as the rest of our library, but we do unit test for exception safety directly (https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/exception_safety_testing.h).  @JonathanDCohen gave a great talk on the exception safety testing framework last week at CppCon; it should show up on https://www.youtube.com/user/CppCon/videos soon.

Google uses the -fno-exceptions compiler flag.  I'm sure there are subtleties in making this work, but I'm unfamiliar with what they are.
