### ISSUE TITLE
[Bug]: clang diagnoses nullability error

### ISSUE THREAD

**Issue by jnooree** [abseil/abseil-cpp#1793]
### Describe the issue

clang diagnoses nullability error on abseil `CHECK_*` macro family.

### Steps to reproduce the problem

https://godbolt.org/z/xPeKv86bE

### What version of Abseil are you using?

Commit `742a0ed4` (according to godbolt)

### What operating system and version are you using?

macOS and Linux both have the same problem.

### What compiler and version are you using?

First found on clang `19.1`.

### What build system are you using?

Irrelevant.

### Additional context

It seems this bug is introduced in commit 2fcebef792241578e8c9dcfbba5745f834509dbb.

**Comment by derekmauro** [comment]
Likely caused by https://github.com/abseil/abseil-cpp/commit/2fcebef792241578e8c9dcfbba5745f834509dbb

@suertreus
