### ISSUE TITLE
synchronization:mutex_test timeout

### ISSUE THREAD

**Issue by BrianEdmonds** [abseil/abseil-cpp#18]
This test reliably times out on my platform (1.8GHz Atom with 4GB RAM, so not tiny). Removing the timeout override allows it to pass.

**Comment by derekmauro** [comment]
Yup, I've noticed this too. Except the timeout to change next week.

**Comment by derekmauro** [comment]
Timeout increased in 9c4178d13e84acf3f0d1b8aeee1f67862aeeadc9.
