### ISSUE TITLE
C++ Guide does not actually document backported C++ library features

### ISSUE THREAD

**Issue by alexweej** [abseil/abseil-cpp#180]
e.g. variant and optional. This is the main reason I'm interested in promoting this within my org, and people are asking what is supported.

https://abseil.io/docs/cpp

Not sure if I'm missing something though?

Thanks!

**Comment by mbxx** [comment]
We rely pretty heavily on our header files for documentation.  Everything
we've released is supported and covered by our compatibility guidelines (
https://abseil.io/about/compatibility), even if it doesn't have a specific
programming guide written for it.

Are there specific questions about support that our documentation doesn't
cover?

**Comment by alexweej** [comment]
Just that the homepage has this blurb

> # Compatibility with the C++ Standard
> 
> Google has developed many abstractions that either match or closely match features incorporated into C++14, C++17, and beyond. Using the Abseil versions of these abstractions allows you to access these features now, even if your code is not yet ready for life in a post C++11 world.

But then actually finding out which C++17 library features have been backported seems to be hard. How exactly should one browse the source to discover what Abseil offers?

Thanks

**Comment by mbxx** [comment]
Ah, okay, now I understand what you're asking for.  The problem is discoverability.

@manshreck , what do you think?

**Comment by JonathanDCohen** [comment]
Putting this up as a good first issue.  We aren't actively working on documenting and maintaining the list of backports we offer but it's a definite nice-to-have

**Comment by manshreck** [comment]
Some of our backports may be more drop-in that others. And we may add drop-ins dynamically, so I'd worry a list would get out of date. I would like to know *why* you need a list of drop-in replacements other than just curiosity :)

We do mention the philosophy behind this in https://abseil.io/about/design/dropin-types, and as Derek mentioned, we primarily rely on documentation within the header files, which denote the drop-ins where they are defined.

**Comment by rogeeff** [comment]
The way things going we are likely to move into c++17 world before we address this. I think having this information in headers should be enough.
