### ISSUE TITLE
absl::optional operator= throws SIGBUS when operand is a misaligned value

### ISSUE THREAD

**Issue by nunojpg** [abseil/abseil-cpp#181]
I have a protocol structure packed (#pragma pack(1))m as so data members can be misaligned.

Under armhf when I use operator= with a specific field:

```
absl::optional<double> opt;
opt = packed_struct.field99;
```

I get a SIGBUS:

```
Program received signal SIGBUS, Bus error.
#0  0x00500752 in absl::optional_internal::optional_data_base<float>::construct<double&> (this=0x634bf0, args#0=@0x634c67: -18) at /base/dependencies/abseil-cpp/absl/types/optional.h:244
#1  0x004fff04 in absl::optional_internal::optional_data_base<float>::assign<double&> (this=0x634bf0, u=@0x634c67: -18) at /base/dependencies/abseil-cpp/absl/types/optional.h:253
#2  0x004ff78a in absl::optional<float>::operator=<double&, void> (this=0x634bf0, v=@0x634c67: -18) at /base/dependencies/abseil-cpp/absl/types/optional.h:660
```

My workaround was to create a temporary:

```
absl::optional<double> opt;
opt = double(packed_struct.field99);
```

I believe this is a bug.

**Comment by EricWF** [comment]
SIGBUS suggests the compiler is generating an aligned access for unaligned memory. Why do you think Abseil is at fault here?

**Comment by nunojpg** [comment]
I don't understand what you mean. You believe it's a compiler bug or that my code is illegal?

**Comment by EricWF** [comment]
The data is misaligned. The error is caused by having misaligned data. The compiler misaligned the data for you. I'm not looking to assign blame.

I don't understand how the bug could be in Abseil.
Without a complete reproducer I can't debug this any further.

**Comment by nunojpg** [comment]
I will look for it, for now I close the issue. Thanks,
