### ISSUE TITLE
[CMAKE] absl::container target should depend on absl::hash

### ISSUE THREAD

**Issue by ilyapopov** [abseil/abseil-cpp#183]
If I just do

    target_link_library(my_app PRIVATE absl::container)

I get linker errors like

    undefined reference to `absl::hash_internal::CityHashState::kSeed'

To fix this, I have to add `absl::hash` to my `target_link_libraries` call.

It would be nice if `absl::container` declared a `PUBLIC` dependency on `absl::hash` in its `CMakeLists.txt`, so the user would not need to figure out it herself.

**Comment by Mizux** [comment]
Should be done once #136  is merged.
I also spot few others, like `absl::hash` depending on itself (which can lead to issue too)
https://github.com/abseil/abseil-cpp/blob/a00bdd176d66ef0b417d9576052a19091fbdf891/absl/hash/CMakeLists.txt#L34

also if we look at a container header (e.g. `absl/container/fixed_array.h`)
https://github.com/abseil/abseil-cpp/blob/a00bdd176d66ef0b417d9576052a19091fbdf891/absl/container/fixed_array.h#L44-L51

`absl::container` should depend on `absl::algorithm`,`absl::base` and `absl::memory` ...

**Comment by JonathanDCohen** [comment]
Hey there!  We've done some significant work to our CMake files.  Is this still an issue?

**Comment by ilyapopov** [comment]
No, this is not fixed. It actually has been made worse.

With current master:

    target_link_libraries(... absl::container) 

does not work, with error messages:

```
/usr/bin/ld: cars.cpp:(.text+0x500): undefined reference to `absl::hash_internal::CityHashState::kSeed'
/usr/bin/ld: cars.cpp:(.text+0x981): undefined reference to `absl::hash_internal::CityHashState::kSeed'
/usr/bin/ld: cars.cpp:(.text+0xc31): undefined reference to `absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)'
<...>
```

so it obviously still does not automatically link to `absl::hash`. So I have to explicitly link to it:

    target_link_libraries(... absl::container absl::hash) 

This was working before (on branch lts_2018_12_18), but with current master I get:

```
cars.cpp:(.text+0xc31): undefined reference to `absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)'
/usr/bin/ld: CMakeFiles/cars.dir/cars.cpp.o: in function `absl::container_internal::raw_hash_set<absl::container_internal::FlatHashMapPolicy<CarState, CarState>, absl::hash_internal::Hash<CarState>, std::equal_to<CarState>, std::allocator<std::pair<CarState const, CarState> > >::prepare_insert(unsigned long)':
cars.cpp:(.text._ZN4absl18container_internal12raw_hash_setINS0_17FlatHashMapPolicyI8CarStateS3_EENS_13hash_internal4HashIS3_EESt8equal_toIS3_ESaISt4pairIKS3_S3_EEE14prepare_insertEm[_ZN4absl18container_internal12raw_hash_setINS0_17FlatHashMapPolicyI8CarStateS3_EENS_13hash_internal4HashIS3_EESt8equal_toIS3_ESaISt4pairIKS3_S3_EEE14prepare_insertEm]+0x1c0): undefined reference to `absl::container_internal::RecordInsertSlow(absl::container_internal::HashtablezInfo*, unsigned long, unsigned long)'
<...>
```

So I searched where this `UnsampleSlow` is defined, and found it in `hashtablez_sampler`. So I linked to it as well:

    target_link_libraries(cars PRIVATE absl::container absl::hash absl::hashtablez_sampler)

But it still does not work:

```
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o): in function `absl::base_internal::DoAllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*)':
low_level_alloc.cc:(.text+0xf2b): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0xf89): undefined reference to `pthread_sigmask'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o): in function `absl::base_internal::LowLevelAlloc::DeleteArena(absl::base_internal::LowLevelAlloc::Arena*)':
low_level_alloc.cc:(.text+0x17a9): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0x1820): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0x186c): undefined reference to `pthread_sigmask'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o):low_level_alloc.cc:(malloc_hook+0x3d9): more undefined references to `pthread_sigmask' follow
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_base.a(thread_identity.cc.o): in function `absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*))':
thread_identity.cc:(.text+0x5b): undefined reference to `pthread_setspecific'
/usr/bin/ld: thread_identity.cc:(.text+0x6a): undefined reference to `pthread_sigmask'
/usr/bin/ld: thread_identity.cc:(.text+0xaf): undefined reference to `pthread_key_create'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_base.a(thread_identity.cc.o): in function `absl::base_internal::CurrentThreadIdentityIfPresent()':
thread_identity.cc:(.text+0x142): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status
```

This is something from pthread, so I added:

```
find_package(Threads)
target_link_libraries(cars PRIVATE absl::container absl::hash absl::hashtablez_sampler Threads::Threads)
```

And finally it builds.

**Conclusion** Dependencies in absl Cmake build system are still completely broken.

**Comment by ilyapopov** [comment]
It looks like `absl::container` is just a dummy target that does nothing:

https://github.com/abseil/abseil-cpp/blob/89ea0c5ff34aaa5855cfc7aa41f323b8a0ef0ede/absl/container/CMakeLists.txt#L20-L24

Shall I link directly to `absl::flat_hash_map` instead?

**Comment by derekmauro** [comment]
This has been reported multiple times. The `absl::container` target was unfortunately deprecated. Please depend on the library you are actually using instead. Sorry about this.

https://github.com/abseil/abseil-cpp/blob/master/absl/container/CMakeLists.txt#L17-L24

**Comment by ilyapopov** [comment]
Unfortunately, linking directly to `absl::flat_hash_map` does not work either.

It still misses dependency on pthread.

```
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o): in function `absl::base_internal::DoAllocWithArena(unsigned long, absl::base_internal::LowLevelAlloc::Arena*)':
low_level_alloc.cc:(.text+0xf2b): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0xf89): undefined reference to `pthread_sigmask'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o): in function `absl::base_internal::LowLevelAlloc::DeleteArena(absl::base_internal::LowLevelAlloc::Arena*)':
low_level_alloc.cc:(.text+0x17a9): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0x1820): undefined reference to `pthread_sigmask'
/usr/bin/ld: low_level_alloc.cc:(.text+0x186c): undefined reference to `pthread_sigmask'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_internal_malloc_internal.a(low_level_alloc.cc.o):low_level_alloc.cc:(malloc_hook+0x3d9): more undefined references to `pthread_sigmask' follow
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_base.a(thread_identity.cc.o): in function `absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*))':
thread_identity.cc:(.text+0x5b): undefined reference to `pthread_setspecific'
/usr/bin/ld: thread_identity.cc:(.text+0x6a): undefined reference to `pthread_sigmask'
/usr/bin/ld: thread_identity.cc:(.text+0xaf): undefined reference to `pthread_key_create'
/usr/bin/ld: extern/abseil-cpp/absl/base/libabsl_base.a(thread_identity.cc.o): in function `absl::base_internal::CurrentThreadIdentityIfPresent()':
thread_identity.cc:(.text+0x142): undefined reference to `pthread_getspecific'
collect2: error: ld returned 1 exit status
```

**Comment by derekmauro** [comment]
Fair enough.

@JonathanDCohen: The cmake targets that correspond to https://github.com/abseil/abseil-cpp/search?q=%22-pthread%22 should link `-pthread`.

**Comment by Mizux** [comment]
my 2 cents:
@derekmauro I hope you don't mean hard coding a `-pthread` in cmake targets ?

The correct way (IMHO)
1. first fix the `find_package` for Thread.
    https://github.com/abseil/abseil-cpp/blob/540e2537b92cd4abfae6ceddfe24304345461f32/CMakeLists.txt#L58-L59
    should be change to:
    ```cmake
    ## pthread 
    set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
    set(THREADS_PREFER_PTHREAD_FLAG TRUE)
    find_package(Threads REQUIRED) 
    ```
    ref: https://cmake.org/cmake/help/v3.1/module/FindThreads.html

2. then, in few cmake targets which need it, add `Threads::Threads` to `DEPS` (and **not** `-pthread`)...

**Comment by JonathanDCohen** [comment]
We're still getting a few weird linker errors relating to threads.  This has proven annoying to track down, but I'm circling back around to this.  Sorry this is taking forever.

**Comment by bartholmberg** [comment]
Did this ever get fixed?  This  is using  #Always enable proper symbolize implementation on Windows ... by Loo Rong Jie <loorongjie@gmail.com>
git checkout ecc0033b54847f6c9ee37dbb0be8aa17e5b6d37b and see the following issue
cartographer.lib(thread_pool.cc.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) public: static class absl::hash_internal::CityHashState __cdecl absl::hash_internal::CityHashState::combine_contiguous(class absl::hash_internal::CityHashState,unsigned char const *,unsigned __int64)" (__imp_?combine_contiguous@CityHashState@hash_internal@absl@@SA?AV123@V123@PEBE_K@Z) referenced in function "class absl::hash_internal::CityHashState __cdecl absl::hash_internal::hash_bytes<class absl::hash_internal::CityHashState,unsigned __int64>(class absl::hash_internal::CityHashState,unsigned __int64 const &)" (??$hash_bytes@VCityHashState@hash_internal@absl@@_K@hash_internal@absl@@YA?AVCityHashState@01@V201@AEB_K@Z)

**Comment by derekmauro** [comment]
The `absl::container` target is deprecated and does nothing. Please take a look at the `CMakeLists.txt` file and depend on the library that you actually need, for example, `absl::flat_hash_set`.

**Comment by bartholmberg** [comment]
Tried changes to CMakeLists.txt [ the one app, not abseil-cpp]- no luck so far.  

Are there any known side affects using std::unordered_map instead?

  std::unordered_map<Task*, std::shared_ptr<Task>> tasks_not_ready_  GUARDED_BY(mutex_);
//    absl::flat_hash_map<Task*, std::shared_ptr<Task>> tasks_not_ready_ GUARDED_BY(mutex_);

**Comment by derekmauro** [comment]
No known issue. Please share a complete example with your CMakeLists.txt file, or even a small git repo that we can clone to test.

**Comment by bartholmberg** [comment]
Abseil-cpp repo & CMakeLIsts.txt are unchanged [except for install locations hack].  Getting close to getting app built with std::unordered_map.    The app is kind of big [and scattered] right now;  But I will share a simpler app with you here demoing the link issue with Abseil [before  leaving this topic].

**Comment by ilyapopov** [comment]
I can confirm that my original issue is fixed.

Currently I use abseil as a git submodule. Then in my CmakeLists.txt I do 

```
add_subdirectory(extern/abseil-cpp)
target_link_libraries(my_app PRIVATE absl::flat_has_map)
```

And everything works. Both `absl::hash` and `-pthread` are linked automatically.
