### ISSUE TITLE
StrReadUntil(string_view&, string_view sep)

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#184]
Request for a function like `string_view StrReadUntil(string_view&, string_view sep)`

Returns the part until (not including) the separator and removes that part (including separator) from the input (in-place).
Returns the entire input and clears it if separator isn't found.

Examples:
StrReadUntil(is, "\n"); // reads next line
StrReadUntil(is, ";"); reads next value from 1;2;3

It's a bit like `getline()` for `string_view`s.

**Comment by zhangxy988** [comment]
`string_view` is a const view of the underlying string, which means it doesn't allow you to modify the underlying string. So I am not sure your requested function would work.

I am not sure about your use case, but if you just want a string_view until the delimiter, you can write:
```
string_view StrReadUntil(string_view input, string_view sep) {
  std::vector<absl::string_view> pieces = absl::StrSplit(input, sep);
  return pieces[0];
}
```
For more information, please check out our contribution guidelines: https://github.com/abseil/abseil-cpp/blob/master/CONTRIBUTING.md

**Comment by OlafvdSpek** [comment]
> So I am not sure your requested function would work.

Hint: remove_prefix().

**Comment by zhangxy988** [comment]
I think I misunderstood what you mean by "removes that part (including separator) from the input (in-place)", so you actually mean "move the start of view to past the separator".

So just let me confirm you want something like:
```
string_view StrReadUntil(string_view* input, string_view sep) {
  auto pos = input->find_first_of(sep);
  if (pos == string_view::npos) {
    // reaches end of input without encountering `sep`, what should we do?
  }
  else {
    string_view ret = input->substr(0, pos);
    input->remove_prefix(pos+1);
    return ret;
  }
}
```

Is this what you want?

**Comment by OlafvdSpek** [comment]
> I think I misunderstood what you mean by "removes that part (including separator) from the input (in-place)", so you actually mean "move the start of view to past the separator".

Yes, as the view is the input.

> auto pos = input->find_first_of(sep);

Just `find(sep)` should do, though this is an interesting variant.
 
>     // reaches end of input without encountering `sep`, what should we do?

> Returns the entire input and clears it if separator isn't found.

> Is this what you want?

Yes

**Comment by zhangxy988** [comment]
OK. Thanks for clarification. We will evaluate this feature request and get back to you.
As per our [contribution guideline](https://github.com/abseil/abseil-cpp/blob/master/CONTRIBUTING.md#priorities), it'd be better if you could prove that this function would meet one or more criteria.

**Comment by mbxx** [comment]
If I understand correctly, I'd implement this using StrSplit and MaxSplits.  Does this do what's desired?

```
absl::string_view StrReadUntil(string_view& input, string_view sep) {
  std::vector<absl::string_view> pieces = absl::StrSplit(input, absl::MaxSplits(sep, 1));
  input = pieces[1];
  return pieces[0];
}
```

**Comment by OlafvdSpek** [comment]
Does that work if sep isn't found?
I'd use the code from https://github.com/abseil/abseil-cpp/issues/184#issuecomment-431394539 as it doesn't require the vector.

> As per our [contribution guideline](https://github.com/abseil/abseil-cpp/blob/master/CONTRIBUTING.md#priorities), it'd be better if you could prove that this function would meet one or more criteria.

Right, I didn't understand it was about that section. Let's see what I can find.

**Comment by mbxx** [comment]
You're right, if `sep` isn't found the vector would have a size of 1.  You could either check the size and handle that case explicitly or split into a `std::pair`, which would work as expected (https://github.com/abseil/abseil-cpp/blob/master/absl/strings/str_split.h#L452).

**Comment by OlafvdSpek** [comment]
It wouldn't, as `The remaining split substrings are discarded.`

I think `StrReadUntil` is a faster `StrSplit` for a subset of scenarios, as it doesn't have to allocate the vector and it doesn't do all input at once.

**Comment by mbxx** [comment]
> It wouldn't, as `The remaining split substrings are discarded.`

There wouldn't be any remaining substrings if you specify `absl::MaxSplits(sep, 1)`, though.  Using `std::pair` with `absl::MaxSplits(sep, 1)` doesn't allocate a vector and doesn't process the full input.

**Comment by OlafvdSpek** [comment]
Then it sounds good.

**Comment by mbxx** [comment]
I'm going to close this issue since absl::StrSplit covers this speciic use case, but please let us know if you feel there are other cases that it doesn't.

**Comment by OlafvdSpek** [comment]
StrSplit can be used to implement this but it provides an entirely different interface..

**Comment by mbxx** [comment]
I understand, but Abseil's goal is to provide a small set of very broadly useful APIs.  Inside of Google, we've had situations where we end up with a proliferation of similar but slightly different APIs.  Compared to having one broadly useful, canonical API, we've found that having a proliferation of APIs is more confusing for users (who now need to figure out which variant is the right one for their situation) and more maintenance for the library maintainers.

If you run into situations that are poorly covered by the APIs we provide, we're be very interested to hear about them.  We are, however, biased towards having a smaller library that covers a majority of use cases rather than having a large library that can cover every possible use case (https://github.com/abseil/abseil-cpp/blob/master/CONTRIBUTING.md#priorities).  Concretely, we're more apt to extend an existing API (perhaps by adding more delimiter modifiers to StrSplit) than we are to introduce entirely new APIs.

**Comment by OlafvdSpek** [comment]
https://github.com/llvm-mirror/clang-tools-extra/blob/master/clang-tidy/abseil/AbseilMatcher.h is probably a very bad example, but let's have a look:

```
  static constexpr llvm::StringLiteral AbslPrefix("absl/");
  size_t PrefixPosition = Path.find(AbslPrefix);
  if (PrefixPosition == StringRef::npos)
    return false;
  Path = Path.drop_front(PrefixPosition + AbslPrefix.size());
```
can be replaced by:
```
  StrReadUntil(Path, "absl/");
```

It's not the canonical example and is probably too clever but it does show how it could simplify existing code. I don't think StrSplit would improve this case.

**Comment by mbxx** [comment]
Ah, that's a common enough case that we have an API for it: `absl::ConsumePrefix` in https://github.com/abseil/abseil-cpp/blob/master/absl/strings/strip.h.

I apologize if I'm being pedantic, but that code snippet also returns if the prefix isn't found.  So the full replacement using `StrReadUntil` would be:

```
if (StrReadUntil(Path, "absl/") != "absl/") return false;
```

The equivalent code with `absl::ConsumePrefix` is very similar:

```
if (!absl::ConsumePrefix(&Path, "absl/")) return false;
```

**Comment by OlafvdSpek** [comment]
But the original code (and `StrReadUntil`) don't require Path to start with `"absl/"`..
I think the original code would allow `"notabsl/"` too, would that be a bug? ;)

> but that code snippet also returns if the prefix isn't found.

It does, but that's not necessary with `StrReadUntil` as `Path` will be empty when `"absl/"` isn't found and the following `std::any_of()` will return false.

BTW, `StrReadUntil` returns the part before the separator, so it wouldn't return `"absl/"`.
