### ISSUE TITLE
#include "" vs <>

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#185]
What's the rationale for using ""?

```
#include "absl/strings/internal/str_format/arg.h"
```

I don't think such includes should be resolved relative to the location of the file they're in..

**Comment by tituswinters** [comment]
With our build systems, there is an assumption that the compiler is only
invoked from the project root.

Doing so allows us to avoid polluting include-dirs, and provide a visual
identifier for "part of this project" vs. "included from elsewhere."

It's Google-style (see the public C++ style guide), but it's also a thing
that I think makes sense and should be done consistently elsewhere.  I'm
arguing for the same policies in C++ build systems and package management
discussions in (for example) SG-15.

**Comment by OlafvdSpek** [comment]
> Doing so allows us to avoid polluting include-dirs, 

I don't understand how this follows from the above. AFAIK the include search path isn't affected by the current working directory at time of compiler invocation.
Even if it was, this wouldn't affect "" vs <> would it?

> and provide a visual identifier for "part of this project" vs. "included from elsewhere."

What's the definition of project here? If I include Abseil, it sounds like the latter. But https://abseil.io/docs/cpp/quickstart uses #include "absl/..."

> It's Google-style (see the public C++ style guide),

I read that part of the guide but didn't see any mention / rationale of "" vs <> apart from the examples.

https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

**Comment by tituswinters** [comment]
+Tom Manshreck <shreck@google.com> - Can you look into the quickstart
example?

**Comment by manshreck** [comment]
So, we use "" quotes for a variety of reasons:

1) We use quotes internally
2) We didn't necessarily want to force people to treat Abseil as "system" libraries. They can, but they can also use it however they like.
3) <> sometimes implies (to me, at least) a "pre-compiled library" and we want people to live at head and treat the code as source. This is more a convention than anything else.
4) (In the quickstart) This was done to keep it simple, rather than invoke the compiler with additional flags to add other directories in the compiler path.

Rather than assume a relative location for invocation, I could see the point in making Abseil treated as a system library, and include its code via <>, but I didn't want to make that assumption to users. I'd rather have us be uniform in this, however, and use <> within the Abseil source as well.

**Comment by manshreck** [comment]
Note that from the OP, these paths are not necessarily resolved from the current directory. We also resolve them from the bazel WORKSPACE file, as pointed out in the quickstart:

  # NOTE: Bazel paths must be absolute paths. E.g., you can't use ~/Source
  path = "/PATH_TO_SOURCE/Source/abseil-cpp",

IMO, I'd prefer "" here and reserve <> for compile-time linking in of external libraries (e.g. out of the current directory or WORKSPACE).

**Comment by OlafvdSpek** [comment]
> We didn't necessarily want to force people to treat Abseil as "system" libraries. They can, but they can also use it however they like.

Where does <> -> system come from?

> Note that from the OP, these paths are not necessarily resolved from the current directory. 

AFAIK (usually) the only difference between "" and <> is that directory of the current file, so if you don't need that part.. there's no reason to use #include "".

**Comment by JonathanDCohen** [comment]
> AFAIK (usually) the only difference between "" and <> is that directory of the current file

and to quote Titus

> With our build systems, there is an assumption that the compiler is only invoked from the project root.

From the cmake perspective, Abseil uses the typical out-or-source build directory, but that's not the case with our Bazel builds.  Either way, this conversation is a bike shed, doesn't really affect Abseil's usability, and has also gone cold.  I'm going to close this as wontfix for now, but please feel free to re-open if you feel that there's more discussion to be had :)

**Comment by OlafvdSpek** [comment]
> but that's not the case with our Bazel builds.

How is that relevant?
I think I'm missing a link somewhere..
