### ISSUE TITLE
max() macro collision

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#186]
Gotta love macros. MSVC project without NOMINMAX defined.

```
 private:
  static constexpr size_type kMaxSize =
      std::numeric_limits<difference_type>::max();

// absl\strings\string_view.h(482): warning C4003: not enough arguments for function-like macro invocation 'max'
```

**Comment by mbxx** [comment]
Ugh, macros.

Thanks for pointing this out.  The fix seems clear, though I don't have a great way of testing it internally.  If you don't mind, I'll release it and then ask you to verify if it worked for you.

**Comment by mbxx** [comment]
The last release added parens to all of the uses of numeric_limits<>::min and numeric_limits<>::max in header files:

https://github.com/abseil/abseil-cpp/blob/a4c3ffff11eec0ee45742f915c255e9f870b7e0f/absl/strings/string_view.h#L493

Does this fix the problem for you?

**Comment by OlafvdSpek** [comment]
Think so, thanks!
