### ISSUE TITLE
Expose custom Base64 encoding/decoding functions.

### ISSUE THREAD

**Issue by Alfus** [abseil/abseil-cpp#188]
It would be great to have support for custom base64 functions (similar to Base64UnescapeInternal and Base64EscapeInternal functions in absl/strings/escaping.cc), so that custom Base64 alphabets can be supported.

I have a use case where I need to convert binary (leveldb) keys to something that works well with Google Cloud Datastore/Firestore and GCS. where the resulting string meets the following requirements:
 - All characters sort after `/`, so "paths" are sorted correctly.
 - All characters are can be used in URI paths, i.e. must be a 'safe', un-encoded pchar from rfc3986,
 specifically one of `[0-9a-zA-Z-._!$&'()*+,;=@:]`.
 - Must not conflict with google api specs (so not `:`).

This leaves `[0-9a-zA-Z;=@_]` as options, from which I chose `[0-9a-zA-Z@_]` (sorted by ASCII value of course).

**Comment by zhangxy988** [comment]
@mbxx Is this something we are already tracking or working on?

**Comment by mbxx** [comment]
This is the first time we've had a feature request for this, so it's not currently on our roadmap.  I'll add it to our list of feature requests.

**Comment by JonathanDCohen** [comment]
This was added at the time of request to our internal feature request list.  At this time we aren't planning on releasing anything Base64 related, but that could change in the future.  I'm going to close this for now, but please feel free to re-open if you feel you have a good argument for inclusion in Abseil :)

**Comment by Alfus** [comment]
Base64 encoding is already exposed by Abseil. This feature request is to just expose the currently internal functions that allow you to specify which base64 'alphabet' to use. Specifically these two functions:

https://github.com/abseil/abseil-cpp/blob/b312c3cb53a0aad75a85ac2bf57c4a614fbd48d4/absl/strings/escaping.cc#L943
https://github.com/abseil/abseil-cpp/blob/b312c3cb53a0aad75a85ac2bf57c4a614fbd48d4/absl/strings/escaping.cc#L956

The usage for the 2 hard-coded alphabets Abseil exposes can be found here:
https://github.com/abseil/abseil-cpp/blob/b312c3cb53a0aad75a85ac2bf57c4a614fbd48d4/absl/strings/escaping.cc#L1075
