### ISSUE TITLE
OrderedCode library

### ISSUE THREAD

**Issue by Alfus** [abseil/abseil-cpp#189]
Have you guys looked at open sourcing OrderedCode? Looks like there are several versions of it out there, including: https://github.com/google/orderedcode
https://github.com/him-28/TensorFlow/tree/master/tensorflow/core/lib/strings

**Comment by zhangxy988** [comment]
Thanks for the request. We also received the same request internally from Google. We are still evaluating and prioritizing. Will keep this thread posted..

**Comment by mbxx** [comment]
We've looked at in the past, but haven't had any requests for it so it's not on our roadmap right now.  I'll add this to our list of feature requests.

**Comment by Alfus** [comment]
BTW, we implemented a arbitrary precision floating point OrderedCode style encoder for Google Cloud Firestore:
https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/cloud/datastore/core/number/NumberIndexEncoder.java
Which proved pretty efficient and useful. Would be nice to move it into an OrderedCode-sytle library.

**Comment by JonathanDCohen** [comment]
We never got back to this, but we had this added to our internal roadmap when it was requested.  Sorry for the lack of transparency. 

This will be closed very soon via a daily release.
