### ISSUE TITLE
Consider separating std backports from other Abseil functionality

### ISSUE THREAD

**Issue by alexweej** [abseil/abseil-cpp#190]
This might make the "live at head" philosophy a bit politically easier to introduce into organizations that may have their own solutions to many of the problems addressed by the non-backports part of this library. Basically anything with a capital letter should be in a separate library to the std backports I think.

I realise that bureaucratically this causes complications, but I thought it was worth considering.

Thanks

**Comment by zhangxy988** [comment]
I don't quite understand your request. Are you suggesting that Abseil put optional.h, variant.h, etc. into a separate git repo?

**Comment by mbxx** [comment]
I suspect creating a separate repo is what's being requested here.  This is closely related to https://github.com/abseil/abseil-cpp/issues/180

**Comment by JonathanDCohen** [comment]
Thank you for the idea.  At this time we have no plans to separate out Abseil into separate repos, although the above mentioned request for up-to-date documentation on backports is a good idea.  For now though, I'm going to close this issue as wontfix.  Please feel free to re-open :)
