### ISSUE TITLE
 CMake: Undefined symbol absl::container_internal::ShouldInsertBackwards

### ISSUE THREAD

**Issue by tido64** [abseil/abseil-cpp#204]
It looks like #173 was accidentally reverted with c16d5557, removing `internal/raw_hash_set.cc` from `absl_container`. Can you fix this upstream so that it doesn't happen again?

**Comment by mbxx** [comment]
Sorry about that :(  As you may have guessed, resolving a merge conflict went badly on our end.  This is now fixed both on GitHub and upstream.

**Comment by tido64** [comment]
Many thanks, @mbxx 👍
