### ISSUE TITLE
raw_hash_set_test occasionally fails (Linux)

### ISSUE THREAD

**Issue by backerman** [abseil/abseil-cpp#205]
Floating-point comparison tolerance needs to be bumped up a touch? Rerunning the test resulted in success.

Compiler: gcc 8.2.1+20180831-1
Kernel: 4.18.16-arch1-1-ARCH
Architecture: x86_64
Distribution: Arch
Abseil pulled @ f86f9413856b65afdd61fea938d684b8ab73115a

[test.log](https://github.com/abseil/abseil-cpp/files/2521953/test.log)

**Comment by shaindelschwartz** [comment]
The latest push, [7990fd4](https://github.com/abseil/abseil-cpp/commit/7990fd459e9339467814ddb95000c87cb1e4d945), includes a change to use multiple trials in CollectPerfectRatios. This should smooth out any outliers and reduce the flakiness of the test.
