### ISSUE TITLE
flat_hash_map fails to compile when 'Warnings as Errors' is turned on in VS2017

### ISSUE THREAD

**Issue by ChewyGumball** [abseil/abseil-cpp#208]
When I include `absl/container/flat_hash_set.h` or `absl/container/flat_hash_map.h` I get the following warnings:

```
absl\container\internal\raw_hash_set.h(206): warning C4244: 'argument': conversion from 'T' to 'uint32_t', possible loss of data
        with
        [
            T=uint64_t
        ]
absl\container\internal\raw_hash_set.h(431): note: see reference to function template instantiation 'int absl::container_internal::TrailingZeros<uint64_t>(T)' being compiled
        with
        [
            T=uint64_t
        ]
absl\container\internal\raw_hash_set.h(212): warning C4267: 'argument': conversion from 'size_t' to 'uint32_t', possible loss of data
absl\container\internal\raw_hash_set.h(480): note: see reference to function template instantiation 'int absl::container_internal::LeadingZeros<size_t>(T)' being compiled
        with
        [
            T=size_t
        ]
```

Looking at the TrailingZeros and LeadingZeros functions we see:
```C++
template <typename T>
int TrailingZeros(T x) {
  return sizeof(T) == 8 ? base_internal::CountTrailingZerosNonZero64(x)
                        : base_internal::CountTrailingZerosNonZero32(x);
}

template <typename T>
int LeadingZeros(T x) {
  return sizeof(T) == 8 ? base_internal::CountLeadingZeros64(x)
                        : base_internal::CountLeadingZeros32(x);
}
```

The warning is spurious because the `base_internal` call that won't lose data will be used, but the other is still compiled, and thus warned about. 

In my case, I have turned on 'Warnings as Errors', so I can't even compile without static casting `x` to the type of the argument of `CountLeadingZerosXX` or `CountTrailingZerosNonZero64`.

**Comment by derekmauro** [comment]
I wasn't able to reproduce this (maybe I have a different version of MSVC?), but I added some casts that should fix this for you. Let us know if it doesn't.

**Comment by Bu11etmagnet** [comment]
This should be a compile-time decision, not a run-time decision, e.g. `if constexpr (...)`.
Is there a `constexpr ?  :` yet?

**Comment by derekmauro** [comment]
Since we are supporting C++11, we can't use `if constexpr`, but I'm pretty sure all modern compilers are smart enough to optimize away the constant branch in this case.
