### ISSUE TITLE
flat_hash_map: Visual Studio never uses SSE2

### ISSUE THREAD

**Issue by sneves** [abseil/abseil-cpp#210]
The use of SSE2 / SSSE3 in the hash tables is controlled by the `SWISSTABLE_HAVE_SSE2` and `SWISSTABLE_HAVE_SSSE3` macros. If they are not explicitly defined by the user, there is some autodetection in place that will enable them if `__SSE2__` is set:

```
#ifndef SWISSTABLE_HAVE_SSE2
#ifdef __SSE2__
#define SWISSTABLE_HAVE_SSE2 1
#else
#define SWISSTABLE_HAVE_SSE2 0
#endif
#endif
```

However, Visual Studio has no concept of `__SSE2__`, and as such SSE2 will never be autodetected. Furthermore, even if one sets this flag manually it will still fail, seeing that 

```
#if SWISSTABLE_HAVE_SSE2
#include <x86intrin.h>
#endif
```
is a GCC-specific header. I solved this with a simple patch that adds [MSVC's own predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2017#microsoft-specific-predefined-macros) (there are none specific to SSSE3):

```diff
-#ifdef __SSE2__
+#if defined(__SSE2__) || defined(_MSC_VER) && (defined(_M_X64) || defined(_M_IX86) && _M_IX86_FP >= 2)
```
and includes the instruction set specific headers necessary:
```diff
 #if SWISSTABLE_HAVE_SSE2
-#include <x86intrin.h>
+#include <emmintrin.h>
+#endif
+
+#if SWISSTABLE_HAVE_SSSE3
+#include <tmmintrin.h>
 #endif
```

**Comment by derekmauro** [comment]
This is done in 7990fd459e9339467814ddb95000c87cb1e4d945.
