### ISSUE TITLE
Can't link library using absl::string_view in api compiled with c++11 against program using this api compiled with c++17

### ISSUE THREAD

**Issue by liamuk** [abseil/abseil-cpp#211]
I'm trying to link a program compiled with c++17 against a library compiled with c++11 that has absl::string_view in its api. Because my program gets std::string_view and the library has absl::string_view, they are binary incompatible and this can't be done.

It would be nice if I could specify using absl::string_view over std::string_view even when std::string_view is available so I can use both this library and c++17.

can `ABSL_HAVE_STD_STRING_VIEW` be made configurable?

**Comment by ahedberg** [comment]
If I understand what you're trying to do correctly, we don't support depending on a compiled representation of Abseil. From https://abseil.io/about/compatibility:

"""
Do not depend on a compiled representation of Abseil. We do not promise any ABI compatibility — we intend for Abseil to be built from source, hopefully from head. The internal layout of our types may change at any point, without notice. Building Abseil in the presence of different C++ standard library types may change Abseil types, especially for pre-adopted types (string_view, variant, etc) — these will become typedefs and their ABI will change accordingly.
"""

Is compiling both libraries at the same time, with the same compiler options, a feasible workaround?

**Comment by liamuk** [comment]
Ah I see.

I can't do that because recompiling the third-party library (tensorflow) is infeasible.

The workaround I'm using currently is to do:
```
#include "absl/base/config.h"
#undef ABSL_HAVE_STD_STRING_VIEW
```
before including the tensorflow headers, which is not great.

Feel free to close this issue.

**Comment by mbxx** [comment]
I think I might call this a bug in TensorFlow.  Binary distributions that include Abseil should either use an LTS branch of Abseil, in which case the inline namespaces that we include would prevent these ODR violations, or they should hide all Abseil symbols from the linker.  Either way, TensorFlow could package their library in such a way that this wouldn't be a problem.

**Comment by JonathanDCohen** [comment]
Seeing no more discussion on this issue and that it seems to be a Tensorflow issue, I'm going to close this.  Please feel free to reopen.

**Comment by ahoereth** [comment]
> Ah I see.
> 
> I can't do that because recompiling the third-party library (tensorflow) is infeasible.
> 
> The workaround I'm using currently is to do:
> 
> ```
> #include "absl/base/config.h"
> #undef ABSL_HAVE_STD_STRING_VIEW
> ```
> 
> before including the tensorflow headers, which is not great.
> 
> Feel free to close this issue.

For others stumbling over this issue, the following is still a valid workaround for me:

```
#include "absl/base/config.h"
#undef ABSL_HAVE_STD_STRING_VIEW
#undef ABSL_USES_STD_STRING_VIEW
```

**Comment by derekmauro** [comment]
> For others stumbling over this issue, the following is still a valid workaround for me:
> 
> ```
> #include "absl/base/config.h"
> #undef ABSL_HAVE_STD_STRING_VIEW
> #undef ABSL_USES_STD_STRING_VIEW
> ```

Don't do that, it is going to be brittle. The supported solution is to edit `options.h`.

https://github.com/abseil/abseil-cpp/blob/48f72c227b94b06387106f71d4450b31e88e283b/absl/base/options.h#L133-L157

See also:
https://abseil.io/docs/cpp/guides/options
https://abseil.io/blog/201901115-options

**Comment by ahoereth** [comment]
(edited) Thanks! This one should be less brittle then, no?

```cpp
#include "absl/base/options.h"
#undef ABSL_OPTION_USE_STD_STRING_VIEW
#define ABSL_OPTION_USE_STD_STRING_VIEW 0
```
