### ISSUE TITLE
Allow AlphaNum(char)?

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#214]
This will be useful for StrCat one char in a char array.

https://github.com/abseil/abseil-cpp/blob/070f6e47b33a2909d039e620c873204f78809492/absl/strings/str_cat.h#L245-L246

**Comment by derekmauro** [comment]
It's been proposed a number of times. Reasons why we've rejected it include the fact that wanting to print a single char from an array is actually very rare, and that it invites `char` vs `char*` errors. Do you have a compelling use case, or is this a speculative improvement?

I'd recommend `absl::StrCat(absl::string_view(&c[n], 1))` if you want to StrCat one char from an array.

**Comment by wjywbs** [comment]
This use case does happen very rarely and I will use the string_view workaround. Thanks.

I found that `absl::strings_internal::AlphaNumBuffer<1>` was also an option.

**Comment by tituswinters** [comment]
Don't (ever) use something out of another library's internal namespace.
Arbitrary changes happen to those interfaces and your code will break
without notice.

See the compatibility guidelines on abseil.io
