### ISSUE TITLE
bazel test failed on Windows

### ISSUE THREAD

**Issue by kzhdev** [abseil/abseil-cpp#216]
Run: bazel test //absl/...

ERROR: C:/dev/slick/core/cpp/third_party/abseil-cpp/absl/types/BUILD.bazel:266:1: C++ compilation of rule '//absl/types:variant_benchmark' failed (Exit 2)
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/internal/variant.h(246): error C3528: 'BoundIndices': the number of elements in this pack expansion does not match the number of elements in 'EndIndices'
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/internal/variant.h(243): note: while compiling class template member function 'absl::variant_internal::SimpleArray<absl::variant_internal::SimpleArray<absl
::variant_internal::SimpleArray<absl::variant_internal::SimpleArray<void (__cdecl *)(FunctionObject &&),3>,3>,3>,3> absl::variant_internal::MakeVisitationMatrixImpl<ReturnType,FunctionObject,absl::integer_sequence<size_t,3,3,3>,
absl::integer_sequence<T,0,1,2>>::Run(void)'
        with
        [
            FunctionObject=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::Varian
tAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonym
ous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>,
            ReturnType=void,
            T=size_t
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/internal/variant.h(424): note: see reference to function template instantiation 'absl::variant_internal::SimpleArray<absl::variant_internal::SimpleArray<ab
sl::variant_internal::SimpleArray<absl::variant_internal::SimpleArray<void (__cdecl *)(FunctionObject &&),3>,3>,3>,3> absl::variant_internal::MakeVisitationMatrixImpl<ReturnType,FunctionObject,absl::integer_sequence<size_t,3,3,3
>,absl::integer_sequence<T,0,1,2>>::Run(void)' being compiled
        with
        [
            FunctionObject=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::Varian
tAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonym
ous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>,
            ReturnType=void,
            T=size_t
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/internal/variant.h(257): note: see reference to class template instantiation 'absl::variant_internal::MakeVisitationMatrixImpl<ReturnType,FunctionObject,ab
sl::integer_sequence<size_t,3,3,3>,absl::integer_sequence<T,0,1,2>>' being compiled
        with
        [
            ReturnType=void,
            FunctionObject=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::Varian
tAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonym
ous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>,
            T=size_t
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/internal/variant.h(427): note: see reference to class template instantiation 'absl::variant_internal::MakeVisitationMatrix<void,Op,absl::integer_sequence<s
ize_t,3,3,3,3>>' being compiled
        with
        [
            Op=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative
<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespac
e'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/variant.h(428): note: see reference to function template instantiation 'void absl::variant_internal::VisitIndicesFallback<2,2,2,2>::Run<absl::variant_inter
nal::PerformVisitation<Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,a
bsl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::V
ariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>,size_t,size_t,size_t,size_t>(Op &&,size_t,size_t,size_t,size_t)' being compiled
        with
        [
            Visitor=absl::`anonymous-namespace'::VisitorApplier::Visitor,
            Op=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative
<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespac
e'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/types/variant.h(423): note: see reference to function template instantiation 'void absl::variant_internal::VisitIndicesFallback<2,2,2,2>::Run<absl::variant_inter
nal::PerformVisitation<Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,a
bsl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::V
ariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>,size_t,size_t,size_t,size_t>(Op &&,size_t,size_t,size_t,size_t)' being compiled
        with
        [
            Visitor=absl::`anonymous-namespace'::VisitorApplier::Visitor,
            Op=absl::variant_internal::PerformVisitation<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative
<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespac
e'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &>
        ]
absl/types/variant_benchmark.cc(71): note: see reference to function template instantiation 'void absl::visit<absl::`anonymous-namespace'::VisitorApplier::Visitor,const absl::variant<absl::`anonymous-namespace'::VariantAlternati
ve<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,const absl::variant<absl::`anonymous-namespac
e'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&>(Visitor &&,const absl::v
ariant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternati
ve<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namesp
ace'::VariantAlternative<1>> &)' being compiled
        with
        [
            Visitor=absl::`anonymous-namespace'::VisitorApplier::Visitor
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/base/internal/invoke.h(155): note: see reference to function template instantiation 'void absl::`anonymous-namespace'::VisitorApplier::operator ()<absl::variant<
absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>,absl::va
riant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>>(c
onst absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::Vari
antAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,const absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anon
ymous-namespace'::VariantAlternative<1>> &) noexcept const' being compiled
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/base/internal/invoke.h(183): note: see reference to function template instantiation 'void absl::base_internal::Callable::Invoke<F,absl::variant<absl::`anonymous-
namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`an
onymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&>(F &&,absl::var
iant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &
,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlterna
tive<1>> &)' being compiled
        with
        [
            F=absl::`anonymous-namespace'::VisitorApplier
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/utility/utility.h(221): note: see reference to function template instantiation 'void absl::base_internal::Invoke<T,absl::variant<absl::`anonymous-namespace'::Var
iantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`anonymous-namespa
ce'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>>&>(F &&,absl::variant<absl::`ano
nymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,absl::variant<
absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &,absl::variant<absl::`anonymous-namespace'::VariantAlternative<0>,absl::`anonymous-namespace'::VariantAlternative<1>> &)' be
ing compiled
        with
        [
            T=absl::`anonymous-namespace'::VisitorApplier,
            F=absl::`anonymous-namespace'::VisitorApplier
        ]
C:\users\owner\_bazel_owner\jddod2b6\execroot\com_google_absl\absl/utility/utility.h(266): note: see reference to function template instantiation 'void absl::utility_internal::apply_helper<T,Tuple&,0,1,2,3>(Functor &&,Tuple,absl
::integer_sequence<unsigned __int64,0,1,2,3>)' being compiled
        with
        [
            T=absl::`anonymous-namespace'::VisitorApplier,
            Functor=absl::`anonymous-namespace'::VisitorApplier,
            Tuple=Tuple &
        ]
absl/types/variant_benchmark.cc(126): note: see reference to function template instantiation 'void absl::apply<absl::`anonymous-namespace'::VisitorApplier,Tuple&>(Functor &&,Tuple)' being compiled
        with
        [
            Functor=absl::`anonymous-namespace'::VisitorApplier,
            Tuple=Tuple &
        ]
absl/types/variant_benchmark.cc(168): note: see reference to function template instantiation 'bool absl::`anonymous-namespace'::VisitTestBody<16,0>::Run<Tuple[16],benchmark::State>(Vars (&),State &)' being compiled
        with
        [
            Vars=Tuple [16],
            State=benchmark::State
        ]
absl/types/variant_benchmark.cc(168): note: see reference to function template instantiation 'bool absl::`anonymous-namespace'::VisitTestBody<16,0>::Run<Tuple[16],benchmark::State>(Vars (&),State &)' being compiled
        with
        [
            Vars=Tuple [16],
            State=benchmark::State
        ]
absl/types/variant_benchmark.cc(202): note: see reference to function template instantiation 'void absl::`anonymous-namespace'::BM_Visit<2,4>(benchmark::State &)' being compiled
INFO: Elapsed time: 45.075s, Critical Path: 34.02s
INFO: 50 processes: 50 local.
FAILED: Build did NOT complete successfully

**Comment by JonathanDCohen** [comment]
Do you know which MSVC version you are using?

**Comment by kzhdev** [comment]
I'm using Visual Studio Community 2017.

**Comment by JonathanDCohen** [comment]
cool.  I'll take a look at this next week.

**Comment by JonathanDCohen** [comment]
Hey there.  We've recently pushed out a number of MSVC fixes.  Is this a problem for you still?

**Comment by JonathanDCohen** [comment]
Closed due to inactivity.  Please feel free to re-open if the problem is still around :)
