### ISSUE TITLE
[GCC 8.2.1, CMake] absl::ByChar::Find link error when absl::string_view is std::string_view

### ISSUE THREAD

**Issue by chenxiaolong** [abseil/abseil-cpp#218]
It seems that when `absl::string_view` is `std::string_view` (i.e. targeting C++17), then `absl::ByChar::Find` fails to link properly.

```
[  2%] Built target absl_internal_spinlock_wait
[  3%] Built target absl_dynamic_annotations
[ 10%] Built target absl_base
[ 12%] Built target absl_internal_throw_delegate
[ 25%] Built target absl_strings
[ 26%] Building CXX object CMakeFiles/main.dir/main.cpp.o
[ 27%] Linking CXX executable main
/usr/bin/ld: CMakeFiles/main.dir/main.cpp.o: in function `absl::strings_internal::SplitIterator<absl::strings_internal::Splitter<absl::ByChar, absl::AllowEmpty> >::operator++()':
main.cpp:(.text._ZN4absl16strings_internal13SplitIteratorINS0_8SplitterINS_6ByCharENS_10AllowEmptyEEEEppEv[_ZN4absl16strings_internal13SplitIteratorINS0_8SplitterINS_6ByCharENS_10AllowEmptyEEEEppEv]+0x65): undefined reference to `absl::ByChar::Find(std::basic_string_view<char, std::char_traits<char> >, unsigned long) const'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/main.dir/build.make:89: main] Error 1
make[1]: *** [CMakeFiles/Makefile2:77: CMakeFiles/main.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

If I target C++14 instead, which causes abseil's own string_view implementation to be used, then everything links just fine. I'm using GCC 8.2.1 on Fedora 29 and building with CMake.

---

I created a very simple project to reproduce this: https://github.com/chenxiaolong/abseil_link_error_test

To test:
```
git clone --recursive https://github.com/chenxiaolong/abseil_link_error_test.git
cd abseil_link_error_test
mkdir build
cd build
cmake ..
make
```

**Comment by JonathanDCohen** [comment]
Thanks for the report!  We're currently migrating all of our cmakelists to use absl_cC_library and ape our bazel targets, so we'll get this when we get to strings/

**Comment by SlavaMelanko** [comment]
Hi @JonathanDCohen 
Do you have any updates?

**Comment by derekmauro** [comment]
The problem here is that you are building the Abseil submodule in C++14 mode and your own project in C++17.  Put `set(CMAKE_CXX_STANDARD 17)` in your `CMakeLists.txt` to build all code in C++17 mode and this will work.
