### ISSUE TITLE
CMake: ABSL_USE_GOOGLETEST_HEAD  doesn't work when including as a subdirectory

### ISSUE THREAD

**Issue by amerry** [abseil/abseil-cpp#219]
When building with CMake, if you define `ABSL_USE_GOOGLETEST_HEAD=1` and use `add_subdirectory` to add abseil-cpp (in a `third_party/abseil-cpp` directory, say), the build will fail complaining about "file not found".

The issue is that `CMake/DownloadGTest.cmake` is not using the `${CMAKE_BINARY_DIR}/` prefix with `configure_file`, but is using it with all the other commands. This means that the `CMakeLists.txt` gets created in `build/third_party/abseil-cpp/`, say, but `execute_process` is looking for it in `build/`.

**Comment by JonathanDCohen** [comment]
I'll take a look.  Thanks for the report!

**Comment by JonathanDCohen** [comment]
There should be fixed with today's release.  I'm closing this issue, please feel free to re-open if the problem is still there.
