### ISSUE TITLE
The choice of in-place cleanup threshold in raw_hash_set

### ISSUE THREAD

**Issue by leventov** [abseil/abseil-cpp#220]
I wonder what is the reasoning behind calling `drop_deletes_without_resize()` only if the efficient load factor is below 0.4375:
https://github.com/abseil/abseil-cpp/blob/f6ae816808cd913e0e2b3e2af14f328fa1071af0/absl/container/internal/raw_hash_set.h#L1700-L1709

It means that with the hash table usage pattern "insertions and deletions occur over time, but the size stays approximately the same" the efficient load factor will end up between ~ 0.22 and 0.4375, that seems to be too low.

**Comment by marvinparedes29** [comment]
Fix my issue.

**Comment by fowles** [comment]
The current invariant for `rehash_and_grow_if_necessary()` is that after growth load factor will be `<= max/2`.  This ensure that the squash case fits the same invariant.

That said, this was chosen somewhat arbitrarily a compelling argument for changing it would be considered.  Compelling arguments for this must be tied to real prod systems not micro benchmarks as a micro benchmark is trivially game-able for this case.

**Comment by JonathanDCohen** [comment]
Closed due to inactivity.  Please feel free to re-open :)
