### ISSUE TITLE
[Benchmark] flat_hash_map considerably slower than std::unordered_map

### ISSUE THREAD

**Issue by bstaletic** [abseil/abseil-cpp#223]
This is not a bug report, more of an interesting data point.
In the past week I've been trying out `absl::flat_hash_map` and `google::dense_hash_map` (and sets) and comparing performance to STL counterparts.

The following gist contains benchmarks for STL (Master), abseil and dense_hash_map:
https://gist.github.com/bstaletic/7d3e31db7fc8d40a12787fab09ff092f

The project whose benchmark results you're looking at is https://github.com/Valloric/ycmd
The benchmarks test two separate algorithms, `FilterAndSortCandidates` and `IdentifierCompleter`.

#### FilterAndSortCandidates benchmark

This is benchmarking [the function of the same name](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/PythonSupport.cpp#L64-L102).
This one actually has the best timings with abseil.

#### IdentifierCompleter benchmark

This is benchmarking [this piece of code](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/IdentifierDatabase.cpp#L68-L112).
Surprisingly, abseil is the slowest of the three.

If there's interest to investigate my benchmark results further, I will gladly provide any information needed.

**Comment by derekmauro** [comment]
Obviously we'd like more information on what's going in including compilers, build commands, etc, so we can reproduce this ourselves.

However, regardless of which container you are using, one thing I'd like to point out in the IdentifierDatabase::ResultsForQueryAndType() code you linked to:
```
if (ContainsKey(seen_candidates, candidate) {
  continue;
}
seen_candidates.insert(candidate);
```
The code above does redundant lookups (it does the same lookup twice - once on find, and once on insert).

This is likely faster:
```
if (!seen_candidates.insert(candidate).second) {
  continue;
}
```

**Comment by sbenzaquen** [comment]
Can you share a PR where `absl::flat_hash_map` is being used?
One thing to note is that `absl::flat_hash_map` is much more sensitive to the quality of the hash function than `std::unordered_map`. The default (`absl::Hash`) should be a good one. Manually specifying one that does not provide good bit mixing can lead to bad performance.

As for microbenchmarks, they might be misleading depending on the inputs. For example, `std::unordered_map` will give you better cache locality when you query the keys in memory order which is something easy to do in a microbenchmark but rarely something that happens in real code.
Having a better idea of the actual code could help identify the problem.

**Comment by bstaletic** [comment]
> Can you share a PR where `absl::flat_hash_map` is being used? 

There's no PR, but here's a link to the branch in my fork:
https://github.com/bstaletic/ycmd/commit/c7c47175fd7bb19e4b448b34c15bdaf7b86d5e4b

> The default (`absl::Hash`) should be a good one.

That's the only one used throughout the code in my branch.

**Comment by sbenzaquen** [comment]
Maybe this is related to the performance problem:
The code is iterating all maps/sets. Iteration on absl's tables is O(capacity), not O(size).
In particular, when you call `ClearCandidatesStoredForFile` and clear an innermost set, iterating that set is still going to be O(capacity) even though it is empty.
`.clear()` balances this problem by releasing the memory if capacity > 127, but for smaller capacities you are still going to be slower to iterate. One solution is to do `= {};` instead of `.clear();` to release the existing memory.

**Comment by bstaletic** [comment]
@derekmauro 
> Obviously we'd like more information on what's going in including compilers, build commands, etc, so we can reproduce this ourselves.

Apologies, I didn't see your reply somehow.
I tried clang and gcc. The repository has a `benchmark.py` script that will compile and run the benchmarks with the correct flags.
The dependencies are python headers/libpython and cmake.

> The code above does redundant lookups (it does the same lookup twice - once on find, and once on insert).

Thanks for pointing that out. With your proposed change abseil got much closer to STL, but still is slower. I've updated the gist above.

@sbenzaquen 
If I'm not mistaken `dense_hash_map`/`dense_hash_set` also keep the memory until you explicitly request for it to be freed, yet those containers perform much faster.

> One solution is to do `= {};` instead of `.clear();` to release the existing memory.

Wouldn't I then pay the price of new allocations?

**Comment by sbenzaquen** [comment]
> @sbenzaquen
> If I'm not mistaken `dense_hash_map`/`dense_hash_set` also keep the memory until you explicitly request for it to be freed, yet those containers perform much faster.

afaik, `dense_hash_*` will also release the allocation unless you requested it explicitly.

> 
> > One solution is to do `= {};` instead of `.clear();` to release the existing memory.
> 
> Wouldn't I then pay the price of new allocations?

It is a tradeoff. `std::unordered_*` has O(size) iteration, but they pay for it with extra memory usage (1 extra pointer per element) and less memory locality.
It all depends on your use case.
Note that `unordered_*` will also pay for memory allocations for every element because it is node based.

I am not saying that this is relevant to your case, though. I am just pointing out use cases that we know are slower. One thing we could do to isolate the problem is change one map at a time. This might help us determine which use case is problematic here.

Just out of curiosity, do you know if your build is enabling SSE2 and/or SSSE3?
When these options are not available the table falls backs to a slower implementation.
You could check by printing `SWISSTABLE_HAVE_SSE2` and `SWISSTABLE_HAVE_SSSE3`.

(unrelated, but something I noticed)
`ResultsForQueryAndType` might be a little wasteful with `results`, at least in that benchmark.
It is potentially pushing thousands of results into the vector to then erase them and keep only 10. A much more efficient solution would be to keep a heap or a sorted vector with the top N and only push when you find a better solution.

**Comment by bstaletic** [comment]
> `= {};` instead of `.clear()`;

This was a step back as far as benchmarks go.

> One thing we could do to isolate the problem is change one map at a time.

Here's the commit reverting all but one `flat_hash_set` to `unordered_set`.
https://github.com/bstaletic/ycmd/commit/f28127d635ac426b88a7884539fa83cc17d6f447

It made the `abseil` branch catch up to `dense_hash_map` branch. In benchmarks where all results are kept `abseil` is a bit ahead of `dense_hash_*`, but in wasteful scenario, where only the top handful is kept, `dense_hash_*` is faster.

> `ResultsForQueryAndType` might be wasteful

The wasteful scenario is the default, though in real use, you are probably not going to have ~65k identifiers *per filetype*.

> A much more efficient solution would be to keep a heap or a sorted vector with the top N and only push when you find a better solution.

I'm not sure I'm following. Currently, the function iterates over all `Candidate`s within the `FiletypeCandidateMap` object, does some filtering (`IsEmpty()`, `ContainsBytes()` and `QueryMatchResult()`) and then calls `PartialSort`.
How can I maintain a heap or a sorted vector if I'm constantly calling `push_back`?
I would still have to iterate through all `Candidate`s, so wouldn't maintaining a heap/sorted vector result in much more time spent swapping candidates?

One other strange thing I've noticed, with the [last commit](https://github.com/bstaletic/ycmd/commit/f28127d635ac426b88a7884539fa83cc17d6f447).
Including the `!seen_candidates.insert( candidate ).second` change results in a tiny bit faster benchmark *except for the 65k* benchmark where it gets a bit slower than doing two look ups.

EDIT: Forgot to mention that the gist with the benchmark results has been updated.

**Comment by sbenzaquen** [comment]
> > `= {};` instead of `.clear()`;
> 
> This was a step back as far as benchmarks go.
> 
> > One thing we could do to isolate the problem is change one map at a time.
> 
> Here's the commit reverting all but one `flat_hash_set` to `unordered_set`.
> [bstaletic/ycmd@f28127d](https://github.com/bstaletic/ycmd/commit/f28127d635ac426b88a7884539fa83cc17d6f447)

How many elements are on those candidate sets on average?
For tiny sets of trivial types like this a sorted (or even unsorted) vector tends to be faster than all the other alternatives.
`flat_hash_*` is optimized for find/insert and iteration is not the fastest around.

> 
> It made the `abseil` branch catch up to `dense_hash_map` branch. In benchmarks where all results are kept `abseil` is a bit ahead of `dense_hash_*`, but in wasteful scenario, where only the top handful is kept, `dense_hash_*` is faster.
> 
> > `ResultsForQueryAndType` might be wasteful
> 
> The wasteful scenario is the default, though in real use, you are probably not going to have ~65k identifiers _per filetype_.
> 
> > A much more efficient solution would be to keep a heap or a sorted vector with the top N and only push when you find a better solution.
> 
> I'm not sure I'm following. Currently, the function iterates over all `Candidate`s within the `FiletypeCandidateMap` object, does some filtering (`IsEmpty()`, `ContainsBytes()` and `QueryMatchResult()`) and then calls `PartialSort`.
> How can I maintain a heap or a sorted vector if I'm constantly calling `push_back`?
> I would still have to iterate through all `Candidate`s, so wouldn't maintaining a heap/sorted vector result in much more time spent swapping candidates?

Currently you insert all possible results into the vector (lets call that M), and then take the top N.
If you keep only the top N, you save the copies for those M elements, save memory by having a smaller vector, etc.
With numbers: lets say M=1000, N=10.
Right now you are doing 1000 `push_back`s into the vector.
Then doing partial_sort (or nth+sort) to get the top 10.
Then erasing 9990 elements from the vector.

The alternative is that you have a min heap with at most 10 elements.
For each new result, you compare with the top (the minimum element). If it is smaller or equal, you ignore that result right away. No copying, no log(n) comparisons for it.
If it is larger, you pop the top (minimum element) from the heap and push the new result.
This is pretty much what partial_sort is doing, but without having to copy everything into the vector first.

> 
> One other strange thing I've noticed, with the [last commit](https://github.com/bstaletic/ycmd/commit/f28127d635ac426b88a7884539fa83cc17d6f447).
> Including the `!seen_candidates.insert( candidate ).second` change results in a tiny bit faster benchmark _except for the 65k_ benchmark where it gets a bit slower than doing two look ups.

`.insert()` is a little bit slower than `.find()` on hits.
If you expect a hit (the element is already there) `.find()` first is faster. If you expect a miss (the element is not there) calling only `.insert()` is faster since you have to do it anyway.
This is one of the points where microbenchmarks might be misleading if they don't provide realistic data access patterns.

> 
> EDIT: Forgot to mention that the gist with the benchmark results has been updated.

**Comment by bstaletic** [comment]
> How many elements are on those candidate sets on average?

Hard to tell. It depends on the users workflow. Basically, the project scans files that user has opened in his editor and populates the cadidates list by extracting all valid identifiers in those files, separated by filetype.

> For tiny sets of trivial types like this a sorted (or even unsorted) vector tends to be faster than all the other alternatives.
`flat_hash_*` is optimized for find/insert and iteration is not the fastest around.

I'll keep that in mind.

> Currently you insert all possible results into the vector (lets call that M), and then take the top N.
If you keep only the top N, you save the copies for those M elements, save memory by having a smaller vector, etc.
With numbers: lets say M=1000, N=10.
Right now you are doing 1000 push_backs into the vector.
Then doing partial_sort (or nth+sort) to get the top 10.
Then erasing 9990 elements from the vector.

> The alternative is that you have a min heap with at most 10 elements.
For each new result, you compare with the top (the minimum element). If it is smaller or equal, you ignore that result right away. No copying, no log(n) comparisons for it.
If it is larger, you pop the top (minimum element) from the heap and push the new result.
This is pretty much what partial_sort is doing, but without having to copy everything into the vector first.

Okay, now it makes sense, I'll play with that idea.

> `.insert()` is a little bit slower than `.find()` on hits.
If you expect a hit (the element is already there) .find() first is faster. If you expect a miss (the element is not there) calling only .insert() is faster since you have to do it anyway.
This is one of the points where microbenchmarks might be misleading if they don't provide realistic data access patterns.

Okay, then I should stick with `.find()` first. Since this is basically iterating over words in all open, say, C++ files, and in most cases one would declare an identifier only if it will be used, at best there should be 50% hits, likely more.

Thanks for the help.

**Comment by greg7mdp** [comment]
> It is a tradeoff. `std::unordered_*` has O(size) iteration, but they pay for it with extra memory usage (1 extra pointer per element) and less memory locality.
> I am not saying that this is relevant to your case, though. I am just pointing out use cases that we know are slower. 

Should absl::flat_hash_map really be slower for iteration though? I agree with the O(size) vs O(capacity) comment, but still iterating over a contiguous array even 43% to 87% full should be faster that following pointers (unless maybe the values inserted are very large).

**Comment by bstaletic** [comment]
What kills performance is using (a pointer to) `absl::flat_hash_set` instead of `std::unordered_set` as the inner map's `Value`. This is the case with every implementation of hash tables I have found.

**Comment by greg7mdp** [comment]
You are using (a pointer to) absl::flat_hash_set instead of  (a pointer to)  std::unordered_set, right? Otherwise it would not be a fair comparison.

**Comment by bstaletic** [comment]
That's right. The objects are large, so you can fit more pointers to objects in the same space than you can fit objects themselves.

Apart from that, the objects themselves are stored in the `candidate_reporitory_` member object, which is a wrapper around `absl::flat_hash_map<std::string, std::unique_ptr< Candidate>>`.

**Comment by greg7mdp** [comment]
OK, I still don't understand why iteration should be slower with absl::flat_hash_map, I would expect it to be faster indeed, unless the map grew to a large size, but then elements were removed and it is now mostly empty.

**Comment by sbenzaquen** [comment]
It is not always slower, it just has different performance characteristics.
For tables with organic growth, most of the table will be full and `flat_hash_map` iteration will be just fine. But if capacity is much greater than size (for example, after many erases or a large `reserve()` call) then `flat_hash_map`'s iteration can be significantly slower.
Trivial example:

```
absl::flat_hash_set<int> s;
for (int i = 0; i < 1000000; ++i) s.insert(i);
for (int i = 0; i < 999999; ++i) s.erase(i);
for (int i : s) { ... }
```
In this case the iteration has to go through 1000000 slots, which is going to be much slower than `unordered_set`'s iteration that only goes directly to the existing element.

When deciding these parts of the design we found that iteration of a sparse table is not common enough to justify the extra per-node cost of the linked-list style iteration.

**Comment by greg7mdp** [comment]
thanks, @sbenzaquen this makes perfect sense. 

> When deciding these parts of the design we found that iteration of a sparse table is not common enough to justify the extra per-node cost of the linked-list style iteration.

There could be other solutions than having an extra per-node pointer, like for example a separate bitset marking occupied slots... could even use SSE instructions to look for the next busy slot. But granted iteration of a sparse table is not common enough to warrant the added complexity and cost.

**Comment by sbenzaquen** [comment]
That is what we already do.
We have a "bitset" marking occupied slots. That is done with the high bits of the control bytes.
And we use SSE instructions to look for the next full slot.
See https://github.com/abseil/abseil-cpp/blob/88a152ae747c3c42dc9167d46c590929b048d436/absl/container/internal/raw_hash_set.h#L653
But this is O(capacity)

**Comment by greg7mdp** [comment]
Oh yes, I had forgotten, I thought that the control byte was interleaved with the values (something like 16 bytes for every 16 values). Indeed, since they are all together, it less memory to go through to skip over many empty slots. Thanks!

>as an aside, despite the O(capacity), I would guess that iteration through the flat_hash_set  would still be faster vs unordered_set even if capacity = 10 * size.

**Comment by sbenzaquen** [comment]
We have not measured the thresholds here, but we know about the pathological cases.
This is one reason why `.clear()` will release the memory if capacity is too large. We don't want to spend time iterating an empty container.

**Comment by greg7mdp** [comment]
In the old google sparsehash (and in the dense_hash_map too), there was some code that checked (when inserting an item) whether to shrink the table:
```
  bool resize_delta(size_type delta) {
    bool did_resize = false;
    if ( settings.consider_shrink() ) {  // see if lots of deletes happened
      if ( maybe_shrink() )
        did_resize = true;
    }
```
