### ISSUE TITLE
Buill Abseil on CI service

### ISSUE THREAD

**Issue by uilianries** [abseil/abseil-cpp#224]
Hi!

It would be nice if it were possible to build Abseil for each new push to be sure of his integrity and reliability .

There are a wide variety of free services for open source projects, which cover most market platforms:

- [Travis CI](https://travis-ci.org/)
- [Appveyor](https://appveyor.com/)
- [Circle CI](https://circleci.com/)
- [Azure DevOps](https://azure.microsoft.com/en-us/services/devops/)

You could build Abseil on Linux, OSX and Windows, for example.

Regards!

**Comment by JonathanDCohen** [comment]
This is already happening in an internal change.  We will be turning on Travis and Appveyor soon, we're just making sure that we have a coherent plan for CI moving forwards and making sure we do all our due diligence to not leak internal stuff.

**Comment by uilianries** [comment]
Thanks for your answer :+1:

**Comment by Mizux** [comment]
seems related to #109 and PR #197 ...

**Comment by Mizux** [comment]
I guess 
https://github.com/abseil/abseil-cpp/blob/93dfcf74cb5fccae3da07897d8613ae6cab958a0/absl/copts/GENERATED_AbseilCopts.cmake#L206-L208
just break windows build :fireworks: 
https://ci.appveyor.com/project/Mizux/cmake-abseil/builds/23528461/job/jrp21qm2jcemx1bf#L185
note: take a look at https://github.com/Mizux/cmake-abseil/tree/install to see how abseil-cpp could be tested against numerous linux distro and windows...

**Comment by Mizux** [comment]
Seems it won't happen...
> Abseil has decided that we're not going to take on travis and appveyor currently, so I will close this > > issue.  Please feel free to reopen in the future.

_Originally posted by @JonathanDCohen in https://github.com/abseil/abseil-cpp/pull/197#issuecomment-477268607_

note: @JonathanDCohen is not part of abseil team anymore...
