### ISSUE TITLE
Build abseil without exceptions

### ISSUE THREAD

**Issue by apmanol** [abseil/abseil-cpp#227]
Hello all,

just a minor question since, it's not clear from the documentation. How can you build the libraries without exceptions, preferably with the use of cmake.
Something like:
```
set(CMAKE_CXX_EXCEPTIONS "-fno-exceptions")
set(ABSL_STD_CXX_FLAG "-fno-exceptions ")
add_subdirectory(thirdparty/abseil-cpp)

```
will do the trick? 

Thanks for any clarifications!

**Comment by JonathanDCohen** [comment]
you should be able to set -fno-exceptions.  We don't set our exceptions flags either way except for specific targets like exception-safety tests which don't make sense without them.

**Comment by apmanol** [comment]
ok, thanks a lot for the tip!
