### ISSUE TITLE
#include <atomic> in raw_hash_set.cc

### ISSUE THREAD

**Issue by no-more-secrets** [abseil/abseil-cpp#229]
I am running into a compiler error when compiling raw_hash_set.cc on OSX with a gcc8 build that apparently does not have `cxx_thread_local` feature which causes `ABSL_HAVE_THREAD_LOCAL` to be undefined.  This would not be a problem, but then in this situation the preprocessor logic in raw_hash_set.cc will reference std::atomic without `#include <atomic>`.  If I insert:

`#include <atomic>`

at the top of raw_hash_set.cc then it fixes it.  Note I am doing a standard build with CMake -- can't think of anything out of the ordinary that I am doing that would cause this.  Should we add an include for atomic when `ABSL_HAVE_THREAD_LOCAL` is undefined?

**Comment by derekmauro** [comment]
Thanks for the report. A fix will be pushed soon.

**Comment by derekmauro** [comment]
The fix for this is in 44b0fafc62d9b8f192e8180cbe9c4b806b339d57.
