### ISSUE TITLE
Recent linking breakage due to missing `-pthread`?

### ISSUE THREAD

**Issue by tkoeppe** [abseil/abseil-cpp#240]
Our project https://github.com/deepmind/lab has a tip-of-trunk dependency on Abseil. Everything was green as of our latest commit, but a fresh build today,

    bazel build //:game

results in the following linker errors:

```text
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::ArenaLock(absl::base_internal::LowLevelAlloc::Arena*): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::Leave(): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::(anonymous namespace)::AllocateThreadIdentityKey(void (*)(void*)): error: undefined reference to 'pthread_key_create'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_setspecific'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::CurrentThreadIdentityIfPresent(): error: undefined reference to 'pthread_getspecific'
```

As a workaround, I can add `--linkopt=-pthread`, but could you perhaps find out if a dependency went missing somewhere recently?

**Comment by tkoeppe** [comment]
This _might_ also be a Bazel regression from 0.21 vs 0.20?

**Comment by behroozmrd47** [comment]
> Our project https://github.com/deepmind/lab has a tip-of-trunk dependency on Abseil. Everything was green as of our latest commit, but a fresh build today,
> 
> ```
> bazel build //:game
> ```
> results in the following linker errors:
> 
> ```
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::ArenaLock(absl::base_internal::LowLevelAlloc::Arena*): error: undefined reference to 'pthread_sigmask'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o:low_level_alloc.cc:function absl::base_internal::(anonymous namespace)::ArenaLock::Leave(): error: undefined reference to 'pthread_sigmask'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::(anonymous namespace)::AllocateThreadIdentityKey(void (*)(void*)): error: undefined reference to 'pthread_key_create'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_setspecific'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::SetCurrentThreadIdentity(absl::base_internal::ThreadIdentity*, void (*)(void*)): error: undefined reference to 'pthread_sigmask'
> bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/base/_objs/base/thread_identity.pic.o:thread_identity.cc:function absl::base_internal::CurrentThreadIdentityIfPresent(): error: undefined reference to 'pthread_getspecific'
> ```
> As a workaround, I can add `--linkopt=-pthread`, but could you perhaps find out if a dependency went missing somewhere recently?

Thanks for your response. I did include the mentioned quick fix but it did not worked and I get the same error. To be concise, I entered the following command "~/lab$ bazel run :game -- -l tests/empty_room_test -s logToStdErr=true --linkopt=-pthread" and got the exact same error. Any ideas why?

Thankfully,

**Comment by tkoeppe** [comment]
@behroozmrd47: the flag needs to go before the `--` flag separator, otherwise it doesn't get passed to bazel (but rather to the program that's being run).
