### ISSUE TITLE
please support cmake install target like protobuf does

### ISSUE THREAD

**Issue by jdmairs** [abseil/abseil-cpp#241]
I'm building my project and dependencies with Visual Studio 2017.  With protobuf I build first with cmake and then run make install and it installs all the headers and libs in a nice consistent way so that I can easily find/link into it from vs2017.  

With abseil, afaik, I have to hand copy the headers and libs to lets say c:\program files\abseil-cpp\.  To make things easier/safer I move the entire directory stuctures including all the build rubbish.  

We are assuming we can treat abseil like boost or protobuf...one dev builds it and then zips it up for the rest to "deploy" on their dev boxes.

I guess one caveat is we took your guidance and added it to our src repo whereas we do not do that for boost since it's too large.

I just noticed "to be nor not to be: CMake install"

Our dev network is isolated from the internet.

Thanks!

**Comment by jdmairs** [comment]
I see this should be closed in favor of #111

**Comment by lauralann6** [comment]
😋
