### ISSUE TITLE
CMake: AppleClang does not provide Leak Sanitizer -> compilation failure when test enabled

### ISSUE THREAD

**Issue by Mizux** [abseil/abseil-cpp#244]
When I tried to add Travis-CI `xcode10.1` jobs, I found a compilation issue when enabling tests...
```shell
[ 58%] Building CXX object absl/debugging/CMakeFiles/absl_disabled_leak_check_test.dir/leak_check_fail_test.cc.o
cd /Users/travis/build/Mizux/abseil-cpp/build/absl/debugging && /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I/Users/travis/build/Mizux/abseil-cpp -isystem /Users/travis/build/Mizux/abseil-cpp/build/googletest-src/googlemock/include -isystem /Users/travis/build/Mizux/abseil-cpp/build/googletest-src/googlemock -isystem /Users/travis/build/Mizux/abseil-cpp/build/googletest-src/googletest/include -isystem /Users/travis/build/Mizux/abseil-cpp/build/googletest-src/googletest  -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/absl_disabled_leak_check_test.dir/leak_check_fail_test.cc.o -c /Users/travis/build/Mizux/abseil-cpp/absl/debugging/leak_check_fail_test.cc
[ 58%] Linking CXX executable absl_disabled_leak_check_test
cd /Users/travis/build/Mizux/abseil-cpp/build/absl/debugging && /usr/local/Cellar/cmake/3.12.3/bin/cmake -E cmake_link_script CMakeFiles/absl_disabled_leak_check_test.dir/link.txt --verbose=1
/Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -O3 -DNDEBUG -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/absl_disabled_leak_check_test.dir/leak_check_fail_test.cc.o  -o absl_disabled_leak_check_test libabsl_internal_leak_check_api_enabled_for_testing.a libabsl_leak_check_disable.a ../base/libabsl_base.a ../../lib/libgmock_main.a -fsanitize=leak ../base/libabsl_dynamic_annotations.a ../base/libabsl_internal_spinlock_wait.a ../../lib/libgmock.a ../../lib/libgtest.a 
clang: error: unsupported option '-fsanitize=leak' for target 'x86_64-apple-darwin17.7.0'
make[2]: *** [absl/debugging/absl_disabled_leak_check_test] Error 1
make[1]: *** [absl/debugging/CMakeFiles/absl_disabled_leak_check_test.dir/all] Error 2
make: *** [all] Error 2
The command "cmake --build build --target all" exited with 2.
```
job ref: https://travis-ci.org/Mizux/abseil-cpp/jobs/474846599#L1164

According to the Apple developer documention Leak Sanitizer does not seem available...
ref: https://developer.apple.com/documentation/code_diagnostics

Code to change: 
https://github.com/abseil/abseil-cpp/blob/7ffbe09f3d85504bd018783bbe1e2c12992fe47c/absl/debugging/CMakeLists.txt#L202-L205

**Comment by Mizux** [comment]
note: since I set `CMP0025` to `NEW` in a previous CL it should be easy for Abseil-Team to fix it..

https://github.com/abseil/abseil-cpp/blob/7ffbe09f3d85504bd018783bbe1e2c12992fe47c/CMakeLists.txt#L21-L24

**Comment by Mizux** [comment]
note: in https://github.com/abseil/abseil.github.io/blob/master/docs/cpp/platforms/platforms.md#linux
> ### Linux
>  **Supported**

| Operating System/Architecture | Compilers | Standard Libraries |
|---|---|---|
| Linux, little-endian, 64-bit | gcc 4.8+<br/>clang 3.3+ | libstdc++<br/>libcxx |

**BUT** Leak Sanitizer seems to come starting to clang 3.5
ref: http://releases.llvm.org/3.5.0/tools/clang/docs/LeakSanitizer.html

-> You'll have to use [`CMAKE_CXX_COMPILER_VERSION`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_VERSION.html)

note: kokoro does not test it
note: it's easy to add a job in Travis-CI see PR #197
```yml
matrix:
  include:
    # works on Trusty
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.3
          packages:
            - clang-3.3
      env:
        - MATRIX_EVAL="CC=clang-3.3 && CXX=clang++-3.3"
before_install:
    - eval "${MATRIX_EVAL}"
```
src: https://docs.travis-ci.com/user/languages/cpp/#clang-on-linux

**Comment by JonathanDCohen** [comment]
Hey there, Mizux.  I'm going through and triaging our CMake issues now that I'm back from vacation.

It looks here like we just want to add -fsanitize=leak only on clang 3.5 and greater?

We could also provide a ctest script instead of invoking ctest directly in our test scripts.  This would let us use [ctest_memcheck()](https://cmake.org/cmake/help/v3.11/manual/ctest.1.html#id30) to enable whatever sanitizers we want.  This has uses for our exception safety tests as well, which rely heavily on ASan.  What do you think?

**Comment by Mizux** [comment]
@JonathanDCohen never play with ctest scripts so I don't have any strong opinion...

But first things first, *we* should at least update the CMakeLists.txt of debugging because currently MacOS users can't compile with tests enabled...
Then, we can figure out (with a pet project first IMHO) if we want to place our bet on the ctest "advanced" framework...

**Comment by jdmairs** [comment]
Still an issue when cloning the head as of 2/20/2019
clang: error: unsupported option '-fsanitize=leak' for target 'x86_64-apple-darwin18.2.0'
