### ISSUE TITLE
absl::Hash specialization fails for std::pair in TensorFlow Windows build

### ISSUE THREAD

**Issue by rjpower** [abseil/abseil-cpp#247]
When attempting to use absl::flat_hash_map for some graph partitioning code in TensorFlow, we found an issue with the template specialization logic for absl::Hash on MSVC.

This change:

https://github.com/tensorflow/tensorflow/commit/67a7f04d010c50fb3d6d1bde7793d3f8d350decf

introduced the use of absl::flat_hash_map for the MemoryTypeMap type.  This compiles successfully on all TF build targets except for Windows.  On Windows, it appears MSVC is failing to resolve the absl::hash specialization for std::pair,<int, int>, and falls back to the std::hash.  It appears MSVC allows the std::hash substitution to pass, but then fails the final compile later on:

"The C++ Standard doesn't provide a hash for this type."

https://source.cloud.google.com/results/invocations/00718e40-2141-4c89-8d47-5a5314eef1e2/targets/tensorflow%2Fgithub%2Fwindows%2Fbazel%2Fcontinuous/log

The absl probe logic seems valid, and indeed this works properly on our other builds:

https://github.com/abseil/abseil-cpp/blob/master/absl/hash/internal/hash.h#L634

Our temporary fix has been to avoid using the std::pair key and instead use a custom struct with an explicit absl::hash friend function.  

We can try to build a smaller reproduction at some point but filing this in case something obvious stands out.

**Comment by sbenzaquen** [comment]
Thanks for the report.
I can reproduce this problem.
We had a similar problem with probing `std::tuple` and we just disabled probing for MSVC, but just for `std::tuple`. It seems that `std::pair` has a similar problem.
Seems like I have to refactor the probing code once more to deal with this problem.
For now, you could workaround the problem by removing the enable_if in the `AbslHashValue` overload for `std::pair`. You can see how we did this for `std::tuple`

**Comment by JonathanDCohen** [comment]
@EricWF has pushed a patch for this.  Can you check to see if the error isn't happening?

**Comment by EricWF** [comment]
Confirmed this is fixed in upstream.

**Comment by EricWF** [comment]
I mistakenly closed this bug when I meant to close #249.

Reopening.

**Comment by sbenzaquen** [comment]
This should be fixed by https://github.com/abseil/abseil-cpp/commit/88a152ae747c3c42dc9167d46c590929b048d436#diff-c284d6f2ba08418ca6ecf7467069442b.
Please confirm.
