### ISSUE TITLE
"Status" class similar to tensorflow::Status

### ISSUE THREAD

**Issue by micahcc** [abseil/abseil-cpp#248]
I've found that tensorflow::Status that is either ok or contains an error is really nice. Documentation:

https://www.tensorflow.org/api_docs/cc/class/tensorflow/status

Something similar would be really great. Could also add [[nodiscard]] to prevent users from ignoring the returned status.

**Comment by derekmauro** [comment]
This is something we've been working on for a while now. The thing that is taking the most time is unifying all of the forks of `Status`, including the one in TensorFlow. We are hoping to release this in a few months.

**Comment by JonathanDCohen** [comment]
I'm going to close this since we're not actively updating the... status... of this issue.  More information will be available the closer we get to releasing `Status`.  Please feel free to re-open if there are any other questions.

**Comment by cloudhan** [comment]
@derekmauro almost a year passed...

**Comment by derekmauro** [comment]
It's still very actively being worked on. Time estimates are hard.

**Comment by ElliottBrossard** [comment]
Is it possible to leave this open until `absl::Status` is released? It would be nice to have an issue to track that support.

**Comment by derekmauro** [comment]
Sure, I've re-opened the issue for tracking purposes.

**Comment by dayfine** [comment]
looking forward to this. So itched to use Status without having to import another repo...
Or I will have to `Result` in Rust 🤪🤪🤪

**Comment by ElliottBrossard** [comment]
Oh hey, it looks like `absl::Status` is here! 😄https://github.com/abseil/abseil-cpp/blob/master/absl/status/status.h

**Comment by zhangxy988** [comment]
Yep, this is a "soft" release. We are not going to publicly announce it until we finish updating the documentation. But feel free to start using it in your projects.

**Comment by dayfine** [comment]
Will there also be `StatusOr`, `status_macros.h` and `StatusBuilder`?

**Comment by rockwotj** [comment]
FWIW the status stuff in mediapipe seems to be the closest to something that may be released in `absl`. For example, their status is just an alias to `absl::Status`.

https://github.com/google/mediapipe/blob/master/mediapipe/framework/deps/status.h
https://github.com/google/mediapipe/blob/master/mediapipe/framework/deps/statusor.h
https://github.com/google/mediapipe/blob/master/mediapipe/framework/deps/status_macros.h

**Comment by micahcc** [comment]
Its here! Closing :) I guess I'll close. Of course StausOr would be nice too :p
