### ISSUE TITLE
Undefined reference to ThrowStdOutOfRange and RawLog

### ISSUE THREAD

**Issue by SlavaMelanko** [abseil/abseil-cpp#250]
I am trying to build a simple example using `GNU 7.3.0`

```cpp
#include <iostream>
#include <string>
#include <vector>

#include <absl/strings/str_join.h>

int main() {
    std::vector<std::string> v = {"foo","bar","baz"};
    std::string s = absl::StrJoin(v, "-");
    absl::StrAppend(&s, 5);
    std::cout << "Joined string: " << s << "\n";
    return 0;
}
```

And get linker errors

```bash
/lib/libabsl_strings.a(numbers.cc.o): In function `absl::lts_2018_12_18::SimpleAtof(absl::lts_2018_12_18::string_view, float*)':
numbers.cc:(.text+0x518): undefined reference to `absl::lts_2018_12_18::base_internal::ThrowStdOutOfRange(char const*)'
/lib/libabsl_strings.a(numbers.cc.o): In function `absl::lts_2018_12_18::SimpleAtod(absl::lts_2018_12_18::string_view, double*)':
numbers.cc:(.text+0x8c8): undefined reference to `absl::lts_2018_12_18::base_internal::ThrowStdOutOfRange(char const*)'
/lib/libabsl_strings.a(numbers.cc.o): In function `absl::lts_2018_12_18::SimpleAtob(absl::lts_2018_12_18::string_view, bool*)':
numbers.cc:(.text+0xb29): undefined reference to `absl::lts_2018_12_18::raw_logging_internal::RawLog(absl::lts_2018_12_18::LogSeverity, char const*, int, char const*, ...)'
/lib/libabsl_strings.a(ascii.cc.o): In function `absl::lts_2018_12_18::RemoveExtraAsciiWhitespace(std::string*)':
ascii.cc:(.text+0x468): undefined reference to `absl::lts_2018_12_18::base_internal::ThrowStdOutOfRange(char const*)'
```

Whereas on `Apple LLVM version 10.0.0 (clang-1000.11.45.5)` everything is ok

Even the whole list of libraries does not help

```bash
absl_dynamic_annotations
absl_internal_spinlock_wait
absl_leak_check_disable
absl_leak_check
absl_bad_optional_access
pow10_helper
absl_internal_city
absl_container
absl_bad_any_cast
absl_int128
absl_numeric
absl_base
absl_utility
absl_meta
absl_internal_throw_delegate
absl_internal_malloc_internal
absl_variant
absl_any
absl_span
absl_demangle_internal
absl_internal_debugging_internal
absl_optional
absl_symbolize
absl_stacktrace
absl_internal_examine_stack
absl_strings
absl_failure_signal_handler
absl_hash
absl_raw_hash_set
str_format_extension_internal
absl_time
str_format_internal
absl_str_format
absl_synchronization
```

How do you think where an issue is?

**Comment by derekmauro** [comment]
This doesn't reproduce for me. Can you provide an exact sequence of commands for me to reproduce it? What OS?

**Comment by SlavaMelanko** [comment]
Hi @derekmauro,

The thing is that we are trying to build a Conan package with the latest stable version (20181200) and got [GCC errors](https://github.com/bincrafters/conan-abseil/pull/11/checks?check_run_id=49876179).

Library is build ok whereas [test package](https://github.com/bincrafters/conan-abseil/tree/testing/20181200/test_package) is not.

It would be great if you had a time to check it.

**Comment by ahedberg** [comment]
We don't use Conan ourselves (support was contributed by @uilianries), so we're not well-equipped to debug this without an exact sequence of commands to reproduce this on a particular operating system. Would you be able to show us the command line you used that resulted in this failure?

**Comment by uilianries** [comment]
Hi everyone! I'm here to help you!

@SMelanko which platform are you using? Linux? And Arch? Is there a build on Travis or a project where we can read all those steps?

**Comment by ericderojas** [comment]
oh

*Eric de Rojas *

*Live in Peace *

**Comment by SlavaMelanko** [comment]
Hi @uilianries,

Here is a [branch](https://github.com/bincrafters/conan-abseil/pull/11) where you suggested changing the libraries order.
I tried it with simple Dockerfile:

```
FROM ubuntu:bionic

RUN apt-get update && apt-get upgrade -y && apt-get install -y cmake git python-pip

RUN pip install conan
RUN conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan

WORKDIR /app
COPY . ./

RUN conan create . smela/testing
```

The result - problem was reproduced and no more for now.

**Comment by EricWF** [comment]
I managed to reproduce using the docker instructions.

Here's what's happening: The test program tries to link against every absl library *in the order as the `conanfile.py`*. Here's a copy of that list:

```
absl_dynamic_annotations
absl_internal_spinlock_wait
absl_bad_optional_access
absl_leak_check
absl_leak_check_disable
absl_container
absl_internal_city
pow10_helper
absl_bad_any_cast
absl_int128
absl_numeric
absl_base
absl_internal_throw_delegate
absl_utility
absl_meta
absl_internal_malloc_internal
absl_optional
absl_span
absl_demangle_internal
absl_internal_debugging_internal
absl_variant
absl_any
absl_strings
absl_stacktrace
absl_symbolize
absl_hash
str_format_extension_internal
absl_raw_hash_set
absl_internal_examine_stack
str_format_internal
absl_failure_signal_handler
absl_str_format
absl_time
absl_synchronization
```

Notice that `absl_strings` comes after `absl_base` and `absl_internal_throw_delegate` despite depending on both libraries. When using static libraries, if `libA` depends on `libB` then `libB` must appear after `libA` when linking.

I managed to avoid your link errors by re-ordering the libraries. Is conan supposed to be tracking the dependency information specified by the absl CMake library targets? Another fix would be to make conan wrap usages of the absl libraries in a `--start-group <absl_archives...> --end-group` directive.

**Comment by uilianries** [comment]
@SMelanko bincrafters/abseil and abseil/abseil-cpp are different things.

The Bincrafters' Abseil package was created before to support Abseil project and it should be deprecated after having the official package from Abseil team available in Conan Center.

If you have a problem related to Bincrafter's package, please, open an issue to https://github.com/bincrafters/community/issues/

Of course, we know about the circular dependency problem, as @EricWF said and `--start-group` could help Abseil itself.
