### ISSUE TITLE
Undefined symbol absl::container_internal::UnsampleSlow

### ISSUE THREAD

**Issue by matthewgingell** [abseil/abseil-cpp#251]
I'm seeing an unresolved reference to absl::container_internal::UnsampleSlow when I depend on absl::container in a CMake build, eg:

add_executable(t t.cc)
target_link_libraries(t absl::container absl::hash)

Undefined symbols for architecture x86_64:
  "absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)", referenced from:
      absl::container_internal::HashtablezInfoHandle::~HashtablezInfoHandle() in t.cc.o
ld: symbol(s) not found for architecture x86_64

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/master/absl/container/CMakeLists.txt#L17-L24

Don't depend on the `absl::container` target anymore, it is deprecated and going away. Depend on the thing you are actually using instead. Sorry about this.
