### ISSUE TITLE
Linker error since commit 968a34ffdaadd7db062a9621dfbdf8b2d16e05af

### ISSUE THREAD

**Issue by bstaletic** [abseil/abseil-cpp#253]
Hello, I'm using CMake for my project and last night I tried to update abseil, but was greeted with linking failures.
The errors can be found here: https://gist.github.com/bstaletic/aac910aca122ca5a226c3f1f59bba2f9

What my `CMakeLists.txt` is doing is:

```CMake
list( APPEND LLVM_FLAGS "-fPIC" )
list( APPEND GCC_FLAGS "-fPIC" )

add_subdirectory( absail )
set( ABSEIL_INCLUDES_DIR "${CMAKE_SOURCE_DIR}/abseil" )
include_directories(
  SYSTEM
  ${Boost_INCLUDE_DIR}
  ${PYBIND11_INCLUDES_DIR}
  ${ABSAIL_INCLUDES_DIR}
  ${PYTHON_INCLUDE_DIRS}
  ${CLANG_INCLUDES_DIR}
  )
target_link_libraries( ${PROJECT_NAME}
                       ${Boost_LIBRARIES}
		       absl::hash
		       absl::container
                       ${PYTHON_LIBRARIES}
                       ${LIBCLANG_TARGET}
                       ${EXTRA_LIBS}
                     )
```

Unfortunately, I couldn't provide a minimal reproducible test case, but the steps to reproduce with my project are as follows:

- `git clone --recursive -b abseil_linker_error https://github.com/bstaletic/ycmd`
- `cd ycmd`
- `YCM_TESTRUN=1 ./build.py --build-dir <some directory>` - note that the dependency is having python headers available.

This will automatically run the cmake and make in user specified directory.

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/master/absl/container/CMakeLists.txt#L17-L24

Don't depend on the `absl::container` target anymore, it is deprecated and going away. Depend on the thing you are actually using instead. Sorry about this.
