### ISSUE TITLE
where is this /contrib/data/kernels/assert_next_dataset_op.cc file 

### ISSUE THREAD

**Issue by SuMacal2019** [abseil/abseil-cpp#256]
CMake Error at tf_core_kernels.cmake:221 (add_library):
  Cannot find source file:

    E:/tensorflow-1.12.0/tensorflow/contrib/data/kernels/assert_next_dataset_op.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  CMakeLists.txt:540 (include)

CMake Error at tf_core_ops.cmake:73 (add_library):
  Cannot find source file:

    E:/tensorflow-1.12.0/tensorflow/contrib/data/ops/dataset_ops.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:538 (include)

CMake Error at tf_core_ops.cmake:73 (add_library):
  No SOURCES given to target: tf_contrib_data_dataset_ops
Call Stack (most recent call first):
  tf_core_ops.cmake:92 (GENERATE_CONTRIB_OP_LIBRARY)
  CMakeLists.txt:538 (include)

CMake Error at tf_core_kernels.cmake:221 (add_library):
  No SOURCES given to target: tf_core_kernels
Call Stack (most recent call first):
  CMakeLists.txt:540 (include)

in tf_core_kernels.cmake
70 line :      "${tensorflow_source_dir}/tensorflow/contrib/data/kernels/assert_next_dataset_op.cc"

**Comment by derekmauro** [comment]
Wrong project. Abseil is not TensorFlow. https://github.com/tensorflow/tensorflow is probably what you want.
