### ISSUE TITLE
No CMAKE_CXX_STANDARD set, assuming 11

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#260]
The default since GCC 6 (2016) is 14, IIRC.
Is assuming 11 a good idea?

Living @ head, aren't we?

**Comment by mbxx** [comment]
Abseil promises 5 years of support for the compilers that we support (https://abseil.io/about/compatibility).  I believe MSVC2015 is the long pole here, so we'll be assuming a baseline of C++11 for a few more years.
