### ISSUE TITLE
Update minimum required cmake version

### ISSUE THREAD

**Issue by progsource** [abseil/abseil-cpp#263]
Because abseil is using `list(FILTER ...` in its cmake files, the minimum required cmake version is actually **3.6** and not 3.1.

See
* https://cmake.org/cmake/help/v3.5/command/list.html
* https://cmake.org/cmake/help/v3.6/command/list.html
* https://github.com/abseil/abseil-cpp/blob/master/CMakeLists.txt#L19
* https://github.com/abseil/abseil-cpp/blob/master/CMake/AbseilHelpers.cmake#L94

**Comment by JonathanDCohen** [comment]
Sorry to just see this.  I would be hesitant to upgrade to cmake 3.6 given that, for example, Ubuntu 14.04 LTS still ships cmake 3.5 (https://packages.ubuntu.com/trusty/cmake3).  We can try toa ccomplish the same thing without using list(FILTER) though.  Thanks for the heads up!

**Comment by JonathanDCohen** [comment]
update: there is an internal fix for this out for review . Should be public in day or two at worst
