### ISSUE TITLE
Https Everywhere

### ISSUE THREAD

**Issue by OlafvdSpek** [abseil/abseil-cpp#265]
There are a lot of `http:` links in the Abseil files.. shouldn't these be `https:`?

**Comment by JonathanDCohen** [comment]
This is low priority but would be nice for a good first issue.  We want to make sure all the links can actually support https.

**Comment by SuchismitaDhal** [comment]
Hello @JonathanDCohen,
I am new to open source and would like to contribute to the project by making minor fixes. I have gone through the codebase. Can you help me with how to begin with this issue?

**Comment by derekmauro** [comment]
@SuchismitaDhal This issue is about as straightforward as it gets. Find all the non-HTTPS links in the codebase. Check to see if the site supports HTTPS, and if it does, replace the HTTP link with an HTTPS link.
