### ISSUE TITLE
internal raw_hash_set key access

### ISSUE THREAD

**Issue by greg7mdp** [abseil/abseil-cpp#267]
This is not really an issue, but maybe you can help me understand something. I'm working on a change which requires me to have access to the key in the insert function, but when I add the two lines shown below, the absl_flat_hash_set_test does not build anymore. 

I'd be super grateful if someone could tell me what mistake I am making.

![image](https://user-images.githubusercontent.com/1496907/53137781-1193cc80-3552-11e9-8ab5-ea2202dfae51.png)

Also, I am puzzled by the comment in this following code, looks to me like we always return the key by value?

```
  struct ReturnKey {
    // We return `Key` here.
    // When Key=T&, we forward the lvalue reference.
    // When Key=T, we return by value to avoid a dangling reference.
    // eg, for string_hash_map.
    template <class Key, class... Args>
    Key operator()(Key&& k, const Args&...) const {
      return std::forward<Key>(k);
    }
  };
```

**Comment by greg7mdp** [comment]
Never mind, I think I found a way to do what I needed to do, using `value_type &v = node.value();`.
Thanks!

**Comment by JonathanDCohen** [comment]
Hey there greg.  Is this still an issue or would you like to re close this?

**Comment by greg7mdp** [comment]
No, I'm all good, forgot I had reopened it, thanks Jonathan! 
I'm really impressed with the implementation, some of the best code I've seen, love how absl::raw_hash_map contains all the functionality.
