### ISSUE TITLE
absl::Span::first, absl::Span::last

### ISSUE THREAD

**Issue by girtsf** [abseil/abseil-cpp#272]
C++20 has `std::span::first` and `std::span::last`:
* https://en.cppreference.com/w/cpp/container/span/first
* https://en.cppreference.com/w/cpp/container/span/last

I've had couple cases already where those would have come in handy.

Would a PR that added those be welcome?

**Comment by derekmauro** [comment]
Hi - Yes we would welcome such a PR.
