### ISSUE TITLE
how to write a format "char * systle string" function

### ISSUE THREAD

**Issue by zhaojunmin387162** [abseil/abseil-cpp#282]
Now I would like to use abseil string-function to write a format char * systle string:
Any suggest:

void Example::AbortV(const char* char, const char* fmt, va_list ap) {
  std::string msg;
  ....
  abort(msg.c_str());
}

From //copy from absl/strings/internal/str_format/convert_test.cc 

void StrAppend(std::string *dst, const char *format, va_list ap) {
  // First try with a small fixed size buffer
  static const int kSpaceLength = 1024;
  char space[kSpaceLength];

  // It's possible for methods that use a va_list to invalidate
  // the data in it upon use.  The fix is to make a copy
  // of the structure before using it and use that copy instead.
  va_list backup_ap;
  va_copy(backup_ap, ap);
  int result = vsnprintf(space, kSpaceLength, format, backup_ap);
  va_end(backup_ap);
  if (result < kSpaceLength) {
    if (result >= 0) {
      // Normal case -- everything fit.
      dst->append(space, result);
      return;
    }
    if (result < 0) {
      // Just an error.
      return;
    }
  }

  // Increase the buffer size to the size requested by vsnprintf,
  // plus one for the closing \0.
  int length = result + 1;
  char *buf = new char[length];

  // Restore the va_list before we use it again
  va_copy(backup_ap, ap);
  result = vsnprintf(buf, length, format, backup_ap);
  va_end(backup_ap);

  if (result >= 0 && result < length) {
    // It fit
    dst->append(buf, result);
  }
  delete[] buf;
}

but it don't exported from abseil.

**Comment by derekmauro** [comment]
The function that uses stdarg-style variadic arguments is intentionally not part of our API. I'm not sure what you are trying to do, but I recommend looking at https://abseil.io/docs/cpp/guides/format.

**Comment by zhaojunmin387162** [comment]
> The function that uses stdarg-style variadic arguments is intentionally not part of our API. I'm not sure what you are trying to do, but I recommend looking at https://abseil.io/docs/cpp/guides/format.

Hi derekmauro:
Thanks for your reply!
Now we use abseil in a product. The existing code have some stdarg-style variadic argument.
