### ISSUE TITLE
Abseil-cpp broken on MacOS since cctz update

### ISSUE THREAD

**Issue by Mizux** [abseil/abseil-cpp#283]
since commit: https://github.com/abseil/abseil-cpp/commit/256be563447a315f2a7993ec669460ba475fa86a
(related to https://github.com/google/cctz/issues/96)

You added this implicit dependency ;)
https://github.com/abseil/abseil-cpp/blob/7c7754fb3ed9ffb57d35fe8658f3ba4d73a31e72/absl/time/internal/cctz/src/time_zone_lookup.cc#L24-L26
note: seems to come from https://github.com/opensource-apple/CF (no CMakeLists.txt available)

When we try to bump abseil-cpp from 93d155b -> 7c7754f in google/or-tools (to fix https://github.com/google/or-tools/issues/1138)
see: https://github.com/google/or-tools/commit/36a87b31ed60c3d0c6348bb72d70e6790727a6d0

the trace in Travis CI of google/or-tools build since the bump...
```sh
make ...
...
Undefined symbols for architecture x86_64:
  "_CFRelease", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetCStringPtr", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFStringGetSystemEncoding", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneCopySystem", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
  "_CFTimeZoneGetName", referenced from:
      absl::time_internal::cctz::local_time_zone() in libabsl_time_zone.a(time_zone_lookup.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libortools.dylib] Error 1
The command "./.travis/script.sh" exited with 2.
```
src: https://travis-ci.org/google/or-tools/builds/508323541?utm_source=github_status&utm_medium=notification

internally: https://critique.corp.google.com/#review/238061818

note: we use abseil-cpp custom CMake install rule (see https://github.com/google/or-tools/blob/master/patches/abseil-cpp-7c7754f.patch) in order to add it to our libortools.so which will be embedded in our native python library (everything in a Makefile based build, with slow migration to CMake based build).

note: I'll try to bump to a commit before 256be56 but after 93d155b (e.g. 88a152a seems a good candidate but I won't "Live at HEAD")

**Comment by derekmauro** [comment]
It looks like we got a PR for CMake https://github.com/abseil/abseil-cpp/pull/280 that I'm going to accept.

@shaindelschwartz - Can you look into whether the BUILD.bazel files need the same fix, and whether the fix belongs here or in google/cctz?

**Comment by Mizux** [comment]
My problem is we will have a libabsl_time_zone.a depending on a shared library (libCoreFoundation.dylib ?).
So my native python package now depends on libCoreFoundation.dylib which means our python user using our provided pipy package must install it (by installing xcode ?)...

**Comment by Mizux** [comment]
your fix should belonfg to cctz then abseil-cpp should bump to this version IMHO.

Note: you should also have CI to detect this issue in CCTZ and Abseil-cpp

**Comment by derekmauro** [comment]
> your fix should belonfg to cctz then abseil-cpp should bump to this version IMHO.

It's not so simple, Abseil imports CCTZ but may have seperate BUILD files for various reasons.


> My problem is we will have a libabsl_time_zone.a depending on a shared library (libCoreFoundation.dylib ?).
>So my native python package now depends on libCoreFoundation.dylib which means our python user using our provided pipy package must install it (by installing xcode ?)...

Are you saying the CCTZ change that introduced libCoreFoundation.dylib is problematic? If so we need to start that conversation with CCTZ now.

**Comment by Mizux** [comment]
> Are you saying the CCTZ change that introduced libCoreFoundation.dylib is problematic? If so we need to start that conversation with CCTZ now.

It may, but to check I would need:
* a fresh MacOS install without any xcode installed, as a user who just want to do some python dev **ONLY**.

Currently, I only have my gMac to build some release and Travis-CI but we use the cpp image with xcode installed since we start from C++ to generate the python package with SWIG.

I'll come back to this thread once I'll have further news...

**Comment by devjgm** [comment]
I was just looking into this issue w/ cctz. We're happy to fix this in whatever way you see fit. I'm happy even to revert this commit from cctz until we can figure out the right solution.

**Comment by Mizux** [comment]
FYI: 
```sh
%otool -L lib/libortools.dylib | grep CoreFoundation
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1555.10.0)
```
 So I guess CoreFoundation should be widely available...
