### ISSUE TITLE
Absl Target/Headers is installed when Absl is introduced as a subdirectory

### ISSUE THREAD

**Issue by fcharlie** [abseil/abseil-cpp#287]
One of the contents of commit [bf29470384a101b307873b26d358433138c857fc](https://github.com/abseil/abseil-cpp/commit/bf29470384a101b307873b26d358433138c857fc) is: Add install rules for Abseil CMake.

In this commit, the developer provides installation rules support for Absl and introduces the variable `ABSL_ENABLE_INSTALL`, but `ABSL_ENABLE_INSTALL` is used, which means that either Absl is built as a subdirectory or a top-level directory, all targets, header files Will be installed, which does not match expectations.

```cmake
# when absl is included as subproject (i.e. using add_subdirectory(abseil-cpp))
# in the source tree of a project that uses it, install rules are disabled.
if(NOT "^${CMAKE_SOURCE_DIR}$" STREQUAL "^${PROJECT_SOURCE_DIR}$")
  set(ABSL_ENABLE_INSTALL FALSE)
else()
  set(ABSL_ENABLE_INSTALL TRUE)
endif()

# install as a subdirectory only
install(EXPORT ${PROJECT_NAME}Targets
  NAMESPACE absl::
  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

configure_package_config_file(
  CMake/abslConfig.cmake.in
  "${PROJECT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
  INSTALL_DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(FILES "${PROJECT_BINARY_DIR}/${PROJECT_NAME}Config.cmake"
  DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(DIRECTORY absl
  DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
  FILES_MATCHING
    PATTERN "*.inc"
    PATTERN "*.h"
)
```

**Comment by JonathanDCohen** [comment]
I think you mean ABSL_ENABLE_INSTALL *isn't* used

Thankfully this doesn't actually install Abseil, it just makes the install rule available, so we aren't doing anything wrong unless the user asks for it.  I've written an internal patch to fix, thank you for the report :)

**Comment by bstaletic** [comment]
I'm not sure if I should report a separate issue, but I'm using Abseil with `add_subdirectory()` and as of the commit mentioned above I get the following warning:

```
CMake Warning at absail/CMakeLists.txt:91 (message):
  The default and system-level install directories are unsupported except in
  LTS releases of Abseil.  Please set CMAKE_INSTALL_PREFIX to install Abseil
  in your source or build tree directly.
```

Yet I don't want to "install" either abseil or my project. I just need it compiled.

**Comment by fcharlie** [comment]
@bstaletic This is the same problem. 

@JonathanDCohen Currently Absl is compiled as a statically linked library, but when people run make install, libabsl_*.a will still be installed anyway. 

see: [https://github.com/abseil/abseil-cpp/blob/5b65c4af5107176555b23a638e5947686410ac1f/CMake/AbseilHelpers.cmake#L158-L165](https://github.com/abseil/abseil-cpp/blob/5b65c4af5107176555b23a638e5947686410ac1f/CMake/AbseilHelpers.cmake#L158-L165)
