### ISSUE TITLE
iterator_tag is a type not a value

### ISSUE THREAD

**Issue by cdyson37** [abseil/abseil-cpp#29]
I haven't tested (sorry!) but it looks like the iterator_tag should have ()s of {}s after it? It's a type not a value. If I'm right this also suggests this function isn't being exercised. Sorry if I've misread!

https://github.com/abseil/abseil-cpp/blob/962e9931d546cd6f062894e15283cea02c7d3220/absl/strings/internal/str_join_internal.h#L245

**Comment by tituswinters** [comment]
iterator_tag is a value of type std::iterator_traits<Iterator>::iterator_category (the typename on the previous line is to disambiguate the nested type references, not to identify that iterator_tag is a type).

**Comment by cdyson37** [comment]
Ugh I misread typename for typedef! Never mind me.

**Comment by tituswinters** [comment]
No worries. Generics aren't particularly reader-friendly anyway. :)
