### ISSUE TITLE
Useless checks in raw_hash_set_test.cc

### ISSUE THREAD

**Issue by greg7mdp** [abseil/abseil-cpp#290]
Why all these setting and checking the max_load_factor() in raw_hash_set_test.cc, when the set function is a no-op and the get function returns a constant?

```
    StringTable t;
    t.max_load_factor(.321f);
    const float lf = t.max_load_factor();
    ...
    EXPECT_EQ(lf, u.max_load_factor());
```

and the implementation is:

```
  float max_load_factor() const { return 1.0f; }
  void max_load_factor(float) {
    // Does nothing.
  }
```

**Comment by shaindelschwartz** [comment]
This seems like a legacy thing from when load_factor could actually be set. We probably could remove them.
