### ISSUE TITLE
How to check a thread own a mutex?

### ISSUE THREAD

**Issue by zhaojunmin387162** [abseil/abseil-cpp#292]
Now we are using absel Mutex in our project.  I need to check if a thread own the mutex.
How to implement the functions? any suggestion?

Thanks very much

**Comment by derekmauro** [comment]
We don't provide a way to do this and I'm not aware of a good reason to need to do it. What are you really trying to do?

**Comment by zhaojunmin387162** [comment]
> We don't provide a way to do this and I'm not aware of a good reason to need to do it. What are you really trying to do?

Hi derekmauro:
We need to check if the thread own the mutex to avoid the deadlock. if the thread have own the mutex, we won't will call some function.

Thanks!

**Comment by derekmauro** [comment]
> > We don't provide a way to do this and I'm not aware of a good reason to need to do it. What are you really trying to do?
> 
> Hi derekmauro:
> We need to check if the thread own the mutex to avoid the deadlock. if the thread have own the mutex, we won't will call some function.
> 
> Thanks!

I understand that sometimes people think they need to do that, but that pattern is usually a sign of a problematic design, so I need more details to understand or give advice. Recall that the primary purpose of a mutex is to guard an invariant. If the flow of your program is written in such a way that at some point you don't know if the mutex is already held in the current thread, I'd question whether the mutex is being used for the proper purpose.
