### ISSUE TITLE
[CMAKE] windows integration failure

### ISSUE THREAD

**Issue by Mizux** [abseil/abseil-cpp#293]
# Description
Since commit on
https://github.com/abseil/abseil-cpp/blob/93dfcf74cb5fccae3da07897d8613ae6cab958a0/absl/copts/GENERATED_AbseilCopts.cmake#L206-L208
it just break my windows test ingration build on appveyor
project src: https://github.com/Mizux/cmake-abseil/tree/install

```sh
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\link.exe
/ERRORREPORT:QUEUE
 /OUT:"C:\projects\cmake-abseil\build\FooApp\Release\FooApp.exe"
 /INCREMENTAL:NO /NOLOGO /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\lib" /LIBPATH:"C:\Tools\vcpkg\installed\x64-windows\lib\manual-link"
 ..\Foo\Release\Foo.lib ..\dependencies\lib\absl_strings.lib [...]
 \ignore:4221
 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib "C:\Tools\vcpkg\installed\x64-windows\lib\*.lib"
 /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:"C:/projects/cmake-abseil/build/FooApp/Release/FooApp.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/projects/cmake-abseil/build/FooApp/Release/FooApp.lib" /MACHINE:X64  /machine:x64 FooApp.dir\Release\main.obj
LINK : fatal error LNK1181:
   cannot open input file '\ignore:4221.obj' [C:\projects\cmake-abseil\build\FooApp\FooApp.vcxproj]
Done Building Project "C:\projects\cmake-abseil\build\FooApp\FooApp.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\projects\cmake-abseil\build\ALL_BUILD.vcxproj" (default targets) -- FAILED.
Build FAILED.
```
src: https://ci.appveyor.com/project/Mizux/cmake-abseil/builds/23528461/job/jrp21qm2jcemx1bf#L185

Please notice the `\` instead of `/` before `ignore:4221`....

My guess:
you can see here:
https://github.com/abseil/abseil-cpp/blob/93dfcf74cb5fccae3da07897d8613ae6cab958a0/CMake/AbseilHelpers.cmake#L151-L155
that we will expose `/ignore:4221` -> explain why FooApp which is linking against few absl::libs get it...

the issue, IMHO, is `/` must be interpreted as path to a library so it is automatically replaced by `\` on windows -> linking error.

# Reference
* [`target_link_libraries()`](https://cmake.org/cmake/help/v3.13/command/target_link_libraries.html)
> The full path to the library file will be quoted/escaped for the shell automatically.

* @googlers come from CL/241222395 as **NOT** indicated in the description
> --
01a8bb5a8cb1e13e88ddb92f9c0160beb6e126be by Derek Mauro <dmauro@google.com>:
Update Clang on Kokoro to r356196.
This includes a workaround for a -Wgnu-include-next warning fixed by
https://reviews.llvm.org/rG0706e144d57305782988dd4367530ae04986116f
PiperOrigin-RevId: 241222395

* starting from CMake 3.13 you'll have [`target_link_options()`](https://cmake.org/cmake/help/v3.13/command/target_link_options.html)

* similar issue: https://github.com/conan-io/conan/issues/861

**Comment by wesleygriffin** [comment]
I can confirm this. This appears to be related to #277  

Here is an MWE: https://github.com/wesleygriffin/absl-msvc-link-flags

Basically, the /ignore:4221 gets added to the build.ninja file as a dependency which then causes ninja to fail:
~~~
>------ Build All started: Project: absl-msvc-link-flags, Configuration: x64-Debug (default) ------
C:\Users\WesleyGriffin\Active\ninja : error : '/ignore:4221', needed by 'case.exe', missing and no known rule to make it

Build All failed.
~~~

**Comment by wesleygriffin** [comment]
Here's a build.ninja snippet:
~~~
#############################################
# Link the executable case.exe

build case.exe: CXX_EXECUTABLE_LINKER__case CMakeFiles\case.dir\case.cpp.obj | abseil-build\absl\base\absl_absl_throw_delegate.lib abseil-build\absl\base\absl_absl_base.lib abseil-build\absl\base\absl_absl_dynamic_annotations.lib abseil-build\absl\base\absl_absl_spinlock_wait.lib \ignore$:4221 || abseil-build\absl\base\absl_absl_base.lib abseil-build\absl\base\absl_absl_dynamic_annotations.lib abseil-build\absl\base\absl_absl_spinlock_wait.lib abseil-build\absl\base\absl_absl_throw_delegate.lib
  FLAGS = /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /JMC
  LINK_FLAGS = /machine:x64 /debug /INCREMENTAL /subsystem:console
  LINK_LIBRARIES = abseil-build\absl\base\absl_absl_throw_delegate.lib abseil-build\absl\base\absl_absl_base.lib abseil-build\absl\base\absl_absl_dynamic_annotations.lib abseil-build\absl\base\absl_absl_spinlock_wait.lib \ignore:4221 kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib
  OBJECT_DIR = CMakeFiles\case.dir
  POST_BUILD = cmd.exe /C "cd /D "C:\Users\WesleyGriffin\CMakeBuilds\116863f0-ec87-c532-bddd-054e060e6611\build\x64-Debug (default)" && powershell -noprofile -executionpolicy Bypass -file C:/Users/WesleyGriffin/Active/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary "C:/Users/WesleyGriffin/CMakeBuilds/116863f0-ec87-c532-bddd-054e060e6611/build/x64-Debug (default)/case.exe" -installedDir C:/Users/WesleyGriffin/Active/vcpkg/installed/x64-windows/debug/bin -OutVariable out"
  PRE_LINK = cd .
  TARGET_COMPILE_PDB = CMakeFiles\case.dir\
  TARGET_FILE = case.exe
  TARGET_IMPLIB = case.lib
  TARGET_PDB = case.pdb
~~~

**Comment by JonathanDCohen** [comment]
If we use "-ignore" instead of "/ignore" does it work?

**Comment by Mizux** [comment]
@JonathanDCohen it may according to https://github.com/conan-io/conan/issues/861#issuecomment-277640034 not tested personally...

**Comment by wesleygriffin** [comment]
Yes that does fix the issue.

I cloned abseil, edited absl/copts/GENERATED_AbseilCopts.cmake and then pointed the MWE linked above to use that directory instead of fetching from github.

The MWE compiles completely and the build.ninja has "-ignore:4221" in it.

Thanks,
Wes

**Comment by fcharlie** [comment]
@JonathanDCohen  '-ignore' test OK. (Ninja OK, NMake OK)

**Comment by amirhoseeinkish** [comment]
در تاریخ جمعه ۵ آوریل ۲۰۱۹،‏ ۴:۳۹ Wesley Griffin <notifications@github.com>
نوشت:

**Comment by JonathanDCohen** [comment]
The fix should have been merged.  Can everyone please verify?  Our internal windows presubmits are undergoing reworking and I didn't want to wait on them to fix us at HEAD

**Comment by Mizux** [comment]
currently testing it through https://ci.appveyor.com/project/Mizux/cmake-abseil/builds/23633723/job/r3a67utj1y8weuvk
