### ISSUE TITLE
absl/time/duration_test.cc uses isnan/isinf from std namespace w/o qualifier, fails to build w/ gcc 5.4.0

### ISSUE THREAD

**Issue by vsrinivas** [abseil/abseil-cpp#3]
On Ubuntu 16.04, g++ 5.4.0, libstdc++6 5.4.0, //absl/time:time_test fails to build; duration_test.cc uses isnan and isinf from the std namespace (from cmath) without std:: qualification.

**Comment by derekmauro** [comment]
This should be fixed at HEAD.
