### ISSUE TITLE
badly constructed ABSL_ADDRESS_SANITIZER_REDZONE macro

### ISSUE THREAD

**Issue by sergeysablin** [abseil/abseil-cpp#310]
Hi guys, this macro requires semicolon after itself, and code path without sanitization has empty definition, which in the next code translates to compilation warning and with -Werror + -Wextra-semi throws an error:

```
abseil-cpp/absl/container/fixed_array.h:423:51: error: extra ';' inside a struct [-Werror,-Wextra-semi]
    ABSL_ADDRESS_SANITIZER_REDZONE(redzone_begin_);
                                                  ^
```

**Comment by rogeeff** [comment]
I believe this is addressed at HEAD. Feel free to reopen if you still observe this.
