### ISSUE TITLE
Typo in adding the leak_check_test test

### ISSUE THREAD

**Issue by stryku** [abseil/abseil-cpp#314]
Well, I'm not sure whether that's a real issue. I saw this while implementing cmakesl scripts for this repo.

While adding the `leak_check_test` test ([here](https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/CMakeLists.txt#L238)) `ABSL_DEFAULT_COPTS` is passed. Shouldn't it be `ABSL_TEST_COPTS`, like in other tests?

**Comment by EricWF** [comment]
Did you just notice the inconsistency or did it cause a problem?

I suspect you're right about it being an oversight.

**Comment by stryku** [comment]
No problems, I just noticed it.
