### ISSUE TITLE
Internal Compiler error MSVC 16.1.0

### ISSUE THREAD

**Issue by miscco** [abseil/abseil-cpp#317]
Using Visual Studio 2019 Professional 16.1.0 I get an internal compiler error in the following test

```cpp
TEST(optionalTest, ValueOr) {
  absl::optional<double> opt_empty, opt_set = 1.2;
  EXPECT_EQ(42.0, opt_empty.value_or(42));
  EXPECT_EQ(1.2, opt_set.value_or(42));
  EXPECT_EQ(42.0, absl::optional<double>().value_or(42));
  EXPECT_EQ(1.2, absl::optional<double>(1.2).value_or(42));

  constexpr absl::optional<double> copt_empty, copt_set = {1.2};
  static_assert(42.0 == copt_empty.value_or(42), "");
  static_assert(1.2 == copt_set.value_or(42), "");
#ifndef ABSL_SKIP_OVERLOAD_TEST_DUE_TO_MSVC_BUG
  using COD = const absl::optional<double>;
  static_assert(42.0 == COD().value_or(42), "");
  static_assert(1.2 == COD(1.2).value_or(42), "");
#endif
}
```

More specifically the offending line is:
```cpp
  constexpr absl::optional<double> copt_empty, copt_set = {1.2};
```

The link I got from Visual Studio wanted to sell me some support plan so I am kind of unwilling to spend much more time registering it with them.

**Comment by EricWF** [comment]
Could you please post the full output produced by the compiler (ideally the verbose output).

**Comment by miscco** [comment]
Dear @EricWF sorry for the terse issue. I went to bed and didnt find time until now. So the First thing to note is that I build in `Debug-x64`. 

Before I came to the test I had to add `/bigobj` to `/absl/container/CMakeLists.txt` and `absl/hash/CMakeLists.txt` for the tests `flat_hash_map_test.cc` and `hash_test.cc`. I dont know whether this is with respect to Debug mode or not but yeah.

The actual error comes from `optional_test.cc` Here is the output with `/verbosity`. I appoligize in advance for the horrible readability

>   [11/114] C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1421~1.277\bin\HostX64\x64\cl.exe  /nologo /TP -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I..\..\..\ -Igoogletest-src\googlemock\include -Igoogletest-src\googlemock -Igoogletest-src\googletest\include -Igoogletest-src\googletest /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /ZI /Ob0 /Od /RTC1 /JMC   /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /wd4018 /wd4101 /wd4996 /U_HAS_EXCEPTIONS /D_HAS_EXCEPTIONS=1 /EHsc /showIncludes /Foabsl\types\CMakeFiles\absl_optional_test.dir\optional_test.cc.obj /Fdabsl\types\CMakeFiles\absl_optional_test.dir\ /FS -c ..\..\..\absl\types\optional_test.cc

>  FAILED: absl/types/CMakeFiles/absl_optional_test.dir/optional_test.cc.obj 
  C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1421~1.277\bin\HostX64\x64\cl.exe  /nologo /TP -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I..\..\..\ -Igoogletest-src\googlemock\include -Igoogletest-src\googlemock -Igoogletest-src\googletest\include -Igoogletest-src\googletest /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /ZI /Ob0 /Od /RTC1 /JMC   /W3 /DNOMINMAX /DWIN32_LEAN_AND_MEAN /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS /D_ENABLE_EXTENDED_ALIGNED_STORAGE /wd4005 /wd4068 /wd4180 /wd4244 /wd4267 /wd4503 /wd4800 /wd4018 /wd4101 /wd4996 /U_HAS_EXCEPTIONS /D_HAS_EXCEPTIONS=1 /EHsc /showIncludes /Foabsl\types\CMakeFiles\absl_optional_test.dir\optional_test.cc.obj /Fdabsl\types\CMakeFiles\absl_optional_test.dir\ /FS -c ..\..\..\absl\types\optional_test.cc

>  Note: including file: C:\Users\msche\Documents\workspace\abseil\absl/types/optional.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/base/config.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\limits.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\sal.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\concurrencysal.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vadefs.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cstddef
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stddef.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xtr1common
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\yvals_core.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\crtdefs.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xkeycheck.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\absl/base/policy_checks.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/utility/utility.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cstdlib
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\math.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_math.h
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdlib.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_malloc.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_search.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wstdlib.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\tuple
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\new
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\exception
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\yvals.h
  Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\crtdbg.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime_new_debug.h
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime_new.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\use_ansi.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\type_traits
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xstddef
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\initializer_list
  Note: including file:      C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\malloc.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime_exception.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\eh.h
  Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_terminate.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xutility
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\climits
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cstring
  Note: including file:      C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\string.h
  Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_memory.h
  Note: including file:        C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_memcpy_s.h
  Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\errno.h
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime_string.h
  Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wstring.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\utility
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\absl/base/internal/inline_variable.h
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\absl/base/internal/identity.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\absl/base/internal/invoke.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\algorithm
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xmemory
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xmemory0
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cstdint
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\stdint.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\limits
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cfloat
  Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\float.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cwchar
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cstdio
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\stdio.h
  Note: including file:           C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wstdio.h
  Note: including file:            C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_stdio_config.h
  Note: including file:         C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\wchar.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wconio.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wctype.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wdirect.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wio.h
  Note: including file:           C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_share.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wprocess.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_wtime.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\sys/stat.h
  Note: including file:           C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\sys/types.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xatomic.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\intrin0.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\absl/meta/type_traits.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\functional
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\typeinfo
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vcruntime_typeinfo.h
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cassert
  Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/base/attributes.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/types/bad_optional_access.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\stdexcept
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xstring
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\iosfwd
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/types/internal/optional.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\absl/memory/memory.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\memory
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\absl/base/macros.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cassert
  Note: including file:      C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
  Note: including file:     C:\Users\msche\Documents\workspace\abseil\absl/base/optimization.h
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\intrin.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\setjmp.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\immintrin.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\wmmintrin.h
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\nmmintrin.h
  Note: including file:          C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\smmintrin.h
  Note: including file:           C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\tmmintrin.h
  Note: including file:            C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\pmmintrin.h
  Note: including file:             C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\emmintrin.h
  Note: including file:              C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xmmintrin.h
  Note: including file:               C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\mmintrin.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\zmmintrin.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\ammintrin.h
  Note: including file:     C:\Users\msche\Documents\workspace\abseil\absl/base/port.h
  Note: including file: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\string
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cctype
  Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\ctype.h
  Note: including file: C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest.h
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\ostream
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\ios
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xlocnum
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cmath
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xtgmath.h
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\streambuf
  Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xiosbase
  Note: including file:       C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\share.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\system_error
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cerrno
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xcall_once.h
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xerrc.h
  Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xlocale
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xfacet
  Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xlocinfo
  Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xlocinfo.h
  Note: including file:          C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\locale.h
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\vector
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-internal.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-port.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\iostream
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\istream
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\sstream
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-port-arch.h
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/custom/gtest-port.h
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\direct.h
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\io.h
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\corecrt_io.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\iomanip
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xlocmon
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xloctime
  Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\ctime
  Note: including file:      C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\time.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\map
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\xtree
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\set
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-message.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-filepath.h
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-string.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-type-util.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-death-test.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-death-test-internal.h
  Note: including file:    C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-matchers.h
  Note: including file:     C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-printers.h
  Note: including file:      C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/custom/gtest-printers.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-param-test.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/internal/gtest-param-util.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cassert
  Note: including file:     C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
  Note: including file:    C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\iterator
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest_prod.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-test-part.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest-typed-test.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest_pred_impl.h
  Note: including file:   C:\Users\msche\Documents\workspace\abseil\out\build\x64-Debug\googletest-src\googletest\include\gtest/gtest.h
  Note: including file: C:\Users\msche\Documents\workspace\abseil\absl/base/internal/raw_logging.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/base/internal/atomic_hook.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\atomic
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cassert
  Note: including file:    C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/base/log_severity.h
  Note: including file:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\array
  Note: including file: C:\Users\msche\Documents\workspace\abseil\absl/strings/string_view.h
  Note: including file:  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.21.27702\include\cassert
  Note: including file:   C:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt\assert.h
  Note: including file:  C:\Users\msche\Documents\workspace\abseil\absl/base/internal/throw_delegate.h

> C:\Users\msche\Documents\workspace\abseil\absl\types\optional_test.cc(1112): fatal error C1001: An internal error has occurred in the compiler.
  (compiler file 'msc1.cpp', line 1533)
   To work around this problem, try simplifying or changing the program near the locations listed above.
  Please choose the Technical Support command on the Visual C++ 
   Help menu, or open the Technical Support help file for more information
  Internal Compiler Error in C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1421~1.277\bin\HostX64\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.
  INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~1\2019\PROFES~1\VC\Tools\MSVC\1421~1.277\bin\HostX64\x64\cl.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
  ninja: build stopped: subcommand failed.

**Comment by zhangxy988** [comment]
This should be fixed in https://github.com/abseil/abseil-cpp/commit/502efe6d7841bff82b1aeef5500491fe9a48c635.
