### ISSUE TITLE
absl is leaking symbols into global namespace

### ISSUE THREAD

**Issue by skgbanga** [abseil/abseil-cpp#318]
Consider the following code:

```cpp
#include <cmath>           
#include <iostream>        

int main() {               
  std::cout << abs(1.5) << std::endl;                 
} 
```

This code compiles, and produces `1` as the output due to `abs` in C not having a double overload: https://en.cppreference.com/w/c/numeric/math/abs

However, consider the following code now:

```cpp
#include "absl/container/flat_hash_map.h"             

#include <cmath>           
#include <iostream>        

int main() {               
  std::cout << abs(1.5) << std::endl;                 
}      
```

The only difference is addition of include line. This code produces the output as `1.5` because it finds C++ `std::abs` now.  https://en.cppreference.com/w/cpp/numeric/math/abs

This makes me believe that absl is doing a `using` declaration somewhere in a header file.

**Comment by EricWF** [comment]
C++ does have a `::abs(double)` overload. C++ STL adds additional overloads for math functions at the global scope as well as in namespace `std`. In your case, which appears to use libstdc++, the `::abs(double)` overload is defined in `<stdlib.h>`.

The C++ standard library is also allowed to include `<stdlib.h>` from `<cmath>` or any other header it chooses. Meaning the original code is allowed to print either `1` or `1.5`.

Abseil isn't involved here.

**Comment by skgbanga** [comment]
Thanks @EricWF for the answer!  like you said, this can be easily reproduced with `stdlib.h` only. 

```cpp
#include <cmath>
#include <iostream>

#include <stdlib.h>  # this has the ::abs(double) overload

int main() {
  std::cout << abs(1.5) << std::endl;
}
```
