### ISSUE TITLE
Intel Compiler 2019 crash and build problems

### ISSUE THREAD

**Issue by ojura** [abseil/abseil-cpp#322]
I have stumbled upon a bug with the Intel compiler, edition 2019 (Windows) and Abseil. The compiler fails with the following when attempting to instantiate a `flat_hash_map` or a `flat_hash_set`:

`assertion failed at: "shared/cfe/edgcpfe/lower_init.c", line 7013 

This is 

There are also static asserts failures related to `std::is_trivially_assignable`/`copyable`. Would appreciate a bringup (especially of `flat_hash_map`/`set`) with ICC.

**Comment by ojura** [comment]
Here is a snippet of the failed static assert:
`...build_intel\_deps\abseil-src\absl/meta/type_traits.h(441): error : static assertion failed with "Not compliant with std::is_trivially_copy_assignable; Standard: true, Implementation: false"
34>    static_assert(compliant || !std::is_trivially_copy_assignable<T>::value,
34>    ^
34>          detected during:
34>            instantiation of class "absl::is_trivially_copy_assignable<T> [with T=double]" at line 175 of "..build_intel\_deps\abseil-src\absl/types/internal/optional.h"
34>            processing of template argument list for "absl::optional_internal::optional_data" based on template argument <double> at line 116 of "...build_intel\_deps\abseil-src\absl/types/optional.h"`

**Comment by derekmauro** [comment]
https://abseil.io/docs/cpp/platforms/platforms

We don't support the Intel compiler. Sorry about this.
