### ISSUE TITLE
Foundation framework link option leaking into Android builds

### ISSUE THREAD

**Issue by goaway** [abseil/abseil-cpp#326]
We have a project that builds a native library for Android that depends on Abseil. With this change:
https://github.com/abseil/abseil-cpp/commit/ca3f87560a0eef716195cadf66dc6b938a579ec6#diff-020a0864e5179d94daa487a30519b6acR79
our builds broke when performed on MacOS with the following error:
```
Execution platform: @bazel_tools//platforms:host_platform
external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find Foundation: No such file or dir
ectory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
We suspect we may somehow be specifying crosstool options or the target platform incorrectly, but what's surprising is up until this point everything worked. (We're actually not specifying these options at all explicitly, but rather relying on transitions built into the `android_binary` rule.)

Although Abseil may very well be doing the right thing here, we wanted to reach out to see if anyone was willing and able to provide us some guidance. This may be as much a Bazel question as it is an Abseil question, and we're following up with Bazel folks as well.

If this falls outside the scope of the support issues in this project, feel free to close.

Thanks!

**Comment by goaway** [comment]
Based on discussion we've had with @jin and other helpful Bazel experts, it sounds like this is an issue with the current native Android build rules not supporting platform toolchains correctly. We're working around this locally by patching out the Foundation dependency in Abseil, since we currently don't rely on cctz.

**Comment by DarkDimius** [comment]
Note that this is very similar to #308 that also affected us on webasm, we had to build a workaround into our toolchain https://github.com/sorbet/sorbet/pull/516

**Comment by jdduke** [comment]
This is also impacting TensorFlow builds (see https://github.com/tensorflow/tensorflow/issues/31190).

**Comment by yyoon** [comment]
Also reported at tensorflow/tensorflow#29731, which is temporarily fixed by applying a local patch as a workaround (tensorflow/tensorflow@04e169a).

**Comment by hevrard** [comment]
This issue is preventing AGI (https://github.com/google/agi) to update to a newer version of gRPC. See https://github.com/google/agi/pull/310#issuecomment-636790512

**Comment by alyssawilk** [comment]
as commented here (https://github.com/google/cctz/pull/237#discussion_r1012300583) we're going to remove the explicit Foundation dep in favor of an implicit one as it should fix these build issues and not regress https://github.com/abseil/abseil-cpp/issues/291

**Comment by junyer** [comment]
FYI, this breaks anything using `BAZEL_USE_CPP_ONLY_TOOLCHAIN`. Ask me how I know. ;)

**Comment by alyssawilk** [comment]
If we have to revert, Envoy can carry the "remove foundation" patch :-(

**Comment by junyer** [comment]
Oh, no, we ended up fixing our GitHub Actions workflows to not use that anymore. (My apologies for not following up earlier!)

**Comment by jpsim** [comment]
I believe this can be closed now that the cctz change was imported in 4a98f786820f72ff7483c46d14fe85f3310f1272
