### ISSUE TITLE
CMake/README.md should suggest using CMAKE_CXX_STANDARD instead of CMAKE_CXX_FLAGS to set the C++ version

### ISSUE THREAD

**Issue by dandrino** [abseil/abseil-cpp#332]
In `CMake/README.md`, there is this line in the sample `CMakeLists.txt` file:

```
set(CMAKE_CXX_FLAGS "-std=c++11 -stdlib=libc++ ${CMAKE_CXX_FLAGS}")
```

The implication here is that if I want to compile with c++17, all I need to do is replace `-std=c++11` with `-std=c++17`. This will successfully compile your binary w/ c++17 (`source.cpp` in the example), but it will still compile `abseil-cpp` with c++11 (or whatever cmake defaults to). The end result is that `absl::string_view` aliases to `std::string_view` from your source file includes, but the abseil-cpp libraries internally compile with abseil's version of `absl::string_view`. This can completely break many of the `absl/strings` libraries on certain platforms rendering them completely unusable (e.g. if the pointer & length members are in a different order).

For instance, running the following:
```bash
git clone https://github.com/abseil/abseil-cpp.git

cat << EOF > CMakeLists.txt
cmake_minimum_required(VERSION 2.8.12)
project(my_project)

set(CMAKE_CXX_FLAGS "-std=c++17 \${CMAKE_CXX_FLAGS}")
add_subdirectory(abseil-cpp)

add_executable(my_exe source.cpp)
target_link_libraries(my_exe absl::strings)
EOF

cat << EOF > source.cpp
#include "absl/strings/str_cat.h"

int main() {
  (void)absl::StrCat("foo", "bar");
  return 0;
}
EOF

cmake . && make -j && ./my_exe
```

Will spit out the following in Ubuntu (`Linux dandrino-ubuntu-1 5.0.0-16-generic #17-Ubuntu SMP Wed May 15 10:52:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`) using g++ (`g++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0`)

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

If I replace `set(CMAKE_CXX_FLAGS "-std=c++17 \${CMAKE_CXX_FLAGS}")` with `set(CMAKE_CXX_STANDARD, 17)`, it compiles and runs successfully.

`CMake/README.md` should be more clear about this potential pitfall.

**Comment by derekmauro** [comment]
Agreed. I will make this change.
