### ISSUE TITLE
UBSan violation in InlineVector when NDEBUG isn't defined

### ISSUE THREAD

**Issue by DarkDimius** [abseil/abseil-cpp#337]
```
    absl::inlined_vector<int, 2> foo;
    absl::inlined_vector<int, 2> bar{1,2,3};
    foo = bar;
```

leads to
```
external/com_google_absl/absl/container/internal/inlined_vector.h:61:15: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:62:62: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior external/com_google_absl/absl/container/internal/inlined_vector.h:61:15 in
```

More specifically, 
https://github.com/abseil/abseil-cpp/blob/e9324d926a9189e222741fce6e676f0944661a72/absl/container/internal/inlined_vector.h#L47
gets called with 
```
alloc_ptr = <some address>, 
destroy_first = nullptr,
destroy_size = 0
```

leading to call to memset with `nullptr` as starting address in 

https://github.com/abseil/abseil-cpp/blob/e9324d926a9189e222741fce6e676f0944661a72/absl/container/internal/inlined_vector.h#L61

**Comment by CJ-Johnson** [comment]
Thank you so much for the bug report!

I just made a change to address this and you should see it upstreamed to public Abseil shortly.
