### ISSUE TITLE
class absl::string_view {aka class absl::string_view}’ has no member named ‘ToString’

### ISSUE THREAD

**Issue by tangjie77wd** [abseil/abseil-cpp#345]
Here is my few code:

`
tensorflow::StringPiece data;

  TF_RETURN_IF_ERROR(file->Read(0, file_size, &data, &(contents)[0]));

  if (data.size() != file_size) {

    return tensorflow::errors::DataLoss("Truncated read of '", filename,

                                        "' expected ", file_size, " got ",

                                        data.size());

  }

  output->scalar<string>()() = data.ToString();
`

as you see, error comes :

`
../src/tf.cpp:55:37: error: ‘using StringPiece = class absl::string_view {aka class absl::string_view}’ has no member named ‘ToString’
   output->scalar<string>()() = data.ToString();
                                     ^
../src/tf.cpp: In function ‘tensorflow::Status ReadTensorFromImageFile(const string&, int, int, float, float, std::vector<tensorflow::Tensor>*)’:
../src/tf.cpp:86:42: error: ‘using StringPiece = class absl::string_view {aka class absl::string_view}’ has no member named ‘ends_with’
   if (tensorflow::StringPiece(file_name).ends_with(".png")) {
                                          ^
../src/tf.cpp:89:49: error: ‘using StringPiece = class absl::string_view {aka class absl::string_view}’ has no member named ‘ends_with’
   } else if (tensorflow::StringPiece(file_name).ends_with(".gif")) {
                                                 ^
../src/tf.cpp:94:49: error: ‘using StringPiece = class absl::string_view {aka class absl::string_view}’ has no member named ‘ends_with’
   } else if (tensorflow::StringPiece(file_name).ends_with(".bmp")) {
                                                 ^
../src/tf.cpp: In function ‘int main(int, char**)’:
../src/tf.cpp:189:7: warning: unused variable ‘ndim2’ [-Wunused-variable]
   int ndim2 = t.shape().dims();             // Get the dimension of the tensor
       ^
make: *** [src/tf.o] Error 1
src/subdir.mk:32: recipe for target 'src/tf.o' failed
`

I do not know what has replaced 'ToString()' .

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/blob/72e09a54d993b192db32be14c65adf7e9bd08c31/absl/strings/string_view.h#L336-L341

This means that the following code can convert from `absl::string_view` to `std::string`:
```
absl::string_view foo = "foo";
std::string foo_string = std::string(foo);
```

**Comment by tangjie77wd** [comment]
Yes，I have solved this issue yesterday by replacing 'tensorflow::StringPiece data;  ... output->scalar<string>()() = data.ToString(); ' with 'tensorflow::StringPiece data;  ... output->scalar<string>()() = string(data); ' .
