### ISSUE TITLE
Can absl::StrJoin() be augmented to accept a container without second argument to concatenate all items?

### ISSUE THREAD

**Issue by yzhao1012** [abseil/abseil-cpp#349]
It's basically a default argument for absl::StrJoin() to make the below works:
std::vector<std::string> strs = {...};
std::string text = absl::StrJoin(strs);
// Now I have to write std::string text = absl::StrJoin(strs, "");
// Which seems annoying.

**Comment by derekmauro** [comment]
It might work on the overload that takes a range as the only other parameter, but I suspect it would break the overload resolution if we tried to add overloads of some of the other `absl::StrJoin` variants. From a quick search I did, it also actually seems pretty rare to use the empty string as the separator. I've never heard anyone else complain that the extra parameter is annoying either. For these reasons, I think the explicit `""` is better, and I'd say no, we aren't going to be adding this.
