### ISSUE TITLE
Would locking_ptr be a useful addition?

### ISSUE THREAD

**Issue by mlimber** [abseil/abseil-cpp#35]
Something like [Loki/Alexandrescu's LockingPtr.h](http://loki-lib.cvs.sourceforge.net/loki-lib/loki/include/loki/LockingPtr.h?view=markup) (sans the `volatile` bits) with additional helpers like a `mutexed` class that wraps a value with a mutex and a `Lock()` function that returns a `locking_ptr` so you get functionality like:
```cpp
struct X { int i; double d; };
abslEx::mutexed<X> x;

// ...
// assert( x.i == 42 ); // Fails to compile because x is not locked

// Lock for a single statement
assert( abslEx::Lock( x )->i == 42 ); // Ok

// Use for multiple statements
const auto locked = abslEx::Lock( x );
assert( locked->i == 42 );
std::cout << locked->i << " " << locked->d;
```
Advantages of this approach are a more RAII-style that is harder to misuse (forget to lock/unlock). I prefer this over the sort of macro annotation style of the current Abseil synchronization primitives, but I'm open to being convinced otherwise.

I'd be willing to work on this, but I'm not sure how open Abseil is to accepting contributions of this sort.

**Comment by derekmauro** [comment]
As you mentioned, we already support annotations that can be checked at compile time for missing synchronization:

https://github.com/abseil/abseil-cpp/blob/master/absl/base/thread_annotations.h
https://clang.llvm.org/docs/ThreadSafetyAnalysis.html

In addition, the bar to getting something new included in Abseil is very high. If you read [our philosophy](https://abseil.io/about/philosophy), everything in our library in widely used at Google. Every additional feature has a maintenance cost and imposes constraints on future changes. Maybe it is surprising, but we've never found the need for anything like this. If that changes, we can reconsider, but aren't accepting features we have no experience with.

**Comment by tituswinters** [comment]
Additionally - I fundamentally mistrust the synchronized/locking_ptr/mutexed design.  It makes it very easy to write that code, but also hides away the synchronization in (innocuous looking) calls.  I have a suspicion (based on nothing concrete) that use of a type like that will make code harder to read and review (and harder to identify potential deadlocks in more complex cases).
