### ISSUE TITLE
Windows MSVC compilation error of constexpr absl::string_view asv{"literal"}

### ISSUE THREAD

**Issue by wrowe** [abseil/abseil-cpp#352]
We are encountering issues compiling building envoy with the following output;
```
ERROR: C:/workspace/envoy/source/extensions/transport_sockets/tls/BUILD:26:1: C++ compilation of rule '//source/extensions/transport_sockets/tls:ssl_socket_lib' failed (Exit 2)
source/extensions/transport_sockets/tls/ssl_socket.cc(32): error C2131: expression did not evaluate to a constant
C:\_eb\execroot\envoy\external\com_google_absl\absl/strings/string_view.h(186): note: failure was caused by call of undefined function or one not declared 'constexpr'
C:\_eb\execroot\envoy\external\com_google_absl\absl/strings/string_view.h(186): note: see usage of 'strlen'
```
The offending line is simply;
```
constexpr absl::string_view NotReadyReason{"TLS error: Secret is not supplied by SDS"};
```

Our initial ticket was filed on the Envoy project;
https://github.com/envoyproxy/envoy/issues/7357

The environment consists of Visual Studio 2017, at MSBuild rev 15.9, using the ucrt rev 10.0.17134.0 compiling with MSVC cl.exe rev 19.16.27031.1 in debug mode, using the abesil-cpp 
repo at commit 61c9bf3e3e1c28a4aa6d7f1be4b37fd473bb5529 of 2019-06-05.

It sounded like something similar was asked and answered, but we are using very current abseil code, and this looks resolved some 9 mos ago;
https://github.com/abseil/abseil-cpp/issues/161

The root bug appeared to be related to the following ticket, which then claims that MSBuild rev 15.7 resolves this constexpr constructor defect;
https://developercommunity.visualstudio.com/content/problem/181276/cant-construct-constexpr-string-view-from-string-l.html

We then discovered a report of varying behavior in debug mode, observed here?
https://github.com/abseil/abseil-cpp/issues/304

This is a blocking issue, guidance is appreciated.

**Comment by derekmauro** [comment]
I *think* it should be possible to fix this on our side for MSVC 2017 or higher by implementing our own constexpr `strlen()` that the `string_view` constructor can use.

**Comment by achasveachas** [comment]
Awesome! We'll be looking out for it!
