### ISSUE TITLE
question about http_archive

### ISSUE THREAD

**Issue by kosuke55** [abseil/abseil-cpp#353]
Hi, I am troubled not knowing how to use http_archive.
How can I get urls, strip_prefix, sha256 ?
```
http_archive(
     name = "com_google_googletest",
     urls = ["https://github.com/google/googletest/archive/b6cd405286ed8635ece71c72f118e659f4ade3fb.zip"],  # 2019-01-07
     strip_prefix = "googletest-b6cd405286ed8635ece71c72f118e659f4ade3fb",
     sha256 = "ff7a82736e158c077e76188232eac77913a15dac0b22508c390ab3f88e6d6d86",
)
```

**Comment by derekmauro** [comment]
The Bazel documentation is here: https://docs.bazel.build/versions/master/repo/http.html#http_archive

If you still have questions, please ask on a Bazel-specific forum.
