### ISSUE TITLE
Abseil's `node_hash_set` must throw when `at` doesn't find a key.

### ISSUE THREAD

**Issue by adamlsd** [abseil/abseil-cpp#355]
https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/raw_hash_map.h#L136-L148

These implementations of `at` will call `std::abort` instead of throwing `std::out_of_range`.

**Comment by adamlsd** [comment]
Stable code link:

https://github.com/abseil/abseil-cpp/blob/36d37ab992038f52276ca66b9da80c1cf0f57dc2/absl/container/internal/raw_hash_map.h#L136-L148

**Comment by acmorrow** [comment]
@derekmauro - Thank you very much for the quick fix. I do have one small comment on how the commit was landed. Because it was fused with another commit, we can't cherry-pick just the fix for the `at` issue into our vendored abseil copy without picking up an unrelated change to `string_view`.
