### ISSUE TITLE
Flags should support main.cc as a main filename

### ISSUE THREAD

**Issue by refi64** [abseil/abseil-cpp#358]
Right now in order for help to display correctly, the filename must be named `<program>.cc`, `<program>_main.cc`, or `<program>-main.cc`. However, simply `main.cc` is not supported. Could this be added?

**Comment by derekmauro** [comment]
This is configurable. It's an advanced feature, but see https://github.com/abseil/abseil-cpp/blob/master/absl/flags/usage_config.h.

**Comment by refi64** [comment]
Ah sorry, didn't realize that, IMO main.cc would still be a nice default but this works too.
