### ISSUE TITLE
git commit messages missing a blank line after line 1.

### ISSUE THREAD

**Issue by BillyDonahue** [abseil/abseil-cpp#361]
When the Copybara (I guess?) batch updates are pushed, the commit messages are missing a blank line after the summary line.

```
$ git log --oneline -1 origin/master
14550be (origin/master) Export of internal Abseil changes. -- 8f685654a7d04eb8a0cb82d31e44e391e906b609 by Derek Mauro <dmauro@google.com>:
```

This should just be "Export of internal Abseil changes."
The extra `-- 8f68565... by Derek Mauro <dmauro@google.com>:` was accidental. It partially describes the first of two subsumed internal patches in the commit.

This is much worse with the LTS branches, which produce a single >9kB line of catenated commit messages.

This should have just printed `Creation of LTS branch "lts_2018_12_18"`, but we get 9kB of stuff instead, because of the missing blank line:

```
$ git log --oneline -1 remotes/origin/lts_2018_12_18
fcb1045 (tag: 20181200, origin/lts_2018_12_18, mongodb-forks/lts_2018_12_18) Creation of LTS branch "lts_2018_12_18"   - 44b0fafc62d9b8f192e8180cbe9c4b806b339d57 Export of internal Abseil changes. by Abseil Team <absl-team@google.com>   - 926bfeb9fff223429c12224b7514243886323e8d Export of internal Abseil changes. by Abseil Team <absl-team@google.com>   - 13327debebc5c2d1d4991b69fe50450e340e50e4 Export of internal Abseil changes. by Abseil Team <absl-team@google.com> ...etc
```

This means that the output of `$ git branch -av` is extremely noisy.

**Comment by derekmauro** [comment]
Should be fixed for new commits.
