### ISSUE TITLE
Abseil fails to compile on ARM with CMake, because it forces x86_64 flags

### ISSUE THREAD

**Issue by lilianmoraru** [abseil/abseil-cpp#365]
`absl/copts/AbseilConfigureCopts.cmake` checks for GCC `"${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU"` and then forcibly adds `msse`: `set(ABSL_RANDOM_RANDEN_COPTS "${ABSL_RANDOM_HWAES_X64_FLAGS}")`, even though it does not compile on x86_64.
That last line adds this:
```
list(APPEND ABSL_RANDOM_HWAES_X64_FLAGS
    "-maes"
    "-msse4.1"
)
```

Note that the ARM flags(from the generated file with compiler flags) also makes some assumptions.
`-mfpu=neon` is buggy with the version of the compiler we have and the hardware we run the software on.

**Comment by pizzard** [comment]
Same issue here. 
The build system just checks fur GCC and then immediately assumes it is and X64 arch. But that itself is never checked, there is plenty of gcc usage on ARM. 

The CMAKE crosscompile flags should be checked and if there is crosscompile setup, it is not safe to assume its x64.

**Comment by asoffer** [comment]
Thanks for the report, and sorry for the delayed response.
Could you explain further how -mfpu=neon is buggy? That is, on which platforms does this not suffice, and how should they be detected with CMAKE_SYSTEM_PROCESSOR?

**Comment by lilianmoraru** [comment]
@asoffer I've found it to be buggy on GCC 6.1 and older. It works most of the times but we had some issues with the `rapidjson` library. I added this check(it was a quick fix, would not recommend it for anybody else) in the toolchain file:
```
if (   (CMAKE_C_COMPILER_ID  STREQUAL  "GNU"    AND  NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 7.1)
    OR (CMAKE_C_COMPILER_ID  STREQUAL  "Clang"  AND  NOT CMAKE_C_COMPILER_VERSION VERSION_LESS 5.0))
    set(target_fpu_cflag       "-mfpu=neon-vfpv4")
else()
    set(target_fpu_cflag       "-mfpu=vfpv4")
endif()

if (   (CMAKE_CXX_COMPILER_ID  STREQUAL  "GNU"    AND  NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 7.1)
    OR (CMAKE_CXX_COMPILER_ID  STREQUAL  "Clang"  AND  NOT CMAKE_CXX_COMPILER_VERSION VERSION_LESS 5.0))
    set(target_fpu_cxxflag     "-mfpu=neon-vfpv4")
else()
    set(target_fpu_cxxflag     "-mfpu=vfpv4")
endif()
```

Inside QEMU, it worked fine. It(`rapidjson`) was crashing(SIGBUS) on `Qualcomm Snapdragon X5 LTE modem(9x28)` and `Qualcomm Snapdragon X12 LTE modem(9x40)`.

Note: `abseil` could keep `neon` and add checks only if people have issues with some specific versions of the compiler for example.
I personally would still prefer for it to allow people to pass custom toolchain files and take the configurations from there and not overwrite them.
```
if ("${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
  # sets its own flags
endif("${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
```

**Comment by lilianmoraru** [comment]
If you want, I could work on this but I will do it when I find some free time(most probably this weekend).
I did not touch the files since it seems that most of the configs are generated from Blaze.

**Comment by powderluv** [comment]
Same issue. According to AbseilConfigureCopts.cmake it is because of this section that assumes if you are using a GNU toolchain you are on x86_64

if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  set(ABSL_DEFAULT_COPTS "${ABSL_GCC_FLAGS}")
  set(ABSL_TEST_COPTS "${ABSL_GCC_FLAGS};${ABSL_GCC_TEST_FLAGS}")
  set(ABSL_RANDOM_RANDEN_COPTS "${ABSL_RANDOM_HWAES_X64_FLAGS}")
elseif("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
MATCHES so we get both Clang and AppleClang

Im building abseil on aarch64 Gentoo on RPi4 for EdgeTPU access and it fails because the default compiler is gcc

**Comment by lilianmoraru** [comment]
Sorry, I am not able to work on this, completely overflowed with work on weekends...

**Comment by amrox** [comment]
This is working for me as of https://github.com/abseil/abseil-cpp/commit/078b89b3c046d230ef3ad39494e5852184eb528b 🎉

**Comment by lilianmoraru** [comment]
Looking at the changes, I think in my case it will throw the warning `Value of CMAKE_SYSTEM_PROCESSOR (${CMAKE_SYSTEM_PROCESSOR}) is unknown and cannot be used to set ABSL_RANDOM_RANDEN_COPTS` and not set any flags, which is fine with me.
I might set manually `CMAKE_SYSTEM_PROCESSOR` to `arm`, for the optimizations.
I will try to test it today and see if it compiles.

**Comment by lilianmoraru** [comment]
Yes, I saw the warning message, but it works.
Closing this since it is fixed in the `master` branch.
Thank you!

**Comment by lilianmoraru** [comment]
I observed that the check on `CMAKE_SYSTEM_PROCESSOR` is a bit "flaky".
People usually set it like this: `set(CMAKE_SYSTEM_PROCESSOR ARM)`, which this check `elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "arm")` would fail, because it is case sensitive and it would expect `STREQUAL "ARM"`.
This is usually fixed with [`string(TOUPPER`](https://cmake.org/cmake/help/v3.16/command/string.html#toupper) or [`string(TOLOWER`](https://cmake.org/cmake/help/v3.16/command/string.html#tolower) and then checking on the new variable.
