### ISSUE TITLE
Provide a libabsl.a combining all installed static libraries

### ISSUE THREAD

**Issue by zifeitong** [abseil/abseil-cpp#367]
It's very difficult now to use `absl` without `Bazel` or `CMake`. I had to link all the standalone static libraries in order to compile a simple program with Flags. It will make the process much easier by providing a `libabsl.a` combining all the individual libraries.

The quickstart can then be super easy.

- Build
```
$ git clone https://github.com/abseil/abseil-cpp.git
$ cd abseil-cpp
$ cmake .
$ make install
```

- Run
```c
// hello_world.cc
#include <absl/flags/flag.h>
#include <absl/flags/parse.h>
#include <iostream>

ABSL_FLAG(std::string, hello_world, "Hello World", "");

int main(int argc, char** argv) {
  absl::ParseCommandLine(argc, argv);
  std::cout << absl::GetFlag(FLAGS_hello_world) << std::endl;
}
```

```
$ g++ hello_world.cc -o hello_world -labsl -lpthread -std=c++11
```

**Comment by christinaa** [comment]
Though I'm sure its modularity is intentional you can in fact combine all objects to form a static archive that consists of all built objects. I think gn does something similar automatically (through `llvm-ar`) and merges the output objects when explicitly requested. In the case below with `use_complete_absl_lib = true`, all source sets are merged into one output library, although in this instance I wouldn't consider it beneficial.

```
declare_args() {
  use_complete_absl_lib = true
}

static_library("absl_complete") {
  complete_static_lib = true
  output_name = "absl"

  public_deps = [ "./absl" ]
}

static_library("absl_summary") {
  complete_static_lib = false
  output_name = "abslSummary"

  public_deps = [ "./absl" ]

  visibility = [ ":*" ]
}

static_library("absl_lib") {
  if (use_complete_absl_lib) {
    public_deps = [ ":absl_complete" ]
  } else {
    public_deps = [ ":absl_summary" ]
  }
}
```

I think you can reproduce that manually by running a script after your build and breaking up each archive (using `ar` if you're using GNU binutils) and then merging all of them again (using `ar`).

**Comment by lilianmoraru** [comment]
This would encourage bad practice. Making it easier to go the inefficient way.

**Comment by asoffer** [comment]
Thanks for raising this issue. This is something we do not intend to support as it encourages what we believe not to be best practices. If at all possible, we encourage using a modern build system (we support Bazel and CMake) and building with smaller modular components.

**Comment by pps83** [comment]
> Thanks for raising this issue. This is something we do not intend to support as it encourages what we believe not to be best practices. If at all possible, we encourage using a modern build system (we support Bazel and CMake) and building with smaller modular components.

So, projects that do not use (or do not want to use) Bazel/CMake should avoid abseil?
Can you please add a cmake option to build "amalgamagted" libabsl.a for those who prefer "inefficient" way instead of relying on manual dependency specification on abseil sub-components.

**Comment by karltsai-lm** [comment]
Your decision makes figuring out which of the 86 absl libs to link against necessary. Is that efficiency?

**Comment by zpassanger** [comment]
I am who I am in 1st place I have like 6 to get 2nd name 3 for sure 4 for
must

**Comment by Ternvein** [comment]
Moreover, it makes figuring out on which of the 85 remaining libs depends the one you need, to properly order them in static builds.

**Comment by pps83** [comment]
> Thanks for raising this issue. This is something we do not intend to support as it encourages what we believe not to be best practices. If at all possible, we encourage using a modern build system (we support Bazel and CMake) and building with smaller modular components.

@asoffer You got tons of downvotes. Perhaps, would be a good idea to reconsider that awful approach absl took
