### ISSUE TITLE
[Question]: About some alerts in code

### ISSUE THREAD

**Issue by Milerius** [abseil/abseil-cpp#368]
Hello, after reading the code through tooling there is some alerts that i want to share (maybe some are relevant):

(/absl/base/internal/spinlock.h line 231)
<img width="1157" alt="Capture d’écran 2019-08-17 à 10 37 38" src="https://user-images.githubusercontent.com/21139416/63208958-2bfecb00-c0db-11e9-8858-b2510e640dbd.png">

same here (absl/flags/internal/commandlineflag.cc line 467):

<img width="1223" alt="Capture d’écran 2019-08-17 à 10 40 35" src="https://user-images.githubusercontent.com/21139416/63208983-7b44fb80-c0db-11e9-9835-d9b614ae08d2.png">

It's not better to do smth like: `if not` instead of leaving an empty block ? or there is a specific reason that i dont get ? 

There is some warning about comparison too:

(absl/debugging/internal/demangle.cc line 1626)
<img width="1219" alt="Capture d’écran 2019-08-17 à 10 44 13" src="https://user-images.githubusercontent.com/21139416/63209033-19d15c80-c0dc-11e9-93bb-40239a429e54.png">

(absl/time/internal/cctz/src/time_zone_format.cc)
<img width="1221" alt="Capture d’écran 2019-08-17 à 10 51 31" src="https://user-images.githubusercontent.com/21139416/63209097-0d013880-c0dd-11e9-995f-bd00673d75cc.png">

some overflow warning:

(absl/time/internal/cctz/src/time_zone_posix.cc)
<img width="620" alt="Capture d’écran 2019-08-17 à 10 52 35" src="https://user-images.githubusercontent.com/21139416/63209116-33bf6f00-c0dd-11e9-8f2c-7bf725fdfd03.png">

(absl/debugging/symbolize_elf.inc)
<img width="1209" alt="Capture d’écran 2019-08-17 à 10 47 05" src="https://user-images.githubusercontent.com/21139416/63209058-76cd1280-c0dc-11e9-868e-fc5ac79116fc.png">
<img width="1205" alt="Capture d’écran 2019-08-17 à 10 47 13" src="https://user-images.githubusercontent.com/21139416/63209059-7765a900-c0dc-11e9-950c-47e338aa5cfa.png">

(abseil-cpp-src/absl/synchronization/mutex.cc)
<img width="1209" alt="Capture d’écran 2019-08-17 à 10 49 49" src="https://user-images.githubusercontent.com/21139416/63209085-d2979b80-c0dc-11e9-8a6d-5eb63f9e9bbc.png">

**Comment by zhangxy988** [comment]
Thank you for your report!
The empty block warning seems valid to me. We will work on removing them.
The warnings in cctz might be valid, but you will need to report them to https://github.com/google/cctz. Abseil doesn't own cctz - it only holds a copy of it.
The other warnings look less straight-forward, so I will leave them for people who are more familiar with the code to comment.

**Comment by zhangxy988** [comment]
@vslashg Could you please look at the other overflow warnings? Thx.

**Comment by vehystrix** [comment]
Using clang scan-build the following warnings show up, perhaps they could be looked at as well:

```
$ scan-build cmake ../../abseil-cpp
scan-build: Using '/usr/lib/llvm-6.0/bin/clang' for static analysis
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/share/clang/scan-build-6.0/libexec/c++-analyzer
-- Check for working CXX compiler: /usr/share/clang/scan-build-6.0/libexec/c++-analyzer -- works

$ cmake --build .

Scanning dependencies of target malloc_internal
[ 10%] Building CXX object absl/base/CMakeFiles/malloc_internal.dir/internal/low_level_alloc.cc.o
/mnt/a/abseil-cpp/absl/base/internal/low_level_alloc.cc:163:42: warning: Dereference of undefined pointer value
  return (head->levels == 0) ? nullptr : prev[0]->next[0];
                                         ^~~~~~~~~~~~~~~~
/mnt/a/abseil-cpp/absl/base/internal/low_level_alloc.cc:176:18: warning: Dereference of undefined pointer value
    e->next[i] = prev[i]->next[i];
                 ^~~~~~~~~~~~~~~~
/mnt/a/abseil-cpp/absl/base/internal/low_level_alloc.cc:284:10: warning: Access to field 'flags' results in a dereference of a null pointer (loaded from variable 'arena')
    if ((arena->flags & LowLevelAlloc::kAsyncSignalSafe) != 0) {
         ^~~~~~~~~~~~
3 warnings generated.
[ 11%] Built target malloc_internal

Scanning dependencies of target debugging_internal
[ 18%] Building CXX object absl/debugging/CMakeFiles/debugging_internal.dir/internal/elf_mem_image.cc.o
/mnt/a/abseil-cpp/absl/debugging/internal/elf_mem_image.cc:351:52: warning: Access to field 'st_name' results in a dereference of a null pointer (loaded from variable 'symbol')
  const char *const symbol_name = image->GetDynstr(symbol->st_name);
                                                   ^~~~~~~~~~~~~~~
1 warning generated.
[ 20%] Built target debugging_internal

Scanning dependencies of target strings
[ 28%] Building CXX object absl/strings/CMakeFiles/strings.dir/ascii.cc.o
[ 29%] Building CXX object absl/strings/CMakeFiles/strings.dir/charconv.cc.o
In file included from /mnt/a/abseil-cpp/absl/strings/charconv.cc:24:
/mnt/a/abseil-cpp/absl/numeric/int128.h:644:45: warning: The result of the right shift is undefined because the right operand is negative
      return MakeUint128(Uint128High64(lhs) >> amount,
                         ~~~~~~~~~~~~~~~~~~~^~~~~~~~~
1 warning generated.
[ 29%] Building CXX object absl/strings/CMakeFiles/strings.dir/escaping.cc.o
/mnt/a/abseil-cpp/absl/strings/escaping.cc:888:9: warning: Value stored to 'szdest' is never read
        szdest -= 2;
        ^         ~
/mnt/a/abseil-cpp/absl/strings/escaping.cc:908:9: warning: Value stored to 'szdest' is never read
        szdest -= 1;
        ^         ~
/mnt/a/abseil-cpp/absl/strings/escaping.cc:926:7: warning: Value stored to 'szdest' is never read
      szdest -= 4;
      ^         ~
3 warnings generated.
[ 33%] Building CXX object absl/strings/CMakeFiles/strings.dir/numbers.cc.o
/mnt/a/abseil-cpp/absl/strings/numbers.cc:208:5: warning: Value stored to 'digits' is never read
    digits = i;
    ^        ~
/mnt/a/abseil-cpp/absl/strings/numbers.cc:373:34: warning: The result of the left shift is undefined due to shifting by '64', which is greater or equal to the width of type 'unsigned long'
    result.first = (result.first << shift) + (result.second >> (64 - shift));
                    ~~~~~~~~~~~~~^~~~~~~~
2 warnings generated.
[ 37%] Built target strings

Scanning dependencies of target graphcycles_internal
[ 37%] Building CXX object absl/synchronization/CMakeFiles/graphcycles_internal.dir/internal/graphcycles.cc.o
/mnt/a/abseil-cpp/absl/synchronization/internal/graphcycles.cc:648:7: warning: Called C++ object pointer is null
      path[path_len] = MakeId(n, rep_->nodes_[n]->version);
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[ 38%] Built target graphcycles_internal

**Comment by rogeeff** [comment]
I believe empty braces are addressed. If you still observe other warnings please file separate issue per occurrence.
