### ISSUE TITLE
StrAppend dereferences invalid iterators (std::string::end())

### ISSUE THREAD

**Issue by kkinnunen** [abseil/abseil-cpp#374]
StrAppend dereferences invalid iterators (std::string::end()) when using pattern &*str.begin() if the str is empty. 
Affects webrtc in https://webrtc.googlesource.com/src/+/refs/heads/master/pc/rtc_stats_collector_unittest.cc#156

Can be caught when compiling with MS c++ stdlib and iterator debugging enabled.

**Comment by EricWF** [comment]
you're allowed to dereference the end iterator for std::string. it points to the terminating null character.

**Comment by derekmauro** [comment]
@EricWF I'm not so sure. Are you sure you aren't thinking of `s[s.size()]`, which I think is legal in C++11.

http://www.cplusplus.com/reference/string/string/end/
> Returns an iterator pointing to the past-the-end character of the string.
>
> The past-the-end character is a theoretical character that would follow the last character in the string. **It shall not be dereferenced.**

I verified that the MSVC debug STL doesn't like this either.

**Comment by EricWF** [comment]
The standard is a lot less clear. I asked the GNU and MSVC standard library implementors and got different answers; making this a standards bug too.

Abseils behavior isn't inherently dangerous, and we should stop short of jumping through hoops to remove it. But a simple fix it would be preferable to waiting for the standard.

**Comment by kkinnunen** [comment]
Nice, thanks
