### ISSUE TITLE
Add an abseil::abseil target to CMake

### ISSUE THREAD

**Issue by bruxisma** [abseil/abseil-cpp#378]
Hello!

When using abseil in an `add_subdirectory` form, it would be nice if there was some way to have a catch-all `INTERFACE` which all targets are linked to, specifically

```cmake
add_library(abseil INTERFACE)
add_library(abseil::abseil ALIAS abseil)
target_link_libraries(abseil
  INTERFACE
    abseil::base
    ... # Other libraries here)
```

This would let me just use all of abseil for my project instead of having to specify each and every library, especially since all of them are built regardless of whether I use them or not.

**Comment by tituswinters** [comment]
I suspect we may soon have individual targets that require C++17, even if
most of the project supports C++11. Would that be an issue for this
proposal?

**Comment by bruxisma** [comment]
If `target_compile_features` is used to set the C++17 requirement, I *believe* that transitive linking in CMake will set that same requirement on whoever uses it. That said, there is some trickery that could be done via the `$<LINK_ONLY:...>` generator expression to make sure that these requirements aren't put onto every library that uses abseil (though I'm unsure when that was added to CMake...).

The other alternative would be to have `abseil::cxx11`, `abseil::cxx14`, and `abseil::cxx17` targets that have the correct libraries linked to them, and then alias `abseil::abseil` to whatever `CMAKE_CXX_STANDARD` standard is set to. (i.e., `add_library(abseil::abseil ALIAS abseil::cxx${ABSEIL_DEFAULT_INTERFACE})` or something similar, with a pessimistic fallback to 11 if a user has not set the version:

```cmake
set(ABSEIL_DEFAULT_INTERFACE ${CMAKE_CXX_STANDARD})
if (NOT ABSEIL_DEFAULT_INTERFACE)
  set(ABSEIL_DEFAULT_INTERFACE 11)
endif()
```

Feel free to choose better variable names :)

**Comment by MikeGitb** [comment]
> If target_compile_features is used to set the C++17 requirement, 

I think that might be a bad idea regardless of the issue at hand,  because the result will be that some abseil libs get compiled in c++11 mode (or rather 14 on most compilers) and others in c++17 mode in the same project.

**Comment by MikeGitb** [comment]
> I suspect we may soon have individual targets that require C++17

Doesn't that conflict with the 5 year support guarantee?

EDIT: Ah sorry,  I guess you are talking about new targets.

**Comment by tituswinters** [comment]
I don't think so. We aren't saying future code works with everything, just
that anything we publish will keep working for 5 years after a replacement
is available.

**Comment by asoffer** [comment]
This is not something we intend to support. As Titus points out, we would have to provide snapshots of this target that work with specific language versions as we add 17-only or 20-only features. Which code gets put into which target would be confusing. While I would not encourage it, you could maintain your own target.

**Comment by bruxisma** [comment]
I would just like to briefly state that while I understand the concern regarding "which targets would be linked against" in the event of a `absl::absl` target, it *would* simply be an `INTERFACE` library with a generator expression for minimum versions:

```cmake
add_library(absl INTERFACE)
add_library(absl::absl ALIAS absl)
target_link_libraries(absl
  INTERFACE
    $<$<COMPILE_FEATURES:cxx_std_11>:absl::target1, absl::target2>,
    $<$<COMPILE_FEATURES:cxx_std_14>:abs::target3, absl::target4>,
    $<$<COMPILE_FEATURES:cxx_std_17>:... you get the idea>)
#  Then users can "set" the minimum version of `absl` to use
target_compile_features(absl INTERFACE cxx_std_14)

# ... later ...

target_link_libraries(MyTarget PRIVATE absl::absl)
```

(If there's a mismatch and `MyTarget` happens to be set to `cxx_std_11` instead of `cxx_std_14`, CMake would error explaining the reason)

Maintaining my own is certainly something I can easily do as long as I know what the minimum targets are for a given library. Then it's as simple as doing the above (though others won't get the library unless I wrap abseil's CMake somehow... 😕)

That said, If some documentation could be published of all the libraries and their minimum standard version, it would go a long way to helping. I can file that as a separate bug however.
