### ISSUE TITLE
Any plan to revamp tcmalloc since a lot of stuff from abseil is in a better shape?

### ISSUE THREAD

**Issue by mzhaom** [abseil/abseil-cpp#381]
A lot of  base stuff in google-perftools in kinda of deprecated since absl came with better version for them, I wonder whether there is any plan to revamp gperftools especially tcmalloc since it has not been officially updated for a long time..

**Comment by tituswinters** [comment]
Yes, this was actually announced at Cppcon this week. We don't have a firm
date for it, but "soon" (ideally within a month).

**Comment by smahapatra1** [comment]
I don't want to start a religious war, but if jemalloc is actually better than tcmalloc to avoid fragmentation, should Abseil adopt jemalloc?

**Comment by derekmauro** [comment]
TCMalloc is going to be released as a separate project. You will be able to use Abseil with any malloc you want.

**Comment by ckennelly** [comment]
This is now done!  Our announcement is on the [Abseil blog](https://abseil.io/blog/20200212-tcmalloc).  The code can be found at https://github.com/google/tcmalloc.
