### ISSUE TITLE
Is there any plan to let glog use absl flag or provide LOG functionality through absl?

### ISSUE THREAD

**Issue by mzhaom** [abseil/abseil-cpp#383]
I'm planning to switch my project from gflags to absl flags since the absl flags API seems to be better and support more types. But I also uses glog which relies on gflags to setup its behavior.

I wonder whether there is any plan to address such an issue so I can have both absl and glog.

Thanks.

**Comment by derekmauro** [comment]
Abseil is going to be releasing the logging library. It is actively being worked on. We don't have a release date to share.

**Comment by smahapatra1** [comment]
In the meanwhile, is it better to use gflags with glog and later switch both to use Abseil? This is in order to control the output directory, verbose level etc.

**Comment by derekmauro** [comment]
We aren't going to be changing gflags or glog, they will remain in separate repositories. If you need both flags and logging, I'd probably wait until the new logging library is released.

**Comment by tlemo** [comment]
Any updates on the logging library release plans?

**Comment by derekmauro** [comment]
It is still actively being worked on.

**Comment by bcsgh** [comment]
FWIW: https://abseil.io/docs/cpp/guides/logging
