### ISSUE TITLE
CMakeLists.txt and intrinsics in int128.h

### ISSUE THREAD

**Issue by ptrmtrx** [abseil/abseil-cpp#385]
Are these two files still useful?
 - "absl/numeric/int128_have_intrinsic.inc"
 - "absl/numeric/int128_no_intrinsic.inc"

They are empty (except licence), but included by int128.h header. The files are not marked as public headers in CMakeLists.txt but they are in sources, but included from public header:

```
absl_cc_library(
  NAME
    int128
  HDRS
    "int128.h"
  SRCS
    "int128.cc"
    "int128_have_intrinsic.inc"
    "int128_no_intrinsic.inc"
  COPTS
    ${ABSL_DEFAULT_COPTS}
  DEPS
    absl::config
    absl::core_headers
  PUBLIC
)
```

It seems like a bug to me. They should be in public headers section in CMakeLists.txt or included by source files, not a public header.

**Comment by rongjiecomputer** [comment]
~~Putting `*.inc` in `SRCS` means that user should never directly include `*.inc` themselves, they should use `int128.h` to do the job instead. This is the semantic borrowed from Bazel.~~

Ah nevermind, I just noticed the line "They are empty (except licence)".

**Comment by asoffer** [comment]
Thanks for noticing this. Indeed these files are not useful in their current public state. We have an implementation that's not quite ready for release and so it strips out the entirety of the files. These should be coming soon. In the meantime, they're definitely weird, but likely not worth cleaning up in the short term.

**Comment by ptrmtrx** [comment]
Ok, it makes sense.
Furthermore, I noticed yesterday that a bug is in my script as the *.inc files are installed by cmake even if they are in source files and not headers.
