### ISSUE TITLE
It crashes when build with -static link flag

### ISSUE THREAD

**Issue by iam5j** [abseil/abseil-cpp#398]
I tried to instantiate flat_hash_map in my example.cc, following https://abseil.io/docs/cpp/tools/cmake-installs#generate-the-abseil-static-binaries, it crashes while `-static` link flag is set in CMakeLists.txt as below:
`target_link_libraries(example absl::strings absl::flat_hash_map -static)`
But it goes well without `-static` flag:
`target_link_libraries(example absl::strings absl::flat_hash_map)`

My env:
`gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4`
`cmake version 3.11.0-rc1`

**Comment by derekmauro** [comment]
Can you please provide a complete example with sources and CMake files?

**Comment by iam5j** [comment]
- source:

`#include <string>`
`#include <iostream>`
`//#include "absl/strings/str_split.h"`
`//#include "absl/strings/str_replace.h"`
`//#include "absl/strings/ascii.h"`
`//#include "absl/strings/str_cat.h"`
`#include "absl/container/flat_hash_map.h"`

`class AbslHashMap {`
` private:`
`  const absl::flat_hash_map<std::string, std::string> map_ = {`
`    {"time", "today"}, {"place", "where"}`
`  };`

` public:`
`  bool contains(absl::string_view key) const {`
`    return map_.find(key) != map_.end();`
`  }`
`};`

`int main() {`
`  AbslHashMap ahm;`
`  std::cout << ahm.contains("hello") << std::endl;`
`  return 0;`
`}`

- cmake file:

`cmake_minimum_required(VERSION 3.5)`
`project(my_project)`
`# Abseil requires C++11`
`set(CMAKE_CXX_STANDARD 11)`
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")`

`# Import Abseil's CMake targets`
`find_package(absl REQUIRED)`

`add_executable(example test.cc)`

`# Declare dependency on the absl::strings library`
`# target_link_libraries(example absl::strings absl::flat_hash_map)`
`target_link_libraries(example absl::strings absl::flat_hash_map -static)`

**Comment by suertreus** [comment]
Looks like there's a known issue with pthread (used by Abseil) and static linking:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52590

The workaround is to turn `--whole-archive` on before passing `-lpthread` (and, optionally, turn it off after).  You can add that to `target_link_libraries` where you pass `-static`, but I think it might be better to set `CMAKE_EXE_LINKER_FLAGS=-static -Wl,--whole-archive -lpthread -Wl,--no-whole-archive` when you want a static binary.
