### ISSUE TITLE
Add building Conan package as part of CI

### ISSUE THREAD

**Issue by aostrowski** [abseil/abseil-cpp#401]
When trying to build Abseil's Conan package I discovered that the script was broken. That's why I filed #400. 

In order not to have such regressions in the future I'd like to propose building the Conan package as part of the CI process.

**Comment by asoffer** [comment]
Thanks for bringing this to our attention Adrian. Abseil doesn't officially support Conan (even at the best-effort level). We welcome pull requests to fix issues. We also welcome pull requests to set up external CI for this with the caveat that members of the Abseil team are unlikely to pay attention to the results of the CI. If this is something the community wants to support we encourage that, but we unfortunately do not currently have the resources to spend on Conan support.
