### ISSUE TITLE
tests failed for inlined_vector_benchmark, fixed_array_benchmark, notification_test, and time_zone_format_test

### ISSUE THREAD

**Issue by sammi** [abseil/abseil-cpp#402]
Windows10

MSVC: 14.23.28105
Windows SDK: 10.0.18362.0

```
C:\Users\songy\source\repos\abseil-cpp>where cl
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\Hostx64\x64\cl.exe

C:\Users\songy\source\repos\abseil-cpp>where cppwinrt
C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\cppwinrt.exe
```

```
cd abseil-cpp
bazel test //absl/...
```

> //absl/utility:utility_test                                              PASSED in 0.3s
//absl/container:inlined_vector_benchmark                               TIMEOUT in 300.0s
  C:/users/songy/_bazel_songy/gbzrkxa5/execroot/com_google_absl/bazel-out/x64_windows-fastbuild/testlogs/absl/container/inlined_vector_benchmark/test.log
//absl/container:fixed_array_benchmark                                   FAILED in 135.0s
  C:/users/songy/_bazel_songy/gbzrkxa5/execroot/com_google_absl/bazel-out/x64_windows-fastbuild/testlogs/absl/container/fixed_array_benchmark/test.log
//absl/synchronization:notification_test                                 FAILED in 0.3s
  C:/users/songy/_bazel_songy/gbzrkxa5/execroot/com_google_absl/bazel-out/x64_windows-fastbuild/testlogs/absl/synchronization/notification_test/test.log
//absl/time/internal/cctz:time_zone_format_test                          FAILED in 0.8s
  C:/users/songy/_bazel_songy/gbzrkxa5/execroot/com_google_absl/bazel-out/x64_windows-fastbuild/testlogs/absl/time/internal/cctz/time_zone_format_test/test.log
//absl/time/internal/cctz:time_zone_lookup_test                          FAILED in 0.7s
  C:/users/songy/_bazel_songy/gbzrkxa5/execroot/com_google_absl/bazel-out/x64_windows-fastbuild/testlogs/absl/time/internal/cctz/time_zone_lookup_test/test.log
//absl/container:btree_test                                              PASSED in 16.3s
  Stats over 10 runs: max = 16.3s, min = 3.6s, avg = 10.5s, dev = 3.9s
//absl/synchronization:mutex_test                                        PASSED in 15.4s
  Stats over 25 runs: max = 15.4s, min = 1.1s, avg = 4.7s, dev = 4.1s

Executed 170 out of 170 tests: 165 tests pass and 5 fail locally.
INFO: Build completed, 5 tests FAILED, 1371 total actions

**Comment by derekmauro** [comment]
You need to run something like `bazel test --test_tag_filters=-benchmark --test_env=TZDIR="%CD%\absl\time\internal\cctz\testdata\zoneinfo" ...`. Hopefully soon you won't need the `--test_tag_filters=-benchmark` part.
