### ISSUE TITLE
CMake Line Continuation Requires Version 3

### ISSUE THREAD

**Issue by wtagg** [abseil/abseil-cpp#46]
In the following location a line continuation mechanism is employed that is only supported by CMake versions > 3.
https://github.com/abseil/abseil-cpp/blob/95ddf85f8075d5645a754bac5742b72ec9c81f2a/CMake/AbseilHelpers.cmake#L77

However the CMakeLists only requires: 

https://github.com/abseil/abseil-cpp/blob/95ddf85f8075d5645a754bac5742b72ec9c81f2a/CMakeLists.txt#L16

**Comment by JonathanDCohen** [comment]
Sorry for the long response time, real life things have been happening (I got married this past weekend <3)

Looks like the solution is just to put a newline in the string, which is what this is trying to do anyways.  I'll make the change internally and close the issue when we upstream.

**Comment by JonathanDCohen** [comment]
This has now been fixed, closing this Issue.  Please re-open if it continues to be a problem
