### ISSUE TITLE
Any libraries similar to Go routines? 

### ISSUE THREAD

**Issue by rjammala** [abseil/abseil-cpp#5]
Any chance you can also include concurrency libraries which are similar to Go routines/channels? I heard that Google developed similar things for C++ internally.

**Comment by derekmauro** [comment]
It's true that we have an implementation of lightweight threads, also known as Fibers, internal to Google.  In fact, if you look at the code, you'll see things like "absl/base/internal/scheduling_mode.h" that are only in our code because the internal version has Fiber support.  However, shipping a version of Abseil with Fiber support isn't on our road map today because they are Linux only and also require a custom kernel.

**Comment by tituswinters** [comment]
Putting out some form of good concurrency APIs is high on our priority list, but the constraints (platforms + aligning with or changing internal APIs) make it ... hard.  I could imagine it taking a year before we have anything significant in this space, but I hope its sooner.

**Comment by rjammala** [comment]
Yeah, anything that you could include will really help. Thanks for considering the request.

**Comment by rjammala** [comment]
ping. Any chance of just open sourcing the Linux version at least?

**Comment by mbxx** [comment]
The Linux-only Fibers require deep modifications to the Linux kernel that as far as I've heard wouldn't be accepted upstream, so it's not clear how we could release it in a way that folks could use.

As for the broader picture of concurrency primitives, we're still working on it but it's hard and we're still in the planing stages.  I wish I had better news.

**Comment by rjammala** [comment]
Thanks for the update @mbxx

**Comment by tituswinters** [comment]
For comparison, the C++ Standard isn't running a whole lot faster on
concurrency primitives and such (executors, futures, etc).  It is indeed a
*very* hard space to get "right", especially in a language like C++ that is
all about performance.

**Comment by erwincoumans** [comment]
There is some update:
https://www.phoronix.com/scan.php?page=news_item&px=Google-UMCG-Linux-v0.7
