### ISSUE TITLE
btree is slower than std::map for finding operation

### ISSUE THREAD

**Issue by assassin5615** [abseil/abseil-cpp#563]
this is not so much an issue as a question.

I did a very simple comparison between std::map and btree using google benchmark. code is as below
```
void BM_find_int(benchmark::State& state)
{
    std::map<int, int> m;
    for (size_t i = 0; i < loop_cnt; ++i)
    {
       m.emplace(i, i);
    }
    for (auto _ : state)
    {
        for (size_t i = 0; i < loop_cnt; ++i)
        {
            auto it = m.find(i);
            benchmark::DoNotOptimize(it);
        }
    }
}

BENCHMARK(BM_find_int);
void BM_find_int_btree(benchmark::State& state)
{
    absl::btree_map<int, int> m;
    for (size_t i = 0; i < loop_cnt; ++i)
    {
       m.emplace(i, i);
    }
    for (auto _ : state)
    {
        for (size_t i = 0; i < loop_cnt; ++i)
        {
            auto it = m.find(i);
            benchmark::DoNotOptimize(it);
        }
    }
}
BENCHMARK(BM_find_int_btree);

```
the benchmark result is as below, btree is only half fast as std::map

> BM_find_int                                 807 ns          805 ns       853435
> BM_find_int_btree                          1976 ns         1971 ns       354867

I also tried with random numbers and the result is similar.

just wonder if  I am using btree incorrectly or the theory that makes btree faster than std::map does not always stand.

I also did benchmark for flat_hash_map and std::unorderd_map.  flat_hash_map is about four times faster than std::unorderd_map for finding operation.

**Comment by derekmauro** [comment]
I noticed your benchmark does not give the value you used for `loop_cnt`. I tried your benchmark with a few values and found that for smaller values, `std::map` is indeed faster, but as you increase the value of `loop_cnt`, `absl::btree_map` starts to outperform `std::map`.

On modern CPUs benchmarking code tends to be tricky, particularly when the code depends on the CPU cache. Simplistic benchmarks tend to minimize the effects of the cache, while realistic programs tend to place much more pressure on the cache. In the realistic cases, btrees tend to win. My advice is to always try the real program under real conditions before you decide which to use.

If there is any place where we claim that btree is always faster that the STL counterparts, please let us know so we can soften the language.

**Comment by assassin5615** [comment]
what you explained is very helpful to me, thanks for looking into the issue.
