### ISSUE TITLE
Can I pass a precomputed value to AbslHashValue?

### ISSUE THREAD

**Issue by lilianmoraru** [abseil/abseil-cpp#568]
I could not find a chat, so I leave the question here:
I have a big collection of strings that I've calculated the hash for, at compile-time(using XXH3) - I've already checked(at compile-time) all of these for hash collisions.
Is there a way to avoid paying the cost of another hash(the internal CityHash) over my numbers?

**Comment by tituswinters** [comment]
Nope. The design intent of the Abseil hashing framework is to make it easy
to identify the values/bytes that go into a hash, without exposing users to
the details of calculating a hash (which they often get wrong or make
choices based on inaccurate information about how hash probing works).

If you've got compile-time constants for all of your hash values, I'm not
sure that Abseil hashes / hash containers are the right solution: it feels
like a Perfect Hash may be a better direction, but I don't know the precise
constraints on your problem.

**Comment by lilianmoraru** [comment]
I know that collection of strings at compile-time but there are a few more that are added/generated at run-time, which I cannot predict the hash for.

I use my custom type as a `flat_hash_map` Key, but I see that like any other map, I can pass a custom Hash(I was hoping I can avoid that, to make the life of the user easy), so I think will do that.
I was going the wrong route, thanks!

**Comment by tituswinters** [comment]
The concern is that the Abseil hash containers require a very particular
(very uniform, highly mixed) bit distribution for hashing. Replacing with
an arbitrary hash, especially one that is based on different assumptions
(prime table sizes, for instance) will result in extraordinarily bad
performance. So you certainly can replace the Hash, but you should do so
carefully and have good benchmarks.
