### ISSUE TITLE
link failure for StrCat with >4 arguments

### ISSUE THREAD

**Issue by NancyLi1013** [abseil/abseil-cpp#570]
Using function `absl::StrCat()`, if we `set(CMAKE_CXX_STANDARD 17)` in `CMakeLists.txt`, there are two different results.
1. if we put less than four arguments, such as absl::StrCat(1,2,3,4), it will compile successfully.
2. if we put five arguments, such as absl::StrCat(1,2,3,4,5), it will post the failures:
```
error LNK2019: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl absl::strings_internal::CatPieces(class std::initializer_list<class std::basic_string_
view<char,struct std::char_traits<char> > >)" (?CatPieces@strings_internal@absl@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$initializer_list@V?$basic_string_view@DU?$char_traits@D@std@@@std@@@4@@Z) referenced i
n function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl absl::StrCat<>(class absl::AlphaNum const &,class absl::AlphaNum const &,class absl::AlphaNum const &,class absl::AlphaNum const
 &,class absl::AlphaNum const &)" (??$StrCat@$$V@absl@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVAlphaNum@0@0000@Z) [C:\Users\matled\source\strcat\build\fail.vcxproj]
```
Please refer to the info in vcpkg [here](https://github.com/microsoft/vcpkg/issues/9142).

Any suggestion is appreciated.

Thanks in advance.

**Comment by mbxx** [comment]
It's entirely possible that this is absl::string_view/std::string_view ABI incompatibility issues.  I'll comment on the vcpkg issue.

**Comment by mbxx** [comment]
This does indeed appear to be caused by Abseil and the code calling Abseil being built with different C++ versions, which caused `absl::string_view` and `std::string_view` to be different types and therefore ABI incompatible.  I suggested setting `ABSL_OPTION_USE_STD_STRING_VIEW` to 0 if this is something vcpkg would like to support.

**Comment by NancyLi1013** [comment]
Thanks for your description and suggestion.
