### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by BotellaA** [abseil/abseil-cpp#572]
I am using Abseil with the CMake integration and would like to use the `absl::flat_hash_map`.
My CMake can find the `absl` package and compile/link perfectly by adding the `absl::flat_hash_map` cmake target. However, I got surprising error only at execution:
```
$ ./bin/test-vertex-set 
./bin/test-vertex-set: error while loading shared libraries: libabsl_exponential_biased.so: cannot open shared object file: No such file or directory
```
Here is some additional info:
```
$ ldd ./bin/test-vertex-set 
        linux-vdso.so.1 (0x00007ffdd7d1b000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc87a973000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc87a75b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc87a36a000)
        libabsl_hash.so => XXX/build/third_party/abseil/install/lib/libabsl_hash.so (0x00007fc879ca1000)
        libabsl_city.so => XXX/build/third_party/abseil/install/lib/libabsl_city.so (0x00007fc879a9c000)
        libabsl_raw_hash_set.so => XXX/build/third_party/abseil/install/lib/libabsl_raw_hash_set.so (0x00007fc879899000)
        libabsl_hashtablez_sampler.so => XXX/build/third_party/abseil/install/lib/libabsl_hashtablez_sampler.so (0x00007fc879693000)
        libabsl_throw_delegate.so => XXX/build/third_party/abseil/install/lib/libabsl_throw_delegate.so (0x00007fc87948d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc8790ef000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fc87d251000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc878ed0000)
        libabsl_exponential_biased.so => not found
        libabsl_synchronization.so => not found
        libabsl_stacktrace.so => not found
        libabsl_time.so => not found
        libabsl_raw_logging_internal.so => not found
```
My executable has a `RUNPATH` pointing to `XXX/build/third_party/abseil/install/lib` and all the abseil libraries can be found inside this directory.

**Comment by derekmauro** [comment]
Please provide full instructions to reproduce the problem.

**Comment by BotellaA** [comment]
Here is a complete example: https://github.com/BotellaA/TestAbseil

**Comment by BotellaA** [comment]
I did another test by exporting `LD_LIBRARY_PATH` to `XXX/build/third_party/abseil/install/lib` and then it works.

My interpretation is that the direct abseil dependencies are correctly found but the indirect dependencies are not. One way to solve this could be to configure the RPATH of the installed libraries instead of adding the `LD_LIBRARY_PATH` which is not handy.

Currently, RPATH is remove during installation:
```
-- Installing: /tmp/abseil-cpp/build/install/lib/libabsl_time.so
-- Set runtime path of "/tmp/abseil-cpp/build/install/lib/libabsl_time.so" to ""
```

One could do it like this:
```
if(APPLE)
    set(OS_RPATH "@executable_path")
else()
    set(OS_RPATH "$ORIGIN")
endif()
set(CMAKE_MACOSX_RPATH ON)
set(CMAKE_INSTALL_RPATH "${OS_RPATH}")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
```

**Comment by derekmauro** [comment]
I did the same thing with `LD_LIBRARY_PATH` and came to the same conclusion. We will have to research what the proper solution is. Thanks for the report.

**Comment by BotellaA** [comment]
I had the same issue with my larger project. I fixed it with the code showed in my previous post. Curious about what solution you will chose.

**Comment by rogeeff** [comment]
I believe we already have shared library build at HEAD including Windows. Is this issue still outstanding?

**Comment by BotellaA** [comment]
No, it can be closed.

**Comment by maxnoe** [comment]
@BotellaA @rogeeff I ran into this today.

current cmake absl does not set the install rpath so that shared libraries find their own internal dependencies

It would be great if absl could set RPATH on installation

**Comment by MonilBhavsar** [comment]
I also ran into this while installing [`libphonenumber`](https:/github.com/google/libphonenumber/blob/master/cpp/README) library  in one of my project.
`libphonenumber` depends on some of abseil's container, hash and string function. When we install libphonenumber, it also installs abseil-cpp and when running my executable, I am getting

` error while loading shared libraries: libabsl_hash.so.2206.0.0: cannot open shared object file: No such file or directory`

My RUNPATH is set to the directory where file `libabsl_hash.so.2206.0.0` is present i.e `externalLib/libphonenumber/cpp/build/_deps/abseil-cpp-build/absl/hash`

We have another related issue here https://github.com/abseil/abseil-cpp/issues/1594. Hope this is resolved soon 🙏
