### ISSUE TITLE
Error while using bazel build

### ISSUE THREAD

**Issue by KutengF** [abseil/abseil-cpp#577]
When I try to use `bazel build //...` in gRPC, it shows:
`
ERROR: error loading package 'bazel-grpc/third_party/abseil-cpp/absl/algorithm': Label '//absl:copts/configure_copts.bzl' is invalid because 'absl' is not a package; perhaps you meant to put the colon here: '//:absl/copts/configure_copts.bzl'?
INFO: Elapsed time: 108.443s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (110 packages loaded)
    currently loading: src/objective-c/tests ... (2 packages)
`
I wish to know why this error happened, and what is the solution.
I'm using Ubuntu LTS 18.04, and it is a flesh new OS just installed.

Thanks

**Comment by derekmauro** [comment]
We don't know anything about the gRPC build. Please ask your question on a gRPC forum.
