### ISSUE TITLE
Conversion warning in bits.h with Visual C++ (2019)

### ISSUE THREAD

**Issue by giles45** [abseil/abseil-cpp#582]
Since upgrading to the latest version of abseil provided by vcpkg, we have many new compiler warnings of this variety:

`D:\jenkins\workspace\vcpkg\installed\x86-windows-utc-default\include\absl\base\internal\bits.h(89,32): warning C4244: 'argument': conversion from 'uint64_t' to 'unsigned long', possible loss of data`

It looks like that all is required is an addition of a static_cast.

The code in question doesn't look to have changed in a while so I assume the header is now being included in scenarios where it wasn't previously.

REF 29235139149790f5afc430c11cec8f1eb1677607 #commit 2019-12-19

**Comment by devjgm** [comment]
Ping on this bug. 
/cc @derekmauro

**Comment by derekmauro** [comment]
Sending out a fix.
