### ISSUE TITLE
Add `constexpr` to absl::NullSafeStringView 

### ISSUE THREAD

**Issue by Alfus** [abseil/abseil-cpp#583]
Both constructors used by [`NullSafeStringView`](https://github.com/abseil/abseil-cpp/blob/ad904b6cd3906ddf79878003d92b7bc08d7786ae/absl/strings/string_view.h#L608) are `constexpr`, but the function itself is missing `constexpr`. This makes it impossible to use in the context of static constexpr values.

**Comment by derekmauro** [comment]
It sounds like it is possible to make this change, I'll look into it.

**Comment by Alfus** [comment]
Thanks!
