### ISSUE TITLE
Compile tensorflow 1.50 I met a question, could you tell me what version of the library is referenced in the graph below abseil

### ISSUE THREAD

**Issue by ghost** [abseil/abseil-cpp#584]
![image](https://user-images.githubusercontent.com/14295852/71762547-5676e680-2f0b-11ea-8420-5558ef064296.png)

**Comment by derekmauro** [comment]
Sorry, I don't understand the question. What do you mean by "version"?

**Comment by ghost** [comment]
> Sorry, I don't understand the question. What do you mean by "version"?

I found the master of abseil-cpp had remove internal .  it case some question at older tensorflow. I hava sovle it. thank your reply.
