### ISSUE TITLE
Swiss tables missing constructor with allocator as argument

### ISSUE THREAD

**Issue by phwissmann** [abseil/abseil-cpp#587]
Hi

As far as I can see, `flat_hash_set` and `flat_hash_map` could support a constructor like
`explicit flat_hash_set(const Allocator& alloc) : Base(alloc) {}` similarly as `std::unordered_set/map` do. The base class does have this constructor.

This would allow to use polymorphic allocators added to the STL with the Swiss tables like
```
std::pmr::memory_resource memory_resource;
absl::flat_hash_set<Key, absl::Hash<Key>, absl::container_internal::hash_default_eq<Key>, std::pmr::polymorphic_allocator<Key>>` set(&memory_resource);
```

Is there any reason abseil does not support polymorphic allocators? Would there be any harm in adding this to my local abseil version?

**Comment by derekmauro** [comment]
https://godbolt.org/z/9x33pw - Your allocator argument needs to be a reference, not a pointer.

**Comment by phwissmann** [comment]
Not sure how I missed that... thanks!
