### ISSUE TITLE
What is the target name for the random module?

### ISSUE THREAD

**Issue by versatran01** [abseil/abseil-cpp#588]
Background

I compiled abseil outside of my project and installed it.
I wanted to use the random library, so I tried the following
```
find_package(absl REQUIRED COMPONENTS random)
...
target_link_libraries(a PUBLIC absl::random)
```
but it says target absl::random was not found.

This is very confusing as all other targets worked, like `absl::time`, `absl::container`.

**Comment by derekmauro** [comment]
See https://github.com/abseil/abseil-cpp/blob/master/absl/random/CMakeLists.txt

It appears to be `absl::random_random`.

**Comment by versatran01** [comment]
@derekmauro Yeah, I just found out that. Don't understand why it is not just called `absl::random`. And also don't understand why this is not clearly listed in the README.
