### ISSUE TITLE
Enable cmake install rules of abseil when added as a subproject

### ISSUE THREAD

**Issue by samuellees** [abseil/abseil-cpp#589]
Hello,

Is there a way to export and install abseil as a subproject?

I use abseil as a cmake subproject by `add_subdirectory(abseil)`, some abls targets are used in my project, and it works well in the build tree. But when I make install, abseil's libs and headers would not be exported and installed along with mine. **That means if I want to use my lib in another project, I have to build and link abseil's libs manually**, like:
```bash
g++ another.cpp -lmylib -labsl_xxxx
```

NOTE: abseil's install rules are disabled according to the following codes:
```cmake
# from abseil/CMakeLists.txt
if(NOT "^${CMAKE_SOURCE_DIR}$" STREQUAL "^${PROJECT_SOURCE_DIR}$")
  set(ABSL_ENABLE_INSTALL FALSE)
else()
  set(ABSL_ENABLE_INSTALL TRUE)
endif()

if(ABSL_ENABLE_INSTALL)
...
endif()
```

Thanks!

**Comment by derekmauro** [comment]
We aren't CMake experts, but we recommend using an LTS release if you want to install Abseil. That has install rules enabled. See https://abseil.io/about/releases. In that case I think you need to use `find_package` instead of using `add_subdirectory`.

**Comment by samuellees** [comment]
I see, Abseil encourages users to “live at head”, which I agree on.  And `find_package` is a nice way for users to use installed abseil (Abseil should be installed independently before `find_package`).

But, my library uses some interface of abseil(meets Apache-2.0 ‘s requirement). In the `find_package` case, if my user want to use my library, they have to build and install abseil first, and then install my library.

Why not enable install rules when added as subproject by `add_subdirectory`? I mean, if it is impossible, users having the same requirements with me may add a rude copy of abseil into their project and modify the install rules, which is confict with “live at head”.

Thank you.

**Comment by asoffer** [comment]
This leads to diamond dependency problems. If multiple projects require an installed Abseil but have different version requirements, problems manifest higher up the dependency graph. For intsallation, Abseil strongly encourages installing an LTS and does not aim to support installation of non-LTS builds.

**Comment by samuellees** [comment]
Got.

Thanks!
