### ISSUE TITLE
BuildBreak: UWP apps can't call GetModuleHandle

### ISSUE THREAD

**Issue by LoadLibrary** [abseil/abseil-cpp#595]
It is not possible to load RtlCaptureStackBackTrace at static init time in UWP.
CaptureStackBackTrace is the public version of RtlCaptureStackBackTrace.

**Comment by mai247596** [comment]
PHACHARA ARYUWANNA

ในวันที่ อ. 14 ม.ค. 2020 06:36 Augusto Righetto <notifications@github.com>
เขียนว่า:
