### ISSUE TITLE
inconsistent licenses() directives in bazel files

### ISSUE THREAD

**Issue by mmp** [abseil/abseil-cpp#6]
meta/BUILD.bazel, numeric/BUILD.bazel, and utility/BUILD.bazel all have

``
licenses(["unencumbered"])  # Owned by Google
``

while I assume they are intended to have

``
licenses(["notice"])  # Apache 2.0
``

like the other BUILD files.

**Comment by derekmauro** [comment]
This should be fixed at HEAD.
