### ISSUE TITLE
AbseilConfigureCopts.cmake does not handle architecture aarch64

### ISSUE THREAD

**Issue by andre-nguyen** [abseil/abseil-cpp#603]
On an nvidia Xavier the cmake variable `CMAKE_SYSTEM_PROCCESSOR` returns `aarch64`. This makes ARM platform detection fail here
https://github.com/abseil/abseil-cpp/blob/29235139149790f5afc430c11cec8f1eb1677607/absl/copts/AbseilConfigureCopts.cmake#L14-L22

which in turn causes compilation failures with absl::random. I can get around the problem by doing
```diff
diff --git a/absl/copts/AbseilConfigureCopts.cmake b/absl/copts/AbseilConfigureCopts.cmake
index b442646..4e55754 100644
--- a/absl/copts/AbseilConfigureCopts.cmake
+++ b/absl/copts/AbseilConfigureCopts.cmake
@@ -11,7 +11,7 @@ if("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "x86_64")
   else()
     set(ABSL_RANDOM_RANDEN_COPTS "${ABSL_RANDOM_HWAES_X64_FLAGS}")
   endif()
-elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "arm")
+elseif("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "arm" OR "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "aarch64" )
   if ("${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
     set(ABSL_RANDOM_RANDEN_COPTS "${ABSL_RANDOM_HWAES_ARM64_FLAGS}")
   elseif("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
```

but I am not entirely sure if it's the best way of going about this. Anyone else get this issue?

**Comment by zhangxy988** [comment]
Thanks for reporting the issue. Let's figure out the details in the PR.
