### ISSUE TITLE
Error building in bazel using c++17

### ISSUE THREAD

**Issue by joprice** [abseil/abseil-cpp#606]
I get the error below when building with `-std=c++17`. c++14 works find. Is there a way to pass that to the abseil build, or some other workaround enabling use of c++17?

`dyld: lazy symbol binding failed: Symbol not found: __ZN4absl8ByStringC1ENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE`

**Comment by derekmauro** [comment]
Please tell us exactly what you did when you are reporting a problem, otherwise we have to guess. How are you specifying C++17 mode in your build?

This is almost certainly an ABI issue. You can't mix compile modes. If you compile one library in C++14 mode and another in C++17 mode, you are going to get errors like the one you are seeing.

**Comment by joprice** [comment]
I can try to reproduce in a separate repo if you'd like. My usage is this:

Add repo in WORKSPACE

```python
abseil_cpp_version = "a2e6adecc294dc4cd98cc285a9134ce58e0f2ad0"

http_archive(
    name = "abseil",
    strip_prefix = "abseil-cpp-{}".format(abseil_cpp_version),
    url = "https://github.com/abseil/abseil-cpp/archive/{}.zip".format(abseil_cpp_version),
    sha256 = "a5a667e6899aa6767cd9bb24ca5afe6e51ba719862a810f30ad39bb256cfe17f"
)```

Use it in BUILD file:

```python
cc_binary(
    name = "parser",
    srcs = ["parser.cpp"],
    deps = [
        "@gflags",
        "@abseil//absl/strings",
        "@cpr",
        "@zlib_archive//:zlib",
    ],
	copts = [
	  "-std=c++14",
      "-stdlib=libc++",
	]
)
```

I am only setting the flag on that one binary. I thought a bit about it and made a guess that I need to set this repo-wide in order for workspace rules to use it (or provide a manual BUILD file to the http_archive). I put `build --cxxopt -std=c++17` in my .bazelrc and that fixes it.
