### ISSUE TITLE
Flags from module formatting

### ISSUE THREAD

**Issue by cruisercoder** [abseil/abseil-cpp#610]
Is there any control over how the module name is displayed?  My GN based build runs from a subdirectory so the module name comes out like this:

Flags from ../../demo/flags/CommonFlags.cc:
    --x (common x flag); default: false;
    --y (common y option); default: "";

**Comment by derekmauro** [comment]
Yes, you can set a callback to modify the filename.

https://github.com/abseil/abseil-cpp/blob/159bf2bf6d1cc8087e02468d071e94d1177d1bae/absl/flags/usage_config.h#L97-L106.

**Comment by rogeeff** [comment]
Please let us know if you have any problems with proposed resolution.

**Comment by cruisercoder** [comment]
Works - Thank you.
