### ISSUE TITLE
Cross platform armv6 invalid instruction

### ISSUE THREAD

**Issue by bvarbanov** [abseil/abseil-cpp#612]
Cross-platform builds for armv6 (Raspberry pi zero) - are causing Segmentation Fault in WebRTC and Tensorflow

**Comment by derekmauro** [comment]
ARMv6 isn't platform we support. If you can provide more information about the problem you are seeing we might be able to assist, but we don't know anything about using WebRTC or Tensorflow, especially on a Raspberry Pi Zero.

**Comment by bvarbanov** [comment]
TensorFlowLite and WebRTC are using abseil-cpp. 
Older version of WebRTC v72 was working fine using Abseil on Armv6. 

The simplest possible way to reproduce it is to follow the build steps for TensorFlowLite on RaspberryPi 3B (https://www.tensorflow.org/lite/guide/build_rpi), but for armv6 are needed some extra parameters.

OR you can use these steps to build armv6 and armv7 version ot TensroFlowLite.

sudo apt-get update
sudo apt-get install crossbuild-essential-armhf
git clone https://github.com/tensorflow/tensorflow.git
cd ./tensorflow
git checkout r2.0
./tensorflow/lite/tools/make/download_dependencies.sh

CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6l

CC_PREFIX=arm-linux-gnueabihf- make -j 8 -f ./tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv7l

Try running on Raspberry Pi Zero the example minimal - it crashes with Invalid Instruction
/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6l/bin/minimal

**Comment by derekmauro** [comment]
Thanks for the directions, but what I was really looking for was something like a stacktrace that might help us figure out what is going on. We don't support this platform and don't have a device. I'm going to close this, but feel free to re-open if you have more information.

**Comment by bvarbanov** [comment]
I did some quick investigation - found that cross compiler has a bug (I guess)
it crashes with SIGILL on code similar like this (abeil-cpp has many similar code statements):

long long a = 1;
auto b = static_cast<double>(a);

This code fails when cross compiled with clang++-9 for Raspberry PI Zero

CMake file for RPI_Zero
# target specific for armv6 / raspberry pi zero W
add_compile_options(-target ${triple})
add_compile_options(-march=armv6zk)
add_compile_options(-mfpu=vfp)
add_compile_options(-mcpu=arm1176jzf-s)
add_compile_options(-mfloat-abi=hard)
add_compile_options(-Wall)
add_compile_options(-fPIC)


Unfortunately TensorFlow and WebRTC can be cross-compiled only... ;-(

For Raspberry Pi 3B+ all is working fine...

CMake for RPI 3B+
add_compile_options(-march=armv8-a+crc)
add_compile_options(-mfpu=neon-fp-armv8)
add_compile_options(-mtune=cortex-a53)
add_compile_options(-mfloat-abi=hard)
add_compile_options(-Wall)
add_compile_options(-fPIC)

**Comment by bvarbanov** [comment]
fix: auto b = static_cast<double>(a);

**Comment by bvarbanov** [comment]
Fix: auto b = (double)a;
`auto b=static_cast<dobule>(a);`
