### ISSUE TITLE
Strict aliasing violation in raw_hash_set.h

### ISSUE THREAD

**Issue by JustusSchwan** [abseil/abseil-cpp#617]
When compiling a file which included `raw_hash_set.h` with `-fstrict-aliasing`, I get a strict aliasing warning:

```
abseil/absl/container/internal/raw_hash_set.h:1537:23: warning: dereferencing type-punned pointer might break strict-aliasing rules [-Wstrict-aliasing]
```

We are currently on version "lts 2018-08-09", but as far as I can tell, this specific piece of code has not changed since.

The offending statement is the `reinterpret_cast` below:

```cpp
typename std::aligned_storage<sizeof(slot_type), alignof(slot_type)>::type
    raw;
size_t total_probe_length = 0;
slot_type* slot = reinterpret_cast<slot_type*>(&raw);
```

From [this article about mozilla's AlignedStorage](https://whereswalden.com/2017/02/27/a-pitfall-in-c-low-level-object-creation-and-storage-and-how-to-avoid-it/) I got the impression that this is in fact UB and the reinterpret cast should be replaced by a placement-new, but this is beyond what I usually deal with.

**Comment by CJ-Johnson** [comment]
Hello @JustusSchwan 

Thank you for the bug report! We really appreciate it. As of [b69c7d880caddfc25bf348dbcfe9d45fdd8bc6e6](https://github.com/abseil/abseil-cpp/commit/b69c7d880caddfc25bf348dbcfe9d45fdd8bc6e6), all use of `aligned_storage` in Abseil is gone, meaning this problem should not be present in the next LTS (slated for release next week).

Happy Abseiling! - CJ
