### ISSUE TITLE
Path/URL/URI manipulation utilities?

### ISSUE THREAD

**Issue by bcsgh** [abseil/abseil-cpp#619]
Feature request: 
Manipulating file paths, URIs and URLs (parsing, un-parsing, etc.) seem like the kind of "small but fiddly to do right" operation that shows up in a lot of places and which ABSL is seeking to cover.

I don't know where this would fit in the priorities, but I personally would find use for it, so I'd like to track when/if it gets done.

**Comment by derekmauro** [comment]
File may happen, but it is probably very far away. I've never used it myself, but if you can use C++17, filesystem is part of the standard library: https://en.cppreference.com/w/cpp/filesystem

I don't think URLs is anywhere on our roadmap.

**Comment by Databean** [comment]
It's not a stretch to assume that some projects using abseil follow the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html#Other_Features), which writes

> In addition to what's described in the rest of the style guide, the following C++ features may not be used:
> ...
> - The `<filesystem>` header, which does not have sufficient support for testing, and suffers from inherent security vulnerabilities.
