### ISSUE TITLE
ABSL_BUILD_DLL for Linux

### ISSUE THREAD

**Issue by BotellaA** [abseil/abseil-cpp#623]
New issue related to #573 with @asoffer.

New `ABSL_BUILD_DLL` is very interesting for windows but we cannot generate shared libraries for linux anymore. The same behavior on Linux would be awesome! Only one library to generate and link is a good idea. 

Could we indirectly set its value using the CMake `BUILD_SHARED_LIBS` variable?
Maybe by editing this [block](https://github.com/abseil/abseil-cpp/blob/master/absl/copts/AbseilConfigureCopts.cmake#L8)
```
if (BUILD_SHARED_LIBS)
  set(ABSL_BUILD_DLL TRUE)
  if (MSVC)
    set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)
  endif()
else()
  set(ABSL_BUILD_DLL FALSE)
endif()
```

**Comment by asoffer** [comment]
Thanks for bringing this to our attention. I think we'd prefer for ABSL_BUILD_DLL to only mean a DLL on windows, so I'm going to fix this in the absl_cc_library function instead

**Comment by TBK** [comment]
@asoffer Would it be possible to provide an option to build static & shared at the same time?

**Comment by asoffer** [comment]
I'm not sure what you mean by this. Are you looking for a way for shared+static to interact, or you want one command instead of two to do the build. Either way, open up a new issue for this and specify?
