### ISSUE TITLE
unresolved external symbol using absl::abseil_dll

### ISSUE THREAD

**Issue by BotellaA** [abseil/abseil-cpp#625]
I am using the new CMake tagret `abseil_dll` (made by @asoffer).
I have the correct linking command line with the `abseil_dll.lib` but I still got some linking errors:
```
error LNK2001: unresolved external symbol "private: static void const * const absl::hash_internal::CityHashState::kSeed" (?kSeed@CityHashState@hash_internal@absl@@0QEBXEB)

error LNK2001: unresolved external symbol "__int64 absl::container_internal::global_next_sample" (?global_next_sample@container_internal@absl@@3_JA)
```

Is there something missing from the `abseil_dll.lib`? Maybe something that is not exported by the `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS`? Because I have no error for `string_view` for example.

**Comment by asoffer** [comment]
I'm a bit confused how global_next_sample is showing up. Looking at https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/hashtablez_sampler.h#L187-L195, `global_next_sample` should not be declared at all in the DLL build. Can you provide reproducing build commands for this issue?

**Comment by BotellaA** [comment]
We configure abseil like [this](https://github.com/Geode-solutions/OpenGeode/blob/Absl-dll/cmake/ConfigureAbseil.cmake) and you can find the log [here](https://github.com/Geode-solutions/OpenGeode/runs/469470263?check_suite_focus=true#step:11:3750).

**Comment by BotellaA** [comment]
Why is there no PUBLIC compile option like `ABSL_CONSUME_DLL` int he `abseil_dll` target? https://github.com/abseil/abseil-cpp/blob/master/CMake/AbseilDll.cmake#L494

**Comment by BotellaA** [comment]
@asoffer So sorry for the huge delay... I finaly got time to test again. With the latest Abseil commit, I do not have the error with the `global_next_sample` anymore, however I still got the error regarding the `kSeed`:
```
error LNK2001: unresolved external symbol "private: static void const * const absl::hash_internal::CityHashState::kSeed" (?kSeed@CityHashState@hash_internal@absl@@0QEBXEB) 
```
I do have time this month I you want me to test things.

**Comment by rogeeff** [comment]
THe symbol is defined in absl/hash/internal/hash.cc. Do you see this translation unit in DLL?

**Comment by BotellaA** [comment]
How can I test that?

**Comment by rogeeff** [comment]
I am not able to reproduce this here. I observe the the file where this variable is defined among the list of DLL sources. This is private static member of the class and as long as DLL builds it should not be visible or accessed from outside. If you still observe this error at HEAD please re-open this issue.

**Comment by funrunskypalace** [comment]
you should use `add_definitions(-DABSL_CONSUME_DLL)`.
