### ISSUE TITLE
absl::Substitute relies on the undefined behavior of absl::string_view(nullptr)

### ISSUE THREAD

**Issue by qzmfranklin** [abseil/abseil-cpp#64]
OS: Ubuntu 16.04
CPU: x86_64
Compiler: clang-5.0.0 (the clang-based toolchain is fully installed under /opt/clang/5.0.0 on the OS)
branch: master (720c017)
Build using Bazel.

I tweaked the BUILD files to build when `abseil-cpp` is included as a submodule.

Here is the error message for the `absl/strings:substitute_test`:
```
Running main() from gmock_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from SubstituteDeathTest
[ RUN      ] SubstituteDeathTest.SubstituteDeath
[       OK ] SubstituteDeathTest.SubstituteDeath (336 ms)
[----------] 1 test from SubstituteDeathTest (336 ms total)

[----------] 2 tests from SubstituteTest
[ RUN      ] SubstituteTest.Substitute
Segmentation fault (core dumped)
```

Is this the correct way of reporting such issues?

**Comment by tituswinters** [comment]
If you run the test against a vanilla pull (without your local changes), does it still segfault?  
Do you have process limits enabled?
This doesn't obviously reproduce for me, and I don't see anything particularly suspect in the test you've identified.

**Comment by qzmfranklin** [comment]
Hi @tituswinters ,

I ran these tests with a vanilla pull plus my own BUILD file. And that BUILD file is constructed by consolidating all the existing BUILD.bazel files together - literally. All options, compiling flags, dependencies, and names are preserved. I would like to think that it is because I used a clang-based toolchain?

**Comment by derekmauro** [comment]
We use clang extensively and aren't aware of any issues.

We need all details to reproduce this.  Where did the compiler come from?  How did you configure it to work with bazel?  Exact state of your workspace?  Exact commands run?  Without knowing exactly what you did, it's hard look into this.

**Comment by zhangxy988** [comment]
@qzmfranklin : Could you please provide more details about the setup you use? Maybe some stack traces?
I'll try running this test when I have a Clang/libc++ 5.0 environment set up. Will keep this thread posted on the result.

**Comment by qzmfranklin** [comment]
Hi @zhangxy988 @derekmauro @tituswinters,


Thanks for all your interest and support. Here is the exact steps to reproduce this issue:

1. Get an x86_64 machine (Sandybridge or later) with the vanilla Ubuntu 16.04 LTS installed.
I never tried doing all of these inside the `xenial` docker container. It may or may not work. I believe it should. But again, I never did it myself.

2. Inside the freshly installed Ubuntu 16.04 (xenial) OS, install some packages:
```
sudo apt update
sudo apt install -y build-essential
wget https://github.com/bazelbuild/bazel/releases/download/0.9.0/bazel-0.9.0-installer-linux-x86_64.sh --output-document bazel-installer.sh
sudo sh bazel-installer.sh
wget http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz --output-document clang-5.0.1.tar.xz
tar xfJ clang-5.0.1.tar.xz
sudo mv clang+llvm-5.0.1-x86_64-linux-gnu-ubuntu-16.04 /opt/clang/5.0.1
# At this point, please verify that /opt/clang/5.0.1/bin/clang exists.
```

3. Pull a working directory and run the tests:
```
git clone https://github.com/qzmfranklin/torrent
git submodule update --init --recursive
# It will take a while. Go grab a cup of coffee :D.
bazel test third_party/cc/abseil-cpp/...
```
Then it produces the error reported in this issue:
```
INFO: Analysed 97 targets (16 packages loaded).
INFO: Found 42 targets and 55 test targets...
INFO: Writing explanation of rebuilds to 'bazel-buildlogs'
FAIL: //third_party/cc/abseil-cpp:strings_substitute_test (see /home/zhongming/.cache/bazel/_bazel_zhongming/252308e7db9d6378926a9d84bb91921c/execroot/torrent/bazel-out/linux_clang-fastbuild/testlogs/third_party/cc/abseil-cpp/strings_substitute_test/test.log)
INFO: From Testing //third_party/cc/abseil-cpp:strings_substitute_test:
==================== Test output for //third_party/cc/abseil-cpp:strings_substitute_test:
Running main() from gmock_main.cc
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from SubstituteDeathTest
[ RUN      ] SubstituteDeathTest.SubstituteDeath
[       OK ] SubstituteDeathTest.SubstituteDeath (371 ms)
[----------] 1 test from SubstituteDeathTest (371 ms total)

[----------] 2 tests from SubstituteTest
[ RUN      ] SubstituteTest.Substitute
Segmentation fault (core dumped)
================================================================================
INFO: Elapsed time: 149.651s, Critical Path: 118.72s
INFO: Build completed, 1 test FAILED, 555 total actions
//third_party/cc/abseil-cpp:algorithm_algorithm_test                     PASSED in 0.2s
... (omitted for clarity)
//third_party/cc/abseil-cpp:strings_substitute_test                      FAILED in 0.6s
  /home/zhongming/.cache/bazel/_bazel_zhongming/252308e7db9d6378926a9d84bb91921c/execroot/torrent/bazel-out/linux_clang-fastbuild/testlogs/third_party/cc/abseil-cpp/strings_substitute_test/test.log

Executed 55 out of 55 tests: 54 tests pass and 1 fails locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

Note that:
1. My custom toolchain is installed in `tools/cpp/CROSSTOOL` with name `linux_clang`. View it [here](https://github.com/qzmfranklin/torrent/blob/master/tools/cpp/CROSSTOOL). It sets the compiler to using the clang-5.0.1 installed in the previous step and uses libc++ instead of libstdc++.
2. The abseil-cpp repo in this example has the patch described in [this PR](https://github.com/abseil/abseil-cpp/issues/65). For easy reference, it is the same with the `master` branch on https://github.com/qzmfranklin/abseil-cpp and consolidated the BUILD.bazel files into a top-level BUILD file. All Bazel targets are kept intact (renaming is made to avoid name conflicts though).



Hope the above helps. It has been a while since I set up a new environment. So the above steps may have breakages. In that case, please feel free to let me know.

**Comment by derekmauro** [comment]
Thanks, that was enough information to reproduce the issue and diagnose the problem.

This is the test that is triggering the problem:
https://github.com/abseil/abseil-cpp/blob/4972c72c5cf2f27e2a0846ce9ff5d377d3f2b7af/absl/strings/substitute_test.cc#L67-L70

And specifically, the problem is that the Abseil implementation of string_view accepts string_view(nullptr), while std::string_view does not.
https://github.com/abseil/abseil-cpp/blob/4972c72c5cf2f27e2a0846ce9ff5d377d3f2b7af/absl/strings/string_view.h#L484-L498

Since you are using a C++17 compiler, absl::string_view = std:string_view.
https://github.com/abseil/abseil-cpp/blob/4972c72c5cf2f27e2a0846ce9ff5d377d3f2b7af/absl/strings/string_view.h#L33-L39

This evaded our test coverage because today we only have CI for C++17 with gcc.

Historically, Google's string_view (which was known as StringPiece before it was accepted as a C++ standard) accepted StringPiece(nullptr).  When it became accepted as a standard, it was decided that this would be undefined behavior, so there was a difference.  We never figured out how to analyze entire Google codebase and make it safe for our string_view to conform to the standard in this case.

This is now a problem we have to solve. Thank you for finding this!

**Comment by qzmfranklin** [comment]
@derekmauro Thanks for the follow up. Much appreciated!

**Comment by zhangxy988** [comment]
@qzmfranklin please check whether the bug is fixed in the last commit. Thanks!

**Comment by zhangxy988** [comment]
Verified that substitute_test passes with clang/libc++ 6.0.
@qzmfranklin Feel free to reopen if there is still problem on your side.
