### ISSUE TITLE
Error with absl::Span< const bool >

### ISSUE THREAD

**Issue by panquez** [abseil/abseil-cpp#644]
Hi all,

I am trying to use absl::Span with bool as parameter of a function following the example in span.h: 

```
// Construct a Span implicitly from a container
int MyRoutine( absl::Span< const int > a )
{
    int res{ 0 };
    for( const auto i : a )
    {
        res += i;
    }
    return res;
}

// Construct a Span implicitly from a container
int MyRoutine_bool( absl::Span< const bool > a )
{
    int res{ 0 };
    for( const auto i : a )
    {
        if( i )
            res++;
    }
    return res;
}

void test_span()
{
    std::vector< int > v = { 1, 2, 3, 4, 5 };
    const auto ri = MyRoutine( v ); // convert to Span<const T>
    std::vector< bool > vb = { true, false, true, true };
    const auto rb = MyRoutine_bool( vb ); // convert to Span<const T>
}
```

But I get a compilation issue (gcc 5.4.0 on Ubuntu 16.04): 

``` 
error: could not convert ‘vb’ from ‘std::vector<bool>’ to absl::Span<const bool>’
     const auto rb = MyRoutine_bool( vb ); // convert to Span<const T>
```

Is there something special with bool ? Or am I wrong somewhere ?

Thank you!

cc @BotellaA

**Comment by derekmauro** [comment]
> Is there something special with bool ? Or am I wrong somewhere ?

You've discovered the C++ horror known as [`std::vector<bool>`](https://en.cppreference.com/w/cpp/container/vector_bool).

`std::vector<bool>` may be implemented as a specialization that behaves similarly to `std::vector<T>`, but is more space efficient. As a result, on some implementations, it is not implemented as a continuous array, and therefore won't work with `absl::Span`. This is the case for libstdc++, which is used by GCC. Your code should work if you use Clang's libc++ as your STL implementation.
