### ISSUE TITLE
Remove use of deprecated/removed allocator typedefs

### ISSUE THREAD

**Issue by Flamefire** [abseil/abseil-cpp#651]
There are some uses of removed typedefs inside allocators. Example: https://github.com/abseil/abseil-cpp/blob/79e0dc11514df035a8d07a356f9ee1800fb2160c/absl/container/fixed_array.h#L110 uses `std::allocator<...>::pointer` which is deprecated since C++17 and removed in C++20. This makes abseil fail to compile in C++20 mode

See e.g. https://en.cppreference.com/w/cpp/memory/allocator

Available typedefs: `value_type, size_type, difference_type`

**Comment by zhangxy988** [comment]
Thanks for reporting this. It seems we need to migrate to use `allocator_traits` to replace these.
