### ISSUE TITLE
Please include a pkg-config file

### ISSUE THREAD

**Issue by espindola** [abseil/abseil-cpp#652]
pkg-config (https://www.freedesktop.org/wiki/Software/pkg-config/) is a tool for making it easy to use an installed library, regardless of the build system.

Example usage with a library that includes one:

$ pkg-config --libs protobuf
-lprotobuf -lpthread
$ pkg-config --libs protobuf --static
-lprotobuf -lpthread -lz

The --static case in particular would super useful with abseil since it is composed of many libraries.

**Comment by devjgm** [comment]
+1 to this issue. 

Installing pkg-config files is really useful and not too difficult to do as part of your cmake install build. pkg-config is commonly used in Makefiles ([example from the google-cloud-cpp project](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/quickstart/Makefile)) to find the right libs that need to be linked with. Without pkg-config files for Abseil libraries, your users need to dig into Abseil's implementation and explicitly list all of Abseil's libs and deps.

**Comment by derekmauro** [comment]
@EricWF and @suertreus volunteered to look into both this and possibly making the build more friendly with linker scripts.

**Comment by chaubunhtha** [comment]
Xin chào thế giới

**Comment by derekmauro** [comment]
For a cross-reference, we have an internal request for this filed as well (b/166312078). I believe we should do this.

**Comment by suertreus** [comment]
Fixed by eb317a701b83bf9a4f2a035d75747a3d76a48324
