### ISSUE TITLE
Error while compiling strings library

### ISSUE THREAD

**Issue by zhuangAnjun** [abseil/abseil-cpp#654]
absl/strings/internal/charconv_parse.cc:419:36: error: comparison of integer expressions of different signedness: ‘std::size_t’ {aka ‘long unsigned int’} and ‘int’ [-Werror=sign-compare]

```c++
if (post_decimal_digits >= DigitLimit<base>()) {
      // refuse to parse pathological inputs
      return result;
    } else if (post_decimal_digits > digits_left) {
      exponent_adjustment -= digits_left;
    } else {
      exponent_adjustment -= post_decimal_digits;
    }
```

I found that `digits_left` type is int but `post_decimal_digits` is unsigned long int.

**Comment by vslashg** [comment]
While we could change this, Abseil is not `-Wsign-compare` clean.  If we fixed this, other parts of Abseil would break under `-Werror=sign-compare`.

**Comment by vslashg** [comment]
(As an aside, the cmake and bazel build files under absl/copts both disable this warning.  How are you building Abseil to be seeing it?)

**Comment by zhuangAnjun** [comment]
Because I use other tools to build it called blade
