### ISSUE TITLE
Building libraries using CMake with optimized mode

### ISSUE THREAD

**Issue by bruno-viva** [abseil/abseil-cpp#656]
Hi,

The quickstart guide doesn't mention how to compile abseil with an optimized mode (e.g. -O2 with gcc): https://abseil.io/docs/cpp/quickstart-cmake.html

Are there any options to turn on optimizations?

Thanks in advance

**Comment by derekmauro** [comment]
It's the same way you do it to any other CMake project. Pass `-DCMAKE_BUILD_TYPE=Release` to the `cmake` command.

You can also take a look at our test script which tests CMake in a variety of configurations: https://github.com/abseil/abseil-cpp/blob/master/ci/linux_gcc-latest_libstdcxx_cmake.sh

**Comment by bruno-viva** [comment]
Thanks, for some reason I thought the build type wasn't working, but I had a typo in it :(
