### ISSUE TITLE
LTS releases leak symbols into the root namespace

### ISSUE THREAD

**Issue by gjasny** [abseil/abseil-cpp#657]
Hello,

If I understand correctly the [LTS](LTS.md) branches are supposed to be isolated and used side-by-side in different components within the same binary:

> An LTS branch allows you to use a known version of Abseil without interfering with other projects which may also, in turn, use Abseil.

This is implemented by putting everything into an unique namespace like `absl::lts_2020_02_25::`. However there are some libraries like `absl_dynamic_annotations` which put their symbols into the root namespace:

```
libabsl_debugging_internal.a
                 U RunningOnValgrind
libabsl_dynamic_annotations.a
00000000000000e0 T RunningOnValgrind
```

I guess this is related to #122 (which IMHO) only talks about prefixing the symbols with a static `ABSL_` prefix which would not help in the side-by-side LTS scenario.

Thanks,
Gregor

**Comment by rogeeff** [comment]
I'll look into this and report back.

**Comment by rogeeff** [comment]
This is addressed at HEAD and going to be released in upcoming LTS.
