### ISSUE TITLE
Logging library and unification with google/glog

### ISSUE THREAD

**Issue by davidzchen** [abseil/abseil-cpp#658]
While the non-public [`ABSL_RAW_LOG`](https://github.com/abseil/abseil-cpp/blob/b69c7d880caddfc25bf348dbcfe9d45fdd8bc6e6/absl/base/internal/raw_logging.h) API and the [`log_severity`](https://github.com/abseil/abseil-cpp/blob/b69c7d880caddfc25bf348dbcfe9d45fdd8bc6e6/absl/base/log_severity.h) interface exists, Abseil currently does not provide a logging library.

However, the [google/glog](https://github.com/google/glog) library open sourced years ago, while providing a full-featured logging library, [uses](https://github.com/google/glog/blob/master/WORKSPACE) [gflag/gflags](https://github.com/gflags/gflags) (which was also open sourced years ago but is no longer maintained by Google) instead of the Abseil flags library.

Further, abseil-py provides a [logging library](https://abseil.io/docs/python/guides/logging).

Are there plans to ship a proper implementation of glog with abseil-cpp on the roadmap?

**Comment by suertreus** [comment]
Yep, it's coming soon =).

The API will remind you of glog's.

**Comment by rogeeff** [comment]
Please keep refreshing the Abseil release page ;) I'll close this for now, since there is no action item for us here.

**Comment by davidzchen** [comment]
Awesome! Looking forward to it!

**Comment by hcoona** [comment]
Is there any progress? @suertreus
