### ISSUE TITLE
Switching build to C++17 causes link error

### ISSUE THREAD

**Issue by sbyma** [abseil/abseil-cpp#660]
Ubuntu 18.04, GCC 8.4.0, Bazel 1.0.0

I am compiling a cc_binary that depends on Abseil (20200225 release, using the strings library) which works fine when compiling my binary with -std=c++14, however, when I switch to -std=c++17 I get undefined symbol link errors such as

`error: undefined reference to 'absl::lts_2020_02_25::ByString::Find(std::basic_string_view<char, std::char_traits<char> >, unsigned long) const'`

I have already tried cleaning with `bazel clean --expunge` to force rebuilding everything, to no avail. Is there some setting I have to use to get Abseil to work with C++17? Any ideas on something I might be missing here? Thanks.

**Comment by sbyma** [comment]
Now I find some documentation that explains this I think, so never mind.

**Comment by zhaojinzhou** [comment]
any idea?
