### ISSUE TITLE
Documentation error for absl::ParseTime 

### ISSUE THREAD

**Issue by grantwwu** [abseil/abseil-cpp#669]
https://github.com/abseil/abseil-cpp/blob/cb52b05ea20e8d196f17b45a420c2d323e401324/absl/time/time.h#L1319 says
> Like ParseTime() above, but if the format string does not contain a UTC

but I think this should refer to the **input** string.

**Comment by grantwwu** [comment]
Actually, it's possibly correct. Is the intended meaning that if you provide a format string with a UTC offset specification (`%z/%Ez/%E*z`) that the provided `TimeZone` parameter is ignored?

**Comment by derekmauro** [comment]
It looks correct to me. The format string format needs to match the input string anyway, so in a way it refers to both. If the format string you are providing includes an offset specification, for clarity you should use the version of the function that doesn't take a time zone parameter.
