### ISSUE TITLE
VS 2017 Checked Iterators Error

### ISSUE THREAD

**Issue by scottnice** [abseil/abseil-cpp#67]
I understand there is another issue/PR relating to VS 2017 flags and Cmake builds because VS 2017 doesn't recognize the -std=c++11 compiler flag.

The flag ```/D_SCL_SECURE_NO_WARNINGS``` needs to be added to the abseil-cpp\CMakeLists.txt file in order for compilation with VS 2017 to succeed. 
``` add_definitions(/DNOMINMAX /DWIN32_LEAN_AND_MEAN=1 /D_CRT_SECURE_NO_WARNINGS /D_SCL_SECURE_NO_WARNINGS) ```

Otherwise VS considers the call to std::copy at line 544 in malloc_hook.cc to be unsafe (this is one among many).

**Comment by JonathanDCohen** [comment]
Sorry this got overlooked.  There have been some changes to malloc_hook recently I think, is this still an issue?

**Comment by scottnice** [comment]
Still getting the unchecked iterators error. It's now at line 505 in malloc_hook.cc. The call to std::copy.

**Comment by JonathanDCohen** [comment]
An internal change is out for review, and should be upstreamed in the next few days.  Thanks for the report

**Comment by derekmauro** [comment]
`malloc_hook.cc` is no longer part of the release. @scottnice is your issue fixed?

**Comment by scottnice** [comment]
Yes that fixed the issue. Thank you.
