### ISSUE TITLE
DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL not set?

### ISSUE THREAD

**Issue by mtklein** [abseil/abseil-cpp#674]
In dynamic_annotations.cc, there's a comment

  /* Compiler-based ThreadSanitizer defines
     DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL = 1
     and provides its own definitions of the functions. */

and then no-op versions of the various hooks if DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL is 0 or undefined.

I can't seem to find that DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL really is defined by compiler-based ThreadSanitizer, neither with Apple's Clang, nor with a more vanilla homebrew version, nor with Clang 8 on Linux:

$ /usr/bin/clang++ --version
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ /usr/bin/clang++ -fsanitize=thread -dM -E - </dev/null | sort | grep -i dynamic
#define __DYNAMIC__ 1

$ clang++ --version
clang version 10.0.0
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Users/mtklein/brew/Cellar/llvm/10.0.0_3/bin

$ clang++ -fsanitize=thread -dM -E - </dev/null | sort | grep -i dynamic
#define __DYNAMIC__ 1

$ clang++ --version
clang version 8.0.1-4 (tags/RELEASE_801/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ clang++ -fsanitize=thread -dM -E -</dev/null | sort | grep -i dynamic
(nothing)

Is DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL something assumed to be set in the build system (Bazel, CCake, etc.) and not the compiler?

**Comment by derekmauro** [comment]
You are correct, it is something assumed to be set by the build system, not the compiler. The comment is imprecise. Unfortunately `dynamic_annotations.cc` wasn't given the attention it needed before we released it, but @rogeeff has an effort underway to clean it up, including getting rid of `DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL`.

What problem are you actually trying to solve? I suspect you are trying to run one of the sanitizers, in which case you currently need to set a few things. See https://github.com/abseil/abseil-cpp/blob/master/ci/linux_clang-latest_libcxx_tsan_bazel.sh for a working example. We are actively working to make this easier.

**Comment by mtklein** [comment]
Yep, that's right.  This came up while investigating why some existing TSAN annotations stopped working once I started linking Abseil.  Turns out those annotations had stopped linking against the real TSAN hooks and started linking against those DYNAMIC_ANNOTATIONS_EXTERNAL_IMPL-is-not-defined empty stubs.

**Comment by StilesCrisis** [comment]
@derekmauro : reading through that bazel file, the part that immediately stands out would be:
          --copt="-DDYNAMIC_ANNOTATIONS_ENABLED=1" \
          --copt="-DTHREAD_SANITIZER" \

Are other parts relevant as well, or are those the missing defines?
When you say @rogeeff is working on this, is this something that is expected to land right away? Or is this a long-term effort?

**Comment by derekmauro** [comment]
Those are the defines you need. You may also need `--test_env="TSAN_OPTIONS=report_atomic_races=0"` if you are using some of Abseil's synchronization code.

Completely fixing all the issues in the file will take some time, but I think it is possible to fix the defines issue in the short term.

**Comment by mtklein** [comment]
I don't think there's any rush on our part.  We can work around this stuff... it was just surprising behavior having not carefully read through the Abseil code.
