### ISSUE TITLE
Document the intent and policy around "LTS" branches

### ISSUE THREAD

**Issue by 0x8000-0000** [abseil/abseil-cpp#679]
First of all thank you for the nice library. I have watched with great interest Titus' "Live at Head" talk a few years ago - it makes sense to keep pushing forward to make progress. So we'll keep updating HEAD as fast as we can.

However, there is the question of the past. And sometimes we need to be able to recreate a build from some time ago for bugfix, regression, or any other business reason. We need to be able to rely on the state of the world as it was Tuesday afternoon, three and a half years ago. Also, other open source projects are starting to depend on Abseil, and they still make releases - with submodules pointing at a commit or other in master or 'LTS' branches..

It would be very useful to have a stated policy (subject to change, naturally) that describes the intent of the "LTS" branches, and the policy of stability of the commits and tags (on the "LTS" branches or anywhere else).

Over at https://github.com/conan-io/conan-center-index/pull/1523#pullrequestreview-405626667 we're updating the Abseil package to support creating the 'gRPC' package and questions arose about the master branch being force-pushed into, or about past tags being removed.

In a world where reproducibility of builds is important, what do we need to do to be able to rely on the past being frozen?

Thank you!

**Comment by derekmauro** [comment]
The concept of live-at-head has been so widely misinterpreted that I wrote an FAQ about it: https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-live-at-head-and-how-do-i-do-it

There is no reason live-at-head is incompatible with build reproducibility.

Your other questions are probably answered by
https://abseil.io/about/compatibility
https://abseil.io/about/releases

**Comment by derekmauro** [comment]
I also read a bit of the Conan issue you linked to. I'm not sure where some of the ideas in that thread are coming from. We will not be force-pushing anything to GitHub, we will not be deleting any old LTS branches, and we will not be removing old tags.

**Comment by Minimonium** [comment]
@derekmauro Hi, Derek! Thank you for looking into it. That's good to hear.

**Comment by 0x8000-0000** [comment]
> I also read a bit of the Conan issue you linked to. I'm not sure where some of the ideas in that thread are coming from. We will not be force-pushing anything to GitHub, we will not be deleting any old LTS branches, and we will not be removing old tags.

@derekmauro Thank you for clarifying this policy specifically. I see that @Minimonium carried your message over to the other review so I'll close this ticket. We will keep packaging new LTS snapshots using the proper Git tags, and strive to use them before the "best by" date lapses :)
