### ISSUE TITLE
Will there be a hash map implementation?

### ISSUE THREAD

**Issue by ghost** [abseil/abseil-cpp#68]
As we all know `std::map` and friend are slow, is there any plan to release a hashmap with abseil?

**Comment by tituswinters** [comment]
Yep, sometime (early?) next year.
https://www.youtube.com/watch?v=ncHmEUmJZf4

**Comment by ghost** [comment]
That's very very good news.

**Comment by tituswinters** [comment]
:)

**Comment by wjywbs** [comment]
Hello, is there any progress on this? Is the flat map about the same as the one in tensorflow? I didn't find the sse instructions mentioned in the video though. Thanks.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/gtl/flatmap.h

**Comment by tituswinters** [comment]
AFAIK, the tensorflow utility APIs tend to be simple re-implementations of the things that we're shipping, at a glance that's the case for that one.

I don't have an ETA for releasing the maps that Matt was talking about.  @JonathanDCohen is poking at it, but has mostly been focusing on better cmake support and double checking exception safety.

**Comment by StephanDollberg** [comment]
Hi @tituswinters, can we reopen this for tracking reasons?

**Comment by tituswinters** [comment]
@shaindelschwartz is the new point person for this, I leave it up to her.

**Comment by shaindelschwartz** [comment]
Sure.

Current generous estimate is that we should be able to release the API by early Q3.

**Comment by jcageman** [comment]
Any update on the estimate? Thanks!

**Comment by shaindelschwartz** [comment]
We're tidying up some loose ends at this point. We're fairly confident that we will be able to release in September.

**Comment by derekmauro** [comment]
I just pushed 48cd2c3f351ff188bc85684b84a91b6e6d17d896 which contains the hash containers. Documentation should be published today as well. Please report any issues you find.

**Comment by shaindelschwartz** [comment]
https://abseil.io/blog/20180927-swisstables
