### ISSUE TITLE
Need copy constructor for absl::FixedArray

### ISSUE THREAD

**Issue by wjywbs** [abseil/abseil-cpp#70]
I'm trying to use absl::FixedArray as a function's return value and value in hash map, instead of std::vector. The size of the array is not known at compile time, while InlinedVector needs a predefined capacity. The burden of using InlinedVector is that passing InlinedVector<int, 5> to a function expecting InlinedVector<int, 10> is not compatible.

The comment in the fixed array code is "Copy and move construction and assignment are deleted because (1) you can't copy or move an array..." I agree that move construction is not needed, but copy construction is simply a copy of all elements. e.g. `absl::FixedArray(other.begin(), other.end())`

```
absl::FixedArray<int> GetIds() {
  absl::FixedArray<int> ids(5);  // some number decided at runtime, but the size is fixed
  return ids;
}

error: use of deleted function 'absl::FixedArray<T, inlined>::FixedArray(const absl::FixedArray<T, inlined>&)'
```

**Comment by ahedberg** [comment]
Many of us are out until after the new year, so you may not receive an in-depth response until then. @JonathanDCohen probably has the most knowledge here.

**Comment by JonathanDCohen** [comment]
This has been on the todo list for a while and just hasn't been done yet.  I can write this up this week although I'm not sure if it will get upstreamed until after the new year.

**Comment by wjywbs** [comment]
Thanks @JonathanDCohen and happy holidays!

**Comment by JonathanDCohen** [comment]
FixedArray now has both copy and move constructors.
