### ISSUE TITLE
ARM + musl breaks stacktrack.cc

### ISSUE THREAD

**Issue by mtahmed** [abseil/abseil-cpp#701]
When cross-compiling for ARM, `stacktrace.cc` includes `absl/debugging/internal/stacktrace_config.h`, which includes `absl/debugging/internal/stacktrace_generic-inl.inc`, which tries to include `execinfo.h` which is not available on musl. That implementation should be included with a `defined(__GLIBC__)` guard since it requires glibc.

```
# elif defined(__arm__)
// Note: When using glibc this may require -funwind-tables to function properly.
#define ABSL_STACKTRACE_INL_HEADER \
  "absl/debugging/internal/stacktrace_generic-inl.inc"
```

**Comment by kartikynwa** [comment]
Sorry for necrobumping but if you were able to build abseil-cpp on musl, can you let me know what compiler/standard you used?

Thanks and sorry again.

**Comment by mtahmed** [comment]
I used gcc 6.3. I don't set the standard – I let CMake handle it so whatever is set in CMake is what I use.

No worries! Hope that helps.
