### ISSUE TITLE
I suggest that the abseil-cpp library add the following functions

### ISSUE THREAD

**Issue by libaineu2004** [abseil/abseil-cpp#704]
I suggest that the abseil-cpp library add the following functions:
1. Multithreading and thread pool
2. Classes of singleton pattern
3. Promises

**Comment by derekmauro** [comment]
Multithreading and a thread pool will probably happen some day. As for the others, please realize that [Abseil is not a general C++ utility library](https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library).
