### ISSUE TITLE
Cannot find GTest::gmock_main in CMake

### ISSUE THREAD

**Issue by Fingolfin1196** [abseil/abseil-cpp#709]
After installing Abseil from the Arch User Repository (https://aur.archlinux.org/packages/abseil-cpp/), which adds no significant options beyond what is stated on https://abseil.io/docs/cpp/tools/cmake-installs, I get the following error from CMake:
```
Found package configuration file:

  /usr/lib64/cmake/absl/abslConfig.cmake

but it set absl_FOUND to FALSE so package "absl" is considered to be NOT
FOUND.  Reason given by package:

The following imported targets are referenced, but are missing:
GTest::gmock_main
```
The part of my `CMakeLists.txt` that concerns Abseil is:
```
find_package(absl REQUIRED)
target_link_libraries(${PROJECT_NAME} PUBLIC absl::strings)
```
I got the same error when installing Abseil manually, but have, in fact, installed both `gtest` and `gmock`, so I am not sure what causes the issue.

**Comment by AvinashSinghNido** [comment]
Where you able to solve this probelm ?

**Comment by Fingolfin1196** [comment]
Kind of, I just installed the latest Abseil LTS manually without the testing flags. My configuration command (omitting `-DCMAKE_INSTALL_LIBDIR` and `-DCMAKE_INSTALL_PREFIX`) looks like this:
```
cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
```
This differs from the command in the AUR package only by removing the testing options. Also, I had to add `-fPIC` as a compile option to be able to statically link Abseil with a shared library.

**Comment by AvinashSinghNido** [comment]
@Fingolfin1196 , I have basically tried everything but I am still getting the error, I must be missing somthing. Can you guide me through this ? 
I am trying to build cartographer but I am not able to solve this one. thanks..

**Comment by Mizux** [comment]
my bet on conformance_testing !

see: https://github.com/abseil/abseil-cpp/issues/703#issuecomment-656083938

**Comment by coryan** [comment]
Did you compile Googletest from source or are you using a version installed with your distribution?  The `FindGTest` module included with CMake does not define a `GTest::gmock_main`:

https://cmake.org/cmake/help/v3.18/module/FindGTest.html

but the GTest config file created when you install googletest from source (with CMake!) does.  I think this is the relevant link for googletest, not positive so be kind:

https://github.com/google/googletest/blob/70b90929b1da20580cad9ed996397cf04ef8f16d/googlemock/CMakeLists.txt#L123

In our builds we use something funky to define our own if needed:

https://github.com/googleapis/google-cloud-cpp/blob/a4cb5ed8695945470647ec6e4cf7f8f14e8eea52/cmake/FindGMockWithTargets.cmake#L96

**Comment by LeiZhang-Hunter** [comment]
undefined reference to `google::protobuf::internal::ArenaStringPtr::Destroy()' 如何解决
