### ISSUE TITLE
Add StringPrintf and friends to strings library

### ISSUE THREAD

**Issue by vertix** [abseil/abseil-cpp#71]
By some reason it's not here. You even refer this function in docs, see [here](https://github.com/abseil/abseil-cpp/blob/17cde19a0f8c939524295d27c3774186ac9a1d29/absl/strings/substitute.h#L48) for example

**Comment by ahedberg** [comment]
We're not planning to release StringPrintf; we'll be releasing a much better string formatting API in the next few quarters. Thanks for catching the error in documentation; I'll see if I can get that fixed.

**Comment by ahedberg** [comment]
Documentation will be fixed with the next release. Thanks again for reporting!
