### ISSUE TITLE
Error while building for musl-x86_64

### ISSUE THREAD

**Issue by kartikynwa** [abseil/abseil-cpp#713]
Hi.

I am trying to package abseil for Void Linux. On other glibc it builds as expected but on musl it throws [this error](https://gist.githubusercontent.com/kartikynwa/d48c6936c1491db058a9efc101d58f75/raw/45b5b3e72189df5d1d54363269a2c16bf4160cae/output).

I don't have much experience with C++ so any advice would be appreciated it.

If you have any questions about this, please feel free to ask. Thanks for reading this.

**Comment by rogeeff** [comment]
What compiler/standard are you using?

**Comment by kartikynwa** [comment]
Hello. Very sorry for that including that in the issue.

The compiler is C++ and standard is 17. This one:

```
c++17
c++1z
    The 2017 ISO C++ standard plus amendments.  The name c++1z is
    deprecated.
```
edit: Using `cmake` because my distro doesn't provide Bazel.

**Comment by kartikynwa** [comment]
Actually, I was using `-DCMAKE_CXX_STANDARD=17` based on the AUR template (I don't know anything about c++) but I removed it and rebuilt and it succeeded on musl. Closing this. Thanks for pointing in the right direction.
