### ISSUE TITLE
Undefined symbols for architecture x86_64 when compiling on macOs Catalina

### ISSUE THREAD

**Issue by minqz2009** [abseil/abseil-cpp#715]
Compile with apple clang

`Undefined symbols for architecture x86_64:
  "absl::container_internal::UnsampleSlow(absl::container_internal::HashtablezInfo*)", referenced from:
      absl::container_internal::HashtablezInfoHandle::~HashtablezInfoHandle() in test-a0f084.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Compiler information:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by rogeeff** [comment]
Do you link against Abseil Library?

**Comment by derekmauro** [comment]
You probably aren't linking against a dependency that you need. Can you give us the steps to reproduce this problem?
