### ISSUE TITLE
absl::disjunction breaks in on gcc 4.8

### ISSUE THREAD

**Issue by devjgm** [abseil/abseil-cpp#718]
When trying to replace my project's custom `disjunction` type with `absl::disjunction` (https://github.com/googleapis/google-cloud-cpp/pull/4409) we came across a weird build break ([build log](https://source.cloud.google.com/results/invocations/4e3abc82-c6c7-48aa-b0ac-72d165fd4371/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fgcc-4.8-presubmit/log)):

```
...
/v/google/cloud/storage/internal/tuple_filter.h:154:78: internal compiler error: in retrieve_specialization, at cp/pt.c:1023
       absl::disjunction<std::is_same<typename std::decay<T>::type, Types>...>;
                                                                              ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Preprocessed source stored into /tmp/ccL9oH9l.out file, please attach this to your bugreport.
```

It's an internal compiler error from gcc-4.8 that's complaining about a particular weird (though from real-world code) invocation. I managed to create a small repro case in godbolt: https://godbolt.org/z/i7-AmM

As you can see in the godbolt code, there is a way that Abseil _could_ work around this compiler bug by _defining_ the base template rather than just declaring it then specializing it for `<>`. Here's a diff of the change that I believe avoids the issue:
https://github.com/abseil/abseil-cpp/compare/master...devjgm:fix-disjunction-on-gcc-4-8

I realize that gcc 4.8 is old, and perhaps unsupported by Abseil. But whatever your policies, I wanted to file this issue anyway.

**Comment by devjgm** [comment]
... obviously I can turn https://github.com/abseil/abseil-cpp/compare/master...devjgm:fix-disjunction-on-gcc-4-8 into a PR if that's at all helpful.

**Comment by derekmauro** [comment]
[GCC 4.8 has been unsupported since August 2019](https://abseil.io/docs/cpp/platforms/platforms), however, the proposed fix is simple enough and not a maintenance burden. Feel free to send a CL (Googlers should use the internal code review process).

**Comment by devjgm** [comment]
Thanks I'll send a CL. I was looking for the supported compilers page and couldn't find it. Thanks for the link, where it clearly says that gcc 4.8 is unsupported :smile:
