### ISSUE TITLE
Any interest in implementing the math functions C++17?

### ISSUE THREAD

**Issue by FranklinYu** [abseil/abseil-cpp#719]
See https://en.cppreference.com/w/cpp/numeric. Things that come to mind are `std::gcd()` and `std::lcm()`. The only implementation that I know is [`boost::integer::gcd()` and `boost::integer::lcm()`](https://www.boost.org/doc/libs/1_73_0/libs/integer/doc/html/boost_integer/gcd_lcm.html).

**Comment by derekmauro** [comment]
No. We generally only release APIs that have high Google-internal usage (1000s of callers). These don't appear to meet that bar.
