### ISSUE TITLE
Remove use of deprecated allocator members and types

### ISSUE THREAD

**Issue by DmitryTsyganov** [abseil/abseil-cpp#722]
There are uses of allocator members and types that were deprecated in C++17 and removed in C++20. Examples:

Members:
https://github.com/abseil/abseil-cpp/blob/10cb35e459f5ecca5b2ff107635da0bfa41011b4/absl/memory/memory.h#L576
[https://en.cppreference.com/w/cpp/memory/allocator/construct](https://en.cppreference.com/w/cpp/memory/allocator/construct)

https://github.com/abseil/abseil-cpp/blob/10cb35e459f5ecca5b2ff107635da0bfa41011b4/absl/memory/memory.h#L587
[https://en.cppreference.com/w/cpp/memory/allocator/destroy](https://en.cppreference.com/w/cpp/memory/allocator/destroy)

Types:
https://github.com/abseil/abseil-cpp/blob/10cb35e459f5ecca5b2ff107635da0bfa41011b4/absl/memory/memory.h#L355
[rebind in **Member types**](https://en.cppreference.com/w/cpp/memory/allocator)

This makes abseil fail to compile in C++20 mode and in C++17 mode if warnings are treated as errors.

Can be replaced with their substitutes from [https://en.cppreference.com/w/cpp/memory/allocator_traits](https://en.cppreference.com/w/cpp/memory/allocator_traits)

**Comment by sbenzaquen** [comment]
All of those are guarded. They are only used if present, as it is specified in the contract for `allocator_traits`.
Is there a repro of this actually failing in C++20?
The traits should just fallback gracefully.

**Comment by DmitryTsyganov** [comment]
It does work, my bad.
The problem is only with  C++17 if warnings are treated as errors.

**Comment by sbenzaquen** [comment]
This warning should go away after c03c18e7fef8d06eb6c445f5607af533e69cadfe.

**Comment by BenFrantzDale** [comment]
> It does work, my bad.
> The problem is only with C++17 if warnings are treated as errors.

Yeah, I'm on C++17 with warnings treated as errors and this is a pain. I'd rather not have to `#define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING`.

**Comment by GindaChen** [comment]
> Is there a repro of this actually failing in C++20?

@sbenzaquen We happen to encounter a C++20 build failure [in this repo issue](https://github.com/UWHustle/hustle/issues/97). Right now we are trying to separate a small enough example as a repro.

**Comment by sbenzaquen** [comment]
> > Is there a repro of this actually failing in C++20?
> 
> @sbenzaquen We happen to encounter a C++20 build failure [in this repo issue](https://github.com/UWHustle/hustle/issues/97). Right now we are trying to separate a small enough example as a repro.

That particular issue has already been fixed in https://github.com/abseil/abseil-cpp/commit/db5773a721a50d1fc8c9b51efea0e70be4003d36

**Comment by GindaChen** [comment]
Awesome! Thanks for your notice! We were using an older version of `arrow`, carried with the older version of `absl`. Hopefully when we upgrade the `absl` version the error will go away.

**Comment by bstaletic** [comment]
This is causing about 40k lines of warnings in [ycmd](https://github.com/ycm-core/ycmd/runs/2431697697?check_suite_focus=true#step:8:211).

**Comment by derekmauro** [comment]
@bstaletic - It seems strange that code is being compiled at all in C++17 mode. I wonder if it is due to https://devblogs.microsoft.com/cppblog/msvc-now-correctly-reports-__cplusplus/. What happens if you add `/Zc:__cplusplus` to the MSVC compile options?

**Comment by derekmauro** [comment]
It looks like we should to use `_MSVC_LANG` to detect the C++ dialect. I think that should fix this issue under MSVC.

**Comment by bstaletic** [comment]
Tested with `/Zc:__cplusplus` and it worked. I have PR submitted for ycmd that adds the flag if run under MSVC.

A note somewhere that users are expected to use that flag would be nice.

**Comment by derekmauro** [comment]
My previous comment, that we should use `_MSVC_LANG`, should make `/Zc:__cplusplus` not needed.

**Comment by derekmauro** [comment]
I think this is now fixed.
