### ISSUE TITLE
Failed to bazel build master branch with clang 8 & libstdc++ from gcc 4.9.2

### ISSUE THREAD

**Issue by hcoona** [abseil/abseil-cpp#731]
Hi Abseil team, I'm failing to build master branch with clang & libstdc++ from gcc 4.9.2 with details below.

## Environment

* clang: clang version 8.0.0 (tags/RELEASE_800/final)
* gcc: gcc (Debian 4.9.2-10+deb8u2) 4.9.2
* bazel: 3.3.1
* os-release: PRETTY_NAME="Debian GNU/Linux 8 (jessie)"  (I know it's pretty old, but the compiler chain matters more)
* abseil commit id: 38db52adb2eabc0969195b33b30763e0a1285ef9

## Reproduce steps

```
git clone https://github.com/abseil/abseil-cpp
cd abseil-cpp
git checkout 38db52adb2eabc0969195b33b30763e0a1285ef9
bazel build //absl/container:btree_test
```

## Error messages

I think the most useful pieces are:

```
In file included from absl/container/btree_test.cc:15:
In file included from ./absl/container/btree_test.h:25:
In file included from ./absl/container/btree_map.h:50:
./absl/container/internal/btree.h:1935:15: error: no matching constructor for initialization of 'absl::container_internal::btree<absl::container_internal::map_params<std::vector<void *, std::allocator<void *> >, int, std::less<std::vector<void *, std::allocator<void *> > >, std::allocator<std::pair<const std::vector<void *, std::allocator<void *> >, int> >, 256, false> >::init_type' (aka 'pair<std::vector<void *, std::allocator<void *> >, int>')
    init_type value(*b);
              ^     ~~
./absl/container/internal/btree_container.h:292:17: note: in instantiation of function template specialization 'absl::container_internal::btree<absl::container_internal::map_params<std::vector<void *, std::allocator<void *> >, int, std::less<std::vector<void *, std::allocator<void *> > >, std::allocator<std::pair<const std::vector<void *, std::allocator<void *> >, int> >, 256, false> >::insert_iterator_unique<const std::pair<int, int> *>' requested here
    this->tree_.insert_iterator_unique(b, e, 0);
                ^
```

Full logs below:

```
bazel build --verbose_failures //absl/container:btree_test
```

[build_log.txt](https://github.com/abseil/abseil-cpp/files/4882232/build_log.txt)

**Comment by hcoona** [comment]
I can build abseil with gcc 4.9.2.

**Comment by hcoona** [comment]
```
#include <cstdio>

int main(void) {
        printf("%d\n", __GLIBCXX__);
        return 0;
}
```

Would print:

```
20141220
```

**Comment by hcoona** [comment]
It's still failing after added "--cxxopts=-std=c++17":

```
bazel build --cxxopt="-std=c++17" --verbose_failures //absl/container:btree_test
```

[build_log.txt](https://github.com/abseil/abseil-cpp/files/4882235/build_log.txt)

**Comment by hcoona** [comment]
Found following macros:

```
// GCC 4.9 has a bug in the std::pair constructors that prevents explicit
// conversions between pair types.
#if defined(__clang__) || !defined(__GNUC__) || __GNUC__ >= 5
```

However, the `std::pair` bug is related to libstdc++ rather than gcc. We should detect the libstdc++ instead of gcc version.

How about this?

```
#if !defined(__GLIBCXX__) || __GLIBCXX__ > 20141220L
```

**Comment by EricWF** [comment]
You're right that we should detect the libstdc++ version instead of the compiler version.
Unfortunatly detecting the libstdc++ version isn't as simple as using `__GLIBCXX__`, because that macro notes the release date of the library., and, for example, libstdc++ 4.9.5 was released after libstdc++ 7. 

But I think with a little more finess we can find the right incantation
