### ISSUE TITLE
[Feature Request] Need basic_string_view

### ISSUE THREAD

**Issue by hcoona** [abseil/abseil-cpp#734]
I want basic_string_view for other char types. On windows, wchar is quite useful talking with Windows API. It would be great to have absl::basic_string_view to support it.

**Comment by rogeeff** [comment]
Long story short, we do not have an incentive to support this. This is pretty massive effort, including all the other string interfaces Abseil supports and Google first party users did not request it. In a few years we'll all migrate to C++17's std::string_view, which does everything you want already. Can you use that?

**Comment by hcoona** [comment]
For who still interested to this topic, please go #124 for a more detailed discussion.
