### ISSUE TITLE
CMake absl::base target missing gtest dependency

### ISSUE THREAD

**Issue by prateekr** [abseil/abseil-cpp#74]
Unlike the bazel build file, CMakeLists doesn't have a build dependency on gtests when building the absl::base library.  This dependency is required to compile the source of https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/exception_safety_testing.h#L28.

I think the CMakeLists file in absl/base should also pull in gtest as an external project similar to what bazel does below:  

https://github.com/abseil/abseil-cpp/blob/4132ce25956a91e1224e0f205b7f8c326304a995/absl/base/BUILD.bazel#L231-L247

**Comment by JonathanDCohen** [comment]
This is a test only library.  I think the correct solution is to turn this library off when we turn off test builds as we currently recommend for using Abseil with CMake.  Sound good?

**Comment by prateekr** [comment]
Yep, makes sense.
