### ISSUE TITLE
CMake error due to "CMP0077"

### ISSUE THREAD

**Issue by veblush** [abseil/abseil-cpp#742]
From July 15, one of gRPC tests with the HEAD of Abseil started failing with the error message;

```
CMake Error at third_party/abseil-cpp/CMakeLists.txt:34 (cmake_policy):
  Policy "CMP0077" is not known to this version of CMake.
```

This policy is available from CMake 3.13 ([ref](https://cmake.org/cmake/help/git-stage/policy/CMP0077.html)) and we use CMake 3.6.2 which is higher than 3.5 which Abseil claims as the minimum version to support.

**Comment by Mizux** [comment]
Sorry my bad, we need it for google/or-tools since we are using `FetchContent()`.

I just sent a patch which should fix it, sorry for the inconvenience...

**Comment by veblush** [comment]
Confirmed that it fixed our test. Thanks!
