### ISSUE TITLE
FormatDuration Consistency

### ISSUE THREAD

**Issue by alwayswimmin** [abseil/abseil-cpp#745]
Right now, `absl::Duration` increments in steps of 0.25ns, though documentation says not to depend on implementation details past 1ns. However, for an _integral_ duration of nanoseconds `d`, can I expect `FormatDuration(d)` to give me the same string each time, or is there no such guarantee as the library updates?

**Comment by derekmauro** [comment]
Good question. I don't see a formal guarantee anywhere, but I don't expect we would ever change this. I'm not sure what your use case is, but I would also expect that any `absl::Duration` will always round trip (such as ` d == absl::ParseDuration(absl::FormatDuration(d))`) even after a library update, which definitely would limit our ability to change this.
