### ISSUE TITLE
absl::Substitude can not work

### ISSUE THREAD

**Issue by xjy198903** [abseil/abseil-cpp#753]
I download the master code ,and use cmake to make library, when I use the API 'absl::Substitute',it shows :

substitute.cc:47: undefined reference to `absl::CEscape[abi:cxx11](absl::string_view)'

#include <iostream>
#include "absl/strings/substitute.h"

using namespace std;

int main() {

//    std::cout << "Hello, World!" << std::endl;
    string s = absl::Substitute("Content-Length:$0",100);
//    string s;

    return 0;

}

**Comment by derekmauro** [comment]
Please post full reproduction instructions. The problem is impossible to diagnose without knowing exactly what you did.

However, if I had to guess, it is probably https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil

**Comment by xjy198903** [comment]
@derekmauro I just use cmake to make library,and the example is wrote by myself to test the library,the CmakeLists.txt is below:
[CMakeLists.txt](https://github.com/abseil/abseil-cpp/files/5019776/CMakeLists.txt)

Tips:
The IDE is QtCreator

After the library is generated, I use a shell script to integrate all the libraries into one library,called libabsl.a,the shell script is below:
[1.txt](https://github.com/abseil/abseil-cpp/files/5019789/1.txt)

**Comment by derekmauro** [comment]
Unfortunately we can't look into why every custom workflow doesn't work. I strongly recommend using one of the supported build systems to link everything together.

https://abseil.io/docs/cpp/quickstart
https://abseil.io/docs/cpp/quickstart-cmake
