### ISSUE TITLE
Consider using SipHash instead of CityHash to protect against hash flooding attacks

### ISSUE THREAD

**Issue by rigtorp** [abseil/abseil-cpp#756]
Since CityHash (used by `asbl::hash`) has been shown to be weak with respect to hash flooding attacks (https://131002.net/siphash/siphashdos_appsec12_slides.pdf) it's worth considering replacing it with SipHash (https://131002.net/siphash/). SipHash seems to have received more security analysis than CityHash.

**Comment by derekmauro** [comment]
We are considering replacing CityHash, but not with SipHash, as the performance would suffer too much. We do randomize our hashes, which provides a good (but not perfect, as the slides show) default. I think if hash-flooding is a concern, you need to do a detailed threat analysis and decide if using a stronger hash function is good enough, or if you need to go further and use a different data structure altogether.
