### ISSUE TITLE
tests don't pass

### ISSUE THREAD

**Issue by bmusin** [abseil/abseil-cpp#76]
## What I did
Was going through [quickstart](https://abseil.io/docs/cpp/quickstart).

I checked out source.
`git clone https://github.com/abseil/abseil-cpp.git`
Created directory.
`mkdir Source`
Entered it.
`cd Source`
Run tests.
`bazel test absl/...:all`

## What happened
They didn't pass:
```
ERROR: /opt/bmusin/Source/abseil-cpp/absl/debugging/BUILD.bazel:129:1: no such package '@com_google_googletest//': Error downloading [https://github.com/google/googletest/archive/master.zip] to /home/bulat/.cache/bazel/_bazel_bulat/c26b823ebcf2d54bae8cd5b9b6d47d60/external/com_google_googletest/master.zip: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//absl/debugging:leak_check_test'
ERROR: Analysis of target '//absl/debugging:leak_check_test' failed; build aborted: Loading failed
INFO: Elapsed time: 20.467s
FAILED: Build did NOT complete successfully (23 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```
(df3af0d03c0d790aa784235e9913f3d8cb9cdb16)

### My bazel
Build label: 0.9.0- (@non-git)
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 5 09:33:20 +49996 (1515570255200)
Build timestamp: 1515570255200
Build timestamp as int: 1515570255200

### My JDK
openjdk-8-jdk/artful-updates,artful-security,now 8u151-b12-0ubuntu0.17.10.2 amd64 [installed]
openjdk-8-jdk-headless/artful-updates,artful-security,now 8u151-b12-0ubuntu0.17.10.2 amd64 [installed,automatic]
openjdk-8-jre/artful-updates,artful-security,now 8u151-b12-0ubuntu0.17.10.2 amd64 [installed]
openjdk-8-jre-headless/artful-updates,artful-security,now 8u151-b12-0ubuntu0.17.10.2 amd64 [installed,automatic]

Thanks.

**Comment by derekmauro** [comment]
I think you are missing some steps in your "What I did" section, but from the error message you are getting `java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`, I suspect Java doesn't have TLS configured correctly.  Do you have the `ca-certificates-java` package installed?

**Comment by bmusin** [comment]
Yes, I have it installed. "20170930" version - in terms of Ubuntu's apt.

**Comment by derekmauro** [comment]
What does your WORKSPACE file look like?

**Comment by bmusin** [comment]
```
workspace(name = "com_google_absl")
# GoogleTest/GoogleMock framework. Used by most unit-tests.
http_archive(
     name = "com_google_googletest",
     urls = ["https://github.com/google/googletest/archive/master.zip"],
     strip_prefix = "googletest-master",
)

# CCTZ (Time-zone framework).
http_archive(
    name = "com_googlesource_code_cctz",
    urls = ["https://github.com/google/cctz/archive/master.zip"],
    strip_prefix = "cctz-master",
)

# RE2 regular-expression framework. Used by some unit-tests.
http_archive(
    name = "com_googlesource_code_re2",
    urls = ["https://github.com/google/re2/archive/master.zip"],
    strip_prefix = "re2-master",
)
```

**Comment by derekmauro** [comment]
This looks like the Abseil WORKSPACE file (from the `workspace(name = "com_google_absl")` line).  It doesn't look like you've created a WORKSPACE file for your personal project.

In the [Quickstart](https://abseil.io/docs/cpp/quickstart) see the section "Linking Your Code to the Abseil Repository".  I don't think you've completely followed it.

If you want more help you'll need to post the exact commands you've run.  Your "What I did" section is missing some steps.

**Comment by bmusin** [comment]
@derekmauro, I just followed tutorial literally and run commands as was said in quickstart(just in /opt/bmusin, not ~ directory.) and stuck on bazel test absl/...:all line.

"Linking Your Code to the Abseil Repository" section is lower than the line where I encountered
problem.

**Comment by derekmauro** [comment]
Does it work if you try it in the ~ directory?

**Comment by bmusin** [comment]
Yes, it gives:
```
......................................
ERROR: /home/bulat/Source/abseil-cpp/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': Error downloading [https://github.com/google/cctz/archive/master.zip] to /home/bulat/.cache/bazel/_bazel_bulat/f1a44aa9b91431a3a92b0471d02f54b7/external/com_googlesource_code_cctz/master.zip: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//absl/time:time'
ERROR: /home/bulat/Source/abseil-cpp/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': Error downloading [https://github.com/google/cctz/archive/master.zip] to /home/bulat/.cache/bazel/_bazel_bulat/f1a44aa9b91431a3a92b0471d02f54b7/external/com_googlesource_code_cctz/master.zip: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//absl/time:time'
ERROR: Analysis of target '//absl/time:time' failed; build aborted: Loading failed
INFO: Elapsed time: 21.766s
FAILED: Build did NOT complete successfully (23 packages loaded)
ERROR: Couldn't start the build. Unable to run tests
```

**Comment by derekmauro** [comment]
I'm pretty confident this isn't an Abseil issue.  It sounds like something is wrong with the Java/TLS configuration on your system.  You might want to try some of the suggestions in https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty, but I don't think we are going to be able to help you.

**Comment by bmusin** [comment]
@derekmauro, tested today without updating the repo - tests passed.

**Comment by derekmauro** [comment]
Great to hear that!
