### ISSUE TITLE
Please add `NOMINMAX` to the default value of `ABSL_CC_LIB_DEFINES`  on Windows by default

### ISSUE THREAD

**Issue by jeremyong** [abseil/abseil-cpp#761]
It appears that the issue of macro collision with the `max` macro defined in `Windows.h` is a perennial issue, so it would be great if all libraries just added that compile definition when compiling on Windows. This is a problem in a number of places that rely on `std::numeric_limits<T>::max()` on the tip of the main branch currently,

`ABSL_CC_LIB_DEFINES` was the variable I found that conveniently enables this when scanning the cmake files.

Thanks,
Jeremy

**Comment by derekmauro** [comment]
Can you please let us know the exact issue you are seeing?

Our headers don't include `windows.h`. We also use parentheses like this
https://github.com/abseil/abseil-cpp/blob/ce4bc927755fdf0ed03d679d9c7fa041175bb3cb/absl/numeric/int128.h#L245
in our headers which should workaround the problem.

Finally, we also build with `/DNOMINMAX`:
https://github.com/abseil/abseil-cpp/blob/ce4bc927755fdf0ed03d679d9c7fa041175bb3cb/absl/copts/GENERATED_AbseilCopts.cmake#L49

Please let us know if we've missed something.

**Comment by jeremyong** [comment]
They don't do that everywhere, I don't believe (based on a codebase wide search). I did see that that was the resolution for the previous issue though. The option doesn't seem to be kicking in for some reason. Just compiling on windows when the project is included transitively using `add_subdirectory` will result in a failure (using clang, aka /DNOMINMAX is not correct). You need the compile definition NOMINMAX.

**Comment by jeremyong** [comment]
@derekmauro Thanks for pointing out the usage of `/DNOMINMAX`, I can confirm the issue is specifically when GCC or Clang is used on Windows (as opposed to clang-cl or MSVC). GCC/clang option syntax is different, so the options should be added with the compiler/platform-independent cmake directive `target_compile_definitions` or `add_compile_definitions` instead.
