### ISSUE TITLE
JSON / XML parser

### ISSUE THREAD

**Issue by SahibYar** [abseil/abseil-cpp#767]
Does Abseil authors have any plan for handling JSON and/or xml as an extended datatypes for all of Abseil containers.
Also it would be great if Abseil can provide a fast Json / XML parser to general public.

**Comment by derekmauro** [comment]
Abseil has no plans for this. My favorite way to parse JSON in C++ is to [parse it to a Protocol Buffer](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/util/json_util.h).
