### ISSUE TITLE
Abseil should have proper commit history

### ISSUE THREAD

**Issue by pps83** [abseil/abseil-cpp#775]
**Describe the bug**

We use absl in our project but we use specific version (because absl's version that we use is pulled by another 3rd party project that requires specific absl version).
For various reason we made some changes here and there, but then we discovered a bug related to clumsy attempt to force define `_HAS_EXCEPTIONS=1` on windows that actually ended up force undefining it. I checked latest master and clearly this bug is already removed from absl. I wanted to cherry pick that commit to our local copy of absl to avoid merge issues later when I update to another absl version. When I wanted to do that, it appears that absl give nice history of nameless code dumps.

...

**Comment by derekmauro** [comment]
This is on our long TODO list.

**Comment by pps83** [comment]
By the way, you might consider even force pushing proper history, or provide alternative master2 branch that has proper history

**Comment by benjaminp** [comment]
See #246 for previous discussion.

**Comment by derekmauro** [comment]
As of today, thanks to @dinord, commits are now individually exported!
