### ISSUE TITLE
Status::Update()'s intended use cases might need more explanation

### ISSUE THREAD

**Issue by yzhao1012** [abseil/abseil-cpp#779]
It appears that Status::Update() means to keep the first countered error, of multiple sequential operations that have to happen regardless of the errors in the previous operation(s). For example:

```
absl::Status foo1() { ... }
absl::Status foo2() { ... }
...

absl::Status foo_wrapper() {
  auto status = foo1();
  status.Update(foo2());
  status.Update(...);
  return status;
}
```

TBH, I never wrote code like these. And I always wanted to have early termination on the first error.

In that case, Status::Update() is not useful at all.

Are my understandings correct?

**Comment by linLIn143** [comment]
Yes I think so, thank you so much

**Comment by derekmauro** [comment]
I agree that it is hard to imagine when I would use this method (and I've never used the method myself). One possible use I can think of is an operation that has multiple sub-operations happening in parallel, possibly in different threads. I can imagine in that case early termination might be complicated.

**Comment by thooria** [comment]
-
