### ISSUE TITLE
Cut a new LTS release with absl::StatusOr

### ISSUE THREAD

**Issue by sfc-gh-ebrossard** [abseil/abseil-cpp#788]
Not a bug report, per se, but the current LTS release is from about seven months ago, and has `absl::Status` but not `absl::StatusOr`. It would be great if you could cut a new release that includes it.

The guidance in https://abseil.io/about/releases says:
> These snapshots are available as “Long Term Support” (LTS) branches of Abseil, and we intend to provide a new snapshot every 6 months or so.

Thank a lot!
-Elliott

**Comment by derekmauro** [comment]
We've been working on this, expect it soon.

**Comment by linLIn143** [comment]
Do you think I was hacked?

**Comment by derekmauro** [comment]
https://github.com/abseil/abseil-cpp/releases/tag/20200923
