### ISSUE TITLE
failure handler crashes on aarch64

### ISSUE THREAD

**Issue by romange** [abseil/abseil-cpp#805]
**Describe the bug**
When running `absl_failure_signal_handler_test` in debug mode on aarch64 it fails at assertion:
```
absl_failure_signal_handler_test: ../absl/debugging/internal/stacktrace_aarch64-inl.inc:45: const unsigned char* GetKernelRtSigreturnAddress(): Assertion `false && "VDSO is present, but doesn't have expected symbol"' failed.
```
   
**Steps to reproduce the bug**

1. 
```
> cmake .. -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Debug  -DABSL_RUN_TESTS=ON \
    -DABSL_USE_GOOGLETEST_HEAD=ON -GNinja
```
2. `ninja absl_failure_signal_handler_test`
3.  `./bin/absl_failure_signal_handler_test` gets stuck at `FailureSignalHandlerDeathTest.AbslFailureSignal` in a infinite loop. But in gdb one can see the aforementioned assertion. 

**What version of Abseil are you using?**
master

**What operating system and version are you using**
ubuntu 20.04

If you are using a Linux distribution please include the name and version of the
distribution as well.
ubuntu 20.04

**What compiler and version are you using?**
gcc 9.3

**Add any other context about the problem here.**

line absl/debugging/internal/stacktrace_aarch64-inl.inc:40 has 
```
    if (!vdso.LookupSymbol("__kernel_rt_sigreturn", "LINUX_2.6.39", STT_FUNC,
                           &symbol_info) ||
```
but my aarch64 system has `__kernel_rt_sigreturn` symbol of type `STT_NOTYPE` (0).
If I replace the line with 
```
    if (!vdso.LookupSymbol("__kernel_rt_sigreturn", "LINUX_2.6.39", STT_NOTYPE, &symbol_info)
```
the test passes.

**Comment by rogeeff** [comment]
Can you send us a pull request with this change? This way we can see if it passes test on all platforms.

**Comment by romange** [comment]
@rogeeff  Sent https://github.com/abseil/abseil-cpp/pull/827

**Comment by EmployedRussian** [comment]
Roman Gershman,

There appears to be something wrong with your kernel build if your `__kernel_rt_sigreturn` has `STT_NOTYPE`.
What is the provenance of your kernel?

Here is what I see in our `3.18.21` kernel:

```
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000300     0 SECTION LOCAL  DEFAULT    7
     2: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS LINUX_2.6.39
     3: 0000000000000460    80 FUNC    GLOBAL DEFAULT    7 __kernel_clock_getres@@LINUX_2.6.39
     4: 0000000000000510     8 FUNC    GLOBAL DEFAULT    7 __kernel_rt_sigreturn@@LINUX_2.6.39
     5: 0000000000000300    92 FUNC    GLOBAL DEFAULT    7 __kernel_gettimeofday@@LINUX_2.6.39
     6: 0000000000000360   244 FUNC    GLOBAL DEFAULT    7 __kernel_clock_gettime@@LINUX_2.6.39
```

Now, it might be reasonable to accept _either_ `STT_NOTYPE` _or_ `STT_FUNC`, but your change "as-is" is not correct.

**Comment by EmployedRussian** [comment]
Same result for 4.19 kernel as well:
```
Symbol table '.dynsym' contains 6 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 OBJECT  GLOBAL DEFAULT  ABS LINUX_2.6.39
     2: 0000000000000634    80 FUNC    GLOBAL DEFAULT    7 __kernel_clock_getres@@LINUX_2.6.39
     3: 0000000000000688     8 FUNC    GLOBAL DEFAULT    7 __kernel_rt_sigreturn@@LINUX_2.6.39
     4: 0000000000000300   164 FUNC    GLOBAL DEFAULT    7 __kernel_gettimeofday@@LINUX_2.6.39
     5: 00000000000003a4   656 FUNC    GLOBAL DEFAULT    7 __kernel_clock_gettime@@LINUX_2.6.39
```

**Comment by romange** [comment]
I've used any recent ubuntu-built kernel from here: https://kernel.ubuntu.com/~kernel-ppa/mainline/

For example, I verified with https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.9.1/ that when I install it over 18.04, 
the symbols above are present with `STT_NOTYPE`. I confirm that vanilla 18.04 has  `STT_FUNC` symbols.

Will you agree to accept the fix that checks for both options?

**Comment by EmployedRussian** [comment]
> Will you agree to accept the fix that checks for both options?

That sounds reasonable to me.

**Comment by romange** [comment]
PR updated.
