### ISSUE TITLE
Does not compile using powerpc32 bit

### ISSUE THREAD

**Issue by Antezedens** [abseil/abseil-cpp#809]
**Describe the bug**

when trying to compile absl using a powerpc 32-bit compiler i get the following error:
In file included from /home/fuchs/Downloads/abseil-cpp-20200923/absl/debugging/stacktrace.cc:46:
/home/fuchs/Downloads/abseil-cpp-20200923/absl/debugging/internal/stacktrace_powerpc-inl.inc: In function 'void** NextStackFrame(void**, const void*)':
/home/fuchs/Downloads/abseil-cpp-20200923/absl/debugging/internal/stacktrace_powerpc-inl.inc:134:64: error: 'const union ucontext_t::uc_regs_ptr' has no member named 'gp_regs'; did you mean 'uc_regs'?
           reinterpret_cast<void**>(signal_context->uc_mcontext.gp_regs[PT_R1]);
                                                                ^~~~~~~
                                                                uc_regs

**Steps to reproduce the bug**

Use a powerpc 32 bit cross-compiler.

**What version of Abseil are you using?**

20200903 LTS

**What operating system and version are you using**

Ubuntu 19.10

**What compiler and version are you using?**

12:02:22 2066> powerpc-linux-gnu-g++ -v
Using built-in specs.
COLLECT_GCC=powerpc-linux-gnu-g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc-cross/powerpc-linux-gnu/9/lto-wrapper
Target: powerpc-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-9ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --disable-libphobos --enable-secureplt --disable-softfloat --with-cpu=default32 --disable-softfloat --enable-targets=powerpc-linux,powerpc64-linux --enable-multiarch --disable-werror --with-long-double-128 --enable-multilib --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=powerpc-linux-gnu --program-prefix=powerpc-linux-gnu- --includedir=/usr/powerpc-linux-gnu/include --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2) 

**What build system are you using?**

11:36:35 2012> cmake --version
cmake version 3.13.4

** Additional info **

Looks like someone else already had that problem in a different project:
http://linuxppc.10917.n7.nabble.com/PATCH-v2-powerpc-tm-Set-MSR-TS-just-prior-to-recheckpoint-tp146277p148069.html

**Comment by marillat** [comment]
And also in the kernel, with this patch
https://git.kernel.org/pub/scm/linux/kernel/git/powerpc/linux.git/commit/?id=e1c3743e1a20647c53b719dbf28b48

**Comment by derekmauro** [comment]
https://abseil.io/docs/cpp/platforms/platforms

This isn't an officially supported platform, and I have no access to a machine to test any patch. Please send us a tested pull request if you need this fixed.
