### ISSUE TITLE
absl/types/internal/variant.h(48): warning: integer conversion resulted in a change of sign

### ISSUE THREAD

**Issue by yasushi-saito** [abseil/abseil-cpp#814]
Use of `absl::variant` always causes the warning described in the title.

Version: e63a5a61045e516b7b3dbca090e2b9ff1d057e46
Compiler: clang 10, libstdc++
OS: Ubuntu 20.04
Build system: bazel 3.5

Changing variant.h:48 to

```
ABSL_INTERNAL_INLINE_CONSTEXPR(size_t, variant_npos, static_cast<size_t>(-1));
```
causes the warning to disappear.

**Comment by sulaeman512** [comment]
Maaf bukan dsaya yang kirim email itu..berikut
Laptop saya rusak lagu

Pada tanggal Sab, 10 Okt 2020 04.14, Yasushi Saito <notifications@github.com>
menulis:
