### ISSUE TITLE
Missing -std=c++17 causes dependent project failures

### ISSUE THREAD

**Issue by yurivict** [abseil/abseil-cpp#819]
For example, Google's ```or-tools``` fails to compile when ```abseil``` is built without ```-std=c++17```.

See https://github.com/google/or-tools/issues/2196

**Comment by derekmauro** [comment]
It looks like you've solved the problem. See https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#how-to-i-set-the-c-dialect-used-to-build-abseil.
