### ISSUE TITLE
std::ranges::iota_view

### ISSUE THREAD

**Issue by steveire** [abseil/abseil-cpp#826]
**Describe the bug**

For many projects, range-based for loops can mostly be used, with the exception of the need to use APIs which require API calls with lookups. Eg:
```
for (auto i = 0; i < container.size(); ++i)
{
    auto thing = storage->getThing(i);
}
```
This of course creates problems/warnings when `container.size()` returns anything other than an `int`. Additionally, it has all of the downsides which led to creation of C++ range-based for loops in the first place.

C++20 provides `std::ranges::iota_view` to satisfy this use-case:
```
for (auto i = std::ranges::iota_view(container.size())
{
    auto thing = storage->getThing(i);
}
```

https://en.cppreference.com/w/cpp/ranges/iota_view

It would be useful to have a simple utility like that in abseil, instead of having to rely on the large ranges-v3 or boost::ranges library.

**Comment by rogeeff** [comment]
Abseil is not really a place for new experimental interfaces. We only expose APIs which are battle tested within Google. That being said, we might have something which pre-adopts ranges at some point, but I can't say for sure when it is going to happen.
