### ISSUE TITLE
Abseil add_subdirectory fails with weird pkg_config errors 

### ISSUE THREAD

**Issue by theunwisewolf** [abseil/abseil-cpp#830]
**Describe the bug**

I use Travis CI to build a test suite that uses Abseil. It was working fine before with just doing git clone on the abseil repo and then using it in the project with add_subdirectory and linking the required absl libraries. Recently, a weird issue came up and the travis builds started failing with these errors:
CMake Error: Cannot open file for write: /usr/local/lib/pkgconfig/absl_absl_atomic_hook.pc.tmp
CMake Error: : System Error: No such file or directory
CMake Error: Cannot open file for write: /usr/local/lib/pkgconfig/absl_absl_errno_saver.pc.tmp
CMake Error: : System Error: No such file or directory
CMake Error: Cannot open file for write: /usr/local/lib/pkgconfig/absl_absl_log_severity.pc.tmp

etc. Full log here: https://travis-ci.org/github/askamn/yas/jobs/738220085#L2806

Important point: The test suite builds fine on Windows in Appveyor.

**Steps to reproduce the bug**

The code is available here: https://github.com/askamn/yas/tree/1b3e8bc9f535868897c5789d1548d0f5841a639b
CMakeLists.txt https://github.com/askamn/yas/blob/1b3e8bc9f535868897c5789d1548d0f5841a639b/tests/base/CMakeLists.txt

**What version of Abseil are you using?**

The build step pulled the latest abseil from master.

**What operating system and version are you using**

Ubuntu 14.04.5 LTS

**What compiler and version are you using?**

Fails with both gcc and clang
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**What build system are you using?**

CMake

**Additional context**

Builds fine on windows.

**Comment by znkr** [comment]
Same problem on Windows:
CMake Error: Cannot open file for write: C:/Program Files (x86)/sndbx/lib/pkgconfig/absl_absl_log_severity.pc.tmp
CMake Error: : System Error: No such file or directory

**Comment by pacom12** [comment]
Ok

**Comment by romange** [comment]
The workaround is to use `-DCMAKE_INSTALL_PREFIX=.` when running cmake

**Comment by derekmauro** [comment]
We have a pending fix from an internal contributor. Thanks for reporting.

**Comment by theunwisewolf** [comment]
Thanks for the update @derekmauro :)

**Comment by derekmauro** [comment]
This should be fixed by e9b9e38f67a008d66133535a72ada843bd66013f. Let us know if this isn't working for you.
