### ISSUE TITLE
absl::flat_hash_map - unexpected key lookup failures in runtime loaded library.

### ISSUE THREAD

**Issue by piyushk** [abseil/abseil-cpp#834]
I'm seeing key lookup failures while adapting code from Google Deepmind's [Reverb](https://github.com/deepmind/reverb) project which I don't fully understand.

### Normal work flow (works as expected):
1) A Reverb server runs a Reverb [table](https://github.com/deepmind/reverb/blob/master/reverb/cc/table.h) that receives data from distributed workers via grpc, stores it in an `absl::flat_hash_map`, and then serves that data via grpc to distributed samplers. All of this code runs via single compiled [pybind module](https://github.com/deepmind/reverb/blob/master/reverb/pybind.cc), which I believe is loaded at runtime. The `absl::flat_hash_map` is only manipulated within this module.
2) A sampler runs a [tensorflow dataset op](https://github.com/deepmind/reverb/blob/master/reverb/cc/ops/dataset.cc) that makes gRPC calls to retrieve this data. The dataset op is also compiled as a library and loaded at runtime.

### Our work flow
In our use case, we only have one sampler that runs in the same python process as the reverb server. To increase throughput, I am trying to short the gRPC comms between the server and the sampler. I pass a pointer to the Reverb table from the server module to the dataset module and get it to sample data directly instead of over gRPC. The server module still accepts data as it did so previously from distributed workers.

### Key lookup issue 
In the dataset module, if I iterate over the keys in the hash map and print them, my key is present. However, things like `map_object.contains(key)` are failing and `map_object[key]` creates **new** objects in the map instead of returning existing objects. If I iterate over the keys, I can see duplicates in there. Both `absl::flat_hash_map` and `absl::node_hash_map` fail this way, while `std::unordered_map` works as expected.

It'll take a bit of time to create a clean working example that demonstrates this behavior, and there's definitely some chance I'm using things incorrectly -- the code is very experimental. But I wanted to check here to see if passing a pointer to the object containing the container from 1 runtime loaded library to another is inherently incorrect. Any advice would be appreciated.

**Comment by derekmauro** [comment]
We mention at https://abseil.io/about/compatibility that dynamic loading is asking for trouble. From the symptoms you describe, I would guess that you are running into the randomization of `absl::Hash`. It sounds like the loaded libraries have different hash seeds, which is probably why you can find objects by iteration, but not by lookup.

**Comment by piyushk** [comment]
Thanks! That makes a lot of sense. I'll test this out on Monday and update/close this thread.

**Comment by piyushk** [comment]
I've verified that using `std::hash` with `absl::flat_hash_map` (which doesn't do randomization) works as expected, and the `absl::hash` for the same key was different in the both loaded libraries. 

Switching to `absl::flat_hash_map` with `std::hash` provides a 10% boost over `std::unordered_map`. The key was a `uint64_t` generated via `absl::Uniform<uint64_t>` and should be sufficiently randomized already, which works fine with `std::hash` typically returning the value itself for integer types.

Thanks for your help! I will close this question.
