### ISSUE TITLE
Is Abseil Ready to be used outside of being a submodule in a cmake project?

### ISSUE THREAD

**Issue by JakeInit** [abseil/abseil-cpp#840]
I have done the following:

`git clone https://github.com/abseil/abseil-cpp.git
cd abseil-cpp
mkdir build && cd build
cmake -G Ninja \ 
  -DCMAKE_BUILD_TYPE=Release \ 
  -DCMAKE_POSITION_INDEPENDENT_CODE=ON \ 
  -DCMAKE_INSTALL_PREFIX=/usr/local/stow/absl \
  ..
ninja
sudo ninja install 
cd /usr/local/stow 
sudo stow absl`

In my cmake project I should only have to do:

"find_package(absl REQUIRED)"

correct?

It then seems I just need to include the libraries found in "/usr/local/inlcude/absl" and then link the static libraries found in "/usr/local/stow/absl/lib". Is there anything else that I may be missing?

**Comment by JakeInit** [comment]
This appears to work without any issue.

**Comment by AziAli181** [comment]
Ok
