### ISSUE TITLE
Should be using memmove instead of memcpy?

### ISSUE THREAD

**Issue by brenoguim** [abseil/abseil-cpp#844]
The function `CUnescapeInternal` claims that the source/destination pointers may point to the same buffer: https://github.com/abseil/abseil-cpp/blob/0bbebc85cd8dbd382b10698b3cefe9a01e88e76f/absl/strings/escaping.cc#L79

However it uses `memcpy` in some situations:
https://github.com/abseil/abseil-cpp/blob/0bbebc85cd8dbd382b10698b3cefe9a01e88e76f/absl/strings/escaping.cc#L140
https://github.com/abseil/abseil-cpp/blob/0bbebc85cd8dbd382b10698b3cefe9a01e88e76f/absl/strings/escaping.cc#L173
https://github.com/abseil/abseil-cpp/blob/0bbebc85cd8dbd382b10698b3cefe9a01e88e76f/absl/strings/escaping.cc#L206
https://github.com/abseil/abseil-cpp/blob/0bbebc85cd8dbd382b10698b3cefe9a01e88e76f/absl/strings/escaping.cc#L254

Because of that, if overlapping buffers are passed in, `memcpy` would be an unsafe choice.

I honestly don't have a way to reproduce the unexpected behavior because I don't have access to an implementation of `memcpy` that actually takes advantage of not allowing overlapping buffers.

**Comment by derekmauro** [comment]
It looks like this function is never called with `leave_nulls_escaped=true`, so it is impossible to trigger this behavior.

(We have unreleased code that does call the function with `leave_nulls_escaped=true`, so I'm patching this for this case, but OSS users are unaffected.)
