### ISSUE TITLE
Tautological compare in absl/time/internal/cctz/src/time_zone_libc.cc (on 20200923.2 release)

### ISSUE THREAD

**Issue by 0x8000-0000** [abseil/abseil-cpp#845]
**Describe the bug**

Building abseil 20200923.2 with Clang12.0 and GCC10.2 library in C++20 mode produces this warning:

     source_subfolder/absl/time/internal/cctz/src/time_zone_libc.cc:193:9: warning: result of comparison 'const std::int_fast64_t' (aka 'const long') < -9223372036854775808 is always false [-Wtautological-type-limit-compare]
      if (s < std::numeric_limits<std::time_t>::min()) {
          ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    source_subfolder/absl/time/internal/cctz/src/time_zone_libc.cc:197:9: warning: result of comparison 'const std::int_fast64_t' (aka 'const long') > 9223372036854775807 is always false [-Wtautological-type-limit-compare]
      if (s > std::numeric_limits<std::time_t>::max()) {
          ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Steps to reproduce the bug**

Building abseil 20200923.2 with Clang12.0 and GCC10.2 library in C++20 mode.

**What version of Abseil are you using?**

20200923.2

**What operating system and version are you using**

Ubuntu 18.04

**What compiler and version are you using?**

    clang version 12.0.0 (https://github.com/llvm/llvm-project.git 96d5d7ef9833d7f88292c694126dd2aa597cec73)
    Target: x86_64-unknown-linux-gnu

**What build system are you using?**

cmake 3.18.3

**Additional context**

**Comment by derekmauro** [comment]
I think this has already been fixed in the latest version. Please re-open if it is not.

**Comment by 0x8000-0000** [comment]
It might have been fixed on HEAD, but it was not backported to the [lts_2020_09_23](/abseil/abseil-cpp/tree/lts_2020_09_23) branch; the problem is present in tag [20200923.2](/abseil/abseil-cpp/releases/tag/20200923.2).

**Comment by 0x8000-0000** [comment]
@derekmauro - I'm not a collaborator in this project and you closed this issue so I can't reopen it.

**Comment by derekmauro** [comment]
Fixes for compile warnings don't get backported. Just turn off the warning with `-Wno-tautological-type-limit-compare`.

**Comment by 0x8000-0000** [comment]
That warning caught bugs in our internal code, it is valuable. I will find the patch myself and cherry-pick it then.
