### ISSUE TITLE
usage of ternary operator vs if else statement

### ISSUE THREAD

**Issue by versatran01** [abseil/abseil-cpp#846]
I saw in a few places in `time.h` where ternary operators are used on return.
This looks fine for short statements, but obscure logic with longer ones like this.
https://github.com/abseil/abseil-cpp/blob/1b465af3bf865f588251470ea0dec60851a24041/absl/time/time.h#L1495

Not that the clients need to understand the logic, but I'm just wondering if there's a reason for doing this vs just using if-else like in
https://github.com/abseil/abseil-cpp/blob/1b465af3bf865f588251470ea0dec60851a24041/absl/time/time.h#L1468

**Comment by derekmauro** [comment]
The former function is constexpr. The latter is not. At least in C++11, a series of if-statements isn't constexpr.

**Comment by versatran01** [comment]
I see, thanks!
