### ISSUE TITLE
LTS symbols leaking into root namespace

### ISSUE THREAD

**Issue by gjasny** [abseil/abseil-cpp#851]
Hi,

(this is a follow-up to #657)

The [Abseil Release Management](https://abseil.io/about/releases) page states:
> Because LTS branches use inline namespaces for all absl:: symbols, collisions between potential Abseil “versions” should not occur, though your library may incur code bloat.
However the recent the September 2020 LTS release still leaks several symbols.

**The first class of problems are the weakly defined symbols** like `AbslInternalSleepFor` and `AbslInternalMutexYield`. I managed to prefix those with the LTS branch name on my local branch: https://github.com/gjasny/abseil-cpp/commit/4e2a9cd5fd0ac3cf95211470ac8df0e24cba14dd

Are duplicated weak symbols with potentially different implementations due to different abseil-cpp versions actually a problem?

**The other class of problems are the generated flags.**

<details>
<summary>Examples...</summary>
<p>

```
libabsl_flags_usage_internal.a
0000000000000510 T AbslFlagDefaultGenForhelpon::Gen(void*)
0000000000002190 T AbslFlagDefaultGenForhelpon::~AbslFlagDefaultGenForhelpon()
00000000000023e0 T AbslFlagDefaultGenForhelpon::~AbslFlagDefaultGenForhelpon()
00000000000005d0 T AbslFlagDefaultGenForhelpmatch::Gen(void*)
0000000000002400 T AbslFlagDefaultGenForhelpmatch::~AbslFlagDefaultGenForhelpmatch()
0000000000002420 T AbslFlagDefaultGenForhelpmatch::~AbslFlagDefaultGenForhelpmatch()

libabsl_flags_parse.a
0000000000000390 T AbslFlagDefaultGenForfromenv::Gen(void*)
00000000000042e0 T AbslFlagDefaultGenForfromenv::~AbslFlagDefaultGenForfromenv()
0000000000004300 T AbslFlagDefaultGenForfromenv::~AbslFlagDefaultGenForfromenv()
0000000000000450 T AbslFlagDefaultGenForundefok::Gen(void*)
0000000000004630 T AbslFlagDefaultGenForundefok::~AbslFlagDefaultGenForundefok()
0000000000004650 T AbslFlagDefaultGenForundefok::~AbslFlagDefaultGenForundefok()
00000000000002b0 T AbslFlagDefaultGenForflagfile::Gen(void*)
0000000000003a50 T AbslFlagDefaultGenForflagfile::~AbslFlagDefaultGenForflagfile()
0000000000003da0 T AbslFlagDefaultGenForflagfile::~AbslFlagDefaultGenForflagfile()
00000000000003f0 T AbslFlagDefaultGenFortryfromenv::Gen(void*)
0000000000004420 T AbslFlagDefaultGenFortryfromenv::~AbslFlagDefaultGenFortryfromenv()
0000000000004440 T AbslFlagDefaultGenFortryfromenv::~AbslFlagDefaultGenFortryfromenv()
```
</p>
</details> 

It looks like they are purposely placed within the root namespace:
https://github.com/abseil/abseil-cpp/blob/0f3bb466b868b523cf1dc9b2aaaed65c77b28862/absl/flags/flag.h#L359

On the other hand the following comment seems to hint a desire to move code generated by `ABSL_FLAG` into the (versioned) `absl` namespace:
https://github.com/abseil/abseil-cpp/blob/0f3bb466b868b523cf1dc9b2aaaed65c77b28862/absl/flags/flag.h#L326-L327
But I could not find any other occurrence of `ABSL_INTERNAL_UNIQUE_SHORT_NAME`. Is that an internal Google thingy?

Could you please take a look and share your thoughts?

Thanks,
Gregor

**Comment by derekmauro** [comment]
> **The first class of problems are the weakly defined symbols** like `AbslInternalSleepFor` and `AbslInternalMutexYield`. 

This is fixed by using the `ABSL_INTERNAL_C_SYMBOL` macro to change the name in an LTS version.

> **The other class of problems are the generated flags.**
> 
> It looks like they are purposely placed within the root namespace:

This problem is harder since flags are essentially globals, and it wouldn't make any sense to have multiple flags of the same name in a program.

https://abseil.io/tips/45 explains that flags should not be used in library code. If you are going to use flags, define them in the same compilation unit as your `main()` function (if you have one), and then use them to configure the library. If your code is just a library without a `main()` function, we don't recommend using flags.

Please let us know if you run into other issues.

**Comment by gjasny** [comment]
Thanks. I verified that both issues are fixed in the `lts_2021_03_24` LTS branch.
