### ISSUE TITLE
Feature request for specifying "std=c++17" in BUILD or WORKSPACE files

### ISSUE THREAD

**Issue by gonzojive** [abseil/abseil-cpp#852]
The [official directions for specifying the C++ dialect](https://chromium.googlesource.com/external/github.com/abseil/abseil-cpp/+/930fbec75b452af8bb8c796f5bb754e953e29cf5/FAQ.md#how-to-i-set-the-c_dialect-used-to-build-abseil) make it sound impossible to specify the necessary C++ compilation options using only BUILD/WORKSPACE file.

While a [workspace-specific .bazelrc](https://docs.bazel.build/versions/master/best-practices.html#using-the-bazelrc-file) is not the end of the world, specifying the dialect on a global workspace level makes it difficult to have multiple C++ dialects within a single workspace. It also just feels strange that language dialect is handled using build flags rather than in the rules. Is there some way of achieving the same result without the .bazelrc config? Perhaps changes to rules_cc will be necessary.

**Comment by derekmauro** [comment]
The answer to the next question [What is ABI and why don't you recommend using a pre-compiled version of Abseil?](https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#what-is-abi-and-why-dont-you-recommend-using-a-pre-compiled-version-of-abseil) explains that this is necessary for correctness. Abseil may be fairly unique in that the C++ dialect affects its ABI. If you have a program that mixes C++ dialects, there is a good chance that you will run into a situation where your program doesn't link, or has ODR violations.

You may be able to work around this problem by [forcing Abseil to use its polyfill types even when the standard type is available](https://github.com/abseil/abseil-cpp/blob/5d8fc9192245f0ea67094af57399d7931d6bd53f/absl/base/options.h#L76-L206), but this [has downsides as explained in the design doc](https://abseil.io/about/design/dropin-types).

Can you explain a bit more about what problem you are trying to solve?

**Comment by gonzojive** [comment]
I have a workspace with multiple C++ dialects, and passing different flags to bazel depending on the target is a burden.

**Comment by derekmauro** [comment]
I don't think this is feasible on our end, for the reasons explained above.

**Comment by gonzojive** [comment]
Thanks. For the rules_cc discussion, see https://groups.google.com/g/cc-bazel-discuss/c/Wa6zBw2F3Ys/m/x3-HgR1dAgAJ
