### ISSUE TITLE
Expose hex parsing routines

### ISSUE THREAD

**Issue by kyessenov** [abseil/abseil-cpp#853]
It would be nice if the functions in `numbers_internal` to parse hex string would be publicly exposed.
Is there a reason why they are kept hidden? For example, `absl::numbers_internal::safe_strto64_base(a, b, 16)` is not declared public.

**Comment by derekmauro** [comment]
I think we've felt that `safe_strto64_base` isn't the right API, but we have talked about releasing something in this area before. I'll see if we can get the discussion restarted.

**Comment by derekmauro** [comment]
Update: The current plan is to release `absl::SimpleHexAtoi()` pending some internal cleanup.

**Comment by mbxx** [comment]
This is now released: https://github.com/abseil/abseil-cpp/blob/c86347d4cec43074e64e225a8753728f4bfc5ed6/absl/strings/numbers.h#L110
