### ISSUE TITLE
Feature: string trim

### ISSUE THREAD

**Issue by Yanpas** [abseil/abseil-cpp#854]
Such a basic building block that is required in a lot of projects. Abseil already has all useful string functions, trimming whitespace is the last piece.

**Comment by derekmauro** [comment]
Is this what you are looking for?
https://github.com/abseil/abseil-cpp/blob/acf3390ca28edf1438fa896602ffede2a7dff103/absl/strings/ascii.h#L195-L237

**Comment by Yanpas** [comment]
Exactly! thx
