### ISSUE TITLE
Build failed with cmake on CentOS 7.6

### ISSUE THREAD

**Issue by guozhongqiu** [abseil/abseil-cpp#858]
**Describe the bug**

When building abseil-cpp with cmake on CentOS 7.6, failed with errors below:

```bash
/root/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
/root/abseil-cpp/absl/flags/marshalling.cc:179:66: note:   mismatched types ‘absl::FormatSpec<Args ...>’ and ‘const char [5]’
       absl::StrFormat("%.*g", std::numeric_limits<T>::digits10, v);
                                                                  ^
......
```

It is expected that build should succeed, but got errors above.

**Steps to reproduce the bug**

1. `git clone https://github.com/abseil/abseil-cpp.git`
2. `cd abseil-cpp`
3. `mkdir build && cd build`
4. `cmake3 .. -DABSL_RUN_TESTS=OFF -DABSL_USE_GOOGLETEST_HEAD=OFF -DCMAKE_CXX_STANDARD=11`
5. `make -j5    (got errors here)`

**What version of Abseil are you using?**
master and tag 20200923 etc.

**What operating system and version are you using**
CentOS 7.6 1810  3.10.0-957.el7.x86_64

**What compiler and version are you using?**
gcc version 4.8.5 20150623 

**What build system are you using?**
cmake3 version 3.17.3

**Additional context**
At first, I got this error in building grpc cpp plugin. Then try building it alone, but got the same error.

**Comment by derekmauro** [comment]
[GCC 4.8 is unsupported](https://abseil.io/docs/cpp/platforms/platforms). We recommend updating your compiler.

**Comment by guozhongqiu** [comment]
Thanks for your reply.
