### ISSUE TITLE
Submit an open source Library

### ISSUE THREAD

**Issue by Spidy104** [abseil/abseil-cpp#864]
Hello, I had a few questions I have worked upon an open-source lib hence want to contribute that Library to abseil, How shall I do that?

**Comment by derekmauro** [comment]
You can let us know when you want to contribute, but just be warned, it is very unlikely that we would accept it. See https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library
