### ISSUE TITLE
How to disable Special Usage flags in flags library

### ISSUE THREAD

**Issue by tadzys** [abseil/abseil-cpp#865]
Hi,

there are bunch of special usage flags defined in flags, and for example running your app with --helpfull

prints all kind of flags from parse.cc or usage.cc wich I don't want to see.

I thought running it like this:
  absl::FlagsUsageConfig config;
  config.version_string  = [version]() { return "1"; };
  config.contains_helppackage_flags = [](absl::string_view){ return false; };
  config.contains_helpshort_flags   = [](absl::string_view) { return false; };
  config.contains_help_flags        = [](absl::string_view f) { return absl::EndsWith(f, "configuration.cpp"); };
  absl::SetFlagsUsageConfig(config);

will show only flag defined in my configuration.cpp file.

thanks

**Comment by derekmauro** [comment]
Did you try running your program with `--help` instead of `--helpfull`?
