### ISSUE TITLE
absl::FormatTime(): %E produces different results in OS X vs Linux

### ISSUE THREAD

**Issue by rgs1** [abseil/abseil-cpp#869]
Given:

```
#include <iostream>
#include <string>
#include <vector>

#include "absl/time/time.h"

int main() {
  absl::TimeZone tz;
  auto t = absl::FromTimeT(time(nullptr));
  absl::LoadTimeZone("America/New_York", &tz);
  std::cout << absl::FormatTime("%E", t, tz) << "\n";

  return 0;
}
```

In OS X the output is:

```
E
```

Whereas in Linux it is:

```
%E
```

Is this expected?

I started looking into this in the context of a test in Envoy that behaves differently across platforms when calling `absl::FormatTime("%E4n")`, see:

https://github.com/envoyproxy/envoy/pull/14494

**Comment by rgs1** [comment]
Sorry, the label should have been "question" -- this is probably not a bug. I just want to understand (and possibly document) why this is so.

**Comment by derekmauro** [comment]
Abseil gets this directly from https://github.com/google/cctz. I've copied your question to https://github.com/google/cctz/issues/180, feel free to subscribe to that issue. I'll leave this issue open so we can update our documentation when we figure out what is going on.
