### ISSUE TITLE
flat_unordered_map doesn't compile in C++20

### ISSUE THREAD

**Issue by Milerius** [abseil/abseil-cpp#872]
**Describe the bug**

```
In file included from ../vcpkg-repo/installed/x64-windows/include\absl/container/flat_hash_map.h:38:
In file included from ../vcpkg-repo/installed/x64-windows/include\absl/algorithm/container.h:55:
../vcpkg-repo/installed/x64-windows/include\absl/meta/type_traits.h:614:35: fatal error: no type named 'result_of' in namespace 'std'
using result_of_t = typename std::result_of<T>::type;
```

**Steps to reproduce the bug**

**What version of Abseil are you using?**
abseil:x64-osx                                     2020-09-23#1 

**What operating system and version are you using**

 MacOS Big Sur (11.1)

**What compiler and version are you using?**

Clang 11.0 / C++20 on windows installed with scoop.

**What build system are you using?**

CMake 3.18

**Additional context**

Full report: https://github.com/KomodoPlatform/atomicDEX-Desktop/runs/1604290164?check_suite_focus=true

```
In file included from ../vcpkg-repo/installed/x64-windows/include\absl/container/flat_hash_map.h:38:
In file included from ../vcpkg-repo/installed/x64-windows/include\absl/algorithm/container.h:55:
../vcpkg-repo/installed/x64-windows/include\absl/meta/type_traits.h:614:35: fatal error: no type named 'result_of' in namespace 'std'
using result_of_t = typename std::result_of<T>::type;
```

According to https://en.cppreference.com/w/cpp/types/result_of the traits is removed in c++20.

**Comment by Milerius** [comment]
It's seems to be fixed in master, but not released yet, any date of the next release by any chance ?

**Comment by derekmauro** [comment]
As noted, this is fixed in master. We strongly recommend users [live-at-head](https://github.com/abseil/abseil-cpp#releases). We aim to cut an LTS release every 6 months, so you can probably expect the next release in February or March.
