### ISSUE TITLE
about flag document and log question?

### ISSUE THREAD

**Issue by math715** [abseil/abseil-cpp#882]
1 could not find flag document in https://abseil.io/docs/cpp/guides/. but find source code have flag. 
I think absl::flags could replace gflags.
2 could add log system file in feture?
I absl::log cloud replace glog. 
If so, I could one library not more.

**Comment by derekmauro** [comment]
> 1 could not find flag document in https://abseil.io/docs/cpp/guides/. but find source code have flag.
> I think absl::flags could replace gflags.

Yes, absl Flags is a replacement for gflags. https://abseil.io/docs/cpp/guides/flags is linked for the page you cited.

> 2 could add log system file in feture?
> I absl::log cloud replace glog.
>If so, I could one library not more.

We are actively working on providing a logging library to replace glog, but it isn't ready yet.

**Comment by Mizux** [comment]
https://github.com/abseil/abseil-cpp/issues/297#issuecomment-484102629
