### ISSUE TITLE
What is the recommended way to use abseil in a CMAKE project that is going to be installed and used externally?

### ISSUE THREAD

**Issue by RajivKurian** [abseil/abseil-cpp#883]
I am creating a project that is built with cmake and I want to use abseil-cpp for parts of my implementation. Based on the recommendations [here](https://github.com/abseil/abseil-cpp/blob/master/CMake/README.md) I added abseil-cpp as a subdirectory in my project. abseil-cpp is a public dependency for libraries of my project that I am trying to export via the CMAKE export functionality. Everything works fine when I create my library and use it locally within my project.
However, if I try to export my library, CMAKE (correctly) complains that I depend on various absl libraries that are not in the export set. Are there any recommended ways for me to export my library along with all it's abseil dependencies?

**Comment by derekmauro** [comment]
Thanks for reaching out. We aren't CMake experts and providing guidance on different ways to use CMake is beyond what we provide in terms of support.
