### ISSUE TITLE
LeakSanitizer usage is not detected automatically / is not enabled together with asan

### ISSUE THREAD

**Issue by TheMozg** [abseil/abseil-cpp#885]
**Describe the bug**

In order to use `absl::IgnoreLeak`, one still has to define `LEAK_SANITIZER` when building abseil.
See [leak_check.cc](https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/leak_check.cc#L21)

Release notes for abseil 20200923 say that additional macros are no longer needed:
> Sanitizer usage is now automatically detected and no longer requires macros like ADDRESS_SANITIZER to be defined on the command line.

Given that leak sanitizer is a part of asan and is enabled by default on Linux, I think it makes sense to enable leak sanitizer in asan builds.

**Steps to reproduce the bug**

1. Build abseil in asan mode with `-fsanitize=address`. 
2. Build and run the following example:
```
#include "absl/debugging/leak_check.h"

int main()
{
    int * qwe = absl::IgnoreLeak(new int(10));
    return *qwe;
}
```
3. Observe leak:
```
=================================================================
==65425==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x4c558d in operator new(unsigned long) /home/fedor.kalugin/rpmbuild/BUILD/llvm10-10.0.1/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cpp:99:3
    #1 0x4c7ead in main /src/utilities/rmme/src/main.cpp:5:34
    #2 0x388841ed1f in __libc_start_main (/lib64/libc.so.6+0x388841ed1f)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

Expected result: no output.

**What version of Abseil are you using?**
`20200923`, `master`

**What operating system and version are you using**

RHEL 6, RHEL 7

**What compiler and version are you using?**
```
clang version 10.0.1 (ssh://git@stash.orcsoftware.com/int/rpmbuild.git 85b3486b6e341621048d50dba2be78ccb7535d22)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**What build system are you using?**

Cmake

**Comment by Huncho3511** [comment]
Certains choses c’est compliqué
