### ISSUE TITLE
Problem building on Darwin post-c9894d1dc38577c4ce50eefe0a944ea8d46d7fc5

### ISSUE THREAD

**Issue by zrlk** [abseil/abseil-cpp#892]
**Describe the bug**

I can't build Abseil at or beyond commit c9894d1dc38577c4ce50eefe0a944ea8d46d7fc5 on Darwin:

```
ERROR: /private/var/tmp/_bazel_me/4047a92cde5c126a2747538e6c63dc38/external/com_google_absl/absl/synchronization/BUILD.bazel:68:11: Linking external/com_google_absl/absl/synchronization/libsynchronization.so failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/external/com_google_absl/absl/synchronization/libsynchronization.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/external/com_google_absl/absl/synchronization/libsynchronization.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: illegal thread local variable reference to regular symbol __ZN4absl13base_internal19thread_identity_ptrE for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**What operating system and version are you using**

Darwin my.hostname 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

**What compiler and version are you using?**

Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**What build system are you using?**

bazel 4.0.0

**Comment by derekmauro** [comment]
Please see https://github.com/bazelbuild/bazel/issues/4341 for the Bazel bug.
