### ISSUE TITLE
Build on Linux sparc64 fails with #error "Undefined Architecture."

### ISSUE THREAD

**Issue by glaubitz** [abseil/abseil-cpp#893]
The build of abseil fails on Linux sparc64 with:

```
[ 69%] Building CXX object absl/debugging/CMakeFiles/examine_stack.dir/internal/examine_stack.cc.o
cd "/<<PKGBUILDDIR>>/static/absl/debugging" && /usr/bin/c++  -I"/<<PKGBUILDDIR>>" -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wcast-qual -Wconversion-null -Wmissing-declarations -Woverlength-strings -Wpointer-arith -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare -DNOMINMAX -std=gnu++14 -o CMakeFiles/examine_stack.dir/internal/examine_stack.cc.o -c "/<<PKGBUILDDIR>>/absl/debugging/internal/examine_stack.cc"
/<<PKGBUILDDIR>>/absl/debugging/internal/examine_stack.cc:72:2: error: #error "Undefined Architecture."
   72 | #error "Undefined Architecture."
      |  ^~~~~
[ 70%] Linking CXX static library libabsl_time.a
cd "/<<PKGBUILDDIR>>/static/absl/time" && /usr/bin/cmake -P CMakeFiles/time.dir/cmake_clean_target.cmake
cd "/<<PKGBUILDDIR>>/static/absl/time" && /usr/bin/cmake -E cmake_link_script CMakeFiles/time.dir/link.txt --verbose=1
/usr/bin/ar qc libabsl_time.a CMakeFiles/time.dir/civil_time.cc.o CMakeFiles/time.dir/clock.cc.o CMakeFiles/time.dir/duration.cc.o CMakeFiles/time.dir/format.cc.o CMakeFiles/time.dir/time.cc.o
/usr/bin/ranlib libabsl_time.a
make[4]: Leaving directory '/<<PKGBUILDDIR>>/static'
[ 70%] Built target time
```

Full build log in: https://buildd.debian.org/status/fetch.php?pkg=abseil&arch=sparc64&ver=0%7E20200923.3-1&stamp=1612822447&raw=0

A sparc64 porterbox running Debian unstable can be access through the gcc compile farm:

> https://gcc.gnu.org/wiki/CompileFarm

**Comment by derekmauro** [comment]
https://abseil.io/docs/cpp/platforms/platforms - This platform isn't supported, and we can't prioritize fixing issues on this platform. We may accept a patch if it doesn't complicate the code.

**Comment by glaubitz** [comment]
OK, I will take care of those issues in the next days.

**Comment by glaubitz** [comment]
I have now sent PRs for the issues on m68k, powerpc and sparc64. Will open more PRs for supporting some more targets once these PRs have been merged.

**Comment by derekmauro** [comment]
Thanks. Tests have passed and these should be merged soon.

**Comment by roastduck** [comment]
Hi team, I am also encountering this this issue when trying to compile to yet another architecture. I see the error is from a function that is commented with "nullptr if unknown". Can we just `return nullptr` instead of `#error "Undefined Architecture."`?
