### ISSUE TITLE
StrSplit that runs on Linux fails on Windows 10 Pro

### ISSUE THREAD

**Issue by DrewGlinsman** [abseil/abseil-cpp#896]
Accidentally made my post the comment below

**Comment by DrewGlinsman** [comment]
This code segment:
   
```
 boost::filesystem::path full_path(boost::filesystem::current_path());
 std::vector<std::string> splitPath = absl::StrSplit(full_path.native(), cOutputRoot);
```
runs on our linux distributions but when ran on windows the compiler throws these errors:

 error C2672: 'absl::StrSplit': no matching overloaded function found
 error C2780: ''absl::strings_internal::Splitter<strings_internal::SelectDelimiter<Delimiter>::type,Predicate> absl::StrSplit(absl::strings_internal::ConvertibleToStringView,Delimiter,Predicate)': expects 3 arguments - 2 provided
error C2440: 'initializing': cannot convert from 'const boost::filesystem::path::string_type' to 'absl::strings_internal::ConvertibleToStringView'

does anyone know why

**Comment by mbxx** [comment]
As a stab in the dark: are all of the translation units being complied with the same version of C++?

absl::string_view is a different type depending on whether it's compiled in C++11/14 or C++17/later.  This feels vaguely like that sort of issue.  Perhaps C++17 is being explicitly requested somewhere but something else is pulling C++14 in by default.

**Comment by derekmauro** [comment]
https://www.boost.org/doc/libs/1_64_0/boost/filesystem/path.hpp

Path chars are `wchar_t` on Windows. `std::string` is composed of `char`. 

If you scroll down a bit, boost seems to provide a `string()` member on Windows, so without testing it, I'd think
```
std::vector<std::string> splitPath = absl::StrSplit(full_path.string(), cOutputRoot);
```
would work.

I also think that if you are using `std::filesystem::path()`, you can use the native path iterators to split the string. Boost probably has the same thing.

**Comment by DrewGlinsman** [comment]
Thank you that fixed my issue
