### ISSUE TITLE
Incorporating Abseil Into a CMake Project (example: snappy, broken)

### ISSUE THREAD

**Issue by ghost** [abseil/abseil-cpp#911]
(possibly related: #367)

## Problem

Google Snappy introduced `absl::GetFlag` and `absl::SetFlag` without adding the absl library to the project, breaking this way the master branch.

## Attempted Solution

https://github.com/abseil/abseil-cpp/blob/master/CMake/README.md#incorporating-abseil-into-a-cmake-project

Adding abseil as mentioned int the readme 

```sh
# within snappy /
cd third_party
git clone https://github.com/abseil/abseil-cpp.git

# within snappy cmakelist.txt
add_subdirectory("third_party/abseil-cpp")
target_link_libraries(snappy_unittest snappy_test_support gmock_main gtest absl::flags)
target_link_libraries(snappy_test_tool snappy_test_support absl::flags)
```

## Errors

does not work, results  in compile errors:

```sh
[ 71%] Building CXX object CMakeFiles/snappy_test_tool.dir/snappy_test_tool.cc.o
/root/host/snappy/snappy_test_tool.cc: In function 'bool snappy::{anonymous}::Uncompress(const string&, snappy::{anonymous}::CompressorType, int, std::string*)':
/root/host/snappy/snappy_test_tool.cc:234:73: warning: unused parameter 'size' [-Wunused-parameter]
  234 | bool Uncompress(const std::string& compressed, CompressorType comp, int size,
      |                                                                     ~~~~^~~~
/root/host/snappy/snappy_test_tool.cc: In function 'void snappy::{anonymous}::MeasureFile(const char*)':
/root/host/snappy/snappy_test_tool.cc:421:49: error: no matching function for call to 'GetFlag(int&)'
  421 |   int start_len = (absl::GetFlag(FLAGS_start_len) < 0)
      |                                                 ^
In file included from /root/host/snappy/snappy_test_tool.cc:44:
/root/host/snappy/third_party/abseil-cpp/absl/flags/flag.h:188:24: note: candidate: 'template<class T> T absl::GetFlag(absl::Flag<T>&)'
  188 | ABSL_MUST_USE_RESULT T GetFlag(const absl::Flag<T>& flag) {
      |                        ^~~~~~~
/root/host/snappy/third_party/abseil-cpp/absl/flags/flag.h:188:24: note:   template argument deduction/substitution failed:
/root/host/snappy/snappy_test_tool.cc:421:49: note:   mismatched types 'absl::Flag<T>' and 'int'
  421 |   int start_len = (absl::GetFlag(FLAGS_start_len) < 0)
      |                                                 ^
/root/host/snappy/snappy_test_tool.cc:423:54: error: no matching function for call to 'GetFlag(int&)'
[...]
```

Any ideas?

## (EDIT) Solution

https://github.com/google/snappy/pull/123

**Comment by derekmauro** [comment]
The changes to Google Snappy appear to be half done. The flags are being accessed though `absl::GetFlag`, but the flags themselves are not actually of the `absl::Flag<T>` type. This is a Snappy bug and needs to be fixed in the Snappy code.

@rogeeff

**Comment by ghost** [comment]
@derekmauro , quite strangely, snappy team broke the public master and does not revert the breaking change (see https://github.com/google/snappy/pull/121) and does not provide any info besides mentioning a mystique internal google (snappy-)consumer with enough priority to break the pubic snappy repo (I assume chrome).

> The flags are being accessed though absl::GetFlag, but the flags themselves are not actually of the absl::Flag<T> type. This is a Snappy bug and needs to be fixed in the Snappy code.

I assume that the relevant type-defs are somewhere in the mystique consumer. Thus one needs to locate them, and copy them to the snappy-repo.

(all this is quite a sad story...)

**Comment by ghost** [comment]
Solution: https://github.com/google/snappy/pull/123
