### ISSUE TITLE
4 Warnings Within a Quasi-Production Setup (snappy)

### ISSUE THREAD

**Issue by ghost** [abseil/abseil-cpp#912]
(related: #845, #591)

**Describe the bug**

Expected: a 0-warning build

Getting: a 4-warnings build

```sh
[146/210] Building CXX object third_pa.../internal/cctz/src/time_zone_libc.cc.o

../third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc:193:9: warning: result of comparison 'const std::int_fast64_t' (aka 'const long') < -9223372036854775808 is always false [-Wtautological-type-limit-compare]

  if (s < std::numeric_limits<std::time_t>::min()) {

      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc:197:9: warning: result of comparison 'const std::int_fast64_t' (aka 'const long') > 9223372036854775807 is always false [-Wtautological-type-limit-compare]

  if (s > std::numeric_limits<std::time_t>::max()) {

      ~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

../third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc:84:6: warning: unused function template 'tm_gmtoff' [-Wunused-template]

auto tm_gmtoff(const T& tm) -> decltype(tm.__tm_gmtoff) {

     ^

../third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc:100:6: warning: unused function template 'tm_zone' [-Wunused-template]

auto tm_zone(const T& tm) -> decltype(tm.__tm_zone) {

     ^

4 warnings generated.
```

Direct link to CI: https://travis-ci.org/github/google/snappy/jobs/761872549#L625

**Steps to reproduce the bug**

This is in context of snappy. The warnings come up when including abseil via `add_subdirectory` to a project (snappy), see https://github.com/google/snappy/pull/123

Snappy uses "-Werror" on clang, which leads to a broken build.

**What version of Abseil are you using?**

`Abseil LTS 20200923.3` (checked out via submodule to third_party/abseil-cpp)

**What operating system and version are you using**

* AMD64, Linux (see ci of PR https://github.com/google/snappy/pull/123)
* ppc64le via qemu/docker (locally)

**What compiler and version are you using?**

clang-10, clang-9 locally

clang version 7.0.0 (strange...) on travis ci

**What build system are you using?**

cmake version 3.12.4 (travis)

cmake version 3.16.3 (locally)

**Additional context**

* https://github.com/google/snappy/pull/123

## Workaround

My workaround was to disable (within snappy) `-Werror` for clang (https://github.com/google/snappy/pull/123/commits/df7073f88ad0ead420b66b7c908a8b5fcf8ff5c7), thus the warnings do not break the build. But I don't like this workaround, as it changes build-behavior for snappy-consumers.

## Questions

* Is there any way to consume/compile only `absl::flags` related code, instead of the whole abseil lib?
* Any chances to get this (warnings) fixed within 20200923.4 ?

**Comment by derekmauro** [comment]
I'd refer you to https://github.com/google/cctz/issues/132#issuecomment-577826089.

Basically, we don't agree with these warnings.

Also, I think `-Werror` is fine for a project to set on its own CI to fail the build when a new warning is introduced, but it should not be set for downstream builds. See for example how we manually enable it on our own CI, but don't force it on our users:
https://github.com/abseil/abseil-cpp/blob/ab21820d47e4f83875dda008b600514d3520fd35/ci/linux_gcc-latest_libstdcxx_bazel.sh#L84

**Comment by ghost** [comment]
@derekmauro , are you sure that at this point, "no action is needed" on your side? Iit is not ok to "comment-close" issues.

You (abseil) are the consumer of `cctz`. You may not agree, but then, suppress the warnings somehow from within your builds (with comments re "non-critical"), thus abseil consumers don't have to face them.

In any way, thank you for the pointers an comments.

> Also, I think -Werror is fine for a project to set on its own CI to fail the build when a new warning is introduced, but it should not be set for downstream builds.

So, you are suggesting that snappy should remove the "hardcoded" -Werror for clang from CMakelists, and add it just to the ci-config (together with the relevant `-Wno`'s

**Comment by ghost** [comment]
(remember that one cannot do much when consuming abseil via cmakes `add_subdirectory` )

**Comment by derekmauro** [comment]
Yes, I'm saying there is no action necessary on the Abseil side. I'm also suggesting that Snappy should remove the hardcoded `-Werror`.
