### ISSUE TITLE
Resizing node_hash_set/map makes unnecessary copy of values

### ISSUE THREAD

**Issue by greg7mdp** [abseil/abseil-cpp#914]
If you look at `node_hash_policy::transfer`, which is invoked during resize(), it makes a copy or move of the values.
When resizing, we should be able to just swap the pointers new_slot and old_slot which should be faster.

**Comment by sbenzaquen** [comment]
`node_hash_set/map` never copy or move the objects once they are in the table.
It is a node-based container (hence the name) and all the objects are held by pointer in the table.
You can actually use this container with types that are not copyable/movable.
Do you have a reproduction where the table is making copies of the underlying objects?

**Comment by greg7mdp** [comment]
You are correct, my mistake, sorry!
