### ISSUE TITLE
[Abseil LTS 20200923, Patch 3] : Compilation errors of synchronization module

### ISSUE THREAD

**Issue by didier31** [abseil/abseil-cpp#917]
mutex.h:477 => Mutex::IncrementSynchSem() is declared when ABSL_INTERNAL_USE_NONPROD_MUTEX is not defined.

mutex.cc:551 => However, Mutex::IncrementSynchSem() definition is not conditioned at all.

As a result, when ABSL_INTERNAL_USE_NONPROD_MUTEX is defined, a compilation error actually occurs.

The same for : Mutex::DecrementSynchSem, Mutex::LockSlowLoop, Mutex::LockSlowWithDeadline, ... and so on.

**Comment by derekmauro** [comment]
The opensource release never supported any platforms in which `ABSL_INTERNAL_USE_NONPROD_MUTEX` was defined. This code path has already been removed at HEAD.

**Comment by didier31** [comment]
Ok. fine.
Thank you for your quick response.
Thank you for your answer.

FYI: I build it for OpenBSD.
