### ISSUE TITLE
clang-cl.exe (on 64bit Windows 10) fails to compile debugging/internal/stack_consumption.h

### ISSUE THREAD

**Issue by mayah** [abseil/abseil-cpp#92]
debugging/internal/stack_consumption.h contains a feature check like

```
#ifdef ABSL_INTERNAL_HAVE_DEBUGGING_STACK_CONSUMPTION
#error ABSL_INTERNAL_HAVE_DEBUGGING_STACK_CONSUMPTION cannot be set directly
#elif !defined(__APPLE__) && \
    (defined(__i386__) || defined(__x86_64__) || defined(__ppc__))
#define ABSL_INTERNAL_HAVE_DEBUGGING_STACK_CONSUMPTION 1
```

With cl.exe, this feature check is resolved to false, so it's OK.
However, with clang-cl.exe, `__x86_64__` is defined, so this feature check is resolved to true. Then stack_consumtion.cc compile fails.

I think we should have `!defined(_WIN32)` if this is not intended to work on Windows.

**Comment by derekmauro** [comment]
Should be fixed in 03c1513538584f4a04d666be5eb469e3979febba.
