### ISSUE TITLE
Can this project cross compile windows program through mingw on ubuntu?

### ISSUE THREAD

**Issue by zuowanbushiwo** [abseil/abseil-cpp#924]
1. install mingw on ubuntu
sudo apt-get install mingw-w64
sudo apt-get install mingw-w64-tools 
sudo apt-get install mingw-w64-i686-dev 
sudo apt-get install mingw-w64-x86-64-dev

2. Use the following cmake cross-compilation toolchain configuration，toolchain-ubuntu-mingw64.cmake 
set(CMAKE_SYSTEM_NAME Windows)
set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)
set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

3.  Use cmake command ： cmake -DCMAKE_TOOLCHAIN_FILE=/home/z/APM/cross/toolchain-ubuntu-mingw64.cmake   -DCMAKE_CXX_STANDARD=14 ..

4.  Compile error：
  [  7%] Building CXX object absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.obj
/home/z/abseil-cpp/absl/base/internal/sysinfo.cc:84:0: warning: ignoring #pragma comment  [-Wunknown-pragmas]
 #pragma comment(lib, "advapi32.lib")  // For Reg* functions.
 
/home/z/abseil-cpp/absl/base/internal/sysinfo.cc: In function ‘int absl::base_internal::GetNumCPUs()’:

/home/z/abseil-cpp/absl/base/internal/sysinfo.cc:71:15: error: ‘std::thread’ has not been declared
   return std::  thread   ::hardware_concurrency();
               ^~~~~~
absl/base/CMakeFiles/base.dir/build.make:113: recipe for target 'absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.obj' failed
 'absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.obj' failed
make[2]: *** [absl/base/CMakeFiles/base.dir/internal/sysinfo.cc.obj] Error 1
CMakeFiles/Makefile2:435: recipe for target 'absl/base/CMakeFiles/base.dir/all' failed

thanks！

**Comment by derekmauro** [comment]
MinGW isn't officially supported, however we do accept patches from the community that do not complicate the code. I think it is probably possible to get this working without too much work, but we currently cannot prioritize this.

**Comment by zuowanbushiwo** [comment]
Where can I see  and download these patches，I can test it,， thanks！

**Comment by derekmauro** [comment]
I think you misunderstand. There are no patches today. Someone from the community will need to create a patch.

**Comment by zuowanbushiwo** [comment]
thanks!
