### ISSUE TITLE
CMake: remove of absl::container missing in the release note

### ISSUE THREAD

**Issue by Mizux** [abseil/abseil-cpp#932]
Please add to the Release note: https://github.com/abseil/abseil-cpp/releases/tag/20210324.0
The remove of the `absl::container` target 

Thx !

```md
## Breaking Changes:
Abseil no longer contains a `container` library. Users
using a supported build system (CMake) may get an error
about a missing target.
```

**Comment by derekmauro** [comment]
Thank you. Done: https://github.com/abseil/abseil-cpp/releases/tag/20210324.0
