### ISSUE TITLE
Failure signal handler should call writerfn with null buffer at the end

### ISSUE THREAD

**Issue by yasushi-saito** [abseil/abseil-cpp#933]
**Describe the bug**

The documentation for FailureSignalHandlerOptions in absl/debugging/failure_signal_handller.h says that writerfn may be called with null buffer to let the callee flush buffered data. But that never happens. It will help us if absl explicitly calls writerfn(nullptr, 0) just before crashing. 

Our use case is that we want to caputure the crash message as one long string and log it specially marked.

I can create a PR if you think this is a good idea.

**What version of Abseil are you using?**

7f4d0ba

**What operating system and version are you using**

Ubuntu 20.04, x86-64.

**What compiler and version are you using?**

clang-10.0

**What build system are you using?**

bazel 3.5

**Comment by derekmauro** [comment]
I vaguely remember writing that comment in the documentation, but I have no idea why it seems like it was never implemented. I would take this as a PR.

**Comment by derekmauro** [comment]
The fix has been merged.
