### ISSUE TITLE
InlinedVector growth factor

### ISSUE THREAD

**Issue by BenjaminNavarro** [abseil/abseil-cpp#934]
While looking for a vector type with SBO I stumbled upon abseil's `InlinedVector`.

After a quick look at the implementation, it appears that a growth factor of 2 is [used](https://github.com/abseil/abseil-cpp/blob/master/absl/container/internal/inlined_vector.h#L312).

I'm not an expert in this domain but I've heard and read multiple times that this is a bad value for a growth factor, a good one would be lower than 2 (I think ~~libc++~~ MSVC uses 1.5).

The main rationale is that in a series of `push_back`s, new allocations will probably be right after the previous ones but with a growth factor of 2, each new allocation is larger than all the previous ones combined so there's no chance for the allocator to reuse the space previously allocated for the vector.

With a value lower than 2 you should be able to reuse some memory at some point which speeds up the vector's growth.

I was wondering if tuning the growth factor for `InlinedVector` was something that has been already studied or if it would be a good thing to do ?

EDIT: some discussion about this by experts: https://groups.google.com/g/comp.lang.c++.moderated/c/asH_VojWKJw

**Comment by derekmauro** [comment]
I believe someone did investigate this empirically a few years ago and we settled on a growth factor of 2. @CJ-Johnson or @EricWF may know more.

I would also ask if `absl::InlinedVector` is the right choice if you are expecting reallocations to happen often enough for this to matter. `std::vector` may be a better choice in this case.

Give it a try a let us know how this performs in real code.

**Comment by BenjaminNavarro** [comment]
I still don't have real code using it so I ran the provided benchmark for both values and there wasn't a clear winner. Sometimes no differences, sometimes small ones and sometimes big ones but it was well balanced.

But if you say that someone looked at it and found 2 is a better grow factor in this case then it's fine.
