### ISSUE TITLE
in Android use abseil

### ISSUE THREAD

**Issue by lilinxiong** [abseil/abseil-cpp#935]
I want to use abseil in Android.
Can I compile it into a static library and use it in Android?
I did not find the method to compile Android version static library in the documentation.
Can you help me?
We are expecting a reply…

**Comment by derekmauro** [comment]
Abseil is a C++ library. You can use it in the same way you would any other C++ library, including building static libraries.

Here are our tutorials to get you started:
https://abseil.io/docs/cpp/quickstart.html
https://abseil.io/docs/cpp/quickstart-cmake.html

**Comment by lilinxiong** [comment]
Thank you for your reply～
I know what to do～
