### ISSUE TITLE
Currently, cmake builds need to manually link the internal library absl_raw_hash_set

### ISSUE THREAD

**Issue by jeremyong** [abseil/abseil-cpp#936]
Linking against, e.g. `absl::base` fails because symbols that used to be defined in the raw_hash_set header moved to the source file with no corresponding change to the cmake files.

Resolving this requires adding `absl_raw_hash_set` as a link target _before_ linking `absl::base` but it'd be preferable if `absl::base` simply included its transitive dependencies (it's possible other symbols are missing as well and I just haven't encountered the template that uses them yet).

**Comment by derekmauro** [comment]
The information provided is not enough for us to understand exactly what is happening. These bug reports should automatically include a template for you to fill out. A complete report allows us to look into the problem more easily. Can you please fill in the information in the report template, especially the reproduction information? Please see https://github.com/abseil/abseil-cpp/blob/master/.github/ISSUE_TEMPLATE/00-bug_report.md.

**Comment by jeremyong** [comment]
Sorry this is my fault. I mistakenly assumed linking `absl::base` enabled the use of `absl::flat_hash_map` but this requires linking to `absl::flat_hash_map` (the target) directly.
