### ISSUE TITLE
absl::numbers_internal assumes CHAR_BIT == 8

### ISSUE THREAD

**Issue by coryan** [abseil/abseil-cpp#94]
The code assumes extensively that CHAR_BIT == 8 for example:

https://github.com/abseil/abseil-cpp/blob/master/absl/strings/numbers.h#L138

reads:

```
static_assert(sizeof(*out) == 4 || sizeof(*out) == 8,
                "SimpleAtoi works only with 32-bit or 64-bit integers.");
```

This is only true on platforms where `CHAR_BIT == 8`.  There are platforms out there where `CHAR_BIT == 16` (I have actually ported code to platforms where `CHAR_BIT == 64`, but I digress),  and therefore a 32-bit integer would have `sizeof(..) == 2` (as you know `sizeof(char) == 1` by definition, even if `char` takes two bytes in memory).

Maybe Abseil will never target platforms where `CHAR_BIT` != 8, but I have not found any documentation saying this is the case.  If the intention is to stick to platforms where `char` is 8-bits then the documentation should say that, and there should be an static assertion to check it.

There are other places in the code where `sizeof()` expressions are compared to `64 / 8`, same problem.

**Comment by mbxx** [comment]
We don't specifically intend to restrict Abseil to platforms where `CHAR_BIT == 8`, but that is the case for all of the platforms that we have ready access to.  You're right that this assumption should at least be documented.  We're also open to the idea of relaxing it.

Are you looking to use Abseil on a platform where `CHAR_BIT != 8`?  If so, we'd love more information about what you'd like to do.  If not, I propose adding some `static_assert`s to the code to document and enforce the assumption that `CHAR_BIT == 8` along with comments saying that anyone running into them should feel free to reach out to us if they'd like us to consider removing them.

**Comment by coryan** [comment]
I have no specific plans to use Abseil on strange platforms.  The `static_assert` proposal LGTM.

**Comment by zhangxy988** [comment]
@mbxx: Is there any update on adding the static_assert?

**Comment by mbxx** [comment]
Sorry, this has been on my todo list but it got buried under a series of fires.  I just mailed out an internal pull request adding two static_asserts to absl/strings/numbers.h.  Those looks like the most critical places.  If you see others, please feel free to point them out and I'll cover them, too.

**Comment by mbxx** [comment]
A policy check for this has been added to absl/base/policy_checks.h.
