### ISSUE TITLE
Wdeprecated-copy warning when compiling with Clang trunk

### ISSUE THREAD

**Issue by haberman** [abseil/abseil-cpp#948]
Compiling ABSL at head with the trunk of Clang yields the following warning:

```
./absl/functional/function_ref.h:124:16: warning: definition of implicit copy constructor for 'FunctionRef<void (int, int, int)>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
  FunctionRef& operator=(const FunctionRef& rhs) = delete;
               ^
absl/functional/function_ref_benchmark.cc:89:12: note: in implicit copy constructor for 'absl::FunctionRef<void (int, int, int)>' first required here
  Function f = c;
```

I'm not sure the correct fix or I'd submit a PR. I'm not sure if `EnableIfCompatible` should be updated to accept `FunctionRef` or if the copy constructor should be explicitly defined separately.

**Comment by derekmauro** [comment]
@vslashg - Can you take a look at this one?

**Comment by haberman** [comment]
Ping? This is blocking builds against Clang trunk that use `-Werror`. It seems like the fix should not be too hard?

**Comment by JamesJCode** [comment]
@haberman Not a permanent solution, but I inject -Wno-deprecated-copy in my build to work around this. Using CMake:

```
add_subdirectory(ExternalLibs/abseil-cpp)
# Following two directives needed to work around https://github.com/abseil/abseil-cpp/issues/948
if(NOT MSVC)
    target_compile_options(absl_strings INTERFACE -Wno-deprecated-copy)
    target_compile_options(absl_flat_hash_map INTERFACE -Wno-deprecated-copy)
endif()
```

**Comment by derekmauro** [comment]
There is an internal change (cl/374995948) pending for this issue.
