### ISSUE TITLE
RFE: provide build against system installed shared gtest library

### ISSUE THREAD

**Issue by kloczek** [abseil/abseil-cpp#953]
At the moment cmake fails with:
```
CMake Error at CMake/AbseilHelpers.cmake:401 (message):
   ABSL: compiling absl requires a gtest CMake target in your project,
                     see CMake/README.md for more details
Call Stack (most recent call first):
  CMakeLists.txt:132 (check_target)
```

**Comment by florin-crisan** [comment]
Created pull request: https://github.com/abseil/abseil-cpp/pull/969

**Comment by florin-crisan** [comment]
May want to correct the typo in the issue's description: provide build against system installed shared GTest library

**Comment by derekmauro** [comment]
This is fixed by 8f92175783c9685045c50f227e7c10f1cddb4d58.

**Comment by kloczek** [comment]
Hmm ... switching from bundled source tree to use another location of the same source tree is not using system gtest library :/
Commiting such changes is really pointless.
```console
[tkloczko@barrel SPECS]$ pkgconf --cflags gtest; pkgconf --libs gtest
-DGTEST_HAS_PTHREAD=1
-lgtest -lpthread
```

**Comment by derekmauro** [comment]
> Hmm ... switching from bundled source tree to use another location of the same source tree is not using system gtest library :/
Commiting such changes is really pointless.

This reply is not helpful. If you have feedback, please be professional about it. Believe it or not, the people who contributed to addressing this issue thought they resolved the issue.

Please let us know how you expected this issue to be resolved.

**Comment by florin-crisan** [comment]
@kloczek I don't think it's enough to rely just on `pkgconf`; you need to re-generate the CMake build directory and build again. If your Google Test is installed in a non-standard location, don't forget to set `CMAKE_PREFIX_PATH`.

```
rm -rf Build/Abseil

cmake -S Source/Abseil -B Build/Abseil -DABSL_USE_EXTERNAL_GOOGLETEST=ON -DABSL_FIND_GOOGLETEST=ON -DCMAKE_PREFIX_PATH=/non/standard/location -DCMAKE_BUILD_TYPE=Release

cmake --build Build/Abseil

ctest --test-dir Build/Abseil --progress --output-on-failure

cmake --build Build/Abseil --target install
```

Hope this helps.

**Comment by kloczek** [comment]
BTW: do you have any plans to make new release?
