### ISSUE TITLE
Abseil bazel build fails on Apple M1 (ARM64)

### ISSUE THREAD

**Issue by devjgm** [abseil/abseil-cpp#954]
**Describe the bug**

I'm on a Mac mini M1 (ARM64), and when I bazel build Abseil I get an error:

```
$ git rev-parse HEAD
a9831f1cbf93fb18dd951453635f488037454ce9

$ bazel info release
release 4.0.0-homebrew

$ bazel build ...
INFO: Analyzed 381 targets (0 packages loaded, 0 targets configured).
INFO: Found 381 targets...
ERROR: /Users/jgm/github/devjgm/abseil-cpp/absl/synchronization/BUILD.bazel:68:11: Linking absl/synchronization/libsynchronization.so failed: (Exit 1): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/absl/synchronization/libsynchronization.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-fastbuild/bin/absl/synchronization/libsynchronization.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
ld: illegal thread local variable reference to regular symbol __ZN4absl13base_internal19thread_identity_ptrE for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
INFO: Elapsed time: 1.778s, Critical Path: 1.07s
INFO: 83 processes: 53 internal, 30 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Steps to reproduce the bug**

*Important* You'll need a Mac with an M1 chip.

1. Checkout Abseil head. For me that was a9831f1cbf93fb18dd951453635f488037454ce9
2. bazel build ...
3. *error*

**What version of Abseil are you using?**

HEAD: a9831f1cbf93fb18dd951453635f488037454ce9

**What operating system and version are you using**

```
ProductName:    macOS
ProductVersion: 11.3
BuildVersion:   20E232
```

On a Mac Mini M1

**What compiler and version are you using?**

```
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**What build system are you using?**

```
bazel 4.0.0-homebrew
```

**Additional context**

**Comment by phst** [comment]
Still happening with Bazel 4.1 for me.

**Comment by jesec** [comment]
I can confirm this. `bazel 4.1.0-homebrew`

**Comment by derekmauro** [comment]
Unfortunately I don't have the hardware to test this at the moment. Those of you who are experiencing the issue, can you try building with `--copt=-DABSL_FORCE_THREAD_IDENTITY_MODE=N`, replacing `N` with `0`, `1`, and `2`, and let us know if the build succeeds in any of those configurations. That may give us a hint on how to fix the issue.

Another thing you could try is to tweak the conditional [here](https://github.com/abseil/abseil-cpp/blob/7971fb358ae376e016d2d4fc9327aad95659b25e/absl/base/internal/thread_identity.h#L245) and [here](https://github.com/abseil/abseil-cpp/blob/7971fb358ae376e016d2d4fc9327aad95659b25e/absl/base/internal/thread_identity.cc#L126) to include this platform.

Thread-local storage has been a major pain on Apple platforms in general. Thanks to those who have reported this.

**Comment by phst** [comment]
For me this works with N = 0 and fails otherwise.

**Comment by derekmauro** [comment]
This fix for this issue as been backported to the latest LTS release: https://github.com/abseil/abseil-cpp/releases/tag/20210324.2.
