### ISSUE TITLE
Linking problems with Wyhash when using Abseil on Godbolt's CompilerExplorer

### ISSUE THREAD

**Issue by Falkgaard** [abseil/abseil-cpp#958]
**Describe the bug**

I reported an issue on Compilerexplorer's repo (<https://github.com/compiler-explorer/compiler-explorer/issues/2658>) and they suggested I go here,

> "Currently we link to the following [compiler-explorer/etc/config/c++.amazon.properties](https://github.com/compiler-explorer/compiler-explorer/blob/126204172c57848260c139046832146d6727ec4b/etc/config/c%2B%2B.amazon.properties#L1282). The binaries were built yesterday so it's pretty fresh."

I get a linking error when I try to use a std::string key with `absl::flat_hash_map<std::string,int>` on Godbolt:

``` ASM generation compiler returned: 0
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/12.0.0/../../../../x86_64-linux-gnu/bin/ld: ./libabsl_hash.a(hash.cc.o): in function `absl::hash_internal::HashState::WyhashImpl(unsigned char const*, unsigned long)':
hash.cc:(.text+0x21d): undefined reference to `absl::hash_internal::Wyhash(void const*, unsigned long, unsigned long, unsigned long const*)'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
Execution build compiler returned: 1
```

**Steps to reproduce the bug**

Here's a minimal Godbolt code: <https://godbolt.org/z/6Ybn94YoT>

The linking error seems to happen whenever I use a std::string as a key and Abseil tries to hash it.

**What version of Abseil are you using?**

Trunk (~1 day old build at most).

**What operating system and version are you using**

I'm using Godbolt, which is run on Linux I believe.

**What compiler and version are you using?**

I tried it with both trunk gcc and trunk clang on Godbolt.

**What build system are you using?**

Not sure what Godbolt uses.

**Additional context**

None that I can think of. Love the library, by the way. Great job!

**Comment by derekmauro** [comment]
I commented on the Godbolt bug. It looks like the linker inputs on Godbolt is missing `absl_wyhash`.

https://github.com/compiler-explorer/compiler-explorer/blob/c3a171c979dd63a7f89b0ee65f9ddbd5b5bdb534/etc/config/c%2B%2B.amazon.properties#L1282
