### ISSUE TITLE
absl::AsciiStrToLower benchmark

### ISSUE THREAD

**Issue by bstaletic** [abseil/abseil-cpp#959]
To be honest, this isn't a blocker of a complaint of any kind. I just made an observation and thought I could share.

I have just realized that Abseil ships the `strings/ascii.h` header and though that maybe I shouldn't [reinvent the wheel](https://github.com/ycm-core/ycmd/blob/master/cpp/ycm/Utils.h#L49).

Then I decided to do a little benchmark, since the approach to `ascii_tolower` is quite different from ours.

```c++
#include <benchmark/benchmark.h>
#include <absl/strings/ascii.h>
#include <absl/algorithm/container.h>
inline char Lowercase( uint8_t ascii_character ) {
  if ( absl::ascii_isupper( ascii_character ) ) {
    return static_cast< char >( ascii_character ^ 0x20 );
  }
  return static_cast< char >( ascii_character );
}


inline std::string Lowercase( std::string_view text ) {
  std::string result( text.size(), '\0' );
  absl::c_transform( text,
                     result.begin(),
                     []( char c ) {
                       return Lowercase( static_cast< uint8_t >( c ) );
                     } );
  return result;
}
static void BM_Ycmd(benchmark::State& state) {
  const int size = state.range(0);
  std::string s(size, 'X');
  for (auto _ : state) {
    benchmark::DoNotOptimize(::Lowercase(s));
  }
}
BENCHMARK(BM_Ycmd)->DenseRange(8, 16);
static void BM_StrToLower(benchmark::State& state) {
  const int size = state.range(0);
  std::string s(size, 'X');
  for (auto _ : state) {
    benchmark::DoNotOptimize(absl::AsciiStrToLower(s));
  }
}
BENCHMARK(BM_StrToLower)->DenseRange(8, 16);
BENCHMARK_MAIN();
```

The dense range `[8, 16]` was chosen because a wider range pointed out that that's where our `Lowercase(string_view)` beats `absl::AsciiStrToLower(string_view)`.

```
Run on (4 X 3400 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x2)
  L1 Instruction 32 KiB (x2)
  L2 Unified 256 KiB (x2)
  L3 Unified 4096 KiB (x1)
Load Average: 0.21, 0.28, 0.33
-----------------------------------------------------------
Benchmark                 Time             CPU   Iterations
-----------------------------------------------------------
BM_Ycmd/8              19.7 ns         19.7 ns     35263260
BM_Ycmd/9              21.1 ns         21.0 ns     32992384
BM_Ycmd/10             22.6 ns         22.6 ns     30962600
BM_Ycmd/11             24.1 ns         24.1 ns     29084350
BM_Ycmd/12             25.7 ns         25.7 ns     27307718
BM_Ycmd/13             27.1 ns         27.0 ns     25698407
BM_Ycmd/14             28.5 ns         28.5 ns     24543281
BM_Ycmd/15             30.0 ns         30.0 ns     23156331
BM_Ycmd/16             27.6 ns         27.6 ns     25320821
BM_StrToLower/8        13.2 ns         13.2 ns     53414662
BM_StrToLower/9        13.7 ns         13.7 ns     51382539
BM_StrToLower/10       14.3 ns         14.3 ns     49182508
BM_StrToLower/11       14.9 ns         14.9 ns     47215213
BM_StrToLower/12       15.4 ns         15.4 ns     45481199
BM_StrToLower/13       16.1 ns         16.1 ns     43644617
BM_StrToLower/14       16.6 ns         16.6 ns     41655834
BM_StrToLower/15       17.3 ns         17.3 ns     40478825
BM_StrToLower/16       33.3 ns         33.3 ns     19152573
```

Here's also the full range:

```
----------------------------------------------------------------
Benchmark                      Time             CPU   Iterations
----------------------------------------------------------------
BM_Ycmd/1                   6.54 ns         6.54 ns    105675681
BM_Ycmd/8                   19.7 ns         19.7 ns     35526262
BM_Ycmd/64                  32.0 ns         32.0 ns     21961984
BM_Ycmd/512                 79.3 ns         79.2 ns      8937840
BM_Ycmd/4096                1173 ns         1172 ns       599881
BM_Ycmd/32768               3661 ns         3659 ns       191832
BM_Ycmd/262144             33832 ns        33788 ns        19985
BM_Ycmd/1048576           144332 ns       144215 ns         4872
BM_StrToLower/1             3.92 ns         3.91 ns    179828825
BM_StrToLower/8             13.1 ns         13.1 ns     53408798
BM_StrToLower/64            68.6 ns         68.6 ns     10270754
BM_StrToLower/512            345 ns          345 ns      2033988
BM_StrToLower/4096          2578 ns         2577 ns       272120
BM_StrToLower/32768        20939 ns        20928 ns        33461
BM_StrToLower/262144      172152 ns       172044 ns         4100
BM_StrToLower/1048576     767885 ns       766875 ns          891
```

Thinking out loud:

- Seems like the table lookup gets costly as the string length grows.
- I thought the 16 byte turning point oddly coincides with libstdc++ small string buffer, but libc++ behaves the same.
- Would it be a good idea to branch on `size() == 16` to decide whether to use the lookup table vs ycmd's solution?

**Comment by derekmauro** [comment]
This doesn't reproduce for me. Abseil's table-based version is consistently faster for me. I tested this on two different machines with gcc and clang, and targeting both plain x86-64 and with `-march=native`.

Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz
Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz

gcc version 10.2.1 20210110 (Debian 10.2.1-6+build2)
Debian clang version 11.0.1-2

How are you building this?

By the way, I think with your benchmark YCmd has a slight advantage due to inlining, but even so, it never wins in my testing.

**Comment by bstaletic** [comment]
> This doesn't reproduce for me.

That's interesting.

Here's my system:

- CPU: Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
- Compiler:
  - gcc (GCC) 10.2.0
  - clang version 11.1.0
- System: Arch linux

> How are you building this?

Mostly `$CXX bench.cpp -O3 -l benchmark -l benchmark_main -l absl_strings`. I tried with and without `-march=native`, with both compilers and both standard libraries that I have installed. The numbers I've shown above are consistent on my laptop.

> By the way, I think with your benchmark YCmd has a slight advantage due to inlining

That's true. I've looked at the produced assembly and everything was inlined in ycmd's benchmark. I've left that as such, because that was what I was considering for my actual use case.

**Comment by derekmauro** [comment]
And how are you building Abseil? Are you using `-DCMAKE_BUILD_TYPE=Release`?

**Comment by bstaletic** [comment]
I am: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=abseil-cpp-git#n31

**Comment by derekmauro** [comment]
From Arch Linux `/etc/makepkg.conf`
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt"
```

I think you are comparing Abseil with `-O2` to Ycmd with `-O3`. I didn't test this theory because I couldn't figure out how to get a usable compiler in the base Arch docker container after 5 minutes.

The instructions emitted are very different: https://godbolt.org/z/abYqKhGdP

**Comment by bstaletic** [comment]
> I think you are comparing Abseil with -O2

My `makepkg.conf` contains `-O3 -march=native`. Anyway, I checked with someone else and it seems I'm the only one (sample size of 3) who measures ycmd's algorithm as faster. Feel free to close the issue.
