### ISSUE TITLE
Make commit short-message of staging PR more readable

### ISSUE THREAD

**Issue by bfierz** [abseil/abseil-cpp#96]
Currently, merges that originate from the staging branch don't contain any useful information without opening the pull-request. All read:
"Changes imported from Abseil "staging" branch".
Do you see any possibility in changing it such that it is more descriptive about the changes it makes?

Thanks
Basil

**Comment by zhangxy988** [comment]
@katzdm : I think this is related to how our internal tool generate the commit log message. Could you please check to see if we can customize the format to make it more friendly for one-line display?

**Comment by mbxx** [comment]
I suspect this is a duplicate of the request for a changelog in https://github.com/abseil/abseil-cpp/issues/87.

@bfierz : I'd like to make sure I understand what you're asking for.  It sounds to me like you want a listing of any new features that are released.  Is that correct?

We're planning to put up blog posts when we release new APIs.  Does that give you what you're looking for?

**Comment by bfierz** [comment]
The answer is yes and no. I would very much appreciate to have changelog/feature change list. This would then indeed correspond to #87.
However, when working with the master directly and going through the log (e.g. on github) all you see at first is a list with entries looks like this:
"Changes imported from Abseil "staging" branch:".
In the detailed message you'll then find:
"Bump version of bazel_toolchains used by Abseil", which I would like to see in the overview list instead.

**Comment by zhangxy988** [comment]
FYI, we are looking into removing the boiler template "Changes imported Abseil "staging" branch". For example, currently the commit message is:

Changes imported from Abseil "staging" branch:".  <== removing this line
- <commit_hash> <description of 1st change>
- <commit_hash> <description of 2nd change>
- ...

**Comment by bfierz** [comment]
Perfect, that is exactly the scope of my inquery.
I'm looking forward to this change.

**Comment by katzdm** [comment]
As of yesterday, our commit messages should be a bit more meaningful - Let me know if this matches what you were hoping to see.

**Comment by bfierz** [comment]
Looks a lot better, thanks. It's not ideal, but make the messages more helpful. Any change getting rid of the hash or using the short-hash at least instead of the long hash?

**Comment by rongjiecomputer** [comment]
@bfierz Perhaps the commit messages can be generated by `git log --date=short --no-merges --format="%ad %ae %s" start_hash..end_hash` instead? (Chromium uses the exact same command to generate commit messages when [rolling dependencies](https://chromium-review.googlesource.com/c/chromium/src/+/1038822)).

The output of the command will look something like this (from Bazel):

```
2018-04-24 tomlu@google.com Pass environment to Skylark provider constructors.
2018-04-24 noreply@google.com Make the static_link_cpp_runtimes feature settable as a normal feature.
2018-04-24 tomlu@google.com Change action construction to use built-in param file support.
2018-04-24 cushon@google.com Use JavaRuleOutputJarsProvider to collect non-transitive runtime jars
2018-04-24 michajlo@google.com Fix profiler slow task limiting
```

**Comment by bfierz** [comment]
@rongjiecomputer Sure locally that does the trick. I was conceirned about readability of the message in the github web interface. But it's now good enough for a fast browsing.
