### ISSUE TITLE
Provide an RAII setter for flags

### ISSUE THREAD

**Issue by sfc-gh-ebrossard** [abseil/abseil-cpp#960]
**Describe the bug**

Please provide an RAII class, e.g. `absl::FlagSetter`, that can set and restore flags in unit tests. Currently, setting a flag in one test causes others to have the new value unless the previous test clears it.

**Steps to reproduce the bug**

I haven't tried compiling this, but here's a sketch:

```c++
// RAII flag setter that restores a flag to its default value once the setter goes
// out of scope.
template <typename T>
class FlagSetter {
 public:
  FlagSetter(absl::Flag<T>* flag, const T& v)
    : flag_(flag) {
    absl::SetFlag(flag_, v);
  }
  FlagSetter(const FlagSetter&) = delete;
  FlagSetter& operator=(const FlagSetter&) = delete;
  FlagSetter(FlagSetter&&) = default;
  FlagSetter& operator=(FlagSetter&&) = default;
  ~FlagSetter() {
    absl::SetFlag(flag_, absl::GetFlagReflectionHandle(*flag_).DefaultValue());
  }

 private:
  absl::Flag<T>* const flag_;
};
```

**What version of Abseil are you using?**
Abseil LTS 20210324.1

**Comment by derekmauro** [comment]
It's not quite RAII, but it is basically the same thing:

https://github.com/abseil/abseil-cpp/blob/1ae9b71c474628d60eb251a3f62967fe64151bb2/absl/flags/reflection.h#L50-L83

**Comment by sfc-gh-ebrossard** [comment]
Ah, thanks, I just didn't think to look in the right header :) I'll go ahead and close this, since that works for the purposes I need.
