### ISSUE TITLE
Add support for hyphenated flags

### ISSUE THREAD

**Issue by jpeach** [abseil/abseil-cpp#961]
Lots of projects use hyphenated flag names, e.g. `--enable-foo` rather than `--enable_foo`. If the flags library had macros to allow callers to pass the flag name separately from the variable name, this would enable those projects to adopt the Abseil flags library. Is this a feature that would be considered?

**Comment by derekmauro** [comment]
It's unlikely to happen.

As mentioned in the [Abseil FAQ](https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library):
> Abseil's primary purpose is to be used as a dependency by Google's open source C++ projects. While we do hope that Abseil is also useful to the C++ community at large, this added constraint also means that we are unlikely to accept a contribution of utility code that isn't already widely used by Google.

The convention that Google has used for about 20 years is to only use underscores in flags in C++ binaries. That means there are 20 years of assumptions baked into how flags are being used. Loosening the requirements would be risky to Google for very little benefit.

**Comment by jpeach** [comment]
Thanks @derekmauro, that rationale makes sense 👍
