### ISSUE TITLE
Filesystem helpers?

### ISSUE THREAD

**Issue by chessai** [abseil/abseil-cpp#968]
Would be useful to have filesystem utilties in abseil, for reading from/writing to files etc. Seems like a natural addition, especially since std is so lacking in this regard. See https://github.com/google/xls/blob/main/xls/common/file/filesystem.cc#L155-L181 as an example of using abseil for this in the wild.

**Comment by derekmauro** [comment]
This is partially answered by https://github.com/abseil/abseil-cpp/blob/master/FAQ.md#is-abseil-the-right-home-for-my-utility-library, but requires some visibility into Google's internal codebase. We have our own file system library that pre-dates `std::filesystem` and supports various non-local filesystems. It is something we would like to have released to support projects that are already using the library, but releasing it would require some non-trivial redesign and cleanup. It is something we did put on our roadmap, but as of today no one is working on it. It is unlikely that a new library of filesystem helpers based on `std::filesystem` will appear in Abseil anytime soon.
