### ISSUE TITLE
constexpr operators for uint128 and int128

### ISSUE THREAD

**Issue by hurchalla** [abseil/abseil-cpp#978]
I have a project that's templated to be able to use 8 bit to 128 bit integer types.  For 128 bit, I've used __uint128_t which works fine.  Today I tried absl::uint128 which resulted in compile errors in my project because many uint128 operators are not constexpr.  For example, just a few of the operators I use at compile time are ==, %, <<, and none of these are constexpr for absl::uint128.
Would it be possible to change most of the uint128 and int128 operators to constexpr?  Ideally they would behave like __uint128_t and __int128_t at compile time, though I wouldn't be too surprised if uint128/int128 sometimes use non-constexpr intrinsics and asm that make it impossible.

**Comment by farukrana** [comment]
yes

**Comment by hurchalla** [comment]
I'd like to make it into a feature request (if possible) then, to have uint128 operators become constexpr across the board aside from whatever specific cases where perhaps it proves impossible to do.  A week or two ago I tried changing the operators myself where I needed them constexpr,  but each change in turn required me to change other functions to constexpr and then the functions they rely on to constexpr, etc.  As best I can recall I didn't run into fundamental roadblocks, but the amount of changes was becoming massive enough that I gave up after 20 or 25 minutes - fearing that there was a very good reason the operators weren't already constexpr, and that Murphy's law meant I would find out that it couldn't be done after spending an hour or three.

My reason for asking is that I'd love to be able to support abseil's uint128 in my github library, which would require many uint128 operators to be changed to constexpr.  Making those changes to abseil myself, it wasn't important enough for me to take the uncertain amount of time it might take to do it, along with the uncertainty of whether I would succeed and whether it would be accepted upstream if successful.  Perhaps Google and others (not just me) would also like to have constexpr uint128/int128, so I'll make it a request for a feature.

Let me know if there's a better way to make a feature request, and if abseil doesn't take feature requests you can safely ignore this.  Many thanks

**Comment by rogeeff** [comment]
I'll look into this.

**Comment by hurchalla** [comment]
Thanks!

**Comment by farukrana** [comment]
yes

**Comment by rogeeff** [comment]
This is an API change (kind of). So I am trying to get an approval for this. It'll probably take few weeks
