### ISSUE TITLE
Parsing input command line flags in absl::flags

### ISSUE THREAD

**Issue by amirhosseindavoody** [abseil/abseil-cpp#979]
My question is about how to parse the input command line flags when using `absl::flags`.

I know how to use gflags to define and use flags (see sample code below). I don't know what is the equivalent of `google::ParseCommandLineFlags` in abseil flags library.

```cpp
#include "gflags/gflags.h"

DEFINE_int64(some_parameter, 100, "Some random parameter");

void main(int argc, char** argv) {
  google::InitGoogleLogging(argv[0]);
  google::ParseCommandLineFlags(&argc, &argv, true); // parse the input command line flags

  // do stuff on FLAGS_some_parameter
}

**Comment by derekmauro** [comment]
Please see [the manual](https://abseil.io/docs/cpp/guides/flags) and [`absl/flags/parse.h`](https://github.com/abseil/abseil-cpp/blob/master/absl/flags/parse.h).

**Comment by amirhosseindavoody** [comment]
Thanks for the reply. A code like this now works for me:

```cpp
#include "absl/flags/flag.h"
#include "absl/flags/parse.h"

ABSL_FLAG(some_parameter, 100, "Some random parameter");

void main(int argc, char** argv) {
  absl::ParseCommandLine(argc, argv); // parse the input command line flags

  // do stuff with FLAGS_some_parameter
}
```
