### ISSUE TITLE
absl::Mutex has multiple "no member named '...'" errors when !ABSL_HAVE_MMAP.

### ISSUE THREAD

**Issue by deeglaze** [abseil/abseil-cpp#98]
There are some declarations in mutex.h that are in the "else" branch of #ifdef ABSL_INTERNAL_USE_NONPROD_MUTEX that mutex.cc has no similar #ifdef protection around the definitions. This leads to many compiler errors.

**Comment by derekmauro** [comment]
Can post the compile errors and give us details about the platform you are building this on?

**Comment by deeglaze** [comment]
I just determined this is due to some BUILD select expressions that should be added for our platform. I'll have to work from a patched archive in the meantime.
