### ISSUE TITLE
Using glog and absl::flag together

### ISSUE THREAD

**Issue by amirhosseindavoody** [abseil/abseil-cpp#980]
Can I use `absl::flags` and glog together?
The problem that I have is glog uses gflags to parse flags like `logtostderr` and I cannot parse the rest of the flags that are defined in `absl::flags`.

In other words, when I try to run the following code I get `ERROR: unknown command line flag 'size_of_grid'` 

```cpp
#include <glog/logging.h>

#include "absl/flags/flag.h"
#include "absl/flags/parse.h"

ABSL_FLAG(int64_t, some_parameter, 100, "Some parameter");

void main(int argc, char** argv) {
  // Initialize Google’s logging library.
  google::InitGoogleLogging(argv[0]);
  google::ParseCommandLineFlags(&argc, &argv, false); // parse flags for gflag without deleting them
  
  // parse flags with abseil
  absl::ParseCommandLine(argc, argv);

  LOG(INFO) << "Some stuff";
  // Do some stuff with FLAGS_some_parameter
}
```

**Comment by derekmauro** [comment]
It looks like the glog project supports turning off the use of gflags: https://github.com/google/glog/search?q=gflags

So I think you can probably make this work, but I would advise only using one commandline flags library in your program. We are working on releasing an updated version the Google logging library. You might just want to wait for us to do that before making the switch.

**Comment by versatran01** [comment]
just to piggyback on this, is the updated version of glog going to depend on absl? or is logging going to be part of absl?

**Comment by derekmauro** [comment]
It will be part of absl.

**Comment by AaronWebster** [comment]
Can you comment on the timeline?

**Comment by Mizux** [comment]
For google/or-tools to get rid of gflags/glog deps, we've hacked a glog's logging version using absl::flags instead (and waiting for the official one to replace it).

see:
https://github.com/google/or-tools/blob/main/ortools/base/logging.h
https://github.com/google/or-tools/blob/main/ortools/base/logging.cc

Hope it will help waiting for godot's logging...
