### ISSUE TITLE
[Question] Any good news about absorbing glog into abseil ?

### ISSUE THREAD

**Issue by benet96** [abseil/abseil-cpp#981]
I am looking through issuses about absorbing the features of glog into abseil. There is an answer in 2019 claiming that absorbing was working on but no date promised, and another answer in 2020 said it was still working on. Glog is a great project, although it took 12 years from v0.1 to v0.5... So any good news ?

**Comment by derekmauro** [comment]
It is still actively being worked on, nothing has changed. A lot of cleanup is going into this effort. Estimating a release date is difficult.

**Comment by benet96** [comment]
Thank you for the information.

**Comment by romange** [comment]
@benet96  I hacked glog library to use absl instead of gflags.  Here is how I import it: https://github.com/romange/helio/blob/master/cmake/third_party.cmake#L186

and here is the modified branch of glog:  https://github.com/romange/glog/tree/Absl
