### ISSUE TITLE
error: "numeric_limits" is not member of "std"

### ISSUE THREAD

**Issue by MensoMG** [abseil/abseil-cpp#992]
### Discussed in https://github.com/abseil/abseil-cpp/discussions/991

<div type='discussions-op-text'>

<sup>Originally posted by **MensoMG** July 30, 2021</sup>
A sequential list of commands I have used:
dir - /home/menso

- mkdir TON_chain
- cd TON_chain
- git clone https://github.com/ton-blockchain/ton.git
- cd ton/
- git submodule update --init --recursive
- cd ..
- sudo pacman -S cmake ( same openssl, clang)
- mkdir liteclient-build (then cd liteclient-build)
- cmake ~/TON_chain/ton
- _and when i started building client_    ->    cmake --build . --target lite-client

there was such a mistake, if I knew C ++, I could fix (or I could not xd), but alas ... so I ask the professionals how to fix it? :)

```
[23%] Linking CXX static library libabsl_symbolize.a
[23%] Built target absl_symbolize
[23%] Building CXX object third-party/abseil-cpp/absl/synchronization/CMakeFiles/absl_graphcycles_internal.dir/ internal / graphcycles.cc.o
/home/menso/TON_chain/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc: In member function "void absl :: lts_2020_02_25 :: synchronization_internal :: GraphCycles :: RemoveNode (void *) ":
/home/menso/TON_chain/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: 'numeric_limits' is not element 'std'
  451 | if (x-> version == std :: numeric_limits <uint32_t> :: max ()) {
      | ^ ~~~~~~~~~~~~~
/home/menso/TON_chain/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before ">" token
  451 | if (x-> version == std :: numeric_limits <uint32_t> :: max ()) {
      | ^
/home/menso/TON_chain/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: ":: max" has not been declared; did you mean "std :: max"?
  451 | if (x-> version == std :: numeric_limits <uint32_t> :: max ()) {
      | ^ ~~
      | std :: max
In file included from /usr/include/c++/11.1.0/algorithm:62,
                 from /home/menso/TON_chain/ton/third-party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:38:
/usr/include/c++/11.1.0/bits/stl_algo.h:3467:5: note: "std :: max" declared here
 3467 | max (initializer_list <_Tp> __l, _Compare __comp)
      | ^ ~~
make [3]: *** [third-party / abseil-cpp / absl / synchronization / CMakeFiles / absl_graphcycles_internal.dir / build.make: 76: third-party / abseil-cpp / absl / synchronization / CMakeFiles / absl_graphcycles_internal.dir /internal/graphcycles.cc.o] Error 1
make [2]: *** [CMakeFiles / Makefile2: 4646: third-party / abseil-cpp / absl / synchronization / CMakeFiles / absl_graphcycles_internal.dir / all] Error 2
make [1]: *** [CMakeFiles / Makefile2: 8246: lite-client / CMakeFiles / lite-client.dir / rule] Error 2
make: *** [Makefile: 2246: lite-client] Error 2
```

</div>

**Comment by derekmauro** [comment]
The project you are trying to build appears to be using an old version of Abseil as a git submodule: https://github.com/ton-blockchain/ton/tree/master/third-party.

The issue you are seeing is fixed in the latest version. The project you are building needs to update.

**Comment by MensoMG** [comment]
> Похоже, что проект, который вы пытаетесь создать, использует старую версию Abseil в подмодуля git: https://github.com/ton-blockchain/ton/tree/master/third-party .
> 
> Проблема, которую вы видите, исправлена ​​в последней версии. Проект, который вы создаете, необходимо обновить.

или я могу использовать старую версию Abseil
