### ISSUE TITLE
join std::thread without check joinable

### ISSUE THREAD

**Issue by MBkkt** [abseil/abseil-cpp#999]
https://github.com/abseil/abseil-cpp/blob/master/absl/synchronization/internal/thread_pool.h#L52
This is a bug, I suppose?

**Comment by derekmauro** [comment]
We know the thread is joinable at that point because we know it has finished and it was never detached, so there is no need to check.

**Comment by MBkkt** [comment]
Yeah, you're right, thread start in ctor, sorry
